import { describe, expect, it } from "vitest";
import {
  V4_ONLY_PROGRAMS,
  V4_PANEL_C,
  v4OnlyProgramByCode,
} from "../v4/data/v4PanelC";
import { v3ProgramByCode } from "../v3/data/v3Programs";

/**
 * A program can be scored on Panel C without being in the assessed portfolio:
 * no exposure, no alumni destinations, no market report. `V4ReportPage` renders
 * that case with the missing half stated rather than refusing to render, and it
 * decides which case it is by asking the v3 registry first and this map second.
 *
 * These guard the invariants that decision depends on. `V4_ONLY_PROGRAMS` is
 * generated by `npm --prefix scripts run dfva:gen-v4`.
 */
describe("V4_ONLY_PROGRAMS contract", () => {
  const codes = Object.keys(V4_ONLY_PROGRAMS);

  it("never contains a program the v3 registry already has", () => {
    // Both lookups returning a hit would make the page's branch order — and so
    // whether it shows an exposure value — depend on an accident of ordering.
    for (const code of codes) {
      expect(v3ProgramByCode(code)).toBeUndefined();
    }
  });

  it("only contains programs that actually carry a v4 score", () => {
    // The map exists to render a scored program. An entry without a panelCv4
    // block would render a page with a name and no assessment.
    for (const code of codes) {
      expect(V4_PANEL_C[code]).toBeDefined();
    }
  });

  it("keys match their own code field, and lookup is case-insensitive", () => {
    for (const code of codes) {
      expect(V4_ONLY_PROGRAMS[code].code).toBe(code);
      expect(v4OnlyProgramByCode(code.toUpperCase())?.code).toBe(code);
    }
  });

  it("carries a display name that is not just the code shouted back", () => {
    // The generator falls back to the upper-cased code when no report markdown
    // exists to read a name from. That fallback is deliberate — never a guessed
    // name — but it should not survive into a page anyone is shown.
    for (const code of codes) {
      expect(V4_ONLY_PROGRAMS[code].name).not.toBe(code.toUpperCase());
    }
  });

  it("does not leak into the reference-cohort median arithmetic", () => {
    // The median is computed over reference-cohort codes read from the v3
    // dataset, so a v4-only program must be invisible to it by construction.
    // This restates that as an assertion so a future generator change cannot
    // quietly widen the cohort.
    for (const code of codes) {
      expect(v3ProgramByCode(code)).toBeUndefined();
    }
  });
});
