// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Social Policy (706AA) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Social Policy (706AA)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-23 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-706aa.md
**Position basis:** Destination AI Exposure 96.05 (exact basis) × Curriculum Adaptiveness 6/15 (v4.2 draft, sub-scale A) · Workplace practice 5/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

The Master of Social Policy provides a rigorous academic grounding in comparative social policy, stakeholder analysis, and policy research design. G1 passes on a coherent discipline core (SOCI90003, SOCI90005, SOCI90011) with clear WAM progression thresholds, and G2 passes on extensive evaluated policy advocacy and stakeholder trade-off analysis under uncertainty.

However, the program faces high exposure (96.05) alongside substantial headroom on both sub-scales: **6 / 15 on Adaptiveness** and **5 / 9 on Workplace**. The most critical vulnerability is C3 (0/3), where digital and AI literacy is entirely absent from the core curriculum despite intense public sector debate on algorithmic welfare governance and automated policy synthesis post-Robodebt. In C1 (1/3) and C2 (1/3), collaborative practice and evaluative judgement are restricted to optional capstone streams or self-reflection without criterion-referenced quality appraisal. On workplace practice, W3 (1/3) reflects that the 25-point social policy internship (SOCI90013) is an elective capstone route that can be bypassed via the purely academic minor thesis, while W1 (2/3) and W2 (2/3) lack mandatory external practitioner panels and live stakeholder constraints across all pathways.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | Adaptive | 0 / 3 | 3 | Direct — Market §2 Signal 4 and §3 Theme 1 emphasize that post-Robodebt public administration mandates rigorous algorithmic governance, automated compliance auditing, and administrative fairness literacy. Core currently contains 0 digital/AI content. | 1 |
| C1 Distributed cognition & relational capability | Adaptive | 1 / 3 | 2 | Direct — Market §1 and §3 Theme 3 highlight multidisciplinary policy teams coordinating participatory co-design and automated synthesis tools. Core assesses only individual tasks; collaborative practice is confined to elective capstone SOCI90023. | 2 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | Direct — Market §2 Signal 2 and §3 Theme 2 document widespread LLM drafting of policy briefs and consultation summaries, demanding evaluative judgement to detect hallucinations and policy bias. Core lacks criterion-referenced rubrics or reliance/override logs. | 3 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | Direct — Market §1 Job Families 1–4 show strong recruitment across DSS, DFFH, and NGOs; SOCI90013 provides 25-point workplace placement but is an elective capstone option rather than a mandatory requirement for all candidates. | 4 |
| C4 Life-long learning & transfer | Adaptive | 2 / 3 | 1 | Direct — Core applies comparative frameworks across OECD cases, but self-scoped independent inquiry (minor thesis) is an optional stream alongside client/host-directed capstones. | 5 |
| C5 Inquiry & evidence generation | Adaptive | 2 / 3 | 1 | Direct — Market §2 Signal 1 and §3 Theme 3 emphasize causal program evaluation (quasi-experiments, RCTs) as a core public sector capability. Core assesses small-scale research proposals (SOCI90005), but substantial thesis inquiry is optional and lacks a viva defence. | 6 |
| W1 Professional communication & conduct | Workplace | 2 / 3 | 1 | Direct — Core assesses authentic policy blogs, briefs, and submissions (SOCI90003, SOCI90011), but all are evaluated by internal academic staff rather than judged by external public sector panels. | 7 |
| W2 Authentic task design | Workplace | 2 / 3 | 1 | Direct — Core reproduces practitioner policy artefacts, but the minor thesis route allows graduating via a purely academic 15,000-word thesis without external client constraints. | 8 |
| **Adaptive capabilities** | **Adaptive** | **6 / 15** | **9** | — | — |
| **Workplace practice** | **Workplace** | **5 / 9** | **4** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | 0 → 1 | "AI or digital tools appear only as electives or as tool operation/training — the operational level TEQSA identifies as non-durable." | Introduce statistical software operation and digital policy database research in compulsory core subject SOCI90005 (Social Research Design and Evaluation). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Add an assessed module in SOCI90003 (Comparative Social Policy) covering generative AI capabilities, LLM prompt design for cross-jurisdictional policy scanning, and ethical hallucination limits in public consultation analysis. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Require an assessed algorithmic governance audit in SOCI90011 (Foundations of Social Policy): students audit an automated welfare compliance or public service allocation system for administrative fairness, bias, and human rights compliance under APS guidelines. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Embed an assessed group policy advocacy campaign with explicit individual contribution grading in compulsory core subject SOCI90003. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | In capstone project SOCI90023, require student teams to document and defend an explicit human-and-AI collaboration agreement allocating tasks between team members and policy analysis tools. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Introduce criterion-referenced peer review in SOCI90005: students evaluate peer research proposals against published evaluation rubrics and exemplar standards. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Attach an assessed reliance and override log to SOCI90003 and capstone projects: students document and defend where AI synthesis tools were accepted, rejected, or corrected on policy grounds. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Make the mentored client project (SOCI90023) or workplace internship (SOCI90013) a mandatory core capstone requirement for all students. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Expand internship partnerships to ensure all students complete an extended placement supervised by public sector/NGO senior managers with documented host accountability. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Require an assessed personal professional development plan and knowledge gap analysis across all capstone pathways. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Require an oral methodology defence before an academic/practitioner panel for all capstone research and evaluation outputs. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Formally invite external policy executives (e.g. from DSS, DFFH, or VCOSS) to evaluate Capstone Presentation Day expositions with assessed professional conduct criteria. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Embed authentic live client briefs from government/NGO partners into SOCI90003, SOCI90011, and the capstone to ensure external practice constraints bind all pathways. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| P1 | C3 | Australian Public Service mandates critical scrutiny of automated welfare systems following the Robodebt Royal Commission; demands training in algorithmic bias and administrative law safeguards. | §2 Signal 4; §3 Theme 1 | HIGH (public administration consensus) |
| P2 | C3 | Rapid growth of generative AI tools in policy synthesis and consultation analysis; APSC guidelines require civil servants to understand AI limitations and privacy risks. | §2 Signal 2; §3 Theme 2 | HIGH (APSC guidelines) |
| P3 | C1 | Policy design increasingly operates through cross-portfolio multidisciplinary taskforces and community co-design coalitions rather than isolated analysis. | §1 Job Families 1–4; §3 Theme 3 | HIGH (public sector hiring standards) |
| P4 | C2 | Proliferation of automated policy drafting tools requires policy analysts to exercise evaluative judgement to verify facts, override hallucinations, and detect subtle ideological bias. | §3 Theme 2; §4 rising skills | HIGH (policy research commentary) |
| P5 | W3 | Government departments (DSS, DFFH) and social consultancies prioritize graduates with direct workplace experience in public policy machinery. | §1 Job Families 1–3; §2 Signal 1 | HIGH (departmental recruitment data) |
| P6 | C5 | Treasury and AIFS mandate quasi-experimental evaluation (RCTs, difference-in-differences) and defended empirical methodologies to justify public spending. | §2 Signal 1; §3 Theme 3 | HIGH (Treasury evaluation toolkit) |
| P7 | W1 | Social policy advisors must present complex legislative submissions and policy pitches to ministerial panels, peak body boards, and public inquiries. | §2 Signal 3; §3 Theme 3 | HIGH (policy consulting requirements) |
| P8 | W2 | Public policy agencies demand live consultation submissions and regulatory impact statements delivered under authentic parliamentary timelines. | §1 Job Families 1 & 3; §4 rising skills | HIGH (public sector hiring) |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C3 | Introduce statistical software operation and digital policy database training in SOCI90005 | C3 level 1 (digital tool operation) | Low | Term 1; syllabus update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P2 | C1 | Embed an assessed collaborative policy project with individual grading in SOCI90003 | C1 level 2 (collaborative practice with individual accountability) | Low–Medium | Term 1; assessment brief update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P3 | C2 | Embed criterion-referenced peer review of research proposals in SOCI90005 | C2 level 2 (criterion-referenced appraisal of quality) | Low–Medium | Term 1; rubric update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P4 | C3 | Add an assessed module on generative AI policy synthesis and limitations in SOCI90003 | C3 level 2 (capabilities and limitations discussed/assessed) | Low–Medium | Term 1; core subject update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P5 | C3 | Introduce an assessed algorithmic welfare governance audit in SOCI90011 | C3 level 3 (governance of AI systems in disciplinary context) | Medium | Term 2; subject curriculum update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P6 | C2 | Attach an assessed AI reliance and override log to SOCI90003 and capstone tasks | C2 level 3 (reliance/override justification) | Medium | Term 2; assessment brief update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P7 | W1 | Invite external public sector policy executives to judge Capstone Presentation Day expositions | W1 level 3 (external practitioner judge and conduct criteria) | Medium | Term 2; external panel recruitment | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P8 | W3 | Make client-directed project (SOCI90023) or workplace internship (SOCI90013) compulsory across all capstones | W3 level 2 (core placement or client project) | Medium–High | Next course review cycle; capstone structure adjustment | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P9 | C5 | Introduce an oral methodology defence before an academic and practitioner panel for all capstone projects | C5 level 3 (defence under scrutiny) | Medium–High | Next course review cycle; capstone staging update | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | The program documents a coherent specialist core with progressive technical and methodological depth rather than generic interchangeable content: compulsory discipline subjects in social policy (SOCI90003 Comparative Social Policy, SOCI90005 Social Research Design and Evaluation, and SOCI90011 Foundations of Social Policy), an unwaivable capstone requirement that must be completed to graduate, and clear WAM progression thresholds (80% / H1 average) and proposal approval rules to enter the minor thesis. | Redesign must preserve the specialist social policy and comparative methodology sequence (SOCI90003, SOCI90005, SOCI90011). Adding digital and AI governance must deepen public administration analysis rather than diluting foundational welfare theory. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | Assessment across the program requires defended trade-off decisions, research design, and applied policy recommendations rather than recall or scripted responses. SOCI90003 requires students to evaluate competing policy frameworks and justify proposals to advocate for policy change; SOCI90011 requires a stakeholder-perspective policy submission analyzing competing definitions and limitations; SOCI90005 requires formulating and executing an empirical research design; and the capstones require either a defended self-directed 15,000-word thesis, a workplace internship report, or a client project report with public oral exposition. | Preserving defended policy trade-offs and stakeholder-perspective advocacy is essential; any assessment modifications must maintain rigorous justification of competing social and economic priorities under real-world ambiguity. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C3 | 0 | 1 | +1 adaptive | 7 / 15 | 5 / 9 |
| P2 | C1 | 1 | 2 | +1 adaptive | 8 / 15 | 5 / 9 |
| P3 | C2 | 1 | 2 | +1 adaptive | 9 / 15 | 5 / 9 |
| P4 | C3 | 1 | 2 | +1 adaptive | 10 / 15 | 5 / 9 |
| P5 | C3 | 2 | 3 | +1 adaptive | 11 / 15 | 5 / 9 |
| P6 | C2 | 2 | 3 | +1 adaptive | 12 / 15 | 5 / 9 |
| P7 | W1 | 2 | 3 | +1 workplace | 12 / 15 | 6 / 9 |
| P8 | W3 | 1 | 2 | +1 workplace | 12 / 15 | 7 / 9 |
| P9 | C5 | 2 | 3 | +1 adaptive | 13 / 15 | 7 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
