// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Medical Technology Innovation (MC-MTI) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Medical Technology Innovation (MC-MTI)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-31 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-mti.md
**Position basis:** Destination AI Exposure 87.13 (field basis) × Curriculum Adaptiveness 7/15 (v4.2 draft, sub-scale A) · Workplace practice 4/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a field basis (JSA HEO · 039903 Biomedical Engineering), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone.

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the scored evidence and market data above; it is
interpretation, not observation.*

The Master of Medical Technology Innovation (MC-MTI) carries a coherent, all-compulsory BioDesign core (G1 PASS) and requires defended trade-off judgement under genuine market, regulatory and IP uncertainty in its capstone (G2 PASS). C4 and C5 both sit mid-scale (2/3): BMEN90042's needs-discovery sequence and BMEN90044's capstone carry a real, clinician-sourced health need through prototype and business-plan development, and BMEN90042 requires students to design a research methodology and collect primary data. C1 also reaches 2/3 on BMEN90039's group written report and oral presentation and BMEN90044's fully team-based capstone.

The program's most exposed gaps are C2 (0/3) and W3 (0/3) — no compulsory assessment appraises the quality of a student's, peer's or a tool's work, and no compulsory or elective subject places a student in a supervised workplace, practicum or community-based project. C3 sits at only 1/3: AI and digital-tool content exists solely among the 18 elective options students may complete the degree without ever choosing, while the market report's sourced GPT-4-class task-exposure figures for this occupation run from roughly 26% to over 50%, up to about 82% on the most inclusive measure (Market §3 Theme 2). Both sub-scale totals — 7/15 adaptive, 4/9 workplace — sit below the instrument mid-point, against a field-basis exposure index of 87.13.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 0 / 3 | 3 | Direct — Market §5 CI-4: no compulsory assessment appraises a tool's output, while sourced trade press (§3 Theme 2) describes AI increasingly drafting regulatory documentation and literature review — precisely the judgement layer the profession's own framing says remains human. | 1 |
| W3 Work-situated learning | Workplace | 0 / 3 | 3 | Direct — Market §3 Theme 3 and §5 CI-2: the two operational functions where the record documents real 2025 AI adoption (clinical/healthcare technology management, manufacturing quality) are functions the program gives students no supervised exposure to; the 75-point compulsory core carries no placement or practicum. | 2 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | Direct — Market §3 Theme 2 and §5 CI-1: AI content sits only in a 25-point elective basket a student can complete the degree without choosing, against a destination occupation with GPT-4-class task exposure of roughly 26–54% (up to 82%). | 3 |
| C1 Distributed cognition & relational capability | Adaptive | 2 / 3 | 1 | Direct — Market §5 CI-5: compulsory assessment already reaches group work with individual accountability (level 2) but not level 3, which additionally requires assessing the division of work between people and AI systems, against an occupation with documented LLM task exposure. | 4 |
| C4 Life-long learning & transfer | Adaptive | 2 / 3 | 1 | Indirect — Market §3 Theme 1: the TGA's UDI/AusUDID compliance regime, binding for Class IIb/III devices from 2026-07-01, is a dynamic regulatory environment that rewards self-scoped independent learning beyond the taught BioDesign sequence. | 5 |
| C5 Inquiry & evidence generation | Adaptive | 2 / 3 | 1 | Indirect — Market §1 Job Family map: the Medical Device Design/R&D Engineer family's core tasks (needs-discovery methodology, prototyping) reward primary evidence generation defended under scrutiny, beyond the current designed-and-conducted-inquiry level. | 6 |
| W1 Professional communication & conduct | Workplace | 2 / 3 | 1 | Indirect — Market §1 Job Family map: the MedTech Commercialisation & Innovation Manager family requires market and reimbursement-pathway communication to real stakeholders beyond the current lay-audience presentation. | 7 |
| W2 Authentic task design | Workplace | 2 / 3 | 1 | Direct — Market §3 Theme 1 and §5 CI-3: BMEN90039 already assesses regulatory-pathway evaluation, but the evidence file records no UDI/AusUDID-specific content, even though Class IIb/III compliance under that regime became binding on 2026-07-01. | 8 |
| **Adaptive capabilities** | **Adaptive** | **7 / 15** | **8** | — | — |
| **Workplace practice** | **Workplace** | **4 / 9** | **5** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | 0 → 1 | "Reflection or self-assessment appears in outcomes or graduate attributes, but no core unit assesses it against criteria." | Add a self-assessment or reflection outcome to BMEN90044's team-based assessment items | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Add a structured peer-review task, marked against published criteria, to BMEN90044's Team-based Written Assignment | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Attach an assessed AI-reliance log to BMEN90044's team assignments, requiring students to document and defend which draft content used AI-assisted tools and why | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| W3 Work-situated learning | 0 → 1 | "Work-situated learning exists only as an elective, an optional internship, or an unassessed extracurricular or careers activity." | Add an elective clinical-engineering or MedTech-manufacturing placement subject, drawing on hospital HTM units and device-manufacturer host partnerships | [[19]](https://www.legislation.gov.au/F2021L00488)[27] |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Convert the placement elective into a short compulsory placement or live client project within BMEN90044, supervised and assessed against practitioner criteria | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice." | Extend the compulsory placement into a full-length practicum with structured reflection and documented accountability to the host organisation | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Embed an assessed module in BMEN90044 (or BMEN90039) on AI capabilities and limitations in MedTech design and regulatory workflows | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Require core assessment critiquing AI governance in medical-device data workflows — bias in AI-assisted regulatory drafting, data governance for AusUDID submissions | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Extend BMEN90044's team assessment criteria to require teams to document and justify which parts of their work used AI-assisted tools versus human effort | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Require BMEN90044 teams to identify and document their own knowledge gaps against the predetermined health need, with a plan to close them, ahead of the capstone deliverable | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make BMEN90044's Technical Oral Examination an explicit methodology defence for the primary evidence collected in BMEN90042, formally reviewed against a defended-methodology rubric | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Require BMEN90044's Lay Person Oral Presentation to be judged by an external panel of MedTech industry practitioners, with professional conduct assessed as an explicit criterion | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Refresh BMEN90039's regulatory-pathway assessment to name the UDI/AusUDID regime specifically, adding it as a live compliance constraint judged against the TGA's own submission standards | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| P1 | C2 | Sourced trade press describes AI increasingly drafting regulatory documentation and literature-review content — the profession's own "isn't about replacing engineers" framing says the judgement layer over that output remains human, and no compulsory assessment currently requires students to appraise it | §3 Theme 2; §5 CI-4 | MEDIUM |
| P2 | W3 | The two operational functions with documented real 2025 AI adoption (clinical/healthcare technology management, manufacturing quality) are functions the compulsory structure gives students no supervised exposure to | §3 Theme 3; §5 CI-2 | MEDIUM |
| P3 | C3 | The occupation carries GPT-4-class task exposure of roughly 26–54% (up to 82% on the most inclusive measure), while AI content sits only in a 25-point elective basket a student can complete the degree without choosing | §3 Theme 2; §5 CI-1 | HIGH for source quality, MEDIUM for Australian applicability |
| P4 | C1 | Compulsory assessment already reaches group work with individual accountability but not the level requiring the division of work between people and AI systems to itself be assessed | §5 CI-5 | MEDIUM |
| P5 | W2 | BMEN90039 already assesses regulatory-pathway evaluation as a compulsory outcome, but the evidence file records no UDI/AusUDID-specific content, even though Class IIb/III compliance became binding on 2026-07-01 | §3 Theme 1; §5 CI-3 | HIGH |
| P6 | C4 | A binding, evolving regulatory regime (TGA UDI/AusUDID) rewards self-scoped independent learning that extends beyond the taught BioDesign sequence | §3 Theme 1 | HIGH |
| P7 | W1 | The MedTech Commercialisation & Innovation Manager job family requires market and reimbursement-pathway communication to real external stakeholders | §1 Job Family map | LOW — no sourced study measures AI exposure or hiring signal for this function specifically |
| P8 | C5 | The Medical Device Design/R&D Engineer job family's core tasks (needs-discovery methodology, prototyping) directly match the program's own BioDesign sequence and reward a defended primary-evidence methodology | §1 Job Family map | MEDIUM — matches the program's own compulsory content; MEDIUM AI-substitution rating |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C2 | Add a self-assessment or reflection outcome to BMEN90044's team assessment | C2 level 1 | Low | Term 1; outcomes statement update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3) |
| P2 | C2 | Add a structured peer-review task marked against published criteria to BMEN90044's Team-based Written Assignment | C2 level 2 | Low | Term 1; assessment brief and rubric update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P3 | W2 | Refresh BMEN90039's regulatory content to name UDI/AusUDID specifically as an assessed compliance constraint | W2 level 3 | Low | Term 1; syllabus and marking-criteria update | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P4 | C1 | Extend BMEN90044's team assessment criteria to require documenting and justifying the AI-versus-human division of team effort | C1 level 3 | Low | Term 1; rubric-level change, aligned to the faculty's assessment-integrity policy on disclosed AI tool use | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P5 | C2 | Attach an assessed AI-reliance log to BMEN90044's team assignments | C2 level 3 | Medium | Term 2; assessment-design work, piloted against new marking criteria | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P6 | C3 | Embed an assessed module in BMEN90044 or BMEN90039 on AI capabilities and limitations in MedTech design and regulatory workflows | C3 level 2 | Medium | Term 2; syllabus and rubric update within an existing compulsory subject | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P7 | C4 | Require BMEN90044 teams to identify and document their own knowledge gaps against the predetermined health need, with a plan to close them | C4 level 3 | Medium | Term 2; assessment-design work ahead of the capstone deliverable | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P8 | W3 | Add an elective clinical-engineering or MedTech-manufacturing placement subject, drawing on hospital HTM units and device-manufacturer host partnerships | W3 level 1 | Medium | Next annual review cycle; requires host-organisation partnerships | [[19]](https://www.legislation.gov.au/F2021L00488)[27] |
| P9 | C3 | Require core assessment critiquing AI governance in medical-device data workflows — bias in AI-assisted regulatory drafting, data governance for AusUDID submissions | C3 level 3 | Medium–high | Next annual review cycle | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P10 | W1 | Require BMEN90044's Lay Person Oral Presentation to be judged by an external panel of MedTech industry practitioners | W1 level 3 | Medium | Next annual review cycle; external panel coordination | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P11 | C5 | Make BMEN90044's Technical Oral Examination an explicit methodology defence for the primary evidence collected in BMEN90042 | C5 level 3 | Medium | Future curriculum re-accreditation | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P12 | W3 | Convert the placement elective into a short compulsory placement or live client project within BMEN90044 | W3 level 2 | High | Future curriculum re-accreditation; restructures the 75/25 compulsory-elective split | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551) |
| P13 | W3 | Extend the compulsory placement into a full-length practicum with structured reflection and host accountability | W3 level 3 | High | Future curriculum re-accreditation | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | The course structure documents a coherent, all-compulsory specialist core: 75 credit points of compulsory subjects, including a 37.5-point capstone, comprising four MedTech/biomedical-engineering subjects (BMEN90042, BMEN90039, BMEN90043, BMEN90044) that progress from foundational content through management/regulation to a needs-discovery-to-capstone-concept-development sequence. | Retain the compulsory MedTech/biomedical-engineering core; ensure new peer-review, reliance-log or placement content is added within it rather than displacing its disciplinary depth. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | BMEN90044 requires teams to carry a real unmet health need through prototype and business-plan development under genuine market, regulatory and IP uncertainty, defended in a Team-based Technical Oral Examination; BMEN90039 additionally requires students to evaluate the process and regulations required to take a new medical device to market. | Preserve BMEN90044's live, defended capstone and BMEN90039's regulatory-evaluation task; avoid replacing either with scripted recall when adding UDI/AusUDID or AI-governance content. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C2 | 0 | 1 | +1 adaptive | 8 / 15 | 4 / 9 |
| P2 | C2 | 1 | 2 | +1 adaptive | 9 / 15 | 4 / 9 |
| P3 | W2 | 2 | 3 | +1 workplace | 9 / 15 | 5 / 9 |
| P4 | C1 | 2 | 3 | +1 adaptive | 10 / 15 | 5 / 9 |
| P5 | C2 | 2 | 3 | +1 adaptive | 11 / 15 | 5 / 9 |
| P6 | C3 | 1 | 2 | +1 adaptive | 12 / 15 | 5 / 9 |
| P7 | C4 | 2 | 3 | +1 adaptive | 13 / 15 | 5 / 9 |
| P8 | W3 | 0 | 1 | +1 workplace | 13 / 15 | 6 / 9 |
| P9 | C3 | 2 | 3 | +1 adaptive | 14 / 15 | 6 / 9 |
| P10 | W1 | 2 | 3 | +1 workplace | 14 / 15 | 7 / 9 |
| P11 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 7 / 9 |
| P12 | W3 | 1 | 2 | +1 workplace | 15 / 15 | 8 / 9 |
| P13 | W3 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name reflection, self-assessment or AI governance | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy a core-placement anchor (for example the AI-ethics or machine-learning electives for C3, or a placement elective for W3) | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |
| Justifying a W3 placement intervention by citing improved graduate employment rates | Jackson & Collings found WIL does not raise full-time employment rates; the honest basis is skill development, employment relevance and professional identity, with the equity cost of unpaid or relocation-dependent placements noted | W3 honesty rule; Jackson & Collings [[28]](https://doi.org/10.1007/s10734-017-0216-z); Jackson [[29]](https://doi.org/10.1080/07294360.2016.1139551); Australian Universities Accord [[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) | [[28]](https://doi.org/10.1007/s10734-017-0216-z)[[29]](https://doi.org/10.1080/07294360.2016.1139551)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
