// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Computer Science (UNSW-7003) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Computer Science (UNSW-7003)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-09-07 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-unsw-7003.md
**Position basis:** Destination AI Exposure 83.30 (field basis) × Curriculum Adaptiveness 5/15 (v4.2 draft, sub-scale A) · Workplace practice 2/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a field basis (Jobs and Skills Australia Higher Education Outcomes (JSA HEO) field 0201 Computer Science), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

UNSW's Diploma in Computer Science (unsw-7003) carries no destination record of its own, so it resolves to the field-of-education Computer Science exposure basis (83.3, estimated). Panel C v4 scores it 5/15 on the adaptive sub-scale and 2/9 on workplace practice: seven of the eight scored items sit at level 1 — outcomes and course overviews name a capability (teamwork, reflection, transfer, inquiry, professional conduct, contextualised tasks) that no core assessment yet tests against criteria — and work-situated learning (W3) is absent from the core sequence entirely.

The market evidence does not counsel retreat from the discipline. Jobs and Skills Australia's Generative AI Capacity Study finds ICT technical-development tasks are augmented rather than automated, and PwC's AI Jobs Barometer finds the most AI-exposed roles carry a wage premium and lean harder on human-intensive judgement. What it does show is a widening gap between what the diploma assesses and what entry employers now expect: assessed disclosure and verification of AI-assisted code, team tasks with documented role and tool allocation, and demonstrated experience — the last one increasingly gate-kept, with the Tech Council of Australia recording software-engineering ad volume roughly halving 2022-2025 while the share of employers expecting prior experience rose from 70% to 85%.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C1 Distributed cognition & relational capability | Adaptive | 1 / 3 | 2 | Teamwork appears in outcomes only; the advertisement sample for the program's largest destination family names System design and Code review & testing as rising skills (market report §2 Signal 1, §4) - both team-coordinated activities in practice. | 2 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | No criterion-referenced appraisal of quality in core assessment; PwC's AI Jobs Barometer finds the most AI-exposed roles rely 2.5x more on human-intensive judgement (market report §3 Theme 6), and the ACS Code of Professional Conduct makes competence and honesty a practitioner's own accountability regardless of what a tool generated (§3 Theme 2). | 3 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | AI content in the core is tool operation only; the market report names AI-assisted coding as a rising skill (7,476 postings, §2 Signal 1) and JSA's Generative AI Capacity Study finds ICT technical-development tasks highly augmentable, ~0.69 (§3 Theme 4) - capability and limitation, not just operation, is what the market is asking the core to teach. | 4 |
| C4 Life-long learning & transfer | Adaptive | 1 / 3 | 2 | No assessed transfer to unfamiliar problems; PwC's AI Jobs Barometer finds the most AI-exposed, most productive firms pay a wage premium for workers who apply skills beyond their original context (§3 Theme 6), and Cloud (K8s/Terraform) is a rising keyword in the program's largest destination family (§4). | 5 |
| C5 Inquiry & evidence generation | Adaptive | 1 / 3 | 2 | No assessed inquiry design in the core; the Computer Systems Analysts family (3,698 postings, §2 Signal 4) names Requirements analysis and System specification as rising skills - both investigative activities the core does not currently assess. | 6 |
| **Adaptive capabilities** | **Adaptive** | **5 / 15** | **10** | — | — |
| W3 Work-situated learning | Workplace | 0 / 3 | 3 | No work-situated learning in the core; entry employers increasingly require prior experience (Tech Council of Australia 2026: software-engineering ads roughly halved 2022-2025 while employer experience expectations rose from 70% to 85%, market report §2 Signal 4). | 1 |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Communication in the core stays academic, addressed to markers; ICT occupations carry no statutory licence in Australia, and the ACS Code and its voluntary Certified Professional scheme are the sector's own standard for professional conduct (market report §3 Themes 2, 3, 5), making the degree the primary signal of professional communication an employer can check. | 7 |
| W2 Authentic task design | Workplace | 1 / 3 | 2 | Core assessment carries no end-to-end professional task; the program's largest destination family (Software Developers, Applications, 7,476 postings) names Full-stack development, Cloud (K8s/Terraform), AI-assisted coding, Code review & testing and System design as its recurring rising skills (market report §2 Signal 1, §4) - none reproduced as a graded artefact in the core. | 8 |
| **Workplace practice** | **Workplace** | **2 / 9** | **7** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| W3 Work-situated learning | 0 → 1 | "Work-situated learning exists only as an elective, an optional internship, or an unassessed extracurricular or careers activity." | Establish an optional, unassessed industry-mentoring or short-internship pathway - brokered through the faculty careers service or an ACS-affiliate mentoring scheme - sign-posted alongside the core but not part of it. Employer experience expectations for entry software roles rose from 70% to 85% between 2022 and 2025 while ad volume roughly halved (Tech Council of Australia, market report §2 Signal 4), so an optional pathway lets a student accumulate documented experience before the core commits credit to it. Cost: a careers-service partnership and mentor recruitment; no unit or credit-point change. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Convert the existing professional-practice elective (DPST1071) into a core unit built around one supervised live-client or community-based project, assessed against practitioner-set criteria with a named host contact. This is warranted by skill development and professional-identity formation under supervision [[29]](https://doi.org/10.1080/07294360.2016.1139551), not by any claim on employment rates, and it carries an equity cost - unpaid or relocation-dependent placement time - that the program should budget for explicitly [[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report). Cost: moving one elective to core, recruiting and vetting hosts, and a supervision load. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the converted unit into a required two-stage sequence - an early short placement or live-client project followed by a longer one - with structured reflection assessed at each stage and documented accountability to the host (sign-off, deliverable acceptance). As at level 2, this is warranted by professional-identity formation, not employment outcomes [[29]](https://doi.org/10.1080/07294360.2016.1139551), and the equity cost of unpaid placement time should be met with a stipend or the Commonwealth Prac Payment where eligible, not assumed [[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report). Cost: a second placement cohort's worth of host relationships and supervision, plus a stipend budget. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Add an assessed group deliverable to DPST1093 Software Engineering Fundamentals with individually accountable components - a marked contribution log or peer-assessed role split alongside the team artefact. The advertisement sample for the program's largest destination family names System design and Code review & testing as rising, both team-coordinated activities (market report §2 Signal 1, §4). Cost: rewriting one unit's assessment brief and marking rubric; no new unit. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Extend the assessed collaboration into a later capstone-style task that documents how work was divided between team members and AI or other tools - who wrote what, what was AI-assisted, who reviewed it - assessed as part of the deliverable. The ACS Code of Professional Conduct (market report §3 Theme 2) makes that division of labour a practitioner's own accountability once AI tools are in use. Cost: a second assessed collaborative task and a tool-disclosure rubric; depends on C1:2 landing first. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Add a structured peer-review or critique stage to an existing core programming assessment, marked against published criteria drawn from code-review standards. PwC's AI Jobs Barometer finds the most AI-exposed roles rely more heavily on human-intensive judgement (market report §3 Theme 6) - criterion-referenced review is that judgement, made assessable. Cost: a rubric and one additional marked stage in an existing unit; no new unit. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Require students to document and justify a reliance decision on an AI coding assistant in the same assessment - where they accepted, edited or rejected a suggestion and why - marked on the reasoning, not the code alone. The ACS Code's competence and honesty obligations (market report §3 Theme 2) apply to a practitioner's sign-off on AI-assisted work regardless of what generated it. Cost: an added reflective component to the existing assessment; depends on C2:2's rubric. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Add a module to a core unit covering what generative coding assistants can and cannot verify - correctness, security, licensing - alongside their use, assessed via a short applied exercise. The market report names AI-assisted coding as a rising skill in the program's largest destination family (7,476 postings, §2 Signal 1), and JSA's Generative AI Capacity Study finds ICT technical-development tasks highly augmentable (§3 Theme 4) - capability AND limitation is what the anchor and the market both call for. Cost: a module addition and one assessed exercise inside an existing unit. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Add an assessed case exercise on AI governance in software practice - bias in generated code, accountability for an AI-assisted defect, data-handling obligations - set against the ACS Code of Professional Conduct and Australia's technology-neutral AI settings (market report §3 Themes 1 and 2). Cost: a case-study brief and marking guide; depends on C3:2's module. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 1 → 2 | "At least one core assessment requires application to novel or unfamiliar problems — case variation, unseen datasets, cross-context projects." | Set one core programming or mathematics assessment in an unfamiliar stack or domain the student has not been taught directly - a new language, framework or dataset - assessed on successful transfer, not on the taught material itself. Cloud tooling (K8s/Terraform) is a rising keyword in the program's largest destination family (market report §4), signalling exactly this kind of transfer demand. Cost: an alternative assessment brief for an existing unit. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Add a short, assessed self-audit at the end of the diploma sequence - a written identification of the student's own knowledge gaps against the Bachelor pathway they are articulating into, with a plan to close them. PwC's AI Jobs Barometer finding that AI-exposed junior roles increasingly need senior-level skills (market report §3 Theme 6) is the market case for building that self-assessment habit before articulation. Cost: a capstone-style reflective task in the final core unit; depends on C4:2 establishing transfer as an assessed norm. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 1 → 2 | "Students design and conduct an inquiry with methodology selection and data collection, assessed." | Move one of the Additional-Courses physics or biomolecular options' experiment-design element into the compulsory core, or add an equivalent assessed mini-investigation (a defined question, a chosen method, data collected and interpreted) to a core unit. The Computer Systems Analysts destination family names Requirements analysis and System specification as rising skills (market report §2 Signal 4) - both investigative activities the diploma does not currently assess in its core. Cost: a core-unit assessment redesign or moving an Additional Course into the core. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Require the mini-investigation from C5:2 for every student, not one route among several, and add a short defended review - a supervised viva or staged check-in - of the methodology chosen. Cost: making an optional route compulsory and adding a supervised review stage; depends on C5:2 existing first. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Redirect one core oral or written assessment from an academic audience to a professional genre - a client-style technical brief or a stand-up delivered to a practitioner panel - marked against criteria drawn from practice rather than academic convention. ICT occupations carry no statutory licence in Australia, so the ACS's voluntary Certified Professional standard and the degree itself are the practitioner-facing signal a graduate carries (market report §3 Themes 3 and 5). Cost: rewriting the brief and criteria for an existing communication assessment; no new unit. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Repeat the professional-genre assessment from W1:2 at a later stage of the program and bring in an external judge - an industry panel, an ACS member, or an employer partner - to score it against practice-drawn criteria that include professional conduct. Cost: a second assessed instance plus recruiting and briefing external assessors; depends on W1:2's criteria existing first. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Replace one core programming assessment's abstract problem set with a realistic client-style brief - an ambiguous requirement, a real or representative dataset - producing the artefact a working developer would produce (a working feature, a system-design document), marked against practice-drawn criteria. The program's largest destination family names Full-stack development, System design and Code review & testing as its recurring rising skills (market report §2 Signal 1, §4); a professional-form task is how the core would assess them. Cost: rewriting one assessment brief and its criteria; no new unit. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Make the W2:2 task-type the assessment spine - one per stage of the sequence, culminating in a capstone - and add a genuine practice constraint to at least one instance: an externally supplied or ambiguous brief, a real resource or time limit, or a consequential audience (a client sign-off, not just a marker). Cost: redesigning assessment across multiple core units rather than one; depends on W2:2 establishing the task type first. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| W3 - work-situated learning | W3 | Tech Council of Australia 2026 update: software-engineering job ads roughly halved 2022-2025 while employer experience expectations rose from 70% to 85%. | §2 Signal 4 | HIGH |
| C1 - team accountability & tool allocation | C1 | System design and Code review & testing recurring in the 7,476-posting Software Developers, Applications sample; the ACS Code of Professional Conduct binds practitioner accountability once AI tools are in use. | §2 Signal 1; §3 Theme 2 | HIGH |
| C2 - criterion-referenced review & reliance decisions | C2 | PwC's AI Jobs Barometer finds AI-exposed roles rely 2.5x more on human-intensive judgement; the ACS Code requires competence and honesty regardless of what generated the work. | §3 Themes 6, 2 | HIGH |
| C3 - AI capability, limits and governance | C3 | AI-assisted coding named in the 7,476-posting sample; JSA's Generative AI Capacity Study finds ICT technical-development tasks highly augmentable (~0.69); Australia's National AI Plan leaves governance to existing law and professional codes. | §2 Signal 1; §3 Themes 4, 1, 2 | HIGH |
| C4 - transfer to unfamiliar contexts | C4 | Cloud (K8s/Terraform) rising in the same sample; PwC finds the most AI-exposed, most productive firms pay a ~68% wage premium - the market rewards transfer, not repetition. | §4 Skill shift summary; §3 Theme 6 | HIGH |
| C5 - assessed inquiry design | C5 | Requirements analysis and System specification rising in the 3,698-posting Computer Systems Analysts sample. | §2 Signal 4 | HIGH |
| W1 - professional-genre communication | W1 | ICT occupations carry no statutory licence in Australia; the ACS Certified Professional scheme is the sector's own voluntary standard, making the degree the primary competence signal employers can check. | §3 Themes 3, 5 | HIGH |
| W2 - authentic end-to-end task | W2 | Full-stack development, Cloud (K8s/Terraform), AI-assisted coding, Code review & testing and System design are the recurring rising skills in the program's largest destination family (7,476 postings). | §2 Signal 1; §4 | HIGH |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C3 | Add a module on generative coding assistants' capabilities and limits (correctness, security, licensing) to a core unit, assessed via a short applied exercise. | Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed. | low | Term 1 - assessment-brief change within an existing unit | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P2 | C1 | Add an assessed group deliverable to DPST1093 with an individually accountable component (contribution log or peer-assessed role split). | At least one core unit assesses collaborative practice - group projects with individual accountability, client or stakeholder work, interprofessional activity. | low | Term 1 - assessment-brief change within an existing unit | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P3 | C2 | Add a structured peer-review or critique stage, marked against published code-review criteria, to an existing core programming assessment. | Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars. | low | Term 1 - rubric addition within an existing unit | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P4 | W1 | Redirect one core communication assessment from an academic audience to a professional genre (client-style brief or practitioner-panel presentation), marked against practice-drawn criteria. | At least one core assessment requires a recognised professional genre or an audience beyond the teaching team - client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact - judged against criteria drawn from professional practice. | low | Term 1 - brief and criteria rewrite within an existing unit | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P5 | W2 | Replace one core programming assessment's abstract problem set with a realistic client-style brief producing a practitioner artefact, marked against practice-drawn criteria. | At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice. | medium | Term 1 - assessment redesign within an existing unit | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P6 | C4 | Set one core assessment in an unfamiliar stack, framework or dataset, assessed on successful transfer rather than taught material. | At least one core assessment requires application to novel or unfamiliar problems - case variation, unseen datasets, cross-context projects. | medium | Term 1 - alternative assessment brief within an existing unit | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P7 | W3 | Establish an optional, unassessed industry-mentoring or short-internship pathway brokered through the careers service or an ACS-affiliate scheme. | Work-situated learning exists only as an elective, an optional internship, or an unassessed extracurricular or careers activity. | medium | Term 1 - careers-service partnership, no credit change | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P8 | C5 | Move a physics/biomolecular Additional Course's experiment-design element into the core, or add an equivalent assessed mini-investigation to a core unit. | Students design and conduct an inquiry with methodology selection and data collection, assessed. | medium | Term 2 - core-unit assessment redesign | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P9 | C3 | Add an assessed case exercise on AI governance in software practice (bias, accountability, data handling), set against the ACS Code and Australia's AI settings. | Core assessment requires critique or governance of AI systems in the discipline's own context - bias, accountability, transparency, regulation or data governance - beyond tool operation. | medium | Term 2 - depends on C3 module landing first | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P10 | C2 | Require students to document and justify a reliance decision on an AI coding assistant within the same assessment, marked on the reasoning. | Assessment requires students to document and justify reliance decisions - when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment). | low | Term 2 - depends on C2's rubric landing first | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P11 | C1 | Extend collaboration into a later capstone-style task documenting the division of work between team members and AI/other tools, assessed. | Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems - e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed. | medium | Term 2 - depends on C1's group deliverable landing first | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P12 | W1 | Repeat the professional-genre assessment at a later stage with an external judge (industry panel, ACS member, employer partner) scoring against practice-drawn criteria. | Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria. | medium | Term 2 - depends on W1's criteria landing first | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P13 | C4 | Add a short, assessed self-audit at the end of the sequence: students identify their own knowledge gaps against the Bachelor pathway with a plan to close them. | The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them. | low | Term 2 - depends on C4's transfer assessment landing first | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P14 | C5 | Make the mini-investigation compulsory for every student and add a short defended review (viva or staged check-in) of the methodology chosen. | A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review). | medium | Term 3 - depends on C5's mini-investigation landing first | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P15 | W2 | Make the professional-task type the assessment spine (one per stage, culminating in a capstone) with a genuine practice constraint on at least one instance. | Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice - an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance. | high | Term 3 - depends on W2's first authentic task landing | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P16 | W3 | Convert the professional-practice elective (DPST1071) into a core unit built around one supervised live-client or community-based project, assessed against practitioner-set criteria. | A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment - placement, practicum, live client project, community-based project - OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure - but it is short or stands alone. | high | Term 3 - curriculum-committee conversion of an elective to core | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P17 | W3 | Extend the converted unit into a required two-stage sequence with structured reflection assessed at each stage and documented accountability to the host. | Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice - OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer). | high | Term 4+ - depends on W3's core placement unit landing first | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | PASS on the all-compulsory specialist core plus staged prerequisite chain route: 30 of the 48 UOC are a compulsory computer-science and mathematics core, and the handbook documents the chain - Computer Systems Fundamentals assumes the prior C programming course, Software Engineering Fundamentals follows it, and Mathematics 1B follows 1A. The content carries clear disciplinary identity rather than being generic or interchangeable, and the sequence is credited as equivalent to first-year Bachelor of Computer Science study. The depth is first-year foundational, which the gate does not exclude. | None of the interventions above should reduce the compulsory computer-science and mathematics core or break the Computer Systems Fundamentals -> Software Engineering Fundamentals / Mathematics 1A -> 1B prerequisite chain that carries this PASS. Adding assessment components to existing core units (C1-C5, W1, W2) is compatible with the gate; only the two W3 steps that convert an elective into a core unit need a curriculum-committee check that the conversion does not displace a compulsory technical unit. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | FAIL | FAIL: no core assessment is documented as requiring defended trade-off decisions, and no capstone, simulation or live project with real uncertainty and accountability appears in the compulsory core. The core mathematics outcomes are statement, proof and application of syllabus techniques to appropriate problems - the scripted-response side of the anchor - and the programming outcomes are construction of a correct program to a given specification. The one course whose overview does describe budget, time and resource constraints on a poorly specified, open-ended problem is DPST1071, which sits in the Additional Courses list rather than the core, and its assessment record is an undescribed mode. | G2 stays FAIL under every intervention above: none of them adds a core assessment with defended trade-off decisions or real uncertainty and accountability. A redesign aimed at G2 must be pursued separately - for example, giving DPST1071's open-ended, resource-constrained problem a core home with an assessed, defended trade-off decision - and moving that unit to core is not sufficient on its own unless its assessment is redesigned to test judgement under genuine uncertainty, not just completion. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | W3 | 0 | 1 | +1 workplace | 5 / 15 | 3 / 9 |
| P2 | W3 | 1 | 2 | +1 workplace | 5 / 15 | 4 / 9 |
| P3 | W3 | 2 | 3 | +1 workplace | 5 / 15 | 5 / 9 |
| P4 | C1 | 1 | 2 | +1 adaptive | 6 / 15 | 5 / 9 |
| P5 | C1 | 2 | 3 | +1 adaptive | 7 / 15 | 5 / 9 |
| P6 | C2 | 1 | 2 | +1 adaptive | 8 / 15 | 5 / 9 |
| P7 | C2 | 2 | 3 | +1 adaptive | 9 / 15 | 5 / 9 |
| P8 | C3 | 1 | 2 | +1 adaptive | 10 / 15 | 5 / 9 |
| P9 | C3 | 2 | 3 | +1 adaptive | 11 / 15 | 5 / 9 |
| P10 | C4 | 1 | 2 | +1 adaptive | 12 / 15 | 5 / 9 |
| P11 | C4 | 2 | 3 | +1 adaptive | 13 / 15 | 5 / 9 |
| P12 | C5 | 1 | 2 | +1 adaptive | 14 / 15 | 5 / 9 |
| P13 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 5 / 9 |
| P14 | W1 | 1 | 2 | +1 workplace | 15 / 15 | 6 / 9 |
| P15 | W1 | 2 | 3 | +1 workplace | 15 / 15 | 7 / 9 |
| P16 | W2 | 1 | 2 | +1 workplace | 15 / 15 | 8 / 9 |
| P17 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
