// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of International Journalism (MC-INTJOUR) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of International Journalism (MC-INTJOUR)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-30 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-intjour.md
**Position basis:** Destination AI Exposure 91.48 (cognate basis) × Curriculum Adaptiveness 7/15 (v4.2 draft, sub-scale A) · Workplace practice 5/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a cognate basis (Master of Journalism), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

This program scores 7 of 15 on curriculum adaptiveness and 5 of 9 on workplace practice. Four items sit at the lowest scored level — collaborative practice, evaluative judgement, AI literacy and work-situated learning — and four sit one level below maximum. The market report shows sustained live demand for public relations, communications and stakeholder-engagement skill (§2 Signal 1) alongside a national study that expects generative AI to augment rather than replace that work (§3 Theme 2), and separately places writers and communications-adjacent occupations among those most exposed to automation (§3 Theme 4). The interventions below target the anchor levels this evidence warrants, each at the cost stated.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C1 Distributed cognition & relational capability | Adaptive | 1 / 3 | 2 | §2 Signal 1: 1,024 postings recurring "stakeholder engagement" and "media relations" keywords for Public Relations Specialists, whose collaborative and stakeholder-facing work is currently unassessed in the core. | 1 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | §3 Theme 2: Jobs and Skills Australia's Gen AI Capacity Study finds generative AI more likely to augment than replace Public Relations Specialists' work, raising the value of assessed judgement over AI-assisted output. | 2 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | §3 Theme 4: JSA's Gen AI Transition exposure data places writers, editors and public-relations roles among the occupations most exposed to automation. | 3 |
| C4 Life-long learning & transfer | Adaptive | 2 / 3 | 1 | §2 Signal 4: only 6 postings for Market Research Analysts and Marketing Specialists against the much larger Signal 1 and Signal 2 counts, favouring a documented capacity to redirect learning toward the higher-demand destinations. | 5 |
| C5 Inquiry & evidence generation | Adaptive | 2 / 3 | 1 | §3 Theme 3: the Copyright Act 1968 (Cth) and the Australian Society of Authors' copyright-reform advocacy are the kind of primary-evidence question a required research capstone would investigate rather than take as given. | 6 |
| **Adaptive capabilities** | **Adaptive** | **7 / 15** | **8** | — | — |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | §2 Signal 1 and Signal 2: 1,024 Public Relations Specialists postings and 301 Writers and Authors postings show live hiring across the program's two largest destination families. | 4 |
| W1 Professional communication & conduct | Workplace | 2 / 3 | 1 | §2 Signal 1 and §3 Theme 2: sustained Public Relations Specialists demand in a market that expects graduates' communication work to be augmented by generative AI, not replaced by it. | 7 |
| W2 Authentic task design | Workplace | 2 / 3 | 1 | §2 Signal 3 and §3 Theme 6: routine, rules-based office-clerk-type tasks are the most automation-exposed in this report's evidence, favouring assessment built around a genuine constraint of practice over a routine one. | 8 |
| **Workplace practice** | **Workplace** | **5 / 9** | **4** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Add an individually accountable group or stakeholder-facing task to one core subject's assessment table — for example, a joint media-relations campaign brief marked with both team and individual components. Signal 1 (§2) shows sustained demand for stakeholder-engagement and media-relations skill that this task would assess directly. Cost: redesigning group-marking criteria and moderation. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Once that task exists, extend it so a comparable task recurs elsewhere in the program and one instance requires students to document how work was divided between people and AI tools. Theme 2 (§3) frames generative AI as augmenting rather than replacing communications work, which makes the human/AI division of labour itself worth assessing. Cost: a second core subject's assessment redesign plus updated moderation guidance. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Add a criterion-referenced peer-review or exemplar-marking task to one core subject, marking student work against a shared rubric or exemplar bank. Signal 1 (§2) and Theme 2 (§3)'s augment-not-replace framing mean graduates will increasingly judge communications output, not only produce it. Cost: developing marking exemplars and a rubric, moderated each teaching period. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Once that task exists, add a short reliance-justification component asking students to document and defend one specific reliance decision — where they relied on or overrode a source, tool or collaborator. This follows directly from the augment-not-replace reading of Theme 2 (§3): evaluative judgement over AI-assisted work is the skill the market expects. Cost: an additional marked component and rubric criterion, built on the C2:2 task. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Move one AI-content topic — for example, the elective content on fact-checking, misinformation and AI — into a core subject's assessed content, addressing both AI capability and its limitations. Theme 4 (§3) places writers and communications-adjacent roles among the occupations most exposed to automation, which argues against leaving AI literacy optional. Cost: core-subject redesign and, if the compulsory list is fixed, a unit-of-study proposal. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Once AI literacy is core, add a governance-focused task — for example, critiquing a real newsroom or PR AI-tool deployment for bias, transparency or accountability. Theme 2 (§3)'s Gen AI Capacity Study is itself an example of the governance literature such a task could draw on. Cost: sourcing case material and a governance-specific marking rubric, built on the C3:2 task. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Move the Internship from an optional capstone-stream choice to a required core placement, supervised by a practitioner and assessed. Signal 1 (§2) and Signal 2 (§2) show live employer demand across the destinations this placement would serve. Per the W3 honesty rule, justify this by skill development and professional identity, not by employment-rate claims, and note the equity cost of unpaid or relocation-dependent placement. Cost: placement-coordinator capacity to source and supervise a compulsory cohort-wide intake. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Once placement is core, extend it into a supervised sequence with structured reflection and documented accountability to the host. Theme 1 (§3) — public relations is self-regulated with no statutory licensing — means supervised placement is one of the few mechanisms available to certify professional conduct before graduates enter the profession. Cost: a second placement unit or an extended single placement, plus reflective-journal marking. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Add a self-scoped element to the Minor Thesis or Journalism Project capstone stream, or an assessed knowledge-gap-and-plan task earlier in the program. Signal 4 (§2)'s thin Market Research Analysts and Marketing Specialists count against Signal 1 and Signal 2's larger counts favours a documented capacity to redirect learning toward the higher-demand destinations. Cost: capstone-proposal marking criteria and supervisory capacity for self-scoped topics. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make the Minor Thesis, or an equivalent primary-evidence-generating capstone, a required route rather than one of three optional streams, with methodology defended under staged supervised review. Theme 3 (§3) — the Copyright Act 1968 (Cth) and the ongoing copyright-reform debate — is the kind of primary-evidence question a required research capstone would equip graduates to investigate. Cost: reduced capstone-stream choice, and additional supervision load if the Internship and Journalism Project streams are retained alongside it. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Add a practitioner-judged component — an industry-panel review or client brief — to one core communication assessment, with professional conduct explicitly among the assessed criteria. Signal 1 (§2)'s advertisement volume and Theme 2 (§3)'s augment-not-replace framing both point to sustained demand for graduates whose professional communication is judged by practitioners, not only markers. Cost: sourcing and briefing panel practitioners each teaching period. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Add a genuine constraint of practice — an externally supplied brief, a real resource or time limit, or a consequential audience — to one of the program's existing practitioner-artefact assessments (the news, audio, video or photojournalism portfolios). Signal 3 (§2) and Theme 6 (§3) single out routine, rules-based tasks as the most automation-exposed, which argues for constraint-bearing tasks over routine ones. Cost: sourcing an external brief-setter and adjusting the marking rubric to assess how students handle the added constraint. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| Public relations / stakeholder-engagement demand | C1 | 1,024 postings recurring "stakeholder engagement" and "media relations" keywords for Public Relations Specialists | §2 Signal 1 | MEDIUM |
| Generative AI expected to augment, not replace, PR and communications work | C2 | Jobs and Skills Australia's Gen AI Capacity Study finds Gen AI more likely to augment than replace this occupation family | §3 Theme 2 | MEDIUM |
| Writers and communications-adjacent automation exposure | C3 | JSA's Gen AI Transition exposure data places writers, editors and public-relations roles among the most automation-exposed occupations | §3 Theme 4 | MEDIUM |
| Live hiring across the program's two largest destination families | W3 | 1,024 postings for Public Relations Specialists and 301 postings for Writers and Authors | §2 Signal 1; §2 Signal 2 | MEDIUM |
| Self-regulated profession with no statutory licensing | W1 | Communication and Public Relations Australia offers voluntary accreditation; no statutory licensing of PR practitioners | §3 Theme 1 | MEDIUM |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C1 | Add an individually accountable group or stakeholder-facing task to one core subject's assessment table. | C1 level 1 → 2 | medium | Next offering | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P2 | C2 | Add a criterion-referenced peer-review or exemplar-marking task to one core subject. | C2 level 1 → 2 | medium | Next offering | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P3 | C3 | Move one AI-content elective topic into a core subject's assessed content. | C3 level 1 → 2 | high | Next offering | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P4 | W3 | Move the Internship from an optional capstone-stream choice to a required, supervised core placement. | W3 level 1 → 2 | high | Following offering, once placement-coordinator capacity is confirmed | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P5 | W1 | Add a practitioner-judged component to one core communication assessment. | W1 level 2 → 3 | medium | Next offering | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P6 | W2 | Add a genuine constraint of practice to one existing practitioner-artefact assessment. | W2 level 2 → 3 | medium | Next offering | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P7 | C4 | Add a self-scoped element to the capstone stream, or an assessed knowledge-gap-and-plan task earlier in the program. | C4 level 2 → 3 | medium | Following offering | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P8 | C5 | Make the Minor Thesis, or an equivalent primary-evidence capstone, a required route with methodology defended under staged supervised review. | C5 level 2 → 3 | high | Following offering, once supervision capacity is confirmed | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P9 | C2 | Add a reliance-justification component to the C2:2 peer-review task. | C2 level 2 → 3 | low | Once C2:2 has landed | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P10 | C1 | Extend the C1:2 task so a comparable task recurs elsewhere in the program, with one instance requiring documentation of the human/AI division of labour. | C1 level 2 → 3 | medium | Once C1:2 has landed | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P11 | C3 | Add a governance-focused task critiquing a real AI-tool deployment in the discipline's own context. | C3 level 2 → 3 | medium | Once C3:2 has landed | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P12 | W3 | Extend the required placement into a supervised sequence with structured reflection and documented accountability to the host. | W3 level 2 → 3 | high | Once W3:2 has landed and placement capacity has scaled | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | The program documents a staged prerequisite chain within a concentrated JOUR-coded specialist core: the compulsory Key Skills subject is a prerequisite for three core subjects, and the core-subject list builds from foundational to advanced journalism skills (including Investigative Journalism), showing progressive disciplinary depth rather than generic, interchangeable content. | Any redesign must keep the JOUR-coded specialist core's staged prerequisite chain and its progression from foundational to advanced journalism skills intact — do not dilute the core with generic or interchangeable content to make room for the interventions above. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | Investigative Journalism documents assessed real uncertainty and accountability: students must initiate an original investigation whose outcome is not guaranteed, with a built-in contingency if the investigation does not succeed, and are introduced to real ethical/legal trade-offs around confidential sources and unauthorised disclosures. | Any redesign must preserve Investigative Journalism's assessed real, undetermined-outcome investigation and its confidential-source and unauthorised-disclosure trade-offs — do not replace that assessment with a scripted or risk-free exercise when adding the components above. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C1 | 1 | 2 | +1 adaptive | 8 / 15 | 5 / 9 |
| P2 | C1 | 2 | 3 | +1 adaptive | 9 / 15 | 5 / 9 |
| P3 | C2 | 1 | 2 | +1 adaptive | 10 / 15 | 5 / 9 |
| P4 | C2 | 2 | 3 | +1 adaptive | 11 / 15 | 5 / 9 |
| P5 | C3 | 1 | 2 | +1 adaptive | 12 / 15 | 5 / 9 |
| P6 | C3 | 2 | 3 | +1 adaptive | 13 / 15 | 5 / 9 |
| P7 | W3 | 1 | 2 | +1 workplace | 13 / 15 | 6 / 9 |
| P8 | W3 | 2 | 3 | +1 workplace | 13 / 15 | 7 / 9 |
| P9 | C4 | 2 | 3 | +1 adaptive | 14 / 15 | 7 / 9 |
| P10 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 7 / 9 |
| P11 | W1 | 2 | 3 | +1 workplace | 15 / 15 | 8 / 9 |
| P12 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
