// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Education in Evidence-Based Teaching (MC-EDEBT) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Education in Evidence-Based Teaching (MC-EDEBT)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-29 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-edebt.md
**Position basis:** Destination AI Exposure 92.44 (variant basis) × Curriculum Adaptiveness 8/15 (v4.2 draft, sub-scale A) · Workplace practice 4/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

Master of Education in Evidence-Based Teaching scores 8/15 on adaptive capabilities and 4/9 on workplace practice. The clearest gaps sit at the floor: collaborative and relational capability (C1) and AI literacy and governance (C3), both at level 1. Both have a direct market warrant in reports/dfva-market-mc-edebt.md — the Gen AI Capacity Study finds education-professional tasks cluster toward higher AI exposure because core work (lesson planning, resource creation, feedback, assessment drafting) is language- and knowledge-intensive (§3 Theme 2), and the Framework for Generative AI in Schools together with AITSL's Principal Standard put AI governance inside standard school-leadership practice (§3 Themes 5–6) — matching the sharply rising 'AI' keyword in the Education Administrator advertisement sample (§2 Signal 3; §4 skill shift row, 651 postings).

Professional communication (W1) and authentic task design (W2) also sit at level 1. The 2026 state shift toward oral, performance and in-person assessment to curb AI-assisted cheating (§3 Theme 3) gives W2 a direct warrant, and recurring 'staff', 'training' and 'leadership' keywords in the administrator sample give W1 one. The remaining items — C2, C4, C5 and W3 — each sit one level short of the maximum and can move with additions to existing assessed tasks; C5's step depends on removing the Research Pathway's entry gate, a more substantial structural change. Both gates pass and constrain how the interventions below may be sequenced.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C1 Distributed cognition & relational capability | Adaptive | 1 / 3 | 2 | Core teaching and leadership tasks are readily AI-supported (§3 Theme 2), and the Framework for Generative AI in Schools governs how all school-connected people use these tools together (§3 Theme 5) — both reward assessed evidence of coordinating work across people and AI systems, not only among people. | 1 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | The Framework for Generative AI in Schools (§3 Theme 5, bearing directly on C3) and the Responsible AI Australia brief's procurement and privacy-due-diligence obligations (§3 Theme 4) make AI governance a binding constraint on school practice, and AI is the most sharply rising keyword in the Education Administrator advertisement sample (§2 Signal 3; §4 skill shift row, 651 postings). | 2 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 2 / 3 | 1 | Because lesson planning, feedback and assessment drafting are readily AI-supported (§3 Theme 2), and the Responsible AI Australia brief requires a human to remain in the loop on judgements such as marking and report writing (§3 Theme 4), graduates need documented practice defending when to rely on, override or revise an AI-drafted output. | 5 |
| C4 Life-long learning & transfer | Adaptive | 2 / 3 | 1 | The regulatory and technological environment shaping teaching practice has shifted repeatedly within a single year — new state assessment-integrity rules (§3 Theme 3), the Responsible AI Australia brief (§3 Theme 4), and the national Framework only endorsed in 2025 (§3 Theme 5) — evidencing that practitioners need structured capacity for independent continued learning rather than a fixed body of content, since what counts as compliant practice keeps changing. | 6 |
| C5 Inquiry & evidence generation | Adaptive | 2 / 3 | 1 | AITSL's Accreditation Standards tie initial teacher education directly to graduates meeting the evidence-based Australian Professional Standards for Teachers (§3 Theme 1), warranting a required, defended inquiry component rather than an optional research route. | 7 |
| **Adaptive capabilities** | **Adaptive** | **8 / 15** | **7** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Recurring 'staff', 'training' and 'leadership' keywords in the Education Administrator sample (§2 Signal 3, 651 postings) point to communication and conduct responsibilities toward staff, and the Responsible AI Australia brief and the national Framework both hold school leaders and teachers to explicit privacy-compliant conduct obligations when communicating and reporting using AI-assisted tools (§3 Themes 4–5). | 3 |
| W2 Authentic task design | Workplace | 1 / 3 | 2 | State education departments' 2026 shift toward oral, performance and in-person assessment to curb AI-assisted cheating (§3 Theme 3) rewards a program whose own assessment tasks model that same authentic, practice-based design rather than conventional written assignments. | 4 |
| W3 Work-situated learning | Workplace | 2 / 3 | 1 | Job-advertisement volume spans all four destination occupations (§2 Signals 1–4, 1,155 postings combined), and AITSL ties the qualification directly to registration to practise (§3 Theme 1) — both reward a required, assessed sequence of own-practice activity with documented accountability to school stakeholders for this already-practising cohort. | 8 |
| **Workplace practice** | **Workplace** | **4 / 9** | **5** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Convert part of EDUC90828's assessed online-discussion contribution (20%) into a small-group collaborative task with individual accountability, an option since the Framework for Generative AI in Schools governs how all school-connected people, including collaborating staff, work together (§3 Theme 5) (cost: revised task design and rubric within the existing unit, no new unit). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Extend that collaborative task to require documented allocation of work between team members and an AI tool — for example a shared resource where student roles and AI-tool use are both recorded and assessed — an option since core teaching tasks such as lesson planning and resource creation are readily AI-supported (§3 Theme 2) and AI is the most sharply rising keyword in the Education Administrator sample (§2 Signal 3; §4 skill shift row) (cost: a revised group-assessment rubric documenting tool allocation; depends on the C1:2 step). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Extend the course-level ICT-capacity generic-skills line into an assessed topic in a core unit covering AI capabilities and limitations/ethics, an option since the Framework for Generative AI in Schools (§3 Theme 5) and the Responsible AI Australia brief's privacy-due-diligence requirements (§3 Theme 4) are both binding on Australian teachers and administrators (cost: one assessed topic slot within an existing core unit, no new unit). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Add a governance-focused assessment task on AI procurement, data privacy or human-in-the-loop marking decisions, an option since the Responsible AI Australia brief makes privacy due diligence and keeping a human in the loop on marking and report writing binding obligations for schools (§3 Theme 4), and AI is the most sharply rising keyword in the administrator sample (§2 Signal 3; §4 skill shift row) (cost: a new assessed component; depends on the C3:2 step). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Convert EDUC90926's assessed presentation (20%) into a genre judged against a professional standard — for example a staff-briefing or parent-communication brief — an option since 'staff', 'training' and 'leadership' recur as keywords in the Education Administrator sample (§2 Signal 3, 651 postings) (cost: revised task brief and criteria within the existing unit). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Add a real or simulated external audience — a school-leadership panel — to that progressive communication task, with privacy-compliant conduct assessed explicitly, an option since the Framework for Generative AI in Schools and the Responsible AI Australia brief both hold school-connected people to explicit conduct obligations around student data and AI use (§3 Themes 4–5) (cost: recruiting or scheduling an external panel; depends on the W1:2 step). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Convert one of EDUC90832's or EDUC90862's case-study/practical-activity tasks into an assessed artefact of the kind a teacher would actually produce — a lesson sequence or intervention plan — judged against practice-derived criteria rather than an academic written-report rubric, an option since state education departments are already shifting classroom assessment toward practice-based, less-AI-exposed formats (§3 Theme 3) (cost: revised task brief and criteria within an existing unit). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Extend that practice-based task across two or more core units and add a genuine constraint of practice — an ambiguous, real classroom scenario or an externally supplied case — an option since the same 2026 policy shift toward oral, performance and in-person assessment (§3 Theme 3) rewards a program whose own assessment spine models that shift (cost: coordinated redesign across units; depends on the W2:2 step). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Add a reflective component to EDUC90926's literature-review task or EDUC90828's judgement-based-assessment report requiring students to document and justify a decision to rely on, override or revise an AI-drafted lesson plan, resource or feedback item, an option since core teaching tasks are readily AI-supported (§3 Theme 2) and the Responsible AI Australia brief requires a human to remain in the loop on marking and report-writing judgements (§3 Theme 4) (cost: an added reflective element within an existing assessment, no new task). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Add a structured, assessed self-audit of practice gaps to EDUC90862's existing written report, or open the Research Pathway's self-negotiated Applied Research Study (EDUC90945) to Coursework Pathway students rather than gating it behind an H2A average, an option since three binding instruments — state assessment-integrity rules (§3 Theme 3), the Responsible AI Australia brief (§3 Theme 4) and the national Framework endorsed only in 2025 (§3 Theme 5) — arrived within a single year, showing graduates need structured capacity for independent continued learning as compliant practice keeps changing (cost: either an added self-audit component within an existing unit, or removing the Research Pathway's entry gate). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Open the Applied Research Methodology / Applied Research Study sequence (EDUC90848, EDUC90945) to all students as a required, staged, supervised methodology-defence milestone rather than an optional Research Pathway gated by an H2A average, an option since AITSL's Accreditation Standards tie initial teacher education directly to graduates meeting the evidence-based Australian Professional Standards for Teachers (§3 Theme 1) (cost: removing the Research Pathway's entry gate and adding supervision capacity for all students, a substantial structural change). | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend EDUC90978's Clinical Praxis Presentation into a required sequence across two or more core units, each assessing own-practice activity with structured reflection and documented accountability to the student's school, an option since job-advertisement volume spans all four destination occupations (§2 Signals 1–4, 1,155 postings combined) and AITSL ties the qualification directly to registration to practise (§3 Theme 1) (cost: sustained supervision and moderation load across units; note the workload cost for students already teaching full-time). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| AI governance now binding on school leadership | C3 | The Framework for Generative AI in Schools and AITSL's Principal Standard both make responsible AI governance part of standard school-leadership practice. | §3 Themes 5–6 | HIGH |
| AI governance now binding on school leadership | W1 | The same Framework requires privacy-compliant conduct from all school-connected people, not leaders alone. | §3 Theme 5 | HIGH |
| AI governance now binding on school leadership | C1 | The same Framework governs how all school-connected people, including collaborating staff, use these tools together. | §3 Theme 5 | HIGH |
| Education-professional AI exposure via language-intensive tasks | C2 | Core teaching tasks — lesson planning, resource creation, feedback, assessment drafting — are language- and knowledge-intensive and readily AI-supported, raising the bar for a teacher's own evaluative judgement of AI-drafted output. | §3 Theme 2 | HIGH |
| State assessment-integrity crackdown shifts toward authentic, in-person assessment | W2 | NSW and Victorian policy changes curbing AI-assisted cheating are moving classroom assessment toward oral, performance and in-person modes. | §3 Theme 3 | HIGH |
| Rapid regulatory change in AI-era schooling | C4 | Three binding instruments — state assessment-integrity rules, the Responsible AI Australia brief and the national Framework — arrived within a single year, showing practitioners need capacity for continued independent learning as compliant practice keeps changing. | §3 Themes 3–5 | HIGH |
| Sharply rising AI, training and leadership keywords in the administrator destination | W1 | AI, training and leadership recur as keywords in the highest-volume destination sample (Education Administrators, 651 postings), pointing to a growing staff-facing communication and training role. | §2 Signal 3; §4 skill shift row | HIGH |
| Regulatory grounding in evidence-based practice | C5 | AITSL's Accreditation Standards tie initial teacher education directly to graduates meeting the evidence-based Australian Professional Standards for Teachers. | §3 Theme 1 | HIGH |
| High job-advertisement volume across an already-practising cohort | W3 | Job-advertisement volume spans all four destination occupations, and AITSL ties the qualification directly to registration to practise, rewarding demonstrated own-practice competence for a cohort already teaching. | §2 Signals 1–4; §3 Theme 1 | HIGH |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C2 | Add a documented, justified reliance-decision component to EDUC90926's literature-review task or EDUC90828's judgement-based-assessment report, requiring students to justify reliance on, or revision of, AI-drafted content. | C2 level 3 (document and justify reliance decisions on a tool, source or collaborator) | Low | Next teaching cycle; reuses an existing assessed task | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P2 | C1 | Convert part of EDUC90828's assessed online-discussion contribution into a small-group collaborative task with individual accountability, then extend it to require documented allocation of work between students and an AI tool. | C1 level 2 (assessed collaborative practice) then level 3 (coordinating work across people AND tools/AI systems) | Low-Medium | Term 1 for the collaborative-task conversion; Term 2 for the tool-allocation extension, once the first is embedded | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P3 | W1 | Convert EDUC90926's assessed presentation into a staff-briefing or parent-communication genre judged against professional criteria, then add a real or simulated external audience with privacy-compliant conduct assessed. | W1 level 2 (professional genre or audience beyond the teaching team) then level 3 (progressive assessment plus a real external audience with conduct assessed) | Low-Medium | Term 1 for the genre conversion; Term 2 for the external-audience step, once the first is embedded | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P4 | C3 | Extend the course-level ICT-capacity line into an assessed topic covering AI capabilities and limitations/ethics in a core unit, then add a governance-focused assessment task on AI procurement, data privacy or human-in-the-loop marking decisions. | C3 level 2 (capabilities AND limitations/ethics assessed) then level 3 (critique or governance of AI systems beyond tool operation) | Medium | Terms 1–2, staged; the governance step depends on the first | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P5 | W2 | Convert one of EDUC90832's or EDUC90862's case-study/practical-activity tasks into a practice-produced artefact judged against practice criteria, then extend that task across two or more core units with a genuine constraint of practice. | W2 level 2 (reproduces a professional task end to end) then level 3 (assessment spine plus a genuine constraint of practice) | Medium | Term 2 for the conversion; Term 3 for the cross-unit extension | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P6 | C4 | Add a structured, assessed self-audit of practice gaps to EDUC90862's existing written report. | C4 level 3 (structured progression toward independent learning, or assessed identification of knowledge gaps) | Medium | Term 2, alongside the W2 step; reuses an existing assessed report | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P7 | W3 | Extend EDUC90978's Clinical Praxis Presentation into a required sequence across two or more core units, each assessing own-practice activity with structured reflection and documented accountability to the student's school. | W3 level 3, in-practice route (required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders) | High | Terms 2–3; sustained supervision and moderation load; note the workload cost for students already teaching full-time | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P8 | C5 | Open the Applied Research Methodology / Applied Research Study sequence (EDUC90848, EDUC90945) to all students as a required, staged, supervised methodology-defence milestone, removing the Research Pathway's H2A entry gate. | C5 level 3 (primary-evidence generation REQUIRED, methodology defended under scrutiny) | High | A structural change requiring course-committee approval; not tied to a single term | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | The program documents an all-compulsory specialist core (EDUC90828, EDUC90862, EDUC90830, EDUC90832 — 'these four subjects comprise the first 50 points of the course') in evidence-based/clinical teaching, followed by a further compulsory 50 points delivered through one of two structured pathways (Coursework or Research). This is coherent progressive depth in a defined specialisation, not generic or interchangeable content. | Keep the four-subject specialist core (EDUC90828, EDUC90862, EDUC90830, EDUC90832) all-compulsory and preserve the two structured 50-point pathways (Coursework and Research); replacing a core unit with an elective, or collapsing the pathway structure into generic content, would flag this gate regardless of the adaptiveness gain. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | The course is built around a documented 'clinical judgement decision-making model' applied to real, uncertain classroom evidence: EDUC90862 requires students to 'select, implement, review and communicate research-supported teaching strategies that address identified student needs', assessed via a written report (50%) and a participation hurdle; EDUC90828 assesses a report on 'the development of judgement-based assessment' (45%). These are defended decisions against evidence, not recall or scripted response. | Keep EDUC90862's applied clinical-judgement report and participation hurdle, and EDUC90828's judgement-based-assessment report, as defended decisions against real classroom evidence; substituting a scripted or recall-based task for either in the C1, C2 or W1 interventions above would flag this gate. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C1 | 1 | 2 | +1 adaptive | 9 / 15 | 4 / 9 |
| P2 | C1 | 2 | 3 | +1 adaptive | 10 / 15 | 4 / 9 |
| P3 | C3 | 1 | 2 | +1 adaptive | 11 / 15 | 4 / 9 |
| P4 | C3 | 2 | 3 | +1 adaptive | 12 / 15 | 4 / 9 |
| P5 | W1 | 1 | 2 | +1 workplace | 12 / 15 | 5 / 9 |
| P6 | W1 | 2 | 3 | +1 workplace | 12 / 15 | 6 / 9 |
| P7 | W2 | 1 | 2 | +1 workplace | 12 / 15 | 7 / 9 |
| P8 | W2 | 2 | 3 | +1 workplace | 12 / 15 | 8 / 9 |
| P9 | C2 | 2 | 3 | +1 adaptive | 13 / 15 | 8 / 9 |
| P10 | C4 | 2 | 3 | +1 adaptive | 14 / 15 | 8 / 9 |
| P11 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 8 / 9 |
| P12 | W3 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
