// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Public Health (USYD-PUBLIC-HEALTH) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Public Health (USYD-PUBLIC-HEALTH)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-09-08 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-usyd-public-health.md
**Position basis:** Destination AI Exposure 76.50 (field basis) × Curriculum Adaptiveness 4/15 (v4.2 draft, sub-scale A) · Workplace practice 3/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a field basis (Jobs and Skills Australia Higher Education Outcomes (JSA HEO) field 0613 Public Health), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

Public Health (USYD-PUBLIC-HEALTH) scores 4/15 on curriculum adaptiveness and 3/9 on workplace practice, with C1 at the floor (0/3) and every other item capped at level 1. Its destination exposure of 76.5 rests on a field basis (Public Health, field of education 0613), not this program's own graduates, and most of the field's ten named job families carry no substitution-pressure or skill-direction data in the market report. Three findings do carry evidence: health promotion is the field's single largest entry destination and has no statutory registration behind it (CI-1); a national survey is under way to define what AI skills and ethical knowledge the health-promotion workforce needs, with no reason for this program to wait for its result (CI-2); and roughly a fifth of the field's graduates enter clerical, administrative or retail destinations that a national AI-capacity study rates as the workforce's most automatable segment (CI-3). Every action below targets one of these three findings. None targets registered nursing: that destination is gated by a separate professional registration body, not by this program (CI-4).

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C1 Distributed cognition & relational capability | Adaptive | 0 / 3 | 3 | No collaboration or teamwork skill-shift is named for any job family (§1). The applicable signal is CI-3: about a fifth of the field's entry destinations are clerical, administrative and retail roles that a national AI-capacity study rates as the workforce's most automatable segment (§3 Theme 4), which makes human coordination the differentiator in exactly that generalist destination. | 1 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | Deakin University's 2026 national survey is defining what evaluative and ethical-use skills the health-promotion workforce needs for responsible AI use (§3 Theme 2; CI-2). Separately, JSA's occupation-level analysis attributes healthcare's low automation exposure to a registered human staying accountable for the decision (§3 Theme 6) — an accountability this field's graduates cannot borrow from a registration body. | 2 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | PHAA's 2026 AI & Public Health Conference and Deakin's 2026 national AI-skills survey (§3 Theme 1, Theme 2) both signal profession-level engagement with AI adoption and risk. The field is defining the competence now, not waiting for the survey's findings (CI-2). | 3 |
| C4 Life-long learning & transfer | Adaptive | 1 / 3 | 2 | CI-3: roughly a fifth of this field's entry destinations are clerical, administrative and retail roles, the segment JSA's Generative AI Capacity Study rates as the workforce's most automatable (§3 Theme 4). A graduate entering that destination through this program has no assessed evidence the transfer was taught. | 4 |
| C5 Inquiry & evidence generation | Adaptive | 1 / 3 | 2 | Deakin's 2026 national survey (§3 Theme 2; CI-2) exists because synthesising what is already known about AI in this workforce has not answered the field's own question. The same shift, from secondary synthesis to primary evidence generation, is the gap this item measures in the curriculum. | 5 |
| **Adaptive capabilities** | **Adaptive** | **4 / 15** | **11** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | CI-1: health promotion is this field's single largest entry destination (4.2%) and carries no AHPRA registration; the Public Health Association of Australia offers guidance, not a licence, so the transcript is the only competence signal an employer reads. | 6 |
| W2 Authentic task design | Workplace | 1 / 3 | 2 | Same basis as W1 (CI-1): the field's largest, unregistered entry destination has no external body vouching for a graduate's competence, so the assessed artefact itself has to carry that weight. | 7 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | Theme 5 and Theme 6: registered nurses face a mandatory NMBA accountability standard that correlates with low automation exposure (§3 Theme 5, Theme 6). Public health has no equivalent registration, and its placement route is currently optional and merit-gated rather than a required structural substitute. | 8 |
| **Workplace practice** | **Workplace** | **3 / 9** | **6** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C1 Distributed cognition & relational capability | 0 → 1 | "Collaboration/teamwork appears in learning outcomes, but no core unit assesses it." | Add a collaboration or teamwork learning outcome to a compulsory core unit (for example PUBH5010), naming stakeholder or team-based work explicitly. Market basis: about a fifth of this field's graduates enter clerical, administrative or retail destinations (CI-3) that a national AI-capacity study rates as the field's most automatable segment (§3 Theme 4); the differentiating skill in a generalist destination is coordinating with people, not the routine task itself, so it needs to appear in outcomes before it can be assessed. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Convert one of PUBH5010's existing tasks (or add a further one) into a group task carrying individual accountability — for example, a team-produced critical appraisal of a systematic review with an individually marked reflection on the division of work. Market basis: same as C1:1 (CI-3; §3 Theme 4) — assessed teamwork differentiates a graduate in the generalist administrative destinations this field feeds, which are exactly the ones the JSA study rates highest for automation. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Extend that group task so the division of labour between people and an AI tool is itself assessed — for example, requiring the team to record which sections a generative tool drafted, who verified them, and why. Market basis: the same JSA study that rates clerical and administrative roles most automatable (§3 Theme 4; CI-3) finds augmentation, not replacement, describes most occupations; assessing human-AI task allocation trains for that augmentation pattern directly. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Add a criterion-referenced appraisal task to a core unit — for example, replacing one of PUBH5010's weekly quizzes with a structured peer-review exercise marked against stated quality criteria, drawn from the unit's own LO6/LO8 appraisal outcomes. Market basis: Deakin University's 2026 national survey is investigating what ethical and evaluative skills the health-promotion workforce needs for responsible AI use (§3 Theme 2; CI-2); criterion-referenced appraisal is that skill in assessable form, and does not need to wait on the survey's results. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Require students to document and justify a reliance decision — for example, submitting an AI-drafted evidence summary alongside a short accountability statement identifying what was checked, corrected or rejected, and why. Market basis: JSA's occupation-level analysis attributes healthcare's low automation exposure specifically to a registered human staying accountable for the decision (§3 Theme 6); an unregistered field such as public health has no equivalent external check, so the accountability step has to be built into assessment directly. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Add a session and an assessed criterion inside an existing core methods subject on the provenance of an AI-drafted evidence synthesis and on verifying that a generated citation exists, rather than only tool operation. Market basis: Deakin's 2026 survey (§3 Theme 2) and PHAA's 2026 AI & Public Health Conference (§3 Theme 1; CI-2) both signal the field is defining AI competence now; teaching verification does not depend on either concluding. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Add a core assessment task that critiques an AI system's use in a public-health context specifically — data governance or bias in an AI-assisted surveillance or evidence-synthesis tool — rather than a generic AI-ethics discussion. Market basis: PHAA's 2026 conference is framed explicitly around maximising benefits and minimising harms (§3 Theme 1), a governance framing the discipline has already adopted for itself. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 1 → 2 | "At least one core assessment requires application to novel or unfamiliar problems — case variation, unseen datasets, cross-context projects." | Add a case variant to an existing core assessment that applies the same epidemiological or evaluation method to a non-health, administrative or business setting. Market basis: CI-3 — roughly a fifth of the field's graduates enter clerical, administrative or retail destinations, exactly the segment a national AI-capacity study rates most automatable (§3 Theme 4); an explicit transfer exercise lets a graduate in that destination name the method they are bringing rather than assume it was health-specific. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Build on the C4:2 transfer task with a structured, assessed step where students identify a gap in their own methodological knowledge relative to an unfamiliar, non-health application and set out how they would close it, short of a fully self-scoped project. Market basis: same as C4:2 (CI-3; §3 Theme 4) — the destinations most exposed to automation are also furthest from this program's disciplinary core, so structured transfer, not a single exercise, is what the evidence supports. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 1 → 2 | "Students design and conduct an inquiry with methodology selection and data collection, assessed." | Add a primary-data component to the research-methods core — for example, a small dataset the student collects or a structured interview, rather than only literature appraisal — so at least one core assessment requires methodology selection and data collection, not synthesis of others' evidence. Market basis: Deakin's 2026 national survey (§3 Theme 2; CI-2) exists precisely because synthesis of what is already known about AI in this workforce has not answered the field's own question; the curriculum should teach the same shift from synthesis to primary evidence. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make primary-evidence generation a required element of the Capstone experience block rather than one route among three restricted to a 75%-average cohort, with a staged supervised review in place of an unstructured research-project brief. Market basis: unchanged from C5:2 (§3 Theme 2; CI-2) — the same reasoning that supports adding primary data collection supports making it required, since the field-level evidence-generation gap does not resolve itself for the two-thirds of students who take a different capstone route. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Give one existing core or capstone assessment a professional genre and a named audience beyond the teaching team — for example, reframing PUBH5040's Q&A and presentation as a health-promotion plan or evaluation report addressed to a specified funder, department or community stakeholder, marked against criteria drawn from that genre. Market basis: CI-1 — health promotion is this field's single largest entry destination (4.2%) and carries no statutory registration; the transcript, not a licence, is the only signal an employer reads, so the assessment needs to demonstrate the professional genre directly. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Extend that reframed task so it is judged, at least in part, by a real external audience or practitioner rather than only the unit's own teaching team, and make professional conduct or accountability an explicit marking criterion. Market basis: Theme 5's NMBA registration standards give registered nurses an external, mandatory accountability check (§3 Theme 5) that this unregistered field does not have (CI-1); an external-judge element is the closest available substitute. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Reframe PUBH5040's placement report and presentation, or an equivalent core assessment, as an end-to-end professional artefact — a health-promotion plan or program evaluation a practitioner would actually produce — marked against practice-derived criteria rather than only academic ones. Market basis: CI-1, as for W1:2 — health promotion's 4.2% entry share and its absence of external registration together mean the assessed artefact has to look like the thing the field's employer expects, not an essay about it. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Make that reframed authentic task recur at more than one point in the program rather than sit only in the capstone, and add a genuine constraint of practice to at least one instance — a real client brief, a fixed resource ceiling, or a consequential audience. Market basis: same as W2:2 (CI-1); one instance addresses the field's single largest, unregulated entry destination once, a spine addresses it across the degree. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Make the Practice Placement, or a shorter equivalent, a required core element for all students, rather than one of three routes restricted to students at or above a 75% weighted average with limited places, reducing the placement duration if needed to make that feasible at cohort scale. Market basis: Theme 6 — JSA-based analysis attributes healthcare's low automation exposure to a registered human staying accountable for the decision (§3 Theme 6); a required placement is the closest structural analogue to that accountability for a field with no registration body of its own. Per the W3 honesty rule, this is not justified by employment rates — Jackson and Collings find WIL does not raise them; the case is skill development and professional identity, and it carries an equity cost for students who cannot take an unpaid or relocation-dependent placement, a cost the current merit-gated elective route does not distribute evenly either. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the now-required placement from W3:2 into a supervised sequence — for example, a shorter placement in an earlier core unit followed by the existing roughly 30-day placement — with structured reflection on professional practice and documented accountability to the host organisation at each stage. Market basis: same as W3:2 (§3 Theme 6); a single required placement reaches level 2's bar, a supervised sequence with structured reflection is what level 3 adds. The equity cost noted at W3:2 compounds across a longer sequence and should be budgeted for, for example a placement bursary, not assessed away. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| Distributed cognition and transfer must anchor on generalist and business-operations destinations as much as on health settings | C1, C4 | About a fifth of this field's entry destinations sit in clerical, administrative and retail roles that JSA's Generative AI Capacity Study rates as the highest-automatability group (CI-3; §3 Theme 4) | §5 CI-3; §3 Theme 4 | HIGH |
| AI skills and ethical-use knowledge for the public-health and health-promotion workforce are being defined in the field right now | C2, C3 | PHAA's 2026 AI & Public Health Conference and Deakin University's 2026 national AI-skills survey (ethics-approved HEAG 2026-HE000205) | §3 Theme 1; §3 Theme 2; §5 CI-2 | HIGH |
| As AI-drafted evidence synthesis becomes available, a graduate's distinguishing value shifts from summarising existing sources to generating primary evidence | C5 | Deakin's national survey exists because the field does not yet know what its practitioners can do with AI tools | §3 Theme 2; §5 CI-2 | HIGH |
| Health promotion, the field's largest entry destination, has no external registration behind it — the transcript is the only competence signal an employer reads | W1, W2 | Health Promotion Officer is the field's single largest entry occupation (4.2%); the Public Health Association of Australia is a peak body, not a registration authority | §5 CI-1; §1 job family map | LOW |
| Regulated health professions retain low automation exposure because a registered human stays accountable for the decision; public health has no equivalent registration to lean on | W3 | NMBA mandatory registration standards for nurses, and a JSA-based analysis placing regulated health occupations at low AI exposure because of that accountability requirement | §3 Theme 5; §3 Theme 6 | HIGH |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C1 | Name collaboration or teamwork in a compulsory core unit's learning outcomes (for example PUBH5010). | Collaboration/teamwork appears in learning outcomes, but no core unit assesses it. | low | Term 1 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P2 | C4 | Add a non-health case variant to an existing core assessment, applying the same method to an administrative or business setting. | At least one core assessment requires application to novel or unfamiliar problems — case variation, unseen datasets, cross-context projects. | low | Term 1 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P3 | C2 | Replace one PUBH5010 weekly quiz with a structured peer-review task marked against the unit's own LO6/LO8 appraisal criteria. | Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars. | low | Term 1 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P4 | C3 | Add a session and an assessed criterion on AI-provenance verification (checking a generated citation exists) inside an existing core methods subject. | Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed. | low | Term 1 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P5 | W1 | Reframe PUBH5040's Q&A and presentation as a health-promotion plan or evaluation report addressed to a named external stakeholder, marked against criteria drawn from that genre. | At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice. | medium | Term 2 | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P6 | W2 | Apply the same reframing as W1 so the artefact produced (the health-promotion plan or evaluation report) is judged against practice-derived criteria, not academic ones. | At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice. | medium | Term 2 | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P7 | C1 | Convert one PUBH5010 task into a group task carrying individual accountability, such as a team critical appraisal with an individually marked reflection on the division of work. | At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity. | medium | Term 2 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P8 | C5 | Add a primary-data component to the research-methods core so at least one core assessment requires methodology selection and data collection, not only literature appraisal. | Students design and conduct an inquiry with methodology selection and data collection, assessed. | medium | Term 2 | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P9 | W3 | Make the Practice Placement, or a shorter equivalent, a required core element for all students rather than one merit-gated route among three. | A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone. | high | Year 2 | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P10 | C4 | Add a structured, assessed step where students identify a gap in their own methodological knowledge relative to an unfamiliar application and set out a plan to close it. | The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them. | medium | Year 2 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P11 | C2 | Require students to document and justify a reliance decision on an AI-drafted evidence summary — what was checked, corrected or rejected, and why. | Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment). | medium | Year 2 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P12 | C3 | Add a core assessment critiquing an AI system's use in a public-health-specific context — data governance or bias in a surveillance or evidence-synthesis tool. | Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation. | medium | Year 2 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P13 | C1 | Extend the assessed group task so the division of labour between people and an AI tool is itself part of what is marked. | Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed. | high | Year 2 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P14 | W1 | Have the reframed W1:2 task judged in part by a real external audience or practitioner, with professional conduct as an explicit marking criterion. | Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria. | high | Year 2 | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P15 | W2 | Make the reframed authentic task recur at more than one point in the program, with a genuine constraint of practice on at least one instance. | Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance. | high | Year 2 | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P16 | C5 | Make primary-evidence generation a required Capstone element rather than one route among three, with a staged supervised review. | A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review). | high | Year 2 | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P17 | W3 | Extend the now-required placement into a supervised sequence, with structured reflection and documented accountability to the host at each stage. | Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer). | high | Year 3 | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | The program documents a coherent specialist core with a staged prerequisite chain, which is the gate's PASS condition. Thirty-six of the seventy-two credit points are compulsory public health core units spanning epidemiology, biostatistics, disease prevention and health promotion, critical challenges, qualitative research methods and health policy and health economics, followed by a required capstone experience whose units carry the whole core as prerequisite or corequisite (the capstone unit requires 30 credit points from the core, and later electives chain off core units, for example Advanced Statistical Modelling on PUBH5217). This is not generic or interchangeable content. | Any C1-C5 intervention above must sit inside the existing compulsory public-health core (epidemiology, biostatistics, disease prevention and health promotion, qualitative methods, health policy and economics) or its prerequisite-linked capstone, not in an elective, or the redesign trades this PASS for the FAIL the gate exists to catch. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | The gate passes on the capstone or live-project route rather than on assessed trade-off decisions. Every candidate must complete 6-12 credit points of capstone experience, and each of the three routes is a project carrying real uncertainty and accountability rather than recall: the placement is a supervised workplace project of relevance and benefit to a host organisation, assessed by proposal, presentation and report, and the research project is 240-300 hours of independent work assessed by proposal and a manuscript for publication. The compulsory core alone would not pass, since the only captured core assessment set is exam and quiz based. | This gate currently passes on the capstone, placement and research-project routes carrying real uncertainty and accountability, not on the compulsory core's exam-and-quiz assessment. Reducing or removing the placement's supervised, real-stakes character when applying W3:2/W3:3 — for example, replacing it with a simulated or shortened desk exercise — risks moving G2 to FAIL even while raising a W-item score. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C1 | 0 | 1 | +1 adaptive | 5 / 15 | 3 / 9 |
| P2 | C1 | 1 | 2 | +1 adaptive | 6 / 15 | 3 / 9 |
| P3 | C1 | 2 | 3 | +1 adaptive | 7 / 15 | 3 / 9 |
| P4 | C2 | 1 | 2 | +1 adaptive | 8 / 15 | 3 / 9 |
| P5 | C2 | 2 | 3 | +1 adaptive | 9 / 15 | 3 / 9 |
| P6 | C3 | 1 | 2 | +1 adaptive | 10 / 15 | 3 / 9 |
| P7 | C3 | 2 | 3 | +1 adaptive | 11 / 15 | 3 / 9 |
| P8 | C4 | 1 | 2 | +1 adaptive | 12 / 15 | 3 / 9 |
| P9 | C4 | 2 | 3 | +1 adaptive | 13 / 15 | 3 / 9 |
| P10 | C5 | 1 | 2 | +1 adaptive | 14 / 15 | 3 / 9 |
| P11 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 3 / 9 |
| P12 | W1 | 1 | 2 | +1 workplace | 15 / 15 | 4 / 9 |
| P13 | W1 | 2 | 3 | +1 workplace | 15 / 15 | 5 / 9 |
| P14 | W2 | 1 | 2 | +1 workplace | 15 / 15 | 6 / 9 |
| P15 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 7 / 9 |
| P16 | W3 | 1 | 2 | +1 workplace | 15 / 15 | 8 / 9 |
| P17 | W3 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
