// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Environmental Engineering (MC-ENVENG) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Environmental Engineering (MC-ENVENG)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-29 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-enveng.md
**Position basis:** Destination AI Exposure 91.09 (cognate basis) × Curriculum Adaptiveness 9/15 (v4.2 draft, sub-scale A) · Workplace practice 5/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a cognate basis (Master of Civil Engineering), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

The Master of Environmental Engineering scores 9/15 on adaptive capabilities and 5/9 on workplace practice. The largest single gaps are digital and AI literacy, including governance (C3, level 1) and professional communication and conduct (W1, level 1); every other scored item sits one level below its ceiling. Both gates pass, so the disciplinary core and the uncertainty-based decision assessments are not at risk from the interventions this plan proposes.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | Design, autocad and cad recur as advertisement keywords (Signal 1, §2), and the advertisement sample gives no signal on whether AI-assisted drafting is changing what counts as competent work (CI-3, §5) — the largest scored gap sits against a field whose entry occupation already carries substantial augmentation exposure (Theme 4, §3). | 1 |
| C1 Distributed cognition & relational capability | Adaptive | 2 / 3 | 1 | "Stakeholder" recurs as an advertisement keyword for the field's engineering roles (Signal 2, §2), and the field carries a high-augmentation, low-automation profile (Automation 33%, Augmentation 71%, Theme 4, §3) — coordinating work across people and AI-assisted tools is a live expectation, not a hypothetical one. | 3 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 2 / 3 | 1 | The field's high-augmentation profile (Augmentation 71% against Automation 33%, Theme 4, §3) means graduates routinely work alongside AI-assisted outputs; the advertisement sample gives no signal on how reliance judgements are made, so this stays an inference from the exposure profile rather than a direct signal. | 4 |
| C4 Life-long learning & transfer | Adaptive | 2 / 3 | 1 | Sustainability recurs as a rising advertisement keyword for Environmental Engineers (Signal 1, §2; §4 Skill shift) and sits inside the field's accreditation and professional-standards scope (Theme 1, §3). | 5 |
| C5 Inquiry & evidence generation | Adaptive | 2 / 3 | 1 | Risk assessment recurs as a rising advertisement keyword (Signal 1, §2; §4 Skill shift), and state registration together with Environmental Protection Act obligations (Theme 2, §3) frame risk judgement as a formal professional accountability rather than only a technical skill. | 6 |
| **Adaptive capabilities** | **Adaptive** | **9 / 15** | **6** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Compliance and risk assessment recur as rising advertisement keywords (Signal 1, §2; §4 Skill shift), and from 6 March 2025 professional engineers in prescribed areas must be registered, with environmental engineering work also framed by state Environmental Protection Acts (Theme 2, §3) — a professional-accountability context this item does not yet reach. | 2 |
| W2 Authentic task design | Workplace | 2 / 3 | 1 | Compliance recurs as a rising advertisement keyword (Signal 1, §2; §4 Skill shift), and the field's professional identity rests on an accreditation body operating a Professional Standards Framework (Theme 3, §3) — CI-5 (§5) calls for a core task built around a real or realistic compliance scenario rather than a checklist exercise. | 7 |
| W3 Work-situated learning | Workplace | 2 / 3 | 1 | State registration and Environmental Protection Act obligations (Theme 2, §3) frame environmental engineering as formally accountable professional practice, and the employers named most often against this field's own job family (WSP, AECOM, Water Technology, Signal 1, §2) are the kind of host site consistent with that accountability. | 8 |
| **Workplace practice** | **Workplace** | **5 / 9** | **4** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Extend the existing System Optimisation & Machine Learning content, or add to a core unit, an assessed component covering AI capabilities together with their limitations and ethics, not only operational tool use, addressing the ambiguity CI-3 (§5) records about whether AI-assisted drafting is changing what counts as competent design or CAD work (cost: coordinator time to identify a core unit with room for the addition, and to write assessment criteria distinct from tool-operation marking). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Add a core assessment task requiring students to critique or govern an AI system's use in an environmental-engineering context — for example AI-assisted drafting or automated monitoring-data analysis — going beyond tool operation to bias, accountability or data-governance questions, warranted by the field's substantial augmentation exposure recorded against 'Other Engineering Professionals' (Theme 4, §3: Augmentation 71%, Automation 33%) (cost: designing a new assessment task and marking rubric, and sourcing case material on AI-assisted engineering practice). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Add a client-brief or regulator-facing deliverable to an existing core assessment, judged against criteria drawn from professional practice, warranted by the link CI-1 (§5) draws between compliance and risk-assessment work and state registration and Environmental Protection Act obligations (Theme 2, §3) — a professional genre addressed to a real regulatory or client audience rather than the teaching team (cost: reworking one assessment's brief and marking criteria to reflect a named professional genre). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Sequence the level-2 professional-genre task across at least two core units and add a practitioner or industry-panel audience for one of them, warranted by Engineers Australia's Professional Standards Framework governing professional identity in the field (Theme 3, §3) and by the employers named most often in the advertisement sample (WSP, AECOM; Signal 1, §2), who could plausibly supply panel input (cost: recruiting and briefing external panel members each offering, and coordinating scheduling across two units). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Add to the existing recurring group assessment (for example the capstone) a requirement that teams document and justify how work was divided between team members and the digital or AI tools used, warranted by the recurring "stakeholder" advertisement keyword (Signal 2, §2) and the field's high-augmentation exposure (Theme 4, §3) (cost: revising the capstone's marking rubric and briefing materials; no new assessment point). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Add to an existing structured-critique or peer-review component (for example ENGR90051's graded peer-feedback item) a requirement that students document and justify a reliance or override decision on a tool, model output or collaborator's input, warranted by the field's high-augmentation, low-automation profile (Theme 4, §3: Augmentation 71%, Automation 33%), which implies graduates will routinely judge when to rely on or override AI-assisted outputs (cost: extending an existing rubric rather than adding a new assessment point). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Add a later-stage core task requiring students to identify and close a personal knowledge gap against a current sustainability standard, tracked across core units for coverage, as CI-2 (§5) recommends directly — sustainability recurs as a rising advertisement keyword for this field (Signal 1, §2; §4 Skill shift) (cost: coordinator time to confirm coverage across units without duplicating existing sustainability content, and to select a current standard for the task). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make the field-camp-based inquiry in Monitoring Environmental Impacts the program's required route to a substantial primary-evidence project, and extend its existing oral component into a structured methodology defence, warranted by the rising risk-assessment keyword (Signal 1, §2; §4 Skill shift) and the professional-accountability framing risk judgement carries under state registration and Environmental Protection Act obligations (Theme 2, §3) (cost: redesigning the oral assessment format and briefing markers on defence-style questioning; no change to the field camp itself). | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Extend the existing genuine-constraint field-camp model in Monitoring Environmental Impacts to at least one further core stage so that professional-task reproduction under a real constraint of practice recurs rather than sitting in a single unit, warranted by CI-5 (§5), which calls for a core task built around a real or realistic compliance scenario judged against industry-practice criteria, and by the rising compliance keyword (Signal 1, §2; §4 Skill shift) (cost: sourcing a second real or realistic constraint-of-practice brief, for example from an external practitioner, and coordinating any additional field or site access). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Tighten the Engineering Practice Hurdle so every accepted route — not only ENGR90033 Internship or STEP — requires practitioner supervision, assessment and structured professional-practice reflection, dropping the extracurricular-activity option from the e-portfolio, warranted by the formal professional-accountability context state registration and Environmental Protection Act obligations create for this field (Theme 2, §3) and by the employers named most often in the advertisement sample (WSP, AECOM, Water Technology; Signal 1, §2) as consistent host sites (cost: auditing existing approved placements and the e-portfolio rubric against the tightened criteria, and the equity cost of a uniformly supervised requirement for students who currently rely on unpaid or relocation-dependent placements). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| Sustainability (rising advertisement keyword) | C4 | Sustainability recurs as a rising keyword in the advertisement sample for Environmental Engineers and sits inside the field's accreditation and professional-standards scope. | §2 Signal 1; §3 Theme 1; §4 Skill shift (sustainability) | MEDIUM |
| Compliance (rising advertisement keyword) and state registration | W1, W2 | Compliance recurs as a rising keyword; from 6 March 2025 professional engineers in prescribed areas must be registered, and environmental engineering work is also framed by state Environmental Protection Acts and planning regimes. | §2 Signal 1; §3 Theme 2; §4 Skill shift (compliance) | MEDIUM |
| Design, autocad and cad (advertisement keywords) | C3, W2 | Design, autocad and cad recur as advertisement keywords; the sample gives no signal on whether AI-assisted drafting is changing what counts as competent work. | §2 Signal 1; §5 CI-3 | MEDIUM |
| Risk assessment (rising advertisement keyword) and registration | C2, C5, W1 | Risk assessment recurs as a rising keyword; state registration and Environmental Protection Act obligations frame risk judgement as a formal professional accountability, not only a technical skill. | §2 Signal 1; §3 Theme 2; §4 Skill shift (risk assessment); §5 CI-4 | MEDIUM |
| Engineers Australia Professional Standards Framework | W1 | Engineers Australia operates a Professional Standards Framework guiding professional engineers, engineering technologists and engineering associates, framing professional identity for the field's occupations. | §3 Theme 3 | HIGH |
| Stakeholder coordination (advertisement keyword) and high augmentation exposure | C1, C2 | "Stakeholder" recurs as an advertisement keyword for the field's broader engineering roles; JSA-derived data record a high-augmentation, low-automation profile (Automation 33%, Augmentation 71%) for the occupation group. | §2 Signal 2; §3 Theme 4 | HIGH |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C3 | Extend a core unit with an assessed component covering AI capabilities together with limitations and ethics, moving C3 from level 1 to level 2 (cost: coordinator time to identify space and write distinct assessment criteria). | Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed. | low | 1 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P2 | W1 | Add a client-brief or regulator-facing deliverable to an existing core assessment, judged against professional-practice criteria, moving W1 from level 1 to level 2 (cost: reworking one assessment's brief and marking criteria). | At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice. | medium | 2 | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P3 | C4 | Add a later-stage core task requiring students to identify and close a personal knowledge gap against a current sustainability standard, moving C4 from level 2 to level 3 (cost: coordinator time confirming coverage without duplicating existing content). | The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them. | medium | 3 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P4 | C2 | Extend an existing structured-critique or peer-review component to require students to document and justify a reliance or override decision on a tool, model output or collaborator's input, moving C2 from level 2 to level 3 (cost: extending an existing rubric, not a new assessment point). | Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment). | medium | 4 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P5 | C1 | Add to an existing recurring group assessment a requirement to document and justify the division of work between team members and the digital or AI tools used, moving C1 from level 2 to level 3 (cost: revising the assessment's marking rubric and briefing materials). | Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed. | medium | 5 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P6 | C5 | Make the field-camp-based inquiry the program's required route to a substantial primary-evidence project and extend its existing oral component into a structured methodology defence, moving C5 from level 2 to level 3 (cost: redesigning the oral-assessment format and briefing markers). | A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review). | medium | 6 | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P7 | W2 | Extend the existing genuine-constraint field-camp model to at least one further core stage so professional-task reproduction under a real constraint of practice recurs across the program, moving W2 from level 2 to level 3 (cost: sourcing a second real or realistic constraint-of-practice brief and coordinating any additional site access). | Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance. | high | 7 | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P8 | C3 | Add a core assessment task requiring students to critique or govern an AI system's use in an environmental-engineering context, moving C3 from level 2 to level 3 (cost: designing a new assessment task and rubric, and sourcing case material). | Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation. | high | 8 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P9 | W1 | Sequence the professional-genre task across at least two core units and add a practitioner or industry-panel audience for one of them, moving W1 from level 2 to level 3 (cost: recruiting and briefing external panel members each offering, and coordinating scheduling across two units). | Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria. | high | 9 | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P10 | W3 | Tighten the Engineering Practice Hurdle so every accepted route requires practitioner supervision, assessment and structured professional-practice reflection, dropping the extracurricular-activity option, moving W3 from level 2 to level 3 (cost: auditing existing approved placements and the e-portfolio rubric, and the equity cost of a uniformly supervised requirement for students relying on unpaid or relocation-dependent placements). | Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer). | high | 10 | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | PASS: matches 'an accredited sequence, or a staged prerequisite chain.' The program is fully accredited by both EUR-ACE and Engineers Australia, requires 225 of 300 credit points as compulsory subjects, and documents a staged Year 1 to 2 to 3 core sequence. | The redesign must preserve the accredited, staged core sequence — 225 of 300 credit points compulsory across the Year 1 to 3 progression — that carries EUR-ACE and Engineers Australia accreditation; no intervention above converts a core disciplinary unit to an elective. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | PASS: matches 'Assessments require defended trade-off decisions, or simulations/capstones/live projects with real uncertainty and accountability.' ENEN30003 assesses well-justified trade-off decisions, and Water Planning & an Uncertain Future is built around decision-making theory under uncertainty, assessed via reports and interactive oral assessments. | The redesign must keep the existing trade-off and uncertainty-based decision assessments intact (ENEN30003's justified trade-off decisions; Water Planning & an Uncertain Future's decision-making-under-uncertainty assessment); no intervention above replaces either with a lower-stakes recall task. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C3 | 1 | 2 | +1 adaptive | 10 / 15 | 5 / 9 |
| P2 | C3 | 2 | 3 | +1 adaptive | 11 / 15 | 5 / 9 |
| P3 | W1 | 1 | 2 | +1 workplace | 11 / 15 | 6 / 9 |
| P4 | W1 | 2 | 3 | +1 workplace | 11 / 15 | 7 / 9 |
| P5 | C1 | 2 | 3 | +1 adaptive | 12 / 15 | 7 / 9 |
| P6 | C2 | 2 | 3 | +1 adaptive | 13 / 15 | 7 / 9 |
| P7 | C4 | 2 | 3 | +1 adaptive | 14 / 15 | 7 / 9 |
| P8 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 7 / 9 |
| P9 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 8 / 9 |
| P10 | W3 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
