// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Private Law (MC-PRIVLAW) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Private Law (MC-PRIVLAW)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-31 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-privlaw.md
**Position basis:** Destination AI Exposure 94.83 (partial basis) × Curriculum Adaptiveness 4/15 (v4.2 draft, sub-scale A) · Workplace practice 3/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a partial basis (the Master
> of Laws record, n=676, since Private Law is a Melbourne Law Masters
> specialisation without its own Job Insights Report (JIR) record) — not on this program's own
> graduates. It is sound enough to say the destinations are highly exposed and
> not sound enough to rank this program against a peer on exposure alone — see
> [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

MC-PRIVLAW fails both gates and scores 4/15 adaptive, 3/9 workplace, with every item at level 0 or 1 except W1 (2). **The course structure specifies no universally compulsory subject.** Students with a common-law degree have zero required subjects and 12.5 of 100 credit points open to the entire Master of Laws catalogue; the one conditional subject, Fundamentals of the Common Law, applies only to students without a common-law background and is linked to nothing else by a documented prerequisite chain. Because every level-2 and level-3 anchor in this instrument requires evidence in a *core* unit, this scoring reads "core unit" as any subject within the program's prescribed private-law list — the same reading that carries the G1 FAIL. G2 fails for an independent reason: every documented assessment format across the extract — take-home exam, approved-topic research paper, participation, short presentation, a 75%-attendance hurdle — resolves to recall or scripted response; no subject documents a simulation, live client matter, capstone, or a decision defended under scrutiny.

The two zero scores are not the same kind of gap. **C3 (0)** is a genuine content absence: no AI or digital-tool material appears anywhere in the extract, at any level, in any subject — the only technology-adjacent evidence is a graduate attribute about physical IT infrastructure in the Law Library. **W2 (0)** is partly a bookkeeping artefact: the one candidate professional-genre task in the extract — a banking-and-finance memorandum — satisfies both W1's genre anchor and could be read as a W2 practitioner-artefact; the record's "one construct, one home" rule assigns it to W1 alone, leaving W2 with no remaining evidence rather than proving no task-design intervention is possible. Any W2 fix therefore needs a *different* task from the one already carried by W1.

Two of the eight items — C1 and W3 — have scored gaps but no signal in \`reports/dfva-market-mc-privlaw.md\` speaks to them directly (the report's own §6 names this as an open gap: QILT and internal Melbourne Law School graduate-destination data for this program were not reviewed). Per this plan's market-warranted rule, no P-lever is built for either item below; they are mapped in §2 on anchor terms alone and flagged for a follow-up market pass.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C1 Distributed cognition & relational capability | Adaptive | 1 / 3 | 2 | None in this report — no signal addresses teamwork or collaborative practice directly; see §6 gap 4 of the market report | 6 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | Indirect — Theme 2's RCT shows AI-assisted legal drafting narrows a productivity gap unevenly, with the reasoning-model condition producing *more* hallucinations than no-AI assistance: exactly the appraisal-of-AI-output-quality construct C2 measures, though the record's own "Bearing" tag places this theme on C4/C5, not C2 | 4 |
| C3 Digital & AI literacy, including governance | Adaptive | 0 / 3 | 3 | Direct, HIGH confidence — Theme 1: the Law Society of NSW's January 2026 AI guide and the Law Council's new Rule 12 AML/CTF disclosure duty (in force from 1 July 2026) now tie AI use directly to solicitors' professional-conduct obligations | 1 |
| C4 Life-long learning & transfer | Adaptive | 1 / 3 | 2 | Direct, MEDIUM confidence — Theme 2: AI reasoning models already narrow the productivity gap on the analytical drafting tasks this program's research-paper format resembles; the Rule 12 disclosure duty is itself a live, newly settled obligation graduates will apply doctrine to | 5 |
| C5 Inquiry & evidence generation | Adaptive | 1 / 3 | 2 | Direct, MEDIUM-HIGH confidence — Theme 2: the RCT's productivity and reliability findings bear directly on whether the dominant research-paper assessment format builds primary-evidence and methodology-defence skill, or only secondary synthesis | 3 |
| **Adaptive capabilities** | **Adaptive** | **4 / 15** | **11** | — | — |
| W1 Professional communication & conduct | Workplace | 2 / 3 | 1 | Direct, LOW confidence — Theme 3: practitioner sentiment on AI splits by practice area, and this program's elective menu weights toward the transactional subjects the split identifies as more AI-exposed; the single memorandum instance is the program's only point of practitioner-facing communication under professional-conduct constraint | 8 |
| W2 Authentic task design | Workplace | 0 / 3 | 3 | Direct, MEDIUM confidence — Theme 2 and Theme 3 together: no subject documents an end-to-end professional artefact, and the RCT shows AI-output reliability is uneven precisely on the analytical/drafting tasks a practitioner artefact would test | 2 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | None in this report — no signal addresses placements or internships directly; the one elective (International Legal Internship) has no overview or assessment page in the handbook extract, so it is separately unverifiable regardless of market evidence | 7 |
| **Workplace practice** | **Workplace** | **3 / 9** | **6** | — | — |

Priority orders items by size of gap and evidence strength. The P-numbers in the
tables that follow are a different ordering — sequenced by effort and
dependency — so an item's priority and its P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

This table is the mechanical anchor map for all eight items — what each level
requires, on the instrument's own terms — independent of whether a P-lever is
built for it in §4. C1 and W3 appear here without a corresponding §4 lever,
per §1.

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Assess collaborative practice in a designated core subject — a joint transaction file, a moot, or a negotiation exercise with documented individual accountability | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Make the collaborative task recurrent across the core and require one instance to document how work was divided between team members and any AI/research tools used | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Add structured peer critique against published marking criteria to a core subject | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Require students to document and justify where they relied on or overrode an AI drafting tool's output, and mark that record — the reliability judgement Theme 2's RCT shows is not yet reliable by default | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 0 → 1 | "AI or digital tools appear only as electives or as tool operation/training — the operational level TEQSA identifies as non-durable." | Introduce baseline AI-tool literacy (operation, capabilities) into at least one subject, elective or core | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Embed AI-use professional-conduct content — confidentiality, hallucination risk, client disclosure — into a designated core subject, mapped directly to the Law Society of NSW guide and the Rule 12 disclosure duty | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Require core assessment of an AI-governance question in its legal context — disclosure of AI use under Rule 12, accountability for an AI-missed compliance issue, or a firm's model data-governance obligations | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 1 → 2 | "At least one core assessment requires application to novel or unfamiliar problems — case variation, unseen datasets, cross-context projects." | Require a core assessment applying settled doctrine to an unsettled problem — a Rule 12 disclosure scenario with no controlling precedent, or a cross-border transaction fact pattern not covered in class | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Reinstate a scoped capstone option within the core (the program currently excludes the Minor Thesis) or assess a documented statement of remaining knowledge gaps with a plan to close them | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 1 → 2 | "Students design and conduct an inquiry with methodology selection and data collection, assessed." | Require the recurring approved-topic research paper to state and defend a methodology and assemble its own evidence base — a case-law dataset, a transaction-precedent set, or a set of regulator decisions — rather than synthesising secondary scholarship | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make the primary-evidence project required rather than one route among several, with the methodology defended in a staged supervised review | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Extend the memorandum genre progressively across the core and have at least one instance judged by a practitioner, with professional conduct among the assessed criteria | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 0 → 1 | "Contextualised or scenario-framed tasks appear (case studies, worked scenarios), but the artefact produced and the criteria applied remain academic." | Add scenario or case-study framing to an existing exam or research-paper task, while the artefact and marking criteria stay academic | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Build a distinct practitioner-facing artefact — a simulated client matter with incomplete facts, judged against practice criteria — separate from the memorandum already carried by W1 | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Extend practitioner artefacts across the core so they are the assessment spine, with at least one carrying a genuine constraint of practice — an ambiguous instruction, a real deadline, or the profession's own conduct standards | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Move a placement — the existing International Legal Internship, formally documented, or an equivalent — into the designated core, with supervision, assessment and host accountability documented | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the core placement into a sequence, or one extended placement, with structured reflection and documented accountability to the host | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

C1 and W3 are listed for completeness with their evidence honestly marked
absent; §4 builds no P-lever from these two rows.

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| P1, P2 — a compulsory core with a mandated practice-area spread, and a defended-judgment task | G1, G2, and every P-lever below | Not market levers on their own. Every level-2/3 anchor requires *core* placement, and this program has none (G1); no documented task anywhere carries a defended trade-off decision (G2). Both are the precondition for every scored lever that follows | — (instrument, not market) | — |
| P6, P12 — AI-use professional-conduct content, then AI governance, in core | C3 | The Law Society of NSW's *Solicitor's Guide to Responsible Use of Artificial Intelligence* (January 2026) ties confidentiality, hallucination risk and client disclosure directly to existing conduct rules; the Law Council's Rule 12 AML/CTF disclosure duty is in force from 1 July 2026 — a statutory obligation, not guidance | §3 Theme 1 | HIGH on the regulatory text; MEDIUM on how it should be assessed, which the guide does not specify (§6) |
| P4, P15 — a defended methodology and required primary-evidence project | C5 | The RCT shows AI reasoning-model assistance narrows the productivity gap on legal analytical drafting by roughly 34–140% but with more hallucinations than no-AI assistance; the ILO's refined exposure index places lawyers in its second-lowest "Minimal Exposure" band (0.36) | §3 Theme 2 | MEDIUM-HIGH source; MEDIUM applicability — US law students under experimental conditions and a Poland-anchored global task survey, not practising Australian solicitors (§6) |
| P7, P13 — criterion-referenced appraisal and reliance-decision documentation | C2 | The same RCT: AI-assisted output quality is uneven by tool and task, which the record's own C2 rationale already identifies as the reflective/appraisal gap — assessed judgement of AI-output reliability is the skill the RCT shows is not yet automatic | §3 Theme 2 (drawn indirectly; the market report's own "Bearing" tag places this theme on C4/C5, not C2) | MEDIUM — an inference from Theme 2's content, not a signal the report itself ties to C2 |
| P8, P14 — novel-problem application and gap-identification | C4 | Rule 12's AML/CTF disclosure duty is newly in force and unsettled in practice; the RCT's productivity findings bear on whether graduates can apply doctrine to problems the curriculum has not pre-solved for them | §3 Theme 1; §3 Theme 2 | MEDIUM |
| P9 — practitioner-judged professional communication | W1 | Junior lawyers report AI absorbing document review and first-draft work in transactional practice, with litigation seen as comparatively insulated; the program's elective list weights toward the transactional subjects on the exposed side of that split | §3 Theme 3; §1 Job Family Map | LOW — UK-focused trade press (Legal Cheek) and two pseudonymous forum threads (RollOnFriday), not a structured or Australian survey (§6) |
| P5, P10, P16 — scenario framing, then an end-to-end practitioner artefact, then the assessment spine | W2 | The RCT's reliability findings and the practice-area sentiment split (Theme 3) both point to the same gap: no task in the extract reproduces a professional artefact end to end, so no assessment currently tests the judgement the market evidence says is unevenly distributed | §3 Theme 2; §3 Theme 3 | MEDIUM |
| — | C1 | None. No signal in this market report addresses teamwork or collaborative practice for this program | — (not evidenced) | N/A |
| — | W3 | None. No signal in this market report addresses placements or internships for this program; the program's own International Legal Internship elective has no assessment page in the handbook extract, so it cannot be independently verified either | — (not evidenced) | N/A |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

C1 and W3 carry no lever here: no market evidence in \`reports/dfva-market-mc-privlaw.md\`
supports an action on either item (see §1 and §3). Both remain fully mapped in
§2 on anchor terms and should return to this plan once a dedicated market pass
covers them.

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | Enabling — G1 | **Designate a compulsory core with a mandated spread across transactional and dispute-resolution electives.** Name two or three existing prescribed subjects — at least one transactional (e.g. Core Principles of Contract or Principles of Banking and Finance Law) and one dispute-resolution subject (e.g. Negligence or Mediation in Practice) — as required of every student, in a stated sequence. This adds no new teaching; it is a course-rule change, and the precondition for every core-unit lever below | No score of its own; moves G1 from FAIL toward PASS | Medium (governance, not teaching) | Sem 1 2027 rules cycle | [[19]](https://www.legislation.gov.au/F2021L00488)[[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) |
| P2 | Enabling — G2 | **Introduce one defended-trade-off task into the newly-designated core** — a simulated client matter or negotiation exercise with incomplete facts, requiring a documented and defended decision. This is the direct remedy for G2 (no subject currently documents a simulation, live matter, capstone or scrutinised defended decision) and becomes the basis for P10's W2 artefact | No score of its own; moves G2 from FAIL toward PASS; feeds P10 | Medium | Sem 1 2027, paired with P1 | [16][[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P3 | C3 | Introduce baseline AI-tool literacy (operation, capabilities) into at least one subject, ahead of the fuller professional-conduct embedding at P6 | C3 level 1 — AI/digital tools appear as electives or tool-operation training | Low | Sem 1 2027 | [[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105) |
| P4 | C5 | Require the recurring approved-topic research paper to state and defend a methodology and assemble its own evidence base — a case-law dataset, a transaction-precedent set, or a set of regulator decisions — rather than synthesising secondary scholarship | C5 level 2 — students design and conduct an inquiry with methodology selection and data collection, assessed | Low | Sem 1 2027 | [[14]](https://doi.org/10.1016/j.techfore.2016.08.019)[[15]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P5 | W2 | Add scenario or case-study framing to an existing exam or research-paper task in a prescribed subject, while artefact and criteria stay academic — the scaffolding step ahead of P10's end-to-end artefact | W2 level 1 — contextualised tasks appear but artefact and criteria remain academic | Low | Sem 1 2027 | [[23]](https://doi.org/10.1080/02602938.2017.1412396) |
| P6 | C3 | Embed AI-use professional-conduct content — confidentiality, hallucination risk, client disclosure — into the designated core, mapped directly to the Law Society of NSW guide and Rule 12 | C3 level 2 — core units address AI capabilities AND limitations/ethics, assessed | Medium | Sem 2 2027 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P7 | C2 | Add structured peer critique against published marking criteria to a core subject | C2 level 2 — criterion-referenced appraisal of quality in core assessment | Medium | Sem 2 2027 | [[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P8 | C4 | Require a core assessment applying settled doctrine to an unsettled problem — a Rule 12 disclosure scenario with no controlling precedent, or a cross-border transaction fact pattern | C4 level 2 — core assessment requires application to novel or unfamiliar problems | Medium | Sem 2 2027 | [[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y) |
| P9 | W1 | Extend the memorandum genre progressively across the newly-designated core and have at least one instance judged by a practitioner, with professional conduct among the assessed criteria | W1 level 3 — assessed repeatedly and progressively, judged by a real external audience, conduct among the criteria | Medium | Sem 2 2027 | [[19]](https://www.legislation.gov.au/F2021L00488)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined) |
| P10 | W2 | Build a distinct practitioner-facing artefact using P2's simulated matter — a real or realistic problem with incomplete facts, judged against practice criteria — kept separate from the memorandum already carried by W1 | W2 level 2 — a core assessment reproduces a professional task end to end | Medium | Sem 2 2027, after P2 | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396) |
| P11 | W3 | Move the International Legal Internship, formally documented with supervision and assessment, into the designated core — or build an equivalent core placement if the existing elective's arrangements cannot be verified and formalised | W3 level 2 — a core unit places students in a real workplace with practitioner supervision and assessment | High | 2028 intake | [27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P12 | C3 | Require core assessment governing an AI system in its legal context — disclosure of AI use under Rule 12, accountability for an AI-missed compliance issue, or a firm's model data-governance obligations | C3 level 3 — core assessment requires critique or governance of AI systems in the discipline's own context | High | 2028 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P13 | C2 | Require students to document and justify where they relied on or overrode an AI drafting tool's output, and mark that record | C2 level 3 — assessment requires documented and justified reliance decisions | High | 2028 | [[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P14 | C4 | Reinstate a scoped capstone option within the core, or assess a documented statement of remaining knowledge gaps together with a plan to close them | C4 level 3 — documented structured progression toward independent learning | High | 2029 | [[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P15 | C5 | Make the primary-evidence project required rather than one route among several, with the methodology defended in a staged supervised review | C5 level 3 — a required substantial project generating primary evidence, methodology defended under scrutiny | High | 2029 | [[14]](https://doi.org/10.1016/j.techfore.2016.08.019)[[15]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P16 | W2 | Extend practitioner artefacts across the core so they are the assessment spine, with at least one carrying a genuine constraint of practice — an ambiguous instruction, a real deadline, or the profession's own conduct standards | W2 level 3 — such tasks are the assessment spine and one carries a genuine constraint of practice | High | 2029 | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P17 | W3 | Extend the core placement into a sequence, or one extended placement, with structured reflection on professional practice and documented accountability to the host | W3 level 3 — substantial required work-situated learning with host accountability and structured reflection | High | 2030 | [27][[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | FAIL | The PASS condition requires a documented coherent specialist core with progressive depth — an all-compulsory core, an accredited sequence, or a staged prerequisite chain. None is documented. Students with a common-law degree have zero required subjects and 12.5 of 100 credit points open to the entire Master of Laws catalogue; the only conditional subject (Fundamentals of the Common Law) applies solely to non-common-law entrants, is a generic legal-method subject rather than private law, and is linked to other subjects only by a recommendation, not a documented prerequisite | **This gate currently FAILS, and P1 is its remedy.** The designated core must show progressive depth and the transactional/dispute-resolution spread P1 specifies — a set of subjects picked only for administrative convenience would satisfy the letter of "compulsory" without addressing either the depth requirement or the exposure-differential the market evidence identifies. Until P1 lands, the adaptiveness score should be read as a measurement of the course rules, not of the curriculum inside them | [[19]](https://www.legislation.gov.au/F2021L00488)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | FAIL | The PASS condition requires defended trade-off decisions, or simulations/capstones/live projects with real uncertainty and accountability. Every documented assessment format resolves to a take-home examination, an approved-topic research paper, participation, a short presentation, or a 75%-attendance hurdle — none of which is a simulation, live matter, capstone, or scrutinised defended decision | P2's simulated-matter task is the direct remedy. It must preserve a genuinely defended decision under real uncertainty — a checklist-style compliance exercise or a scripted negotiation would satisfy the letter of "simulation" without the accountability the gate requires | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the
two sub-scales tracked separately, never summed. Every row below presupposes
**P1** and, where noted, **P2** — without a compulsory core there is no "core
unit" for a level-2/3 anchor to bind to.

C1 has no market-warranted lever in this plan (see §1, §3, §4), so its
cumulative ceiling reachable here is 1/3, not 3/3 — the table below stops
adaptive short of the instrument maximum for that reason, not because the
remaining steps are unreachable in principle.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P3 | C3 | 0 | 1 | +1 adaptive | 5 / 15 | 3 / 9 |
| P4 | C5 | 1 | 2 | +1 adaptive | 6 / 15 | 3 / 9 |
| P6 | C3 | 1 | 2 | +1 adaptive | 7 / 15 | 3 / 9 |
| P7 | C2 | 1 | 2 | +1 adaptive | 8 / 15 | 3 / 9 |
| P8 | C4 | 1 | 2 | +1 adaptive | 9 / 15 | 3 / 9 |
| P12 | C3 | 2 | 3 | +1 adaptive | 10 / 15 | 3 / 9 |
| P13 | C2 | 2 | 3 | +1 adaptive | 11 / 15 | 3 / 9 |
| P14 | C4 | 2 | 3 | +1 adaptive | 12 / 15 | 3 / 9 |
| P15 | C5 | 2 | 3 | +1 adaptive | 13 / 15 | 3 / 9 |
| P5 | W2 | 0 | 1 | +1 workplace | 13 / 15 | 4 / 9 |
| P9 | W1 | 2 | 3 | +1 workplace | 13 / 15 | 5 / 9 |
| P10 | W2 | 1 | 2 | +1 workplace | 13 / 15 | 6 / 9 |
| P11 | W3 | 1 | 2 | +1 workplace | 13 / 15 | 7 / 9 |
| P16 | W2 | 2 | 3 | +1 workplace | 13 / 15 | 8 / 9 |
| P17 | W3 | 2 | 3 | +1 workplace | 13 / 15 | 9 / 9 |

Reachable ceiling with this market-warranted plan: **13/15 adaptive, 9/9
workplace** — short of the 15/15 instrument maximum only on C1 (stuck at 1/3),
which needs a dedicated market-evidence pass before a lever can be built for
it here.

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports. This is exactly how the record already scores C1, C2 and C4 at level 1 — collaboration, reflection and transfer are all *claimed* in outcomes and none is assessed in a core unit | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy an anchor | Every level-2/3 anchor requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged. This is why the existing International Legal Internship carries no W3 credit above level 1 and why the memorandum task alone could not lift W2 | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |
| Counting the banking-and-finance memorandum toward both W1 and W2 | The record scores it once, under W1, per the "one construct, one home" rule — its defining construct is the professional-communication genre, not an end-to-end practitioner artefact. P10 must build a separate task | Evidence record ambiguity note (W1/W2, "one construct, one home") | — |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
