// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Energy and Resources Law (MC-ENRSLAW) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Energy and Resources Law (MC-ENRSLAW)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-29 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-enrslaw.md
**Position basis:** Destination AI Exposure 94.83 (partial basis) × Curriculum Adaptiveness 3/15 (v4.2 draft, sub-scale A) · Workplace practice 3/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a partial basis (Master of Laws), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

The Master of Energy and Resources Law shows early-level scores on every scored item, and both gates fail. G1 fails because the course requires only Fundamentals of the Common Law conditionally, plus 87.5 credit points drawn from a roughly 30-subject prescribed list shared with other Melbourne Law Masters streams, so no compulsory, discipline-specific sequence exists. G2 fails because sampled subjects are assessed almost entirely by take-home examination, research paper or class participation; the one subject built around simulated negotiation is not offered in 2026, and its graded items do not reference the exercises anyway.

The program holds addressable headroom on every item: 3 / 15 on Adaptiveness and 3 / 9 on Workplace, at a partial-basis exposure estimate of 94.83. The widest gaps are C2 (0 / 3) and C3 (0 / 3): no sampled subject assesses appraisal of work quality, and none names AI or digital content in a core outcome or assessment. C1, C4, C5, W1, W2 and W3 each sit one level above the floor, blocked either by the absence of a compulsory core (see G1) or by an elective-only route to work-situated, collaborative or research-methodology practice.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 0 / 3 | 3 | Direct — §3 Theme 3 and §5 CI-3: accounting professional standards require auditors to verify automated anomaly-detection output and document AI-generated estimates; §2 Signal 2 records 6,240 accountant/auditor postings and §4 names audit sampling as a rising skill. No sampled subject assesses appraisal of work quality or AI-reliance decisions. | 1 |
| C3 Digital & AI literacy, including governance | Adaptive | 0 / 3 | 3 | Direct — §5 CI-1 draws on the same §3 Theme 3 verification duty and on §3 Theme 4's mandatory sustainability-reporting shortage. No sampled subject overview or outcome names AI, generative AI or digital tools as content; the only technology-related graduate attribute is explained purely as IT-infrastructure access. | 2 |
| C1 Distributed cognition & relational capability | Adaptive | 1 / 3 | 2 | Indirect — no signal in the market report names collaborative or team-based practice directly. §3 Theme 6 (Jobs and Skills Australia's Generative AI Capacity Study) finds that augmentation of human work by AI systems outweighs automation across the workforce, which bears on the level-3 anchor's own criterion of assessed human-and-tool coordination, but the program has no compulsory core unit for that assessment to sit in (see G1). | 3 |
| C4 Life-long learning & transfer | Adaptive | 1 / 3 | 2 | Direct — §5 CI-2 draws on §3 Theme 6: the clerical and general business-operations occupations this program's graduates enter sit in the automation-exposed cluster the study names, with limited internal mobility once there. Program outcomes claim adaptability, but no sampled subject assesses application to a novel or unfamiliar regulatory context. | 4 |
| C5 Inquiry & evidence generation | Adaptive | 1 / 3 | 2 | Direct — §3 Theme 4: mandatory Australian sustainability-reporting standards create a shortage of graduates able to conduct multi-capital and climate-risk assurance analysis, work resting on inquiry and evidence generation. Several subjects assess a substantial research paper, but it is doctrinal, not shown to require methodology selection and data collection, and in more than one subject is elective against a take-home exam. | 5 |
| **Adaptive capabilities** | **Adaptive** | **3 / 15** | **12** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Indirect — no signal in the market report names professional communication or conduct for this occupation set directly. Assessed presentations recur across sampled subjects, but all are delivered to the teaching team, and the market report records no external-audience or professional-conduct signal to warrant more. | 6 |
| W2 Authentic task design | Workplace | 1 / 3 | 2 | Direct — §3 Theme 5 and §5 CI-4: the energy-consulting slice of this program's business-operations destinations is gated by Solar Accreditation Australia accreditation, which the Clean Energy Regulator uses to restrict Small-scale Technology Certificate issuance. Sampled case-study assessments are scenario-framed but not shown to be judged against that pathway's own criteria. | 7 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | Indirect — no signal in the market report names work-situated learning directly. §3 Theme 5's accreditation gate implies practical exposure matters for the energy-consulting slice of this program's destinations, but the market report does not itself specify a placement route; the elective International Legal Internship (LAWS70067) offers a genuine placement but is application-based, not core. | 8 |
| **Workplace practice** | **Workplace** | **3 / 9** | **6** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | 0 → 1 | "Reflection or self-assessment appears in outcomes or graduate attributes, but no core unit assesses it against criteria." | Add a reflection or self-assessment element, judged against stated criteria, to the existing Reflective/Research Essay (Indigenous Rights in Global Context, 60%) or an equivalent research-paper subject, so students explicitly appraise the quality of their own analysis before submission (§3 Theme 3; cost: criteria drafting and a marking-guide addition to an existing task). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Add a criterion-referenced peer-review or marking-against-exemplars step to one of the research-paper assessments (Environmental Law, Climate Change Law or International Petroleum Transactions), so students critique a peer's or a released exemplar's analysis against the marking criteria before submitting their own (§3 Theme 3; §2 Signal 2; cost: exemplar preparation and an added marking cycle). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Attach a reliance-and-override log to one of those same audit/assurance-adjacent research-paper tasks, requiring students to document and defend any point where they relied on or departed from an automated finding, consistent with the verification duty the accounting standards body sets for auditors (§3 Theme 3; §5 CI-3; cost: rubric redesign and added marking criteria). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 0 → 1 | "AI or digital tools appear only as electives or as tool operation/training — the operational level TEQSA identifies as non-durable." | Add AI or digital-tool content as an elective module — for example within Climate Law, Economics and Finance or International Sustainable Finance — covering AI-assisted anomaly detection and estimate generation as used in audit and sustainability-assurance work, as a first step toward core coverage (§3 Theme 3; §5 CI-1; cost: elective module design). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Add a module to one of the more widely taken prescribed-list subjects (Environmental Law or Climate Change Law) that addresses AI capabilities and limitations/ethics in audit and sustainability-assurance contexts, assessed rather than descriptive (§3 Theme 3; §3 Theme 4; §5 CI-1; cost: module development and moderation). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Add an assessed AI-governance critique task to the same subject — auditing an automated anomaly-detection or disclosure tool for bias, transparency or accountability gaps against the accounting standards body's technology provisions (§3 Theme 3; cost: task design and access to a representative tool or case study). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Add an assessed group task with individual accountability to one of the case-study-bearing subjects (Environmental Law, International Sustainable Finance or Impact Investing), where students negotiate a shared position across a client, stakeholder or interdisciplinary team (§3 Theme 6; cost: group-marking design and moderation to protect individual accountability). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Extend that group task so the division of work between students and an AI or digital tool is itself documented and assessed — for example, requiring the team to record and justify which drafting, research or analysis steps a tool performed versus a person, consistent with the augmentation-over-automation pattern the Generative AI Capacity Study finds (§3 Theme 6; cost: task redesign and a role/tool-allocation rubric). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C4 Life-long learning & transfer | 1 → 2 | "At least one core assessment requires application to novel or unfamiliar problems — case variation, unseen datasets, cross-context projects." | Add an assessed novel-context task to a research-paper subject (Environmental Law, Climate Change Law or International Petroleum Transactions), requiring application of the doctrine taught to an unfamiliar jurisdiction or regulatory scenario rather than the topic as taught (§5 CI-2; §3 Theme 6; cost: new case material each offering). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Make a self-scoped applied project — students identify their own knowledge gap in an unfamiliar regulatory context and set out a plan to close it — a required element of the program rather than confined to the excluded Minor Thesis option (§5 CI-2; cost: supervision load for individualised project scoping). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 1 → 2 | "Students design and conduct an inquiry with methodology selection and data collection, assessed." | Redesign one research-paper assessment (Environmental Law, Climate Change Law or International Petroleum Transactions) so the topic requires students to select a methodology and collect primary evidence — practitioner interviews, a regulatory filing sample, or comparable primary material — rather than doctrinal synthesis alone (§3 Theme 4; cost: methodology-training content and revised marking criteria). | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make that redesigned research paper the required route for all students rather than one option alongside a take-home exam, and add a staged supervised review of the methodology before final submission (§3 Theme 4; cost: loss of the exam alternative's marking-load relief, plus added supervision time). | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Convert one of the recurring in-class presentations (International Environmental Law, Climate Change Law or Indigenous Rights in Global Context) into a client-brief or policy-advice genre — a memorandum or advice note addressed to a named stakeholder — judged against criteria drawn from professional practice rather than academic presentation criteria (cost: criteria redesign and exemplar sourcing). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Extend the guest-speaker element already present in Climate Law, Economics and Finance so the guest speaker judges the presentation against professional-conduct criteria, rather than only receiving questions, and repeat a comparable external-audience task in at least one other subject (cost: guest-panel coordination and shared assessment criteria). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Replace the generic energy-policy case study with an authentic accreditation-application task set against current Solar Accreditation Australia criteria, so the artefact produced is the one a practitioner would actually submit (§3 Theme 5; §5 CI-4; cost: sourcing current accreditation materials and updating the task annually). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Extend the accreditation-application task, and the term-sheet negotiation and pitch work already described in International Sustainable Finance's subject overview, into an assessed capstone-level task with a genuine practice constraint — a real resource limit, an externally supplied brief, or assessment by an industry panel (§3 Theme 5; §2 Signal 3; cost: capstone redesign and possible industry-panel coordination). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Make the International Legal Internship (LAWS70067) a required rather than an elective, application-based subject for one cohort stream, so a compulsory unit places students in a real workplace with practitioner supervision and assessment (§3 Theme 5; cost: placement capacity, host-organisation recruitment, the loss of the current application-based selectivity, and an equity cost for students who cannot take an unpaid or relocation-dependent placement). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the internship into a required sequence — an initial shorter placement earlier in the program plus the existing five-week placement — with structured reflection and documented accountability to the host organisation added to the current Organisation-report hurdle and legal-writing assessment (cost: additional host partnerships, a second supervised placement cycle, and further equity cost from extending unpaid or relocation-dependent placement time). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| P1 | C2 | Accounting professional standards require auditors to verify automated anomaly-detection output and document AI-generated estimates. | §3 Theme 3; §5 CI-3 | HIGH (regulatory and statutory instrument, Accountants and Auditors lane) |
| P2 | C3 | The same verification duty, plus a mandatory sustainability-reporting shortage of graduates skilled in multi-capital assurance and climate-risk governance. | §3 Theme 3; §3 Theme 4; §5 CI-1 | HIGH (regulatory and scholarly lanes, Accountants and Auditors) |
| P3 | C1 | Jobs and Skills Australia's Generative AI Capacity Study finds augmentation of human work by AI systems outweighs automation across the workforce. | §3 Theme 6 | HIGH (scholarly and grey-literature lane, Business Operations Specialists) |
| P4 | C4 | Clerical and general business-operations occupations this program's graduates enter sit in the automation-exposed cluster the same study names, with limited internal mobility once there. | §3 Theme 6; §5 CI-2 | HIGH (scholarly and grey-literature lane, Business Operations Specialists) |
| P5 | C5 | Mandatory sustainability-reporting standards create an acute shortage of accounting graduates able to conduct multi-capital and climate-risk assurance analysis, work resting on inquiry and evidence generation. | §3 Theme 4 | HIGH (scholarly and grey-literature lane, Accountants and Auditors) |
| P6 | W1 | No signal in the market report names professional communication or conduct for this occupation set directly; recurring in-class presentation assessment is the only related pattern the sampled subjects show. | not stated in the market report | LOW (no direct signal recorded) |
| P7 | W2 | The energy-consulting slice of this program's business-operations destinations is gated by Solar Accreditation Australia accreditation, with the Clean Energy Regulator restricting Small-scale Technology Certificate issuance to accredited practitioners. | §3 Theme 5; §5 CI-4 | HIGH (regulatory and statutory instrument, Business Operations Specialists) |
| P8 | W3 | The same accreditation gate implies practical, supervised exposure matters for the energy-consulting slice of this program's destinations, though the market report does not itself specify a placement route. | §3 Theme 5 | MEDIUM (regulatory instrument cited, but no placement-specific claim recorded) |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C2 | Add a reflection or self-assessment element, judged against stated criteria, to the existing Reflective/Research Essay (Indigenous Rights in Global Context, 60%) or an equivalent research-paper subject, so students explicitly appraise the quality of their own analysis before submission (§3 Theme 3; cost: criteria drafting and a marking-guide addition to an existing task). | C2 level 1 (reflection/self-assessment named in outcomes) | Low | Term 1; existing-task addition | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P2 | C3 | Add AI or digital-tool content as an elective module — for example within Climate Law, Economics and Finance or International Sustainable Finance — covering AI-assisted anomaly detection and estimate generation as used in audit and sustainability-assurance work, as a first step toward core coverage (§3 Theme 3; §5 CI-1; cost: elective module design). | C3 level 1 (AI/digital content as elective) | Low | Term 1; elective module | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P3 | C2 | Add a criterion-referenced peer-review or marking-against-exemplars step to one of the research-paper assessments (Environmental Law, Climate Change Law or International Petroleum Transactions), so students critique a peer's or a released exemplar's analysis against the marking criteria before submitting their own (§3 Theme 3; §2 Signal 2; cost: exemplar preparation and an added marking cycle). | C2 level 2 (criterion-referenced appraisal of quality) | Low-Medium | Term 1-2; rubric update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P4 | C3 | Add a module to one of the more widely taken prescribed-list subjects (Environmental Law or Climate Change Law) that addresses AI capabilities and limitations/ethics in audit and sustainability-assurance contexts, assessed rather than descriptive (§3 Theme 3; §3 Theme 4; §5 CI-1; cost: module development and moderation). | C3 level 2 (capabilities and limitations/ethics assessed) | Medium | Term 2; module development | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P5 | C1 | Add an assessed group task with individual accountability to one of the case-study-bearing subjects (Environmental Law, International Sustainable Finance or Impact Investing), where students negotiate a shared position across a client, stakeholder or interdisciplinary team (§3 Theme 6; cost: group-marking design and moderation to protect individual accountability). | C1 level 2 (core-adjacent collaborative practice assessed) | Medium | Term 2; group-task redesign | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P6 | C4 | Add an assessed novel-context task to a research-paper subject (Environmental Law, Climate Change Law or International Petroleum Transactions), requiring application of the doctrine taught to an unfamiliar jurisdiction or regulatory scenario rather than the topic as taught (§5 CI-2; §3 Theme 6; cost: new case material each offering). | C4 level 2 (application to a novel or unfamiliar problem) | Low-Medium | Term 2; new case material | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P7 | C5 | Redesign one research-paper assessment (Environmental Law, Climate Change Law or International Petroleum Transactions) so the topic requires students to select a methodology and collect primary evidence — practitioner interviews, a regulatory filing sample, or comparable primary material — rather than doctrinal synthesis alone (§3 Theme 4; cost: methodology-training content and revised marking criteria). | C5 level 2 (methodology selection and data collection assessed) | Medium | Term 2; task redesign | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P8 | W1 | Convert one of the recurring in-class presentations (International Environmental Law, Climate Change Law or Indigenous Rights in Global Context) into a client-brief or policy-advice genre — a memorandum or advice note addressed to a named stakeholder — judged against criteria drawn from professional practice rather than academic presentation criteria (cost: criteria redesign and exemplar sourcing). | W1 level 2 (professional genre or audience beyond the teaching team) | Low-Medium | Term 2; task redesign | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P9 | W2 | Replace the generic energy-policy case study with an authentic accreditation-application task set against current Solar Accreditation Australia criteria, so the artefact produced is the one a practitioner would actually submit (§3 Theme 5; §5 CI-4; cost: sourcing current accreditation materials and updating the task annually). | W2 level 2 (professional task end to end, judged against practice criteria) | Medium | Term 2; task replacement, updated annually | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P10 | W3 | Make the International Legal Internship (LAWS70067) a required rather than an elective, application-based subject for one cohort stream, so a compulsory unit places students in a real workplace with practitioner supervision and assessment (§3 Theme 5; cost: placement capacity, host-organisation recruitment, the loss of the current application-based selectivity, and an equity cost for students who cannot take an unpaid or relocation-dependent placement). | W3 level 2 (core placement with practitioner supervision) | High | Next course review; capstone structure update | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P11 | C2 | Attach a reliance-and-override log to one of those same audit/assurance-adjacent research-paper tasks, requiring students to document and defend any point where they relied on or departed from an automated finding, consistent with the verification duty the accounting standards body sets for auditors (§3 Theme 3; §5 CI-3; cost: rubric redesign and added marking criteria). | C2 level 3 (documented reliance/override decisions) | Medium | Term 2; assessment-brief update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P12 | C3 | Add an assessed AI-governance critique task to the same subject — auditing an automated anomaly-detection or disclosure tool for bias, transparency or accountability gaps against the accounting standards body's technology provisions (§3 Theme 3; cost: task design and access to a representative tool or case study). | C3 level 3 (governance/critique of AI systems in context) | Medium-High | Next course review; subject update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P13 | C1 | Extend that group task so the division of work between students and an AI or digital tool is itself documented and assessed — for example, requiring the team to record and justify which drafting, research or analysis steps a tool performed versus a person, consistent with the augmentation-over-automation pattern the Generative AI Capacity Study finds (§3 Theme 6; cost: task redesign and a role/tool-allocation rubric). | C1 level 3 (assessed people-and-tool coordination) | Medium-High | Next course review; task redesign | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P14 | C4 | Make a self-scoped applied project — students identify their own knowledge gap in an unfamiliar regulatory context and set out a plan to close it — a required element of the program rather than confined to the excluded Minor Thesis option (§5 CI-2; cost: supervision load for individualised project scoping). | C4 level 3 (self-scoped progression toward independent learning) | Medium-High | Next course review; capstone-option change | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P15 | C5 | Make that redesigned research paper the required route for all students rather than one option alongside a take-home exam, and add a staged supervised review of the methodology before final submission (§3 Theme 4; cost: loss of the exam alternative's marking-load relief, plus added supervision time). | C5 level 3 (required primary-evidence project, defended) | High | Next course review; assessment-structure change | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P16 | W1 | Extend the guest-speaker element already present in Climate Law, Economics and Finance so the guest speaker judges the presentation against professional-conduct criteria, rather than only receiving questions, and repeat a comparable external-audience task in at least one other subject (cost: guest-panel coordination and shared assessment criteria). | W1 level 3 (repeated, external-audience-judged communication) | Medium-High | Next course review; external-panel coordination | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P17 | W2 | Extend the accreditation-application task, and the term-sheet negotiation and pitch work already described in International Sustainable Finance's subject overview, into an assessed capstone-level task with a genuine practice constraint — a real resource limit, an externally supplied brief, or assessment by an industry panel (§3 Theme 5; §2 Signal 3; cost: capstone redesign and possible industry-panel coordination). | W2 level 3 (assessment spine with a genuine practice constraint) | High | Next course review; capstone-level task | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P18 | W3 | Extend the internship into a required sequence — an initial shorter placement earlier in the program plus the existing five-week placement — with structured reflection and documented accountability to the host organisation added to the current Organisation-report hurdle and legal-writing assessment (cost: additional host partnerships, a second supervised placement cycle, and further equity cost from extending unpaid or relocation-dependent placement time). | W3 level 3 (substantial required, supervised work-situated learning) | High | Next course review; placement-sequence expansion | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | FAIL | PASS requires 'an all-compulsory specialist core, an accredited sequence, or a staged prerequisite chain.' This course requires only Fundamentals of the Common Law (conditionally) plus 87.5 credit points 'from the prescribed list' — a ~30-subject elective menu with no documented compulsory sequence or prerequisite chain. The prescribed list mixes energy/resources-specific subjects with generic law subjects also offered across other Melbourne Law Masters streams (e.g. International Commercial Arbitration, Indigenous Rights in Global Context), so students can satisfy the credit requirement without a fixed, progressive, discipline-specific core. No accreditation is mentioned. | Actions above that require a 'core unit' placement — most of the level-2 and level-3 anchors — would need to nominate one or more named subjects as compulsory within a stream, since the program currently has no all-compulsory specialist core, accredited sequence or staged prerequisite chain of its own. Doing so for even a small subject set would itself begin to address this gate, but no single action in this plan depends on a full G1 fix (cost: reduced elective choice for the affected cohort). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | FAIL | PASS requires assessments with 'defended trade-off decisions, or simulations/capstones/live projects with real uncertainty and accountability.' Sampled subjects are assessed almost entirely by take-home examination, research paper, or class participation. Two subjects gesture toward simulation: Energy Resources in Emerging Markets states 'There will be daily simulated negotiation exercises,' but that subject is 'Not available in 2026' and its graded items are only participation (10%) and a take-home exam (90%), with no documented link to the exercises; International Sustainable Finance describes 'term sheet negotiations, and pitches' in its overview, not confirmed against the graded 'Case study activity' item. Insufficient to pass; resolved to FAIL. | Actions that introduce defended trade-off or simulation-style tasks (the C1, C5 and W2 actions above) should build on the case-study and negotiation content already described in Environmental Law, International Sustainable Finance and Impact Investing, rather than on a new stand-alone simulation: Energy Resources in Emerging Markets' own simulated-negotiation exercises are not linked to its graded items, and the subject is not offered in 2026 (cost: redesign of an existing assessed task rather than reliance on an unavailable one). | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C2 | 0 | 1 | +1 adaptive | 4 / 15 | 3 / 9 |
| P2 | C2 | 1 | 2 | +1 adaptive | 5 / 15 | 3 / 9 |
| P3 | C2 | 2 | 3 | +1 adaptive | 6 / 15 | 3 / 9 |
| P4 | C3 | 0 | 1 | +1 adaptive | 7 / 15 | 3 / 9 |
| P5 | C3 | 1 | 2 | +1 adaptive | 8 / 15 | 3 / 9 |
| P6 | C3 | 2 | 3 | +1 adaptive | 9 / 15 | 3 / 9 |
| P7 | C1 | 1 | 2 | +1 adaptive | 10 / 15 | 3 / 9 |
| P8 | C1 | 2 | 3 | +1 adaptive | 11 / 15 | 3 / 9 |
| P9 | C4 | 1 | 2 | +1 adaptive | 12 / 15 | 3 / 9 |
| P10 | C4 | 2 | 3 | +1 adaptive | 13 / 15 | 3 / 9 |
| P11 | C5 | 1 | 2 | +1 adaptive | 14 / 15 | 3 / 9 |
| P12 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 3 / 9 |
| P13 | W1 | 1 | 2 | +1 workplace | 15 / 15 | 4 / 9 |
| P14 | W1 | 2 | 3 | +1 workplace | 15 / 15 | 5 / 9 |
| P15 | W2 | 1 | 2 | +1 workplace | 15 / 15 | 6 / 9 |
| P16 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 7 / 9 |
| P17 | W3 | 1 | 2 | +1 workplace | 15 / 15 | 8 / 9 |
| P18 | W3 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
