// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Urban and Cultural Heritage (MC-UCH) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Urban and Cultural Heritage (MC-UCH)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-30 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-uch.md
**Position basis:** Destination AI Exposure 92.85 (partial basis) × Curriculum Adaptiveness 6/15 (v4.2 draft, sub-scale A) · Workplace practice 6/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a partial basis (Master of Urban Planning), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

Panel C scores this program at level 1 across four of five Adaptive items (C1 distributed cognition and relational capability, C2 hybrid metacognition and evaluative judgement, C3 digital and AI literacy including governance, C5 inquiry and evidence generation) and level 2 across life-long learning and transfer (C4) and all three Workplace items (W1 professional communication and conduct, W2 authentic task design, W3 work-situated learning). Both gates — G1 disciplinary foundation and G2 decision-making under uncertainty — currently fail.

The market evidence in reports/dfva-market-mc-uch.md rests on a field-of-education destination basis, not this program's own graduates (§1), and names five occupation families. The regulatory and study-level themes recorded against those families point most directly at the Adaptive gap: unresolved AI-generated design authorship (§3 Theme 1), new AI/digital-tool duties layered onto construction management (§3 Theme 3, Theme 4), voluntary rather than statutory ICT professional standards (§3 Theme 5), and a study-level finding that generative AI is more likely to augment technical/engineering-adjacent work than automate it (§3 Theme 6). None of the five named job families carries a statutory licensing regime for this program's likely graduates (§1; §3 Theme 2, Theme 5), so the market evidence puts the weight on the program's own assessed AI/digital literacy and evaluative judgement, not on an external accreditation floor — the gap this plan targets first.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C1 Distributed cognition & relational capability | Adaptive | 1 / 3 | 2 | No signal in §2 or §3 names team-based or human-AI-tool coordination directly; the closest is §3 Theme 3, where new WHS duties require construction managers to coordinate decisions across people and digital/AI systems on site. | 1 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | §3 Theme 4: state builder licensing holds the construction manager, not the AI tool, accountable for the accuracy of AI-generated representations — the market's clearest signal that evaluative judgement over AI-generated output is a live requirement in a named occupation. | 2 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | §3 Theme 1 (AI-generated design copyright left unresolved), Theme 3 and Theme 4 (AI/digital-tool WHS and accountability duties), Theme 5 (voluntary, not statutory, ICT certification) and Theme 6 (generative AI more likely to augment than automate technical/engineering-adjacent work) together point to AI/digital-tool literacy and governance as a live, unresolved requirement across the named occupation families. | 3 |
| C5 Inquiry & evidence generation | Adaptive | 1 / 3 | 2 | No signal in §2 or §3 names research-methods or evidence-generation skill directly; none of the five named job families' advertisement samples (§2) calls out inquiry or evidence-generation keywords. | 4 |
| C4 Life-long learning & transfer | Adaptive | 2 / 3 | 1 | §4 marks project delivery — the largest-volume named skill (§2 Signal 2, 6,711 postings) — Rising, because Theme 3 and Theme 4 (§3) add new WHS and accountability duties to construction managers as AI/digital tools enter site delivery, a transfer-and-adaptation demand. | 5 |
| **Adaptive capabilities** | **Adaptive** | **6 / 15** | **9** | — | — |
| W1 Professional communication & conduct | Workplace | 2 / 3 | 1 | §3 Theme 4: construction managers must own the accuracy of AI-generated representations to a client or regulator — professional accountability delivered to a real external party, the signal behind this item's target level. | 6 |
| W2 Authentic task design | Workplace | 2 / 3 | 1 | §2 Signal 2 (6,711 postings) and §3 Theme 3/Theme 4 describe project delivery as a live, accountable, regulator-facing task carrying genuine constraints (WHS duties, licensing accountability) — the market's clearest authentic-task signal. | 7 |
| W3 Work-situated learning | Workplace | 2 / 3 | 1 | No signal names placement or work-situated learning directly; the closest is the combined volume of the two largest named job families (§2 Signal 1, Signal 2), which together account for most of the advertisement sample. | 8 |
| **Workplace practice** | **Workplace** | **6 / 9** | **3** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Option: add an assessed group or stakeholder-facing task to a compulsory core unit (cost: assessment redesign and moderation across the unit), warranted by Theme 3 (§3): new AI/digital-work-systems WHS duties require construction managers to coordinate decisions across people and digital tools on site, a distributed-cognition demand this anchor targets. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Option: extend the level-2 collaborative task so it recurs in a second compulsory unit, adding a task where the division of work between people and an AI/digital tool is itself assessed (cost: redesign across two units, ongoing moderation), warranted by the same Theme 3 (§3) WHS duties on AI/digital work systems. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Option: add a criterion-referenced peer-review or portfolio-standards component to a compulsory core assessment (cost: rubric design, moderation time), warranted by Theme 4 (§3): the licensed construction manager, not an AI tool, is held accountable for the accuracy of AI-generated representations, so criterion-referenced appraisal of quality is a live requirement in that named occupation. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Option: add a reliance-decision task requiring students to document when they accepted, overrode or corrected AI-generated output before it is issued (cost: assessment redesign, marking time), warranted directly by Theme 4's (§3) accuracy-accountability finding. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Option: add assessed coverage of AI capabilities and limitations to a compulsory core unit (cost: curriculum hours, staff development), warranted by Theme 1's (§3) unresolved AI-generated design copyright status and Theme 6's (§3) finding that generative AI is more likely to augment than automate technical/engineering-adjacent work. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Option: extend the level-2 content to an assessed governance task auditing an AI tool's output against the discipline's own accountability and regulatory context (cost: further curriculum hours, assessment redesign), warranted by Theme 3 and Theme 4's (§3) WHS and accuracy-accountability duties, and Theme 5's (§3) voluntary, non-statutory ICT professional standards, which leave governance judgement to the graduate rather than a regulator. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 1 → 2 | "Students design and conduct an inquiry with methodology selection and data collection, assessed." | Option: add a methodology-selection-and-data-collection component to a compulsory research task (cost: assessment redesign, supervision capacity), warranted by Theme 6 (§3): the Jobs and Skills Australia Generative AI Capacity Study is itself a methodology-driven inquiry into AI's occupational effects, the kind of primary evidence graduates in these AI-adjacent occupations will need to interpret for their own field. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Option: make a substantial primary-evidence project, with methodology defended under supervised review, the required capstone route rather than one option among several (cost: restructuring the capstone menu, staffing capacity), warranted by the same Theme 6 (§3) finding — graduates able to independently generate and defend evidence about a fast-changing, AI-adjacent labour market are better placed to track how it moves for their own occupation than by relying on a study that ages after graduation. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Option: extend the self-scoped, coordinator-approved research project already offered on one compulsory Pathway option so structured progression toward independent learning is documented for the whole cohort, not one route among two (cost: redesigning the alternative Pathway option, or adding an equivalent self-scoped component to it), warranted by §4's rising call on project delivery (§2 Signal 2, 6,711 postings) and Theme 3/Theme 4 (§3), which put a premium on managers who can adapt their own practice as AI/digital-tool duties change. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Option: route an existing professional-genre assessment to an external practitioner panel or host organisation for judging, with professional accountability explicitly among the marking criteria (cost: partner sourcing, added coordination time each teaching period), warranted by Theme 4 (§3): construction managers must own the accuracy of AI-generated representations to a real client or regulator, the professional-accountability signal behind this anchor. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Option: extend the existing host-organisation project so equivalent authentic, constraint-bearing tasks recur earlier in the program rather than in a single capstone-adjacent subject (cost: redesigning at least one additional core unit, sourcing further host relationships), warranted by Signal 2 (§2, 6,711 postings) and Theme 3/Theme 4 (§3), which describe project delivery as a live, regulator- and accountability-constrained task, the genuine constraint of practice this anchor requires. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Option: extend the current 20-day minimum placement into a longer or repeated required sequence with structured reflection and documented accountability to the host (cost: sourcing additional placement capacity, coordination and supervision time, and an equity cost for students who cannot self-fund an extended or relocation-dependent placement); justified by skill development and professional-identity formation [29], not by employment-rate gains, which Jackson and Collings [28] found WIL does not raise. Warranted by the combined volume of the two largest named job families (§2 Signal 1, Signal 2). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| AI/digital-tool WHS duties for construction managers | C3, W1 | Safe Work Australia guidance (23 Jul 2026) and NSW's WHS Amendment (Digital Work Systems) Act 2026 place express WHS duties on construction managers who introduce AI, automation or digital platforms on site. | §3 Theme 3 | MEDIUM |
| Accuracy accountability for AI-generated construction representations | C2, W1 | State builder licensing (NSW Fair Trading, Victorian Building Authority, QBCC) holds the licensed construction manager, not the AI tool, responsible for the accuracy of AI-generated quotes and representations. | §3 Theme 4 | MEDIUM |
| Unresolved AI-generated design authorship | C3 | The Copyright Act 1968 and the Attorney-General's confirmation (Oct 2025) that no text-and-data-mining exception is under consideration leave the copyright status of AI-generated design output unresolved. | §3 Theme 1 | MEDIUM |
| Generative AI augments rather than automates technical/engineering-adjacent work | C4, C5, W2 | The Jobs and Skills Australia Generative AI Capacity Study (Aug 2025) finds augmentation outweighs automation, with Technical Development & Engineering tasks showing the highest augmentability (~0.69). | §3 Theme 6 | MEDIUM |
| Project delivery is the largest-volume named skill and rising in scope | C4, W1, W2 | 6,711 postings for Construction Managers and Quantity Surveyors, the largest of the five signals; marked Rising given the WHS and accountability duties above. | §2 Signal 2; §4 | MEDIUM |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C3 | Add assessed coverage of AI capabilities and limitations to a compulsory core unit (cost: curriculum hours, staff development), warranted by Theme 1's unresolved AI-generated design copyright status and Theme 6's augmentation finding. | Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed. | medium | Term 1 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P2 | C2 | Add a criterion-referenced peer-review or portfolio-standards component to a compulsory core assessment (cost: rubric design, moderation time), warranted by Theme 4's accuracy-accountability finding for construction managers. | Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars. | medium | Term 1 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P3 | C1 | Add an assessed group or stakeholder-facing task to a compulsory core unit (cost: assessment redesign, moderation), warranted by Theme 3's AI/digital-work-systems WHS duties, which require coordinating decisions across people and digital tools. | At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity. | medium | Term 1 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P4 | C5 | Add a methodology-selection-and-data-collection component to a compulsory research task (cost: assessment redesign, supervision capacity), warranted by Theme 6, itself a methodology-driven study of AI's occupational effects. | Students design and conduct an inquiry with methodology selection and data collection, assessed. | medium | Term 2 | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P5 | C4 | Extend the self-scoped research project already offered on one compulsory Pathway option so it is documented for the whole cohort, not one route among two (cost: redesigning the alternative Pathway option), warranted by §4's rising call on project delivery and Theme 3/Theme 4. | The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them. | medium | Term 2 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P6 | C2 | Add a reliance-decision task requiring students to document when they accepted, overrode or corrected AI-generated output before it is issued (cost: assessment redesign, marking time; depends on the P2 peer-review step landing first), warranted by Theme 4. | Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment). | medium | Term 2, after the C2 peer-review step | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P7 | C3 | Extend the level-2 AI content to an assessed governance task auditing an AI tool's output against the discipline's own accountability context (cost: further curriculum hours, assessment redesign; depends on the P1 step landing first), warranted by Theme 3, Theme 4 and Theme 5. | Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation. | high | Term 3, after the C3 core-content step | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P8 | C1 | Extend the level-2 collaborative task so it recurs in a second compulsory unit and add a task where the division of work between people and an AI/digital tool is itself assessed (cost: redesign across two units, ongoing moderation; depends on the P3 step landing first), warranted by Theme 3. | Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed. | high | Term 3, after the C1 core-task step | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P9 | W1 | Route an existing professional-genre assessment to an external practitioner panel or host organisation for judging, with professional accountability explicitly among the marking criteria (cost: partner sourcing, added coordination each teaching period), warranted by Theme 4. | Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria. | high | Term 3 | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P10 | W2 | Extend the existing host-organisation project so equivalent authentic, constraint-bearing tasks recur earlier in the program rather than in a single subject (cost: redesigning at least one additional core unit, sourcing further host relationships), warranted by Signal 2 and Theme 3/Theme 4. | Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance. | high | Term 3-4 | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P11 | W3 | Extend the current 20-day minimum placement into a longer or repeated required sequence with structured reflection and documented accountability to the host (cost: sourcing additional placement capacity, coordination and supervision time, and an equity cost for students who cannot self-fund an extended or relocation-dependent placement); justified by skill development and professional-identity formation, not by employment-rate gains, which Jackson and Collings found WIL does not raise. Warranted by the combined volume of the two largest named job families. | Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer). | high | Year-level, spans multiple terms | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P12 | C5 | Make a substantial primary-evidence project, methodology defended under supervised review, the required capstone route rather than one option among several (cost: restructuring the capstone menu, staffing capacity; depends on the P4 step landing first), warranted by Theme 6. | A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review). | high | Year-level, after the C5 methodology step | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | FAIL | PASS: the program documents a coherent, staged heritage-specific structure rather than generic or interchangeable content — a compulsory Core (both subjects specific to heritage theory, policy and global practice), a compulsory Pathway component, and a Selective list confined to heritage/architecture-specific subjects (measured drawings and digital heritage, architectural conservation in Asia, urban and landscape heritage, applied heritage conservation techniques), giving disciplinary depth and progression within urban and cultural heritage. DEMOTED to FAIL by verification pass: the PASS rests on descriptive About-page marketing copy ('The core subjects... examine contemporary and theoretical approaches...') plus the four bare credit-point headings, not on documented 'progressive technical or methodological depth' or a 'staged prerequisite chain' — no prerequisite structure appears anywhere in the extract. Only 25 of 100 credit points (the two Core subjects) are genuinely compulsory and heritage-specific; the Pathway (25cp) is a choice of two unrelated formats (research thesis vs. internship); the Selective list (25cp) is heritage-confined as claimed, but the Elective list (25cp, unconstrained choice) pulls in subjects with no disciplinary tie to urban/cultural heritage — Marketing the Arts, Cultural Festivals and Special Events, Twenty-first Century Architecture, Planning Theory and History, Construction History, RESPECT, Sustainable Collections. That is a quarter of the degree open to generic/interchangeable content, which cuts against 'all-compulsory specialist core' and toward the FAIL anchor ('generic or interchangeable content without disciplinary identity') for that portion. G1 is treated as, at minimum, a much weaker PASS than argued, defaulted to FAIL given the evidentiary gap on progression/depth. | Any redesign that further dilutes the compulsory, heritage-specific core (currently only the two Core subjects, 25 of 100 credit points) or extends the unconstrained Elective list (25 credit points, currently open to subjects with no disciplinary tie to urban or cultural heritage) worsens this gate. Interventions above should land in the Core or Pathway components, not the Elective list, consistent with the anchor's requirement for core placement. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | FAIL | PASS: the compulsory Internship Pathway option places students in a live project with real accountability — students 'develop and complete a specific project in discussion with the host organisation,' supervised jointly by the Subject Coordinator and a host-organisation representative, assessed via a project deliverable, a reflective journal and a coordinator-meeting hurdle. This is a live project with real uncertainty and accountability to an external party, satisfying the anchor. Rests on the Internship route specifically (see ambiguities). DEMOTED to FAIL by verification pass: the PASS is earned entirely by the internship's live host-organisation project — one of two compulsory Pathway options. The rationale's own ambiguities note admits 'the alternative Minor Thesis route does not evidence comparable real-world uncertainty/accountability in the extract,' meaning roughly half the cohort (by design, a free compulsory choice) has no documented basis for this gate. A program-level gate that only half of all graduates' documented curriculum satisfies is exactly the kind of ambiguous-between-outcomes case the scoring-direction rule addresses ('when the evidence is ambiguous... take the LOWER level... never resolve ambiguity upward'); the same reasoning was used elsewhere in this scoring to withhold level-3 credit on W1–W3 for single-route, non-universal evidence. For internal consistency and per the default-to-refute instruction, G2 does not stand as a clean program-wide PASS on internship-only evidence. | The PASS this gate would need currently rests entirely on the Internship Pathway option; the alternative Minor Thesis route does not evidence comparable real-world uncertainty or accountability. Any redesign must not make the live, accountable Internship project easier to avoid, and closing the gap requires adding comparable uncertainty and accountability content to the Minor Thesis route too, not only preserving the Internship route for the half of the cohort that chooses it. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C1 | 1 | 2 | +1 adaptive | 7 / 15 | 6 / 9 |
| P2 | C1 | 2 | 3 | +1 adaptive | 8 / 15 | 6 / 9 |
| P3 | C2 | 1 | 2 | +1 adaptive | 9 / 15 | 6 / 9 |
| P4 | C2 | 2 | 3 | +1 adaptive | 10 / 15 | 6 / 9 |
| P5 | C3 | 1 | 2 | +1 adaptive | 11 / 15 | 6 / 9 |
| P6 | C3 | 2 | 3 | +1 adaptive | 12 / 15 | 6 / 9 |
| P7 | C5 | 1 | 2 | +1 adaptive | 13 / 15 | 6 / 9 |
| P8 | C5 | 2 | 3 | +1 adaptive | 14 / 15 | 6 / 9 |
| P9 | C4 | 2 | 3 | +1 adaptive | 15 / 15 | 6 / 9 |
| P10 | W1 | 2 | 3 | +1 workplace | 15 / 15 | 7 / 9 |
| P11 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 8 / 9 |
| P12 | W3 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
