// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Science (Mathematics and Statistics) (MC-SCIMAT) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Science (Mathematics and Statistics) (MC-SCIMAT)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-30 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-scimat.md
**Position basis:** Destination AI Exposure 95.71 (cognate basis) × Curriculum Adaptiveness 8/15 (v4.2 draft, sub-scale A) · Workplace practice 3/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a cognate basis (Bachelor of Science (Mathematics and Statistics)), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

The program sits at Level 1 on five of eight items (C2, C3, W1, W2, W3) and Level 2 on the remaining three (C1, C4, C5), for an adaptive sub-scale of 8/15 and a workplace sub-scale of 3/9. The market report's dominant signal is Accountants and Auditors (§2, Signal 1, 6,240 postings against a named employer set of PwC, Deloitte, EY, KPMG, BDO and Grant Thornton), paired with a regulatory requirement (§3, Theme 1) that auditors verify automated anomaly-detection outputs and keep documented audit trails for AI-generated financial estimates, and a sharply rising sustainability-assurance skill (§4) traced to a graduate shortage in multi-capital greenhouse-gas assurance (§3, Theme 2).

Both patterns point the same way: the curriculum's gaps in appraising and governing automated-tool output (C2, C3), producing a practitioner-grade assurance artefact (W2), and defending independent research judgement (C4, C5) line up with named, dated market evidence rather than a generic AI-adjacent concern.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | Theme 1 (§3): professional standards require auditors to verify automated anomaly-detection outputs and keep documented audit trails for AI-generated estimates — a criterion-referenced appraisal and reliance-justification task the curriculum does not yet assess. | 1 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | The same regulatory requirement (§3, Theme 1), read as a governance gap: auditors must discuss and account for the limits of the automated tools they rely on, where the curriculum currently confines AI content to electives or operational tool use. | 2 |
| C1 Distributed cognition & relational capability | Adaptive | 2 / 3 | 1 | Signal 5 (§2): the Software Developers family's recurring keywords (AI-assisted coding, code review and testing) and Theme 1's (§3) auditor/automated-tool verification requirement both describe work divided between people and automated systems, not people alone. | 6 |
| C4 Life-long learning & transfer | Adaptive | 2 / 3 | 1 | Theme 2 (§3) names a specific, fast-moving knowledge area — sustainability-assurance methods — where a documented, self-scoped progression toward independent learning has a concrete, checkable stake. | 7 |
| C5 Inquiry & evidence generation | Adaptive | 2 / 3 | 1 | The same sustainability-assurance shortage (§3, Theme 2) implies that methodology in this area needs to be defended under scrutiny, not only selected and reported. | 8 |
| **Adaptive capabilities** | **Adaptive** | **8 / 15** | **7** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Signal 1 and Signal 3 (§2) name concentrated employer sets (PwC, Deloitte, EY, KPMG, BDO, Grant Thornton; Queensland Treasury) that expect client- or stakeholder-facing communication; Theme 5 (§3) sets a practice-drawn communication and conduct standard for statisticians through the Statistical Society of Australia's accreditation pathways. | 3 |
| W2 Authentic task design | Workplace | 1 / 3 | 2 | Theme 2 (§3): mandatory sustainability reporting standards create an acute shortage of accounting graduates able to produce multi-capital greenhouse-gas assurance work, matching the sharply rising ASRS sustainability assurance keyword (§4) — a practitioner artefact the curriculum does not yet assess. | 4 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | Signal 1 and Signal 3 (§2) show that the destinations this program's graduates already enter (Accountants and Auditors; Statisticians, per §1) are active, named-employer job families, which supports a placement host base without implying a placement would raise employment rates. | 5 |
| **Workplace practice** | **Workplace** | **3 / 9** | **6** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Add a structured-critique task to a core assessment in which students appraise the quality of an automated tool's output (for example, an anomaly-detection or forecasting model) against a marking rubric and justify their judgement, satisfying Level 2's criterion-referenced appraisal requirement. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Extend that task so students keep and submit a documented log of when they relied on, adjusted or overrode the automated tool's output, and defend that judgement — mirroring the audit-trail discipline Theme 1 (§3) describes for AI-generated financial estimates. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Add a core assessment task requiring students to identify and discuss the capabilities and limitations of an automated tool used in a discipline context (for example, an anomaly-detection or forecasting algorithm), rather than assessing only its operation. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Extend that task to require students to critique the governance of the AI system against a named regulatory or professional-standards requirement — for example, the audit-trail and verification obligations Theme 1 (§3) describes for AI-generated financial estimates. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Add a core assessment in a recognised professional genre — for example a client-facing audit memo, or a briefing note styled on the Statistical Society of Australia's practice criteria (§3, Theme 5) — judged against criteria drawn from professional practice rather than academic criteria. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Sequence that professional-genre task so it recurs at a later stage of the program, with the later instance delivered to, or judged by, an external practitioner and professional conduct named explicitly among the assessed criteria. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Add a core assessment where students produce a multi-capital greenhouse-gas assurance or climate-risk governance artefact of the kind Theme 2 (§3) reports accounting graduates are short in, judged against criteria drawn from practice. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Make that task recur at more than one stage of the program rather than standing alone, with at least one instance set against the Australian Sustainability Reporting Standards themselves as the externally supplied constraint Theme 2 (§3) describes. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Move the existing Science and Technology Internship from an elective option to a core, assessed live-client or community project supervised by a practitioner — justified by skill development and professional identity, not by an employment-rate claim (per the instrument's W3 honesty rule). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the core placement added at Level 2 into a longer or repeated requirement, with structured reflection and documented accountability to the host, noting the equity cost of an unpaid or relocation-dependent placement. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Add a second, later core assessment beyond the existing group project (MAST90014) that requires students to document how work was divided between team members and an automated tool or AI system, mirroring the human/automated-system coordination Signal 5 (§2) and Theme 1 (§3) describe in adjacent job families. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Document the Research Project Component's topic-selection step so it clearly requires students to scope their own research question rather than select from a supervisor-offered list, and add an assessed step where students identify a knowledge gap — for example, in the sustainability-assurance area Theme 2 (§3) names — with a plan to close it. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Add a staged, supervised review or oral defence of the Research Project's methodology to the existing thesis-and-presentation requirement, so methodology is defended under scrutiny rather than only reported. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| Audit-trail and reliance-documentation task | C2 | Theme 1 (§3): professional standards require auditors to verify automated anomaly-detection outputs and keep documented audit trails for AI-generated financial estimates. | §3, Theme 1 | HIGH |
| AI-governance critique task | C3 | Theme 1 (§3), read as a governance requirement: auditors must account for the limits of automated tools they rely on. | §3, Theme 1 | HIGH |
| Professional-genre communication task | W1 | Signal 1 and Signal 3 (§2): named Big Four/mid-tier and Queensland Treasury employers; Theme 5 (§3): SSA accreditation sets a practice-drawn communication standard for statisticians. | §2, Signal 1 and Signal 3; §3, Theme 5 | HIGH |
| Sustainability-assurance artefact | W2 | Theme 2 (§3): mandatory sustainability reporting standards create an acute shortage of graduates skilled in multi-capital greenhouse-gas assurance; §4: ASRS sustainability assurance is a sharply rising keyword. | §3, Theme 2; §4 | HIGH |
| Core placement | W3 | Signal 1 and Signal 3 (§2) show the Accountants and Auditors and Statisticians job families this program's graduates already enter are active, named-employer families. | §1; §2, Signal 1 and Signal 3 | HIGH |
| Human/AI work-division task | C1 | Signal 5 (§2): recurring Software Developers keywords (AI-assisted coding, code review and testing); Theme 1 (§3): auditors coordinating work with automated anomaly-detection tools. | §2, Signal 5; §3, Theme 1 | HIGH |
| Self-scoped research documentation | C4 | Theme 2 (§3) names sustainability-assurance methods as a specific, fast-moving knowledge area suited to an independent-learning gap-closing task. | §3, Theme 2 | HIGH |
| Methodology defence | C5 | Theme 2 (§3): the same sustainability-assurance shortage implies methodology in this area needs to be defended, not only reported. | §3, Theme 2 | HIGH |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C4 | Document the Research Project Component's topic-selection step as self-scoped, and add an assessed knowledge-gap identification step (optionally scoped to sustainability-assurance methods, §3 Theme 2). | The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them. | low | Term 1 — documentation and process clarification, before teaching starts | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P2 | C1 | Add a second, later core assessment requiring students to document how work was divided between team members and an automated tool or AI system. | Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems. | medium | Term 1 — extends the existing MAST90014 group assessment | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P3 | C2 | Add a structured-critique task appraising an automated tool's output against a rubric, then extend it to a documented reliance log defending each override or adjustment decision. | Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time. | medium | Term 1–2 — critique task first, reliance log added the following term | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P4 | C3 | Add an AI capability/limitations discussion to a core unit's assessment, then extend it to a governance critique against a named regulatory or professional-standards requirement. | Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation. | medium | Term 2 — capability/limits discussion first, governance critique added the following term | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P5 | W1 | Add a client-facing or practice-styled professional-genre task judged against practice criteria, then sequence a later instance to a real external audience or practitioner. | Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner, with professional conduct or accountability explicitly among the assessed criteria. | medium | Term 1–2 — professional-genre task first, external audience added the following instance | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P6 | C5 | Add a staged supervised review or oral defence of the Research Project's methodology to the existing thesis-and-presentation requirement. | A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review). | medium | Term 3 — added to the existing Research Project Component | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P7 | W2 | Add a multi-capital greenhouse-gas assurance or climate-risk governance artefact as a core assessment, then make it recur at more than one stage with at least one instance set against the Australian Sustainability Reporting Standards themselves. | Such tasks are the program's assessment spine rather than a single instance AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance. | high | Term 2–3 — new artefact first, spine and externally supplied constraint follow | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P8 | W3 | Move the elective Science and Technology Internship into a core, assessed, practitioner-supervised project, then extend it into a longer or repeated requirement with structured reflection and accountability to the host. | Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice. | high | Term 3–4 — core placement first, extension and sequencing follow | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | A compulsory specialisation (62.5 points) chosen from five discipline strands, each with compulsory subjects plus electives, layered with 75 points of Further Discipline subjects — a coherent, progressively advanced specialist core. | Any redesign must preserve the coherent, progressively advanced specialist core (the compulsory specialisation plus Further Discipline subjects) that carries this gate; new assessment tasks should sit inside that core, not dilute it with generic content. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | The compulsory Research Project Component is a self-scoped, supervised, 800-hour original research undertaking culminating in a thesis and presentation — the closest documented match to a capstone with real uncertainty and accountability. | Any redesign must keep the Research Project Component's self-scoped, supervised, substantial character intact; new C5/W2 assessment should build on that 800-hour thesis requirement rather than replace or shrink it. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C2 | 1 | 2 | +1 adaptive | 9 / 15 | 3 / 9 |
| P2 | C2 | 2 | 3 | +1 adaptive | 10 / 15 | 3 / 9 |
| P3 | C3 | 1 | 2 | +1 adaptive | 11 / 15 | 3 / 9 |
| P4 | C3 | 2 | 3 | +1 adaptive | 12 / 15 | 3 / 9 |
| P5 | W1 | 1 | 2 | +1 workplace | 12 / 15 | 4 / 9 |
| P6 | W1 | 2 | 3 | +1 workplace | 12 / 15 | 5 / 9 |
| P7 | W2 | 1 | 2 | +1 workplace | 12 / 15 | 6 / 9 |
| P8 | W2 | 2 | 3 | +1 workplace | 12 / 15 | 7 / 9 |
| P9 | W3 | 1 | 2 | +1 workplace | 12 / 15 | 8 / 9 |
| P10 | W3 | 2 | 3 | +1 workplace | 12 / 15 | 9 / 9 |
| P11 | C1 | 2 | 3 | +1 adaptive | 13 / 15 | 9 / 9 |
| P12 | C4 | 2 | 3 | +1 adaptive | 14 / 15 | 9 / 9 |
| P13 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
