// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Public Health (UNSW-9045) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Public Health (UNSW-9045)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-09-07 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-unsw-9045.md
**Position basis:** Destination AI Exposure 76.50 (field basis) × Curriculum Adaptiveness 5/15 (v4.2 draft, sub-scale A) · Workplace practice 3/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a field basis (Jobs and Skills Australia Higher Education Outcomes (JSA HEO) field 0613 Public Health), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

UNSW's Master of Public Health scores 5/15 on adaptive capabilities and 3/9 on workplace practice, with every item at level 1 — the capability is named in a program or course outcome, but no core unit assesses it. This field carries an estimated destination AI exposure of 76.50 (field-of-education basis, since this program has no destination record of its own), so the priority order below follows headroom; where the market report names no signal for a specific item, the action rests on the rubric anchor alone and says so.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C1 Distributed cognition & relational capability | Adaptive | 1 / 3 | 2 | About a fifth of the field's entry destinations sit in clerical, administrative and retail occupations that Jobs and Skills Australia's Generative AI Capacity Study scores as its highest-automatability cluster (market report §3 Theme 4; §5 CI-3). | 1 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | Deakin University's 2026 national survey is mapping what skills and ethical knowledge this workforce needs for responsible AI use, with findings pending at the time of writing (market report §3 Theme 2; §5 CI-2) — evaluative judgement of AI-assisted work is the open question that survey is trying to answer. | 2 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | The Public Health Association of Australia convened an AI & Public Health Conference in 2026 on maximising benefits and minimising harms (market report §3 Theme 1), and Deakin's 2026 workforce survey is running because the field does not yet know what AI-integrated practice should look like (§3 Theme 2; §5 CI-2). | 3 |
| C4 Life-long learning & transfer | Adaptive | 1 / 3 | 2 | About a fifth of entry destinations sit in the field's highest-automatability occupational cluster (market report §3 Theme 4; §5 CI-3), so transfer of public health methods into a general administrative setting is a live destination for this cohort, not a hypothetical one. | 4 |
| C5 Inquiry & evidence generation | Adaptive | 1 / 3 | 2 | No occupation-specific market signal in this report names inquiry or research-methods skill directly; the case rests on the field's overall estimated 76.50 destination AI exposure (field-of-education basis) rather than a named market shift. | 5 |
| **Adaptive capabilities** | **Adaptive** | **5 / 15** | **10** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Health promotion is the field's single largest entry destination (4.2% of graduates) and carries no statutory registration — the Public Health Association of Australia offers guidance, not a licence (market report §3 Theme 1; §5 CI-1) — so the transcript is the only signal an employer reads. | 6 |
| W2 Authentic task design | Workplace | 1 / 3 | 2 | The same destination gap as W1: health promotion's status as the largest entry destination with no external competence certification (market report §5 CI-1) means an assessed artefact has to carry the evidence a licence would otherwise supply. | 7 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | No occupation-specific market signal in this report supports a placement mandate for this cohort. §3 Theme 6 ties low AI-automation risk for nursing and allied health to AHPRA's requirement that a registered human remain accountable for care decisions, but §3 Theme 1 records that health educators are not AHPRA-registered practitioners, so that accountability logic does not transfer to this program's core cohort. | 8 |
| **Workplace practice** | **Workplace** | **3 / 9** | **6** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Add an assessed group task to one core course — a joint health-promotion plan in PHCM9012, or a team-based epidemiological brief in PHCM9794 — marked with individual as well as team-level criteria, so collaboration moves from an outcome statement to assessed practice. Warranted by CI-3: about a fifth of the field's entry destinations sit in the clerical/administrative/retail cluster JSA scores as most automatable (§3 Theme 4), where team-based coordination is a documented point of difference from routine solo tasks. Cost: a group-assessment brief and an individual-contribution criterion, within the existing course. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Extend the same group task so the brief specifies which parts of the work are done by team members and which by a named tool — a statistics package, a drafting assistant — and mark the documented division of labour as a criterion, not only the output. Warranted by Deakin University's 2026 national survey of how AI tools are used in public health and health-promotion work (§3 Theme 2; §5 CI-2): the field is actively defining this human/tool division, and assessment should track it, not assume it. Cost: an amendment to the existing rubric; no additional credit points. Per R2, if only the brief's wording changes and no criterion actually marks the division of labour, the level does not move. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Add a criterion-referenced peer-review or structured-critique task to one core course — for example, peer critique of an epidemiological study appraisal in PHCM9794, marked against a stated quality rubric rather than open commentary — so appraisal becomes assessed, criteria-driven judgement rather than an outcome statement. Warranted by Deakin's 2026 survey identifying evaluative and ethical judgement as an open skill gap for this workforce (§3 Theme 2; §5 CI-2). Cost: a marking rubric and a peer-allocation mechanism, within the existing course. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Once appraisal is criterion-referenced, add a short reflective component requiring students to state where they relied on, or overrode, a specific tool, source or collaborator, and defend that call against the same criteria. Warranted by the same Deakin survey, whose stated purpose is establishing what reliance-aware, ethical AI use looks like for this workforce ahead of its own findings (§3 Theme 2). Cost: an added component on an existing assessment; no new subject. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Extend PHCM9795's existing statistical-software task to cover what its outputs can and cannot be trusted to do, and add an assessment criterion on that judgement rather than leaving the software content at pure operation. Warranted directly by CI-2: Deakin's 2026 survey is investigating this because the field does not yet know, so teaching the verification half now — provenance of an AI-drafted synthesis, checking a generated citation exists — does not wait on the survey's result (§3 Theme 2; §5 CI-2). Cost: a session and an assessment criterion inside an existing subject, matching the market report's own costing for this implication. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Extend the same assessment so students critique a governance question specific to public health data — bias in a health dataset, or accountability for an AI-assisted screening or triage recommendation — rather than AI use in general. Warranted by the Public Health Association of Australia's 2026 AI & Public Health Conference, convened on maximising benefits and minimising harms (§3 Theme 1), which signals the profession is defining its own governance questions rather than importing a generic AI-ethics unit. Cost: a case study drawn from public health practice, within the same course. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 1 → 2 | "At least one core assessment requires application to novel or unfamiliar problems — case variation, unseen datasets, cross-context projects." | Add a second, contrasting case or dataset to an existing core assessment — the current health-promotion planning task applied to a non-clinical setting such as a workplace or local-government program, alongside its present health-service setting — so transfer is assessed rather than assumed. Warranted by CI-3: about a fifth of the field's entry destinations sit in the clerical, administrative and retail occupations JSA scores as most automatable (§3 Theme 4; §5 CI-3), so graduates need to show the same method travels into that kind of setting. Cost: an alternative assessment context, no new subject — the market report's own costing for this implication. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Make the existing Project, Independent Study or Minor Project route (PHCM9144 and its siblings) a required core capstone rather than a WAM-gated elective substitution; short of that, add a core-course task where students identify a knowledge or skill gap relevant to a target destination and set out a plan to close it, assessed against a rubric. Warranted by the same CI-3 exposure pressure (§3 Theme 4): a fifth of destinations sit in the field's most automatable cluster, so a documented plan for closing that gap is a defensible market response. Cost: opening a WAM-gated elective to the whole cohort is a program-structure change with admission and staffing implications; the knowledge-gap task alone is a rubric addition to an existing course. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 1 → 2 | "Students design and conduct an inquiry with methodology selection and data collection, assessed." | Extend PHCM9795's existing statistical-software task so students source or collect a dataset themselves, rather than working only from data supplied to them, and justify the methodology choice against stated criteria for data-collection design. No occupation-specific market signal in this report names inquiry skill directly; the field's overall estimated 76.50 destination AI exposure (field-of-education basis) is the only market context available, so this action rests primarily on the rubric anchor. Cost: a data-sourcing component added to an existing assessment. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make the Project (PHCM9144) or an equivalent substantial-inquiry route a required core component, with a staged supervised review — a proposal review, then a final defence — rather than a single submission. As with C5:2, no market-report signal names this item specifically; the option is recorded against the rubric anchor, with the field-of-education exposure basis as the only available market context. Cost: converting an elective, WAM-gated route to a required core component is a substantial program-structure and staffing change. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Give one core course's existing assessment — PHCM9012's health-promotion planning task, or PHCM9795's data-presentation outcome — a professional brief and audience: a health-promotion plan written for a named funding body or local health district, or a statistical findings report addressed to a public-health audience rather than the marker, judged against criteria drawn from that genre. Warranted by CI-1: health promotion is the field's largest entry destination (4.2%) and carries no statutory registration, so the transcript is the only signal an employer reads (§3 Theme 1; §5 CI-1). Cost: rewriting an existing assessment's brief and marking criteria, within current credit points — the market report's own costing. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Repeat the professional-genre task from W1:2 in at least one further core course, and for at least one instance bring in a practitioner or a real health district's stated evaluation criteria to judge the artefact, with professional conduct explicitly among the assessed criteria. Warranted by the same CI-1 gap (§5): with no licence certifying competence, a real-audience judgement is the closest available substitute. Cost: recurring the brief across two courses, plus arranging one external or practitioner reviewer per cohort. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Turn PHCM9012's practitioner-role framing into an assessed end-to-end task: students take a real or realistically constrained community health problem from root-cause mapping to a costed intervention plan, producing the artefact a health-promotion practitioner would produce, marked against practice-drawn criteria rather than an essay rubric. Warranted by CI-1 (§5): with no registration body certifying competence, the assessed artefact has to carry the evidence a licence would otherwise supply. Cost: the course already carries the scenario; the change is to the artefact and criteria, not new content. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Make an end-to-end authentic task the spine across at least two core courses, not a single instance, and give at least one of them a genuine constraint — an externally supplied or ambiguous brief, a real resource or time limit, or a named external audience. Warranted by the same CI-1 destination pressure (§5) at greater scale: the largest single entry destination has no external quality gate at all, so the program's own assessment spine is the only calibration a graduate carries into it. Cost: coordinating criteria and constraints across two or more course coordinators. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Convert the existing internship (PHCM9143) from a merit-based elective substitution into a short required core placement or live community-based project, with practitioner supervision and an assessed outcome. Justify this on skill-development and professional-identity grounds [[29]](https://doi.org/10.1080/07294360.2016.1139551), not on employment-rate grounds — work-integrated learning does not raise employment rates [[28]](https://doi.org/10.1007/s10734-017-0216-z) — and note the equity cost of an unpaid or relocation-dependent placement for a fee-paying postgraduate cohort [[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report). No occupation-specific market signal in this report supports this specifically for health promotion; §3 Theme 1 places health educators outside AHPRA registration, so Theme 6's registered-accountability logic does not transfer. Cost: converting a merit-based elective into a required core placement carries admission-load and host-capacity implications the market report does not cost. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the placement into a required sequence — two shorter placements, or one extended one — with structured reflection and documented accountability to the host, on the same skill and professional-identity grounds [[29]](https://doi.org/10.1080/07294360.2016.1139551) rather than employment-rate grounds [[28]](https://doi.org/10.1007/s10734-017-0216-z), and with the same equity caveat [[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report). As with W3:2, no report signal warrants this specific extension; it is recorded for rubric completeness only. Cost: substantially larger than W3:2 — host-capacity and supervision costs scale with sequence length. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| CI-1: Health promotion carries no statutory registration; the transcript is the only signal an employer reads | W1, W2 | Health promotion is the field's largest entry occupation (4.2% of graduates, REAL GRADUATE DESTINATIONS table) and has no licence validating competence — the Public Health Association of Australia offers guidance, not registration | §5 CI-1; §3 Theme 1 | MEDIUM (§3 declares this section MEDIUM confidence); the 4.2% destination share is drawn from the JSA Higher Education Outcomes table |
| CI-2: Deakin's 2026 national AI-skills survey for the public health and health-promotion workforce | C2, C3 | An ethics-approved national survey is mapping AI tool use and the ethical knowledge this workforce needs, precisely because the field does not yet know; findings were pending at the time of writing | §5 CI-2; §3 Theme 2 | MEDIUM (§3 declares this section MEDIUM confidence); the survey's own findings are not yet available |
| CI-3: Clerical, administrative and retail destinations are the field's highest-automatability cluster | C1, C4 | JSA's Generative AI Capacity Study scores routine clerical and administrative roles as the highest-exposure occupations; roughly a fifth of this field's entry destinations sit in that cluster | §5 CI-3; §3 Theme 4; REAL GRADUATE DESTINATIONS table | MEDIUM (§3 discussion signal, JSA study); the destination share itself is LOW confidence per §6 — field-of-education grain, not this program's own graduates |
| CI-4: Registered nursing is a gated destination reached by a separate qualification, not by this program | — (no curriculum action, per the market report's own instruction) | Registered nursing is 3.7% of entry destinations, and NMBA registration standards (CPD, recency of practice, English-language requirements) are a floor this program does not supply | §5 CI-4; §3 Theme 5 | HIGH (regulatory and statutory instrument, per §6's per-lane confidence table) |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C3 | Extend PHCM9795 to cover AI capabilities and limitations, with an assessment criterion added — teach verification (provenance, checking a generated citation exists) now, ahead of Deakin's survey findings. | Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed. | low | term 1 | §3 Theme 2; §5 CI-2 |
| P2 | W1 | Give PHCM9012 or PHCM9795's existing assessment a professional brief and an audience beyond the teaching team, judged against practice-drawn criteria. | At least one core assessment requires a recognised professional genre or an audience beyond the teaching team. | low | term 1 | §3 Theme 1; §5 CI-1 |
| P3 | C2 | Add a criterion-referenced peer-review task to PHCM9794's study-appraisal work, marked against a stated quality rubric. | Core assessment includes criterion-referenced appraisal of quality. | low | term 1 | §3 Theme 2; §5 CI-2 |
| P4 | C1 | Add an assessed group task with individual-contribution criteria to PHCM9012 or PHCM9794. | At least one core unit assesses collaborative practice. | medium | term 2 | §3 Theme 4; §5 CI-3 |
| P5 | C4 | Add a second, contrasting case or dataset — a non-clinical setting — to an existing core assessment. | At least one core assessment requires application to novel or unfamiliar problems. | medium | term 2 | §3 Theme 4; §5 CI-3 |
| P6 | W2 | Turn PHCM9012's practitioner-role framing into an assessed end-to-end task producing a practitioner artefact, marked against practice-drawn criteria. | At least one core assessment reproduces a professional task end to end. | medium | term 2 | §5 CI-1 |
| P7 | C3 | Extend the C3 assessment to a public-health-specific governance question (bias in a health dataset, accountability for an AI-assisted screening recommendation), depending on the term-1 change landing first. | Core assessment requires critique or governance of AI systems in the discipline's own context. | medium | term 3, after the C3 term-1 action | §3 Theme 1 |
| P8 | C2 | Add a reflective component requiring students to document and justify a reliance decision on a tool, source or collaborator, depending on the term-1 criterion-referenced task landing first. | Assessment requires students to document and justify reliance decisions. | medium | term 3, after the C2 term-1 action | §3 Theme 2; §5 CI-2 |
| P9 | C1 | Extend the group task so the brief documents the division of labour between people and a named tool, assessed as a criterion, depending on the term-2 group task landing first. | Coordinating work across people AND tools/AI systems. | medium | term 3, after the C1 term-2 action | §3 Theme 2; §5 CI-2 |
| P10 | W1 | Repeat the professional-genre task in a further core course, with a practitioner or real health-district audience judging at least one instance, depending on the term-1 brief landing first. | Professional communication is assessed repeatedly and progressively across the program AND judged by a real external audience or practitioner. | high | term 3, after the W1 term-1 action | §5 CI-1 |
| P11 | W3 | Convert the existing internship from a merit-gated elective into a short required core placement with practitioner supervision, justified on skill and professional-identity grounds, not employment-rate grounds. | A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment. | high | term 4 — admission-load and host-capacity dependent | no report-specific signal; rubric anchor and [[29]](https://doi.org/10.1080/07294360.2016.1139551) [[28]](https://doi.org/10.1007/s10734-017-0216-z) [[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P12 | C4 | Open the WAM-gated Project/Independent Study/Minor Project route to the whole cohort as a required capstone, or add a knowledge-gap identification task short of that. | The program documents structured progression toward independent learning: a self-scoped capstone or research project. | high | term 4 — program-structure change | §3 Theme 4; §5 CI-3 |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | The PASS condition for an all-compulsory specialist core is met: 24 of 48 UOC are four named, compulsory public health courses covering the discipline's own method base — epidemiology, biostatistics, health promotion and health systems — and the remaining load runs through named disciplinary specialisations of 24 UOC each. This is specialist content with disciplinary identity, not generic or interchangeable material. | G1 already passes on the four compulsory public health core courses and the named disciplinary specialisations. None of the interventions above remove or dilute that specialist core; they add assessment tasks and criteria within the existing courses and credit points, so redesign should keep the four compulsory courses and the specialisation structure intact rather than trading disciplinary depth for the added tasks. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | FAIL | The PASS condition requires assessments that demand defended trade-off decisions, or simulations, capstones or live projects with real uncertainty and accountability. The extract documents no assessment task for any core course — each lists only a delivery mode with an N/A weighting and no hurdle — so no defended decision can be evidenced. The capstone-type routes that would carry uncertainty and accountability (Project, Internship) are optional elective substitutions requiring Program Director approval and a WAM gate, not core. What the core documents is appraisal, interpretation and planning stated as outcomes, which the FAIL side treats as scripted rather than defended decision-making. | G2 already fails because no core assessment documents a defended trade-off decision. W2's end-to-end authentic-task interventions and C1's people/tool coordination criterion are the ones most likely to also carry decision-under-uncertainty evidence, since they introduce judged, criteria-based decisions under a real or realistic constraint — but moving a C or W item's score does not itself close G2. Closing G2 needs its own assessed evidence of a defended trade-off decision, simulation, capstone or live project with real uncertainty and accountability; redesign should not assume the W2 or C1 changes above satisfy it as a side effect. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C1 | 1 | 2 | +1 adaptive | 6 / 15 | 3 / 9 |
| P2 | C1 | 2 | 3 | +1 adaptive | 7 / 15 | 3 / 9 |
| P3 | C2 | 1 | 2 | +1 adaptive | 8 / 15 | 3 / 9 |
| P4 | C2 | 2 | 3 | +1 adaptive | 9 / 15 | 3 / 9 |
| P5 | C3 | 1 | 2 | +1 adaptive | 10 / 15 | 3 / 9 |
| P6 | C3 | 2 | 3 | +1 adaptive | 11 / 15 | 3 / 9 |
| P7 | C4 | 1 | 2 | +1 adaptive | 12 / 15 | 3 / 9 |
| P8 | C4 | 2 | 3 | +1 adaptive | 13 / 15 | 3 / 9 |
| P9 | C5 | 1 | 2 | +1 adaptive | 14 / 15 | 3 / 9 |
| P10 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 3 / 9 |
| P11 | W1 | 1 | 2 | +1 workplace | 15 / 15 | 4 / 9 |
| P12 | W1 | 2 | 3 | +1 workplace | 15 / 15 | 5 / 9 |
| P13 | W2 | 1 | 2 | +1 workplace | 15 / 15 | 6 / 9 |
| P14 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 7 / 9 |
| P15 | W3 | 1 | 2 | +1 workplace | 15 / 15 | 8 / 9 |
| P16 | W3 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
