// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Geography (MC-GEOG) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Geography (MC-GEOG)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-29 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-geog.md
**Position basis:** Destination AI Exposure 91.75 (cognate basis) × Curriculum Adaptiveness 6/15 (v4.2 draft, sub-scale A) · Workplace practice 3/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a cognate basis (Bachelor of Arts (Geography)), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

Master of Geography carries the field's highest scored gap on C3 (0/3): no core unit addresses digital tools or AI, even at an elective or operational level. Five items sit at 1/3 — C1, C2, W1, W2 and W3 — reflecting collaboration, evaluative judgement, professional communication, authentic task design and work-situated learning that appear only in outcomes or graduate attributes, not in assessed core practice. C4 and C5 already reach 2/3 through the Research Project pathway's self-scoped, defended capstone, with headroom remaining mainly for students who complete the coursework-only Geography Practical route instead.

The program has no destination record of its own; market evidence in this plan rests on the field-of-education basis set out in §1 of the market report (Human Geography, field 090309). The largest destination families — Office Clerks, General and Business Operations Specialists, All Other — sit inside the clerical and administrative cluster the market report's skill-shift table (§4) and discussion themes (§3) mark as the most automation-exposed part of the labour market, the evidence base for the C3, C1 and C2 interventions in §2 and §4. G1 and G2 both pass, so every intervention in this plan preserves the disciplinary core and the staged, defended project structure those gates certify.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | Adaptive | 0 / 3 | 3 | No core unit's overview, outcomes or generic-skills list names digital tools or AI (item rationale); the program's largest destination family, Office Clerks, General, sits in the cluster §4's skill shift marks ↓↓ falling sharply for clerical and data entry, and Theme 4 (§3) names routine clerical and administrative roles as carrying the highest automation exposure nationally. | 1 |
| C1 Distributed cognition & relational capability | Adaptive | 1 / 3 | 2 | Theme 4 (§3) and the skill-shift table (§4) describe automation replacing routine, rules-based tasks rather than whole roles; CI-1 (§5) proposes grading the division of an administrative or clerical task between a student and an automation tool — a form of coordinated human-tool work C1 does not yet assess. | 2 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | Theme 2 (§3) finds routine, rules-based office tasks the most readily automated; evaluative judgement over when a rule-following approach or an automation tool should be trusted or overridden is the capability the field's own automation exposure argues for, and no core assessment currently requires it. | 3 |
| C4 Life-long learning & transfer | Adaptive | 2 / 3 | 1 | Theme 4 (§3) finds augmentation, not full automation, defines most of the field's near-term occupational change, favouring graduates who can keep redefining their own scope of practice; the Research Project pathway's self-scoped topic already reaches this bar, but Geography Practical draws its topic from a staff-supplied list, so the progression is uneven across pathways. | 7 |
| C5 Inquiry & evidence generation | Adaptive | 2 / 3 | 1 | The same augmentation-favouring finding in Theme 4 (§3) rewards graduates who can design and defend their own inquiry; a defended primary-evidence project is one route among several rather than a requirement, so the instrument's level 3 (required, defended) is not yet reached program-wide. | 8 |
| **Adaptive capabilities** | **Adaptive** | **6 / 15** | **9** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | CI-4 (§5) notes that office-clerk-track destinations handle personal and commercial information bound by the Privacy Act 1988 Australian Privacy Principles and the Fair Work Act's seven-year employee-record retention duty (Theme 1, §3); no core communication task currently addresses that governance obligation or reaches an audience beyond the teaching team. | 4 |
| W2 Authentic task design | Workplace | 1 / 3 | 2 | Theme 6 (§3) and CI-3 (§5) note that social-work-track destinations sit under AASW self-regulation with externally set professional-practice criteria; the program's assessed tasks remain academic in artefact and criteria rather than judged against those standards. | 5 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | The Social and Human Service Assistants family (§2 Signal 3, 18 live postings) and the Mental Health and Substance Abuse Social Workers family (§2 Signal 4) are destinations where placement-based practice is the profession's own entry route, yet the program's only work-situated unit, International Internship in Environment, is an elective, not a core requirement. | 6 |
| **Workplace practice** | **Workplace** | **3 / 9** | **6** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | 0 → 1 | "AI or digital tools appear only as electives or as tool operation/training — the operational level TEQSA identifies as non-durable." | Option: add an introductory module on AI-assisted and digital data-processing tools (for example, spatial or automation-adjacent tools relevant to geography) to an existing core unit, addressed against the automation-exposed clerical and administrative cluster the program's own graduates enter (§4 skill shift: administration falling, clerical falling sharply, data entry falling sharply; §3 Theme 4) (cost: staff time to source tool-specific training material). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Option: extend that module with an assessed discussion of AI capabilities and limitations, including the Privacy Act's automated decision-making transparency obligation that takes effect 10 December 2026 (§3 Theme 5) (cost: a new assessment criterion and additional marking time). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Option: add a core assessment item requiring students to critique AI system governance in a geography or community-service context, drawing on the Privacy Act's automated decision-making transparency obligation (§3 Theme 5; §5 CI-2) and AASW's Medicare and registration standards (§3 Theme 6; §5 CI-3) as case material (cost: a new assessment task and marking rubric). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Option: convert one individual assessment in Geography Practical or GEOG90029 into a graded group task with individually accountable roles, framed around the administrative or clerical task-division activity the market report itself proposes (§5 CI-1) (cost: redesign of an existing individual assessment and its marking rubric). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Option: extend the group task above so the division of labour explicitly spans people and an automation or AI tool, matching CI-1's own proposal (§5) that the division of an administrative or clerical task between a student and an automation tool is itself graded (cost: further redesign of the group task's marking rubric to add a tool-allocation criterion). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Option: add a peer-review or structured-critique component to one core assessment (for example, critiquing draft Rationale, Methods and Results reports in Geography Practical against a marking criteria sheet), motivated by Theme 2's finding that routine, rules-based tasks are the ones most exposed (§3) (cost: peer-review scaffolding and moderation time). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Option: require students to log and justify decisions to rely on or override an automation or AI tool during the Geography Practical or Research Project data-analysis stage, tied to Theme 4's finding that routine tasks carry the highest automation exposure (§3) (cost: a reflective-log component added to an existing assessment). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Option: replace or supplement one core written report (for example, the Rationale, Methods and Results report in Geography Practical) with a policy-brief or consultancy-advice genre addressed to a stated external audience, informed by CI-4's finding that office-clerk-track destinations handle governance-bound information under the Privacy Act and Fair Work Act (§3 Theme 1; §5 CI-4) (cost: rewriting the assessment brief and marking criteria). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Option: extend the policy-brief task across two core units and add a real external reviewer, such as a community-sector or government practitioner, to judge the final version, reflecting the governance and accountability expectations of the Social and Human Service Assistants and Business Operations Specialists destination families (§2 Signals 2 and 3) (cost: sourcing and briefing an external reviewer each teaching period). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Option: judge Geography Practical's staged reports against AASW-published professional-practice criteria for the social-work-track destinations (§3 Theme 6; §5 CI-3), replacing the current academic marking rubric with one drawn from external practice standards (cost: staff time to source and apply an external rubric). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Option: extend the AASW-criteria marking to the Research Project's proposal and results seminars as well, and add a genuine time constraint modelled on the automated decision-making transparency compliance date in Theme 5 (§3) — for example, a case requiring a transparency notice drafted against the 10 December 2026 date (cost: redesigning two further assessments' criteria and constraints). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Option: move International Internship in Environment (GEOG90022) from an elective to a core-adjacent, assessed placement option for at least one discipline stream, situating students with the Social and Human Service Assistants or Business Operations Specialists destination families the program already produces (§2 Signals 2 and 3) (cost: timetabling and host-organisation agreements to support a compulsory placement). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Option: extend the core placement above into a required sequence, such as a shorter placement followed by a capstone placement, with structured reflection assessed against professional-practice criteria. Per the market report's own caution, justify this by skill development and professional-identity formation, not by employment-rate claims, and weigh the equity cost for students unable to relocate or take unpaid placements (cost: two placement rotations' worth of host coordination and supervision, plus an equity cost to weigh). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Option: extend the Research Project's self-scoped-topic model to coursework-only students by adding a self-scoped topic option to Geography Practical, currently drawn from a staff-supplied list only, or add an assessed gap-analysis-and-plan component to Geography Practical instead, reflecting Theme 4's finding that augmentation rather than full automation defines most of the field's near-term occupations and rewards graduates who keep redefining their own scope (§3) (cost: staff time to supervise self-scoped topics at greater volume, or to design and mark a gap-analysis task). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Option: make a defended primary-evidence project (a thesis-style proposal and results seminar) a required stage for all students rather than one route among several, or add a staged, supervised methodology-defence step to Geography Practical itself, reflecting the same augmentation-favouring finding in Theme 4 (§3) that rewards graduates able to design and defend their own inquiry rather than follow a fixed procedure (cost: additional supervision load if extended to the full cohort, or added staff time to run a defence-style review within Geography Practical). | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| Automation exposure of the largest destination family's core skills | C3, C1 | administration falling, clerical falling sharply, data entry falling sharply, office administration falling, reception falling sharply (§4 skill shift); Theme 4's finding that routine clerical and administrative roles carry the highest automation exposure nationally (§3). | §2 Signal 1; §3 Theme 4; §4 | MEDIUM (Office Clerks, General — job-advertisement signals; §6) |
| Automated decision-making transparency obligation for charities and NGOs | C3, W2 | Privacy Act automated decision-making transparency obligation, effective 10 December 2026, requiring charities and NGOs to notify individuals affected by an automated eligibility or triage decision (§3 Theme 5). | §3 Theme 5; §5 CI-2 | HIGH (Social and Human Service Assistants — regulatory and statutory instruments; §6) |
| AASW self-regulation and the Medicare-billing restriction on mental-health practice | W2, C3 | Social workers are self-regulated through the Australian Association of Social Workers (AASW); only Accredited Mental Health Social Workers hold a Medicare provider number (§3 Theme 6). | §3 Theme 6; §5 CI-3 | HIGH (Social and Human Service Assistants — regulatory and statutory instruments; §6) |
| Privacy Act and Fair Work Act governance duties on office-clerk destinations | C3, W1 | Office clerks handle personal and commercial information bound by the Privacy Act 1988 Australian Privacy Principles and the Fair Work Act's seven-year employee-record retention duty (§3 Theme 1). | §3 Theme 1; §5 CI-4 | MEDIUM (Office Clerks, General — regulatory and statutory instruments; §6) |
| Modest but live demand in community-service and mental-health destination families | W3 | 18 live postings matching Social and Human Service Assistants roles (§2 Signal 3); Mental Health and Substance Abuse Social Workers returned 0 postings against the search term run for this report (§2 Signal 4), so this route's demand signal is read from Signal 3 alone. | §2 Signal 3; §2 Signal 4 | HIGH (Social and Human Service Assistants — job-advertisement signals; §6) |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C3 | Add an introductory module on AI-assisted and digital data-processing tools to an existing core unit. | C3 level 1 (AI or digital tools appear only as electives or as tool operation/training). | low | Term 1; module addition | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P2 | C2 | Add a peer-review or structured-critique component, marked against criteria, to an existing core assessment in Geography Practical. | C2 level 2 (criterion-referenced appraisal of quality). | low | Term 1; rubric addition | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P3 | C3 | Extend the new module with an assessed discussion of AI capabilities, limitations and the Privacy Act's automated decision-making transparency obligation. | C3 level 2 (capabilities and limitations discussed and assessed). | low-medium | Term 1; same module, new assessment criterion | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P4 | C1 | Convert one individual assessment in Geography Practical or GEOG90029 into a graded group task with individually accountable roles. | C1 level 2 (at least one core unit assesses collaborative practice). | medium | Term 1-2; assessment redesign | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P5 | W1 | Replace or supplement one core written report with a policy-brief or consultancy-advice genre addressed to a stated external audience. | W1 level 2 (a recognised professional genre or an audience beyond the teaching team). | medium | Term 2; assessment brief rewrite | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P6 | W2 | Judge Geography Practical's staged reports against AASW-published professional-practice criteria in place of the current academic marking rubric. | W2 level 2 (a core assessment reproduces a professional task end to end, judged against criteria drawn from practice). | medium | Term 2; external-rubric adoption | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P7 | C3 | Add a core assessment item requiring students to critique AI system governance in a geography or community-service context. | C3 level 3 (critique or governance of AI systems in the discipline's own context). | medium | Term 2; new assessment task | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P8 | C2 | Require students to log and justify decisions to rely on or override an automation or AI tool during the Geography Practical or Research Project data-analysis stage. | C2 level 3 (document and justify reliance decisions). | medium | Term 2; reflective-log component | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P9 | C1 | Extend the graded group task so the division of labour explicitly spans people and an automation or AI tool. | C1 level 3 (coordinating work across people and tools/AI systems is itself assessed). | medium | Term 2; marking-rubric extension | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P10 | C4 | Add a self-scoped topic option, or an assessed gap-analysis-and-plan component, to Geography Practical for coursework-only students. | C4 level 3 (structured progression toward independent learning: a self-scoped project, or an assessed gap analysis with a plan to close it). | medium | Next course review; capstone-structure update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P11 | W1 | Extend the policy-brief task across two core units and add a real external reviewer to judge the final version. | W1 level 3 (assessed repeatedly and progressively, judged by a real external audience or practitioner). | medium-high | Term 3; external-reviewer coordination | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P12 | W2 | Extend AASW-criteria marking to the Research Project's proposal and results seminars, and add a genuine time constraint modelled on the automated decision-making transparency compliance date. | W2 level 3 (the profession's own standards of performance form the program's assessment spine, with a genuine constraint of practice). | medium-high | Term 3; two further assessment redesigns | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P13 | C5 | Make a defended primary-evidence project a required stage for all students, or add a staged, supervised methodology-defence step to Geography Practical. | C5 level 3 (a substantial primary-evidence project is required, with methodology defended under scrutiny). | medium-high | Next course review; capstone-staging update | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P14 | W3 | Move International Internship in Environment from an elective to a core-adjacent, assessed placement option for at least one discipline stream. | W3 level 2 (a core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment). | high | Next course review; host-organisation agreements | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P15 | W3 | Extend the core placement into a required sequence with structured reflection assessed against professional-practice criteria, justified by skill development and professional-identity formation rather than employment rates, and weighed against its equity cost. | W3 level 3 (substantial required work-situated learning, supervised, assessed, with structured reflection on professional practice). | high | Next course review, following W3 level 2; host-coordination and equity review | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | The program documents a compulsory two-subject Discipline Core (GEOG90018, GEOG90029) plus, depending on pathway, Geography Practical or a Research Project, with substantial Discipline Electives (100-137.5 pt) drawn from one of three named geography streams — a coherent, discipline-specific specialist structure, not generic or interchangeable content. | Redesign must keep the two-subject Discipline Core (GEOG90018, GEOG90029) and the pathway-dependent capstone (Geography Practical or the Research Project) intact; new AI, collaboration, evaluative-judgement and governance content should be layered onto these existing core units and the Discipline Elective streams, not substituted for them, so the coherent specialist core the gate certifies is preserved. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | The Research Project pathway requires a defended proposal (grant-application-style, with a proposal seminar) and a results seminar, each independently marked, and Geography Practical requires staged Rationale/Methods/Results reports on an independently chosen topic with real, undetermined outcomes — both represent live projects with real uncertainty and accountability to a supervisor, matching the PASS condition rather than recall or scripted responses. | Any redesign of Geography Practical or the Research Project — adding AASW criteria, tool-allocation grading, or a required primary-evidence stage — must keep the staged, independently chosen topic and the defended-proposal, results-seminar accountability that carries this gate; collapsing the topic choice into a fully prescribed exercise, or removing the defended or staged review, would put the gate at risk. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C3 | 0 | 1 | +1 adaptive | 7 / 15 | 3 / 9 |
| P2 | C3 | 1 | 2 | +1 adaptive | 8 / 15 | 3 / 9 |
| P3 | C3 | 2 | 3 | +1 adaptive | 9 / 15 | 3 / 9 |
| P4 | C1 | 1 | 2 | +1 adaptive | 10 / 15 | 3 / 9 |
| P5 | C1 | 2 | 3 | +1 adaptive | 11 / 15 | 3 / 9 |
| P6 | C2 | 1 | 2 | +1 adaptive | 12 / 15 | 3 / 9 |
| P7 | C2 | 2 | 3 | +1 adaptive | 13 / 15 | 3 / 9 |
| P8 | W1 | 1 | 2 | +1 workplace | 13 / 15 | 4 / 9 |
| P9 | W1 | 2 | 3 | +1 workplace | 13 / 15 | 5 / 9 |
| P10 | W2 | 1 | 2 | +1 workplace | 13 / 15 | 6 / 9 |
| P11 | W2 | 2 | 3 | +1 workplace | 13 / 15 | 7 / 9 |
| P12 | W3 | 1 | 2 | +1 workplace | 13 / 15 | 8 / 9 |
| P13 | W3 | 2 | 3 | +1 workplace | 13 / 15 | 9 / 9 |
| P14 | C4 | 2 | 3 | +1 adaptive | 14 / 15 | 9 / 9 |
| P15 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
