// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Business Administration (ADELAIDE-MBUSA_MBUSAD) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Business Administration (ADELAIDE-MBUSA_MBUSAD)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-09-07 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-adelaide-mbusa_mbusad.md
**Position basis:** Destination AI Exposure 88.71 (field basis) × Curriculum Adaptiveness 6/15 (v4.2 draft, sub-scale A) · Workplace practice 3/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a field basis (Jobs and Skills Australia Higher Education Outcomes (JSA HEO) field 0803 Business and Management), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

This Master of Business Administration passes both gates: a compulsory nine-course specialist core (G1) and multiple assessments requiring defended trade-off decisions under real uncertainty (G2). Its curriculum adaptiveness sits at 6 of 15 and its workplace practice at 3 of 9, with every item held back by the same pattern — outcomes state a capability that no core assessment task actually exercises.

The occupational families reachable from this field (market report §1) split into a highly exposed clerical-and-retail cluster and a more durable consulting, audit and marketing-analytics cluster; the second cluster is where a regulator-driven skills shortage (ASRS sustainability assurance) and a documented verification duty (APESB algorithmic-output review) already name capabilities that this program's existing core units — Tech eChallenge, Business Research Methods, Strategic Management — are best placed to carry.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C1 Distributed cognition & relational capability | Adaptive | 1 / 3 | 2 | Sales Manager job ads recur on team leadership and coaching (§2 Signal 5); Management Analyst ads recur on stakeholder management (§2 Signal 7) — both name collaborative capability the current core does not assess. | 2 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | APESB professional standards require auditors to verify automated ledger anomaly-detection output and keep a documented audit trail of that verification (§3 Theme 1) — a criterion-referenced appraisal duty the current core does not assess. | 3 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | The same APESB provision (§3 Theme 1) and the Privacy Act/APP handling duty bound to office-based roles in this field (§3 Theme 3) both require graduates to reason about an AI or data system's limits, not just operate it. | 4 |
| C5 Inquiry & evidence generation | Adaptive | 1 / 3 | 2 | Mandatory Australian Sustainability Reporting Standards have created a named, dated shortage of accountants able to assure multi-capital and climate-risk disclosures (§3 Theme 2) — a live-data assurance skill this program's methods unit does not yet require students to execute. | 5 |
| C4 Life-long learning & transfer | Adaptive | 2 / 3 | 1 | The ASRS-driven assurance shortage (§3 Theme 2) rewards graduates who can carry an existing method into a new, regulator-created context — the transfer this item anchors at level 3. | 7 |
| **Adaptive capabilities** | **Adaptive** | **6 / 15** | **9** | — | — |
| W3 Work-situated learning | Workplace | 0 / 3 | 3 | Management Consultant recurs as an early- and senior-stage field destination (JSA HEO graduate-destinations table); Management Analyst job ads recur on stakeholder and change-management skills (§2 Signal 7) that a client-facing placement would build directly. | 1 |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | The Privacy Act's Australian Privacy Principles bind the entities this field's graduates enter, with no delegation to a specialist occupation (§3 Theme 3), making disclosure-handling conduct a live professional-communication requirement rather than a lecture topic. | 6 |
| W2 Authentic task design | Workplace | 2 / 3 | 1 | About a fifth of this field's entry destinations are clerical, administrative and retail roles that Jobs and Skills Australia names as its most automatable group (§3 Theme 4; §1 job family map); a professional-grade artefact assessed early is how a transcript is distinguished from that pool. | 8 |
| **Workplace practice** | **Workplace** | **3 / 9** | **6** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| W3 Work-situated learning | 0 → 1 | "Work-situated learning exists only as an elective, an optional internship, or an unassessed extracurricular or careers activity." | Add a documented elective consulting or internship placement option — for example a client-facing engagement aligned to the Management Analyst pathway that recurs in this field's destinations (§2 Signal 7) — and record it as an assessed elective rather than an unassessed careers activity. Cost: one new elective listing plus a placement-assessment rubric; no change to the compulsory core. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Extend Tech eChallenge's existing practitioner-mentor structure into a short, assessed live-client engagement — a real organisation's problem, supervised by the practitioner mentors already in the course — rather than a simulated prototype only, addressing the stakeholder- and change-management skills recurring in Management Analyst job ads (§2 Signal 7). Cost: renegotiating Tech eChallenge's brief with a partner organisation; no new credit points. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Sequence the live-client engagement above across two core terms with a second, later engagement and a structured reflection component, so accountability to the host and professional-practice reflection are assessed twice rather than once. This is an option, not a directive: Jackson and Collings found WIL does not raise employment rates [[28]](https://doi.org/10.1007/s10734-017-0216-z), so the warrant is skill development and professional identity [[29]](https://doi.org/10.1080/07294360.2016.1139551), and any placement design should account for the equity cost of unpaid or relocation-dependent placements [[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report). Cost: a second assessed engagement slot and a reflective-journal rubric. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Convert People and Organisations' stated collaborative outcome into an assessed group task with individually marked contribution logs, addressing the team-leadership-and-coaching skill recurring in Sales Manager job ads (§2 Signal 5). Cost: a new group-assessment rubric inside an existing core unit; no new credit points. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Add a documentation requirement to Tech eChallenge's team assessment: teams record how work was divided between members and any analytics or AI tool used in building the prototype, matching the stakeholder-and-tool coordination skills recurring in Management Analyst ads (§2 Signal 7). Cost: one documentation criterion added to an existing assessed task. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Add a structured peer-review stage, marked against a stated rubric, to Business Research Methods' existing Proposal task — the professional duty to appraise output against criteria that APESB now requires of auditors reviewing automated analysis (§3 Theme 1). Cost: a peer-review rubric and a marked review submission; no new credit points. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Require the Business Research Methods Proposal to include a short reliance log where students state which findings came from an AI or analytics tool and justify accepting or overriding it, mirroring the documented audit-trail duty APESB now places on auditors reviewing automated output (§3 Theme 1). Cost: one additional assessed component on an existing task. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Extend Business and Corporations Law's existing 'utilise modern technology effectively' outcome into an assessed component covering AI tool limitations and the Privacy Act obligations that bind this field's graduate employers (§3 Theme 3), rather than tool operation alone. Cost: a new assessed component inside an existing core unit. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Assess a governance task in which students critique an AI-assisted business decision against the audit-trail and verification duties APESB now imposes on automated ledger anomaly detection (§3 Theme 1) — accountability and transparency in the discipline's own regulatory terms, not general AI ethics. Cost: a new assessed task, potentially replacing an existing case-study component. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 1 → 2 | "Students design and conduct an inquiry with methodology selection and data collection, assessed." | Move Business Research Methods' Proposal from a plan-only deliverable to a shortened executed study in which students collect and analyse real, even small-sample, data on a business problem, informed by the live sustainability-disclosure assurance shortage the market names (§3 Theme 2). Cost: extending the unit's existing Proposal task with a data-collection stage; no new credit points. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make Strategic Management's stated capstone research-based strategic report the program's required, not optional, research route, with a staged supervisor review of the methodology, addressing the same ASRS-driven assurance shortage (§3 Theme 2) that rewards graduates able to defend a primary-evidence methodology. Cost: assessment criteria and a supervised-review slot for a currently undocumented capstone. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Formalise Tech eChallenge's existing judge-panel presentation as a graded professional-genre pitch judged against practice-drawn criteria, and add the disclosure-handling duty the Privacy Act places on this field's employers (§3 Theme 3) as an explicit marking criterion. Cost: a criteria rubric for an existing assessed task. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Add a second, later professional-genre assessment — for example a client-facing report in Marketing Management judged against documented criteria — so professional communication is assessed twice with progression, and add a professional-conduct or disclosure-handling criterion consistent with the Privacy Act obligation named in the market report (§3 Theme 3). Cost: a new assessed task and criteria sheet in a second core unit. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Give Strategic Management's stated capstone strategic-report outcome an actual assessment brief and criteria, framed as a self-scoped project addressing the ASRS-driven assurance skills shortage (§3 Theme 2) — turning a documented outcome with no assessment task into the progression-toward-independence evidence this level requires. Cost: an assessment brief and marking criteria for an outcome that currently has none. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Add a genuine resource or time constraint — a fixed client budget, as already specified in the Business Research Methods Proposal, plus a fixed turnaround — to a second core task, for example Tech eChallenge's prototype brief, so at least two core assessments in the spine carry a real constraint of practice. This helps distinguish graduates from the automatable clerical-and-retail share of this field's destinations (§3 Theme 4; §1). Cost: a constraint clause added to an existing task brief. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| CI-1 — auditor duty to verify and log automated anomaly-detection output (APESB APES 110) | C2, C3 | APESB professional standards require auditors to verify automated ledger anomaly-detection algorithms and maintain documented audit trail logs for AI-generated financial estimates. | Market report §3 Theme 1; §5 CI-1 | HIGH (Accountants and Auditors — regulatory and statutory instruments: HIGH; scholarly and grey-literature studies: HIGH) |
| CI-2 — ASRS-driven shortage of sustainability-assurance accountants | C4, C5 | Mandatory Australian Sustainability Reporting Standards create an acute shortage of accounting graduates skilled in multi-capital greenhouse gas assurance and climate risk governance. | Market report §3 Theme 2; §5 CI-2 | HIGH (Accountants and Auditors — scholarly and grey-literature studies: HIGH) |
| CI-3 — automatable clerical and retail share of field-wide entry destinations | C1, W2, W3 | About a fifth of this field's entry destinations are clerical, administrative and retail roles, and JSA names exactly those as its highest-automatability group. | Market report §1 job family map; §3 Theme 4; §5 CI-3 | LOW (Destination basis: LOW — field-of-education grain, not this program's own graduates) |
| CI-4 — Privacy Act APP handling duty bound to graduate employers | W1, C3 | The Privacy Act's Australian Privacy Principles bind the entities office-based graduates enter, with no delegation to a specialist occupation. | Market report §3 Theme 3; §5 CI-4 | MEDIUM (Office Clerks, General — regulatory and statutory instruments: MEDIUM) |
| Signal 5 — Sales Manager team leadership and coaching, CRM/pipeline management rising | C1 | 9,850 postings matching 'sales manager'; recurring keywords include team leadership and coaching and CRM and pipeline management. | Market report §2 Signal 5 | HIGH (Sales Managers — job-advertisement signals: HIGH) |
| Signal 7 — Management Analyst stakeholder and change management | W3, C1 | 169 postings matching the management consultant vacancy listing; recurring keywords include stakeholder management, change management and project management. | Market report §2 Signal 7 | MEDIUM (Management Analysts — job-advertisement signals: MEDIUM) |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C2 | Add a structured, criterion-referenced peer-review stage to the Business Research Methods Proposal. | Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars. | low | Term 1 (documentation only) | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P2 | C3 | Extend Business and Corporations Law's technology outcome into an assessed component on AI capabilities and limitations, including the Privacy Act obligation. | Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed. | low | Term 1 (documentation only) | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P3 | W1 | Add practice-drawn criteria and a disclosure-handling criterion to Tech eChallenge's existing judge-panel pitch. | At least one core assessment requires a recognised professional genre or an audience beyond the teaching team ... judged against criteria drawn from professional practice. | low | Term 1 (documentation only) | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P4 | C1 | Convert People and Organisations' collaborative outcome into an assessed group task with individually marked contribution logs. | At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity. | low | Term 1 (documentation only) | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P5 | W3 | Add a documented, assessed elective consulting or internship placement option. | Work-situated learning exists only as an elective, an optional internship, or an unassessed extracurricular or careers activity. | low | Term 1 (documentation only) | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P6 | C2 | Require a reliance log in the Business Research Methods Proposal, documenting and justifying any reliance on an AI or analytics tool. | Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality. | medium | Term 2 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P7 | C5 | Extend the Business Research Methods Proposal into a shortened executed study with real data collection and analysis. | Students design and conduct an inquiry with methodology selection and data collection, assessed. | medium | Term 2 | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P8 | C4 | Write an assessment brief and criteria for Strategic Management's stated capstone strategic-report outcome, which currently has none. | The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them. | medium | Term 2 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P9 | C3 | Add a governance task critiquing an AI-assisted business decision against the audit-trail and verification duties named in the market report. | Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation. | medium | Term 2 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P10 | W2 | Add a genuine budget-and-turnaround constraint to a second core task, for example Tech eChallenge's prototype brief. | Such tasks are the program's assessment spine rather than a single instance ... AND at least one carries a genuine constraint of practice. | medium | Term 2 | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P11 | C1 | Add a role-and-tool documentation requirement to Tech eChallenge's team assessment. | Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems. | medium | Term 2 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P12 | W1 | Add a second, later professional-genre assessment in Marketing Management with a professional-conduct criterion. | Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner ... with professional conduct or accountability explicitly among the assessed criteria. | medium | Term 3 | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P13 | W3 | Extend Tech eChallenge into a short, assessed live-client engagement supervised by the existing practitioner mentors. | A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment ... but it is short or stands alone. | high | Term 3 | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P14 | C5 | Make Strategic Management's capstone research-based strategic report the program's required research route, with a staged supervisor review of methodology. | A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review). | high | Term 3-4 | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P15 | W3 | Sequence the live-client engagement across two core terms with a second, later engagement and structured reflection, with documented host accountability. | Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice. | high | Term 4 | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | The PASS condition of an all-compulsory specialist core is met: 27 of the 36 units are core and every one of the nine named courses must be completed, spanning accounting, finance, economics, law, marketing, organisational behaviour, strategy, project leadership and research methods, with a further 3 required research units. That is a fixed disciplinary core with management identity rather than generic or interchangeable content, and Strategic Management is documented as building on the research content of other MBA courses, which evidences sequencing rather than a flat menu. | Any redesign must keep the nine named core courses compulsory and specialist; converting a core course into an elective, or diluting Strategic Management's stated sequencing role, would put this documented PASS at risk. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | The PASS condition is met by assessments requiring defended trade-off decisions rather than recall or scripted responses. The Business Research Methods Proposal (40%%) requires a study design traded off against budgetary constraints, Tech eChallenge is an open-ended innovation project judged by a panel where the market need is not given in advance, and the program-level outcome requires diagnosing adaptive challenges and generating a range of solutions. Multiple-choice components exist in Project Leadership and Communication but account for 30%% of that course only, so the FAIL condition of recall-only assessment does not hold. | Any redesign must preserve the Business Research Methods Proposal's budget trade-off and Tech eChallenge's open-ended, judged brief; increasing the multiple-choice share of Project Leadership and Communication beyond its current 30% would move that unit toward the FAIL condition (recall-only assessment) and put this PASS at risk. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | W3 | 0 | 1 | +1 workplace | 6 / 15 | 4 / 9 |
| P2 | W3 | 1 | 2 | +1 workplace | 6 / 15 | 5 / 9 |
| P3 | W3 | 2 | 3 | +1 workplace | 6 / 15 | 6 / 9 |
| P4 | C1 | 1 | 2 | +1 adaptive | 7 / 15 | 6 / 9 |
| P5 | C1 | 2 | 3 | +1 adaptive | 8 / 15 | 6 / 9 |
| P6 | C2 | 1 | 2 | +1 adaptive | 9 / 15 | 6 / 9 |
| P7 | C2 | 2 | 3 | +1 adaptive | 10 / 15 | 6 / 9 |
| P8 | C3 | 1 | 2 | +1 adaptive | 11 / 15 | 6 / 9 |
| P9 | C3 | 2 | 3 | +1 adaptive | 12 / 15 | 6 / 9 |
| P10 | C5 | 1 | 2 | +1 adaptive | 13 / 15 | 6 / 9 |
| P11 | C5 | 2 | 3 | +1 adaptive | 14 / 15 | 6 / 9 |
| P12 | W1 | 1 | 2 | +1 workplace | 14 / 15 | 7 / 9 |
| P13 | W1 | 2 | 3 | +1 workplace | 14 / 15 | 8 / 9 |
| P14 | C4 | 2 | 3 | +1 adaptive | 15 / 15 | 8 / 9 |
| P15 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
