// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Arts and Cultural Management (175AA) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Arts and Cultural Management (175AA)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-22 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-175aa.md
**Position basis:** Destination AI Exposure 85.86 (exact basis) × Curriculum Adaptiveness 8/15 (v4.2 draft, sub-scale A) · Workplace practice 6/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

The Master of Arts and Cultural Management provides a comprehensive professional qualification in arts leadership, cultural policy, and creative enterprise operations. G1 passes on a staged progression across 62.5 credit points of compulsory subjects (principles, policy, operations, cultural economics, and applied research methods) culminating in a required capstone stream. G2 passes on defended trade-offs and live project management under incomplete information across capstone streams (ARTS90024, MULT90064, AMGT90027/28) and authentic grant proposals (AMGT90013).

However, operating under moderate exposure (85.86), the degree exhibits clear headroom across both sub-scales: **8 / 15 on Adaptiveness** and **6 / 9 on Workplace**. The primary deficit is C3 (0/3), where the core contains zero digital or AI literacy content despite profound automation of arts ticketing algorithms (Tessitura/Spektrix), dynamic pricing, and AI-assisted audience analytics. On adaptiveness, C1 (2/3), C2 (2/3), C4 (2/3), and C5 (2/3) are bounded by the absence of explicit human-and-AI collaboration agreements, AI reliance/override logs, and compulsory oral viva defences. On workplace practice, W1 (2/3), W2 (2/3), and W3 (2/3) reflect that authentic tasks and the 150-hour industry placement (ARTS90024) are elective options rather than a uniform assessment spine across the whole cohort.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | Adaptive | 0 / 3 | 3 | Direct — Market §2 Signal 2 and §3 Theme 2 document widespread adoption of AI in ticketing CRM (Tessitura), audience segmentation, and promotional copy generation, creating acute risks regarding artist copyright and patron data privacy. Core contains 0 digital/AI content. | 1 |
| C1 Distributed cognition & relational capability | Adaptive | 2 / 3 | 1 | Direct — Arts managers coordinate across artistic directors, venue technicians, union delegates, and CRM platforms; core assesses group projects with individual grading (AMGT90001), but lacks human-and-AI collaboration protocols. | 2 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 2 / 3 | 1 | Direct — Market §3 Theme 2 highlights the need to audit AI-generated arts marketing content against copyright standards and artistic integrity. Core includes peer review (MULT90064) but lacks AI reliance/override logs. | 3 |
| C4 Life-long learning & transfer | Adaptive | 2 / 3 | 1 | Direct — Core applies operational management to diverse organisational case studies (AMGT90001, AMGT90029), but self-scoped research capstones remain an elective stream. | 4 |
| C5 Inquiry & evidence generation | Adaptive | 2 / 3 | 1 | Direct — Compulsory research methods (AMGT90029) assesses research design (3000w proposal), but primary data collection is elective (thesis route) and lacks an oral viva defence under scrutiny. | 5 |
| W1 Professional communication & conduct | Workplace | 2 / 3 | 1 | Direct — Core assesses professional management presentations and grant proposals (AMGT90013), but all tasks are marked internally by academic staff without external Creative Australia or festival executive panels. | 6 |
| W2 Authentic task design | Workplace | 2 / 3 | 1 | Direct — Core reproduces authentic grant management and operational budgets, but live venue and budget constraints bind only elective capstone streams. | 7 |
| W3 Work-situated learning | Workplace | 2 / 3 | 1 | Direct — Performing arts companies (MTC, Arts Centre, RISING) prioritize candidates with hands-on venue experience; ARTS90024 provides 150h placement but is one of three capstone options. | 8 |
| **Adaptive capabilities** | **Adaptive** | **8 / 15** | **7** | — | — |
| **Workplace practice** | **Workplace** | **6 / 9** | **3** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | 0 → 1 | "AI or digital tools appear only as electives or as tool operation/training — the operational level TEQSA identifies as non-durable." | Introduce arts CRM and ticketing software training (e.g. Tessitura, Spektrix) in AMGT90013. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Add an assessed module in AMGT90013 or AMGT90001 covering AI audience analytics, predictive ticket pricing, and artist copyright ethics. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Introduce an assessed cultural data governance problem in AMGT90004: students audit algorithmic dynamic pricing equity, patron privacy, and generative AI copyright frameworks. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | In MULT90064 (Arts Management Project), require student creative enterprise teams to document and defend an explicit human-and-AI collaboration protocol allocating roles across team members and marketing/ticketing tech tools. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Attach an assessed reliance and override log to AMGT90013 / MULT90064: students document and defend where AI grant drafting or financial forecasts were overridden on artistic or statutory grounds. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | In all capstone options, institute an assessed professional development portfolio requiring students to identify their arts management gaps and articulate a long-term learning plan. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Require an oral methodology defence before an academic and arts industry panel for all capstone project and thesis outputs. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | In AMGT90013 / MULT90064, invite external festival directors and Creative Australia officers to evaluate grant pitches with assessed professional conduct and cultural safety criteria. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Embed authentic live venue budgets and industrial award compliance (Live Performance Award) across AMGT90013 and the capstone to ensure practice constraints bind all students. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Ensure all students complete an extended 150+ hour placement or live industry project sequence with senior practitioner supervision and host-evaluated deliverables. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| P1 | C3 | Performing arts and festival organisations adopt AI ticketing CRM (Tessitura/Spektrix); managers require training in algorithm governance and artist copyright protection. | §2 Signal 2; §3 Theme 2 | HIGH (ticketing tech & NAVA standards) |
| P2 | C1 | Arts management operates through interdisciplinary teams coordinating artists, technical crew, union reps, and digital marketing tools. | §1 Job Families 1 & 2; §4 rising skills | HIGH (LPA operations standards) |
| P3 | C2 | Proliferation of generative AI in arts copywriting requires managers to exercise evaluative judgement to audit authenticity and intellectual property rights. | §3 Theme 2; §4 rising skills | HIGH (cultural policy discourse) |
| P4 | W1 | Arts leaders must present defended grant applications and commercial sponsorship pitches to funding bodies (Creative Australia) and corporate boards. | §1 Job Families 3 & 4; §4 rising skills | HIGH (arts philanthropy practice) |
| P5 | W2 | Live performance sector demands operational budgets developed under authentic industrial award constraints and venue safety rules. | §2 Signal 3; §3 Theme 3 | HIGH (LPA industrial benchmarks) |
| P6 | W3 | Performing arts companies (MTC, Arts Centre, RISING) prioritize graduates with direct, supervised venue placement experience. | §1 Job Families 1 & 2; §2 Signal 1 | HIGH (cultural sector recruitment) |
| P7 | C5 | Cultural research requires defended methodologies in audience impact evaluation and social return on investment (SROI). | §1 Job Family 4; §2 Signal 1 | HIGH (funding evaluation guidelines) |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C3 | Introduce arts CRM and ticketing software training in AMGT90013 | C3 level 1 (digital tool operation) | Low | Term 1; syllabus update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P2 | C3 | Add an assessed module on generative AI in arts marketing and copyright in AMGT90013 | C3 level 2 (capabilities and limitations discussed/assessed) | Low–Medium | Term 1; curriculum update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P3 | C3 | Introduce an assessed cultural data governance problem in AMGT90004 | C3 level 3 (governance of AI/data in disciplinary context) | Medium | Term 2; subject update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P4 | C2 | Attach an assessed AI reliance and override log to AMGT90013 / MULT90064 | C2 level 3 (reliance/override justification) | Medium | Term 2; assessment brief update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P5 | W1 | Invite external festival directors and Creative Australia officers to judge AMGT90013 pitches | W1 level 3 (external practitioner judge and conduct criteria) | Medium | Term 2; practitioner coordination | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P6 | C1 | Require an assessed human-and-AI collaboration protocol in MULT90064 | C1 level 3 (people and tools collaboration assessed) | Medium | Term 2; capstone update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P7 | W3 | Make extended placement (ARTS90024) or live industry project sequence mandatory across all pathways | W3 level 3 (extended placement sequence with host evaluation) | Medium–High | Next course review; capstone structure update | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P8 | C5 | Require an oral methodology defence before an academic and arts industry panel for capstone outputs | C5 level 3 (defence under scrutiny) | Medium–High | Next course review; capstone staging update | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | The program documents a coherent specialist core with progressive depth: 62.5 credit points of compulsory subjects (AMGT90001 Principles of Arts Management, AMGT90004 Cultural Policy, AMGT90013 Arts Operations, AMGT90018 The Economics of Culture, AMGT90029 Applied Research Methods) plus a required capstone stream (25-37.5 points). The compulsory subjects build from foundational management through operations, economics, policy and research methods, culminating in a capstone. This is a coherent specialist core with progressive depth. | Redesign must preserve the core arts management, economics of culture, and cultural policy sequence. Introducing AI ticketing analytics and digital governance must strengthen arts leadership without displacing cultural policy foundations. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | G2 requires assessments with defended trade-off decisions, or simulations/capstones/live projects with real uncertainty and accountability. The capstone streams involve real uncertainty: ARTS90024 (placement in a professional environment), MULT90064 (entrepreneurial project with 'unstructured and incomplete information'), and AMGT90027/90028 (thesis with methodology defended). AMGT90001 assessment includes 'a test' requiring analysis of 'issues specific to the arts industry' with 'class discussion'. The research proposal (AMGT90029, 50%) requires designing a research project with methodology selection — a defended trade-off decision. | Assessment tasks must preserve live entrepreneurial project execution, unscripted industry negotiations, and defended decisions under creative and financial uncertainty. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C3 | 0 | 1 | +1 adaptive | 9 / 15 | 6 / 9 |
| P2 | C3 | 1 | 2 | +1 adaptive | 10 / 15 | 6 / 9 |
| P3 | C3 | 2 | 3 | +1 adaptive | 11 / 15 | 6 / 9 |
| P4 | C2 | 2 | 3 | +1 adaptive | 12 / 15 | 6 / 9 |
| P5 | W1 | 2 | 3 | +1 workplace | 12 / 15 | 7 / 9 |
| P6 | C1 | 2 | 3 | +1 adaptive | 13 / 15 | 7 / 9 |
| P7 | W3 | 2 | 3 | +1 workplace | 13 / 15 | 8 / 9 |
| P8 | C5 | 2 | 3 | +1 adaptive | 14 / 15 | 8 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
