// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Landscape Architecture/Master of Urban Design (MC-LARCHUD) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Landscape Architecture/Master of Urban Design (MC-LARCHUD)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-30 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-larchud.md
**Position basis:** Destination AI Exposure 92.85 (partial basis) × Curriculum Adaptiveness 6/15 (v4.2 draft, sub-scale A) · Workplace practice 3/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a partial basis (Master of Urban Planning), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

Master of Landscape Architecture/Master of Urban Design scores 6/15 on the adaptive sub-scale and 3/9 on the workplace-practice sub-scale, and both gates — G1 Disciplinary foundation and G2 Decision-making under uncertainty — pass on verification review. Every item bar C1 is scored from the captured Year 1 core subjects (ABPL90107, HORT90033, ABPL90271, ABPL90176, ABPL90283); the Year 4 core theses, ABPL90375 (Landscape Architecture Design Thesis) and ABPL90376 (Urban Design Thesis), were not captured in the extract and plausibly carry disciplinary depth, inquiry training or a self-scoped capstone that would raise several of these scores once confirmed.

The two committed job families in the market report — Landscape Architects and Urban and Regional Planners — bear most directly on C2, C3, C4 and W1. W2 rests on the range of named employers rather than a specific task description, and C5 and W3 carry no direct market signal, so those items are planned on the instrument's own anchor terms alone, flagged below for a follow-up market pass once a stronger research-methods or placement signal is available.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | Theme 2 and Theme 4 (§3) both find augmentation dominant for professional roles in the Landscape Architects and Urban and Regional Planners job families; graduates need evaluative judgement over AI-assisted design and planning outputs, which the core does not yet assess against criteria. | 1 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | Theme 2 (§3) places Landscape Architects in the high-augmentation band, and Theme 3 (§3) records the Planning Institute of Australia formalising AI-governance guidance for planners; both point to a gap in how AI-tool capability, limitation and governance content is addressed in the core, which currently documents AI content only as an elective. | 2 |
| C4 Life-long learning & transfer | Adaptive | 1 / 3 | 2 | Theme 3 (§3) records the Planning Institute of Australia's guidance evolving from the 2021 PlanTech principles through the 2022 Strategy to the 2026 national AI-infrastructure standards and a Data Centres Guidance Note; graduates need transfer and independent-learning capability to keep pace with guidance that keeps changing, which the core does not yet document a structured route toward. | 3 |
| C5 Inquiry & evidence generation | Adaptive | 1 / 3 | 2 | None reported — no theme or signal in the market report speaks to research-methods training or primary-evidence generation for either committed job family; this item is planned on the instrument's own anchor terms alone. | 4 |
| C1 Distributed cognition & relational capability | Adaptive | 2 / 3 | 1 | Indirect — Theme 2 (§3) finds professional Skill Level 1-2 roles, including Landscape Architects, carry the highest augmentation exposure and the lowest automation risk; §4 reads design, urban, client, construction and environmental as Stable on that same finding, so coordinating work between people and AI-assisted design tools, not replacing people with tools, is the market-supported direction for this item. | 8 |
| **Adaptive capabilities** | **Adaptive** | **6 / 15** | **9** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Theme 1 (§3) names the Australian Institute of Landscape Architects' 'Registered Landscape Architect' recognition scheme, a private professional-conduct credential; graduates need professional communication and conduct assessed against that standard, which the core's assessment table does not currently document beyond outcome statements. | 5 |
| W2 Authentic task design | Workplace | 1 / 3 | 2 | Signal 1 and Signal 2 (§2) name employers spanning private consultancies (Urbis, HASSELL, AECOM, Arup) and local government bodies (City of Rockingham, Bayside Council, Townsville City Council); graduates need a core task reproducing both a private-practice and a public-sector or regulatory client brief, which the core's studio assessment does not yet document beyond the academic studio brief. | 6 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | Indirect — Signal 1 and Signal 2 (§2) name a broad range of employers across private practice and local government, but the market report records no placement, practicum or supervised-experience requirement for either committed job family; this item is planned on the instrument's own anchor terms, with the employer range as context only. | 7 |
| **Workplace practice** | **Workplace** | **3 / 9** | **6** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Add a criterion-referenced peer review or structured critique task to a core studio assessment, for example ABPL90176 (Landscape Studio 2), where students appraise a peer's design proposition against published criteria — responding to Theme 3's (§3) call to keep evaluative judgement of AI-assisted planning output with a person rather than the tool. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Require students in a core design studio to document and justify reliance decisions on AI-assisted design or drafting tools — where they relied on, overrode or adjusted a tool's output — extending Theme 2's (§3) augmentation finding into an assessed judgement task. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Extend a core studio, for example ABPL90176 or ABPL90271, to address AI-assisted design and documentation tools' capabilities together with their limitations and ethics, with use and its limits assessed, responding to Theme 2's (§3) finding that professional design roles carry high augmentation exposure. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Require a core assessment that critiques the governance of AI-assisted planning or design tools in a landscape-architecture or urban-design context — bias in generative site analysis, data provenance, or accountability for AI-drafted planning advice — beyond tool operation, extending Theme 3's (§3) call for AI-governance content in the planning discipline. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 1 → 2 | "At least one core assessment requires application to novel or unfamiliar problems — case variation, unseen datasets, cross-context projects." | Add an assessed task to a core Year 2-3 subject that applies design or planning methods to a novel or unfamiliar site or regulatory context, drawing on Theme 3's (§3) record of the Planning Institute of Australia's guidance evolving from the 2021 PlanTech principles through the 2022 Strategy to the 2026 national AI-infrastructure standards. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Confirm and document the Year 4 core theses, ABPL90375 (Landscape Architecture Design Thesis) and ABPL90376 (Urban Design Thesis), as a self-scoped capstone with an assessed plan for closing identified knowledge gaps, responding to the continuing evolution of planning guidance recorded in Theme 3 (§3). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 1 → 2 | "Students design and conduct an inquiry with methodology selection and data collection, assessed." | Add an introductory research-methods or literature-review component to a core Year 1 subject, for example ABPL90283, assessed alongside its existing design coursework. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make a substantial primary-evidence project required, rather than one route among several, within the Year 4 core theses ABPL90375 and ABPL90376, with methodology defended under staged supervised review. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Add a client-brief or public-facing presentation task to a core studio, for example ABPL90176, judged against criteria drawn from the Australian Institute of Landscape Architects' professional-conduct expectations named in Theme 1 (§3), rather than assessment addressed only to the teaching team. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Assess professional communication repeatedly and progressively across the core, with at least one assessment in the Year 4 core theses (ABPL90375/ABPL90376) judged by a practitioner panel and professional conduct explicitly among the assessed criteria, extending the private-credential conduct expectations named in Theme 1 (§3). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Reframe a core studio assessment, for example ABPL90271 or ABPL90176, around a real or realistic public-sector or regulatory client brief alongside the existing private-practice brief, drawing on Signal 1 and Signal 2's (§2) named employers spanning private consultancies (Urbis, HASSELL, AECOM) and local government (City of Rockingham, Bayside Council, Townsville City Council), judged against practice-derived criteria. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Make practice-derived, client-brief tasks the program's assessment spine across the core studio sequence, with at least one, in the Year 4 theses, carrying a genuine constraint of practice — an externally supplied brief, a real regulatory timeline, or the profession's own performance standards — consistent with the private-practice and public-sector client range named in Signal 1 and Signal 2 (§2). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Move the elective Bower Studio (ABPL90152, Community Development) into the compulsory core, with practitioner supervision and assessment, giving graduates the work-situated experience the market report's named employer range (Signal 1, Signal 2, §2) implies they will need across both private-practice and public-sector settings. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the now-core Bower Studio placement, or an equivalent, into a required sequence across the program, supervised by a practitioner, assessed, with structured reflection and documented accountability to the host organisation. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Extend ABPL90176's assessed collaborative group project, or add a further core instance later in the program, to require documenting the allocation of work between students and AI-assisted design or documentation tools, with that allocation among the assessed criteria — responding to Theme 2's (§3) finding that professional design roles carry high augmentation exposure. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| P1 | C2 | Theme 2 and Theme 4 both find augmentation dominant for professional roles in the Landscape Architects and Urban and Regional Planners job families; graduates need evaluative judgement over AI-assisted design and planning outputs, not yet assessed in the core. | §3 Theme 2; §3 Theme 4 | MEDIUM |
| P2 | C3 | Theme 2 places Landscape Architects in the high-augmentation band, and Theme 3 records the Planning Institute of Australia formalising AI-governance guidance for planners. | §3 Theme 2; §3 Theme 3 | MEDIUM |
| P3 | C4 | Theme 3 records the Planning Institute of Australia's guidance evolving from the 2021 PlanTech principles through the 2022 Strategy to the 2026 national AI-infrastructure standards and Data Centres Guidance Note. | §3 Theme 3 | MEDIUM |
| P4 | C5 | No theme or signal in the market report bears on research-methods training or primary-evidence generation for either committed job family. | §1 job family map (no direct signal) | Not rated — no signal for this item |
| P5 | W1 | Theme 1 names the Australian Institute of Landscape Architects' 'Registered Landscape Architect' recognition scheme, a private professional-conduct credential the core does not yet assess against. | §3 Theme 1 | MEDIUM |
| P6 | W2 | Signal 1 and Signal 2 name employers spanning private consultancies and local government bodies; the core studio brief does not yet reproduce both client types. | §2 Signal 1; §2 Signal 2 | MEDIUM |
| P7 | W3 | Signal 1 and Signal 2 name a broad range of employers across private practice and local government, but the market report records no placement or supervised-experience requirement for either job family. | §2 Signal 1; §2 Signal 2 | Not rated — no direct placement signal |
| P8 | C2 | As P1 — Theme 2 and Theme 4's augmentation finding carries through to the level-3 reliance-decision anchor. | §3 Theme 2; §3 Theme 4 | MEDIUM |
| P9 | C3 | As P2 — Theme 2 and Theme 3 carry through to the level-3 governance anchor. | §3 Theme 2; §3 Theme 3 | MEDIUM |
| P10 | C4 | As P3 — Theme 3's record of continually evolving AI-planning guidance carries through to the level-3 independent-learning anchor. | §3 Theme 3 | MEDIUM |
| P11 | C5 | As P4 — no market signal for inquiry at this level either; the level-3 anchor is instrument-driven, not market-driven, for this program. | §1 job family map (no direct signal) | Not rated — no signal for this item |
| P12 | W1 | As P5 — Theme 1's private-credential conduct expectation carries through to the level-3 anchor. | §3 Theme 1 | MEDIUM |
| P13 | W2 | As P6 — Signal 1 and Signal 2's named-employer range carries through to the level-3 anchor. | §2 Signal 1; §2 Signal 2 | MEDIUM |
| P14 | W3 | As P7 — no market signal for a required placement sequence either. | §2 Signal 1; §2 Signal 2 | Not rated — no direct placement signal |
| P15 | C1 | Theme 2's high-augmentation, low-automation finding for professional design roles, and §4's Stable reading of design, urban, client, construction and environmental on that same finding, support coordinating work between people and AI-assisted tools as the level-3 anchor's target. | §3 Theme 2; §4 | MEDIUM |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C2 | Add a criterion-referenced peer review or structured critique task to a core studio assessment, for example ABPL90176 (Landscape Studio 2), where students appraise a peer's design proposition against published criteria — responding to Theme 3's (§3) call to keep evaluative judgement of AI-assisted planning output with a person rather than the tool. | C2 level 2 | Medium | Year 1; rubric update to ABPL90176's design-proposition assessment | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P2 | C3 | Extend a core studio, for example ABPL90176 or ABPL90271, to address AI-assisted design and documentation tools' capabilities together with their limitations and ethics, with use and its limits assessed, responding to Theme 2's (§3) finding that professional design roles carry high augmentation exposure. | C3 level 2 | Low-medium | Year 1; syllabus and rubric update to ABPL90176 or ABPL90271 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P3 | C4 | Add an assessed task to a core Year 2-3 subject that applies design or planning methods to a novel or unfamiliar site or regulatory context, drawing on Theme 3's (§3) record of evolving Planning Institute of Australia guidance. | C4 level 2 | Low-medium | Year 2-3; assessment-table update to a core Year 2-3 subject | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P4 | C5 | Add an introductory research-methods or literature-review component to a core Year 1 subject, for example ABPL90283, assessed alongside its existing design coursework. | C5 level 2 | Low | Year 1; assessment-table update to ABPL90283 | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P5 | W1 | Add a client-brief or public-facing presentation task to a core studio, for example ABPL90176, judged against criteria drawn from the Australian Institute of Landscape Architects' professional-conduct expectations named in Theme 1 (§3), rather than assessment addressed only to the teaching team. | W1 level 2 | Medium | Year 1; task and criteria redesign to ABPL90176 | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P6 | W2 | Reframe a core studio assessment, for example ABPL90271 or ABPL90176, around a real or realistic public-sector or regulatory client brief alongside the existing private-practice brief, drawing on Signal 1 and Signal 2's (§2) named employers, judged against practice-derived criteria. | W2 level 2 | Medium | Year 1-2; task and criteria redesign to a core studio | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P7 | W3 | Move the elective Bower Studio (ABPL90152, Community Development) into the compulsory core, with practitioner supervision and assessment, giving graduates the work-situated experience the market report's named employer range (Signal 1, Signal 2, §2) implies they will need. | W3 level 2 | Medium-high | Year 2-3; course-structure change moving ABPL90152 into the core | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P8 | C1 | Extend ABPL90176's assessed collaborative group project, or add a further core instance later in the program, to require documenting the allocation of work between students and AI-assisted design or documentation tools, with that allocation among the assessed criteria — responding to Theme 2's (§3) finding that professional design roles carry high augmentation exposure. | C1 level 3 | Low | Year 1-2; assessment-criteria update to ABPL90176's existing collaborative-work component | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P9 | C2 | Require students in a core design studio to document and justify reliance decisions on AI-assisted design or drafting tools — where they relied on, overrode or adjusted a tool's output — extending Theme 2's (§3) augmentation finding into an assessed judgement task. | C2 level 3 | Medium-high | Year 2; assessment-brief update to a core design studio | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P10 | C3 | Require a core assessment that critiques the governance of AI-assisted planning or design tools — bias in generative site analysis, data provenance, or accountability for AI-drafted planning advice — beyond tool operation, extending Theme 3's (§3) call for AI-governance content in the planning discipline. | C3 level 3 | Medium | Next annual course review; assessment redesign to a core studio | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P11 | C4 | Confirm and document the Year 4 core theses, ABPL90375 (Landscape Architecture Design Thesis) and ABPL90376 (Urban Design Thesis), as a self-scoped capstone with an assessed plan for closing identified knowledge gaps, responding to the continuing evolution of planning guidance recorded in Theme 3 (§3). | C4 level 3 | Medium | Year 4; capstone documentation update to ABPL90375/ABPL90376 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P12 | W1 | Assess professional communication repeatedly and progressively across the core, with at least one assessment in the Year 4 core theses (ABPL90375/ABPL90376) judged by a practitioner panel and professional conduct explicitly among the assessed criteria, extending the private-credential conduct expectations named in Theme 1 (§3). | W1 level 3 | Medium-high | Year 4; a practitioner-panel assessment added to ABPL90375/ABPL90376 | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P13 | W2 | Make practice-derived, client-brief tasks the program's assessment spine across the core studio sequence, with at least one, in the Year 4 theses, carrying a genuine constraint of practice — an externally supplied brief, a real regulatory timeline, or the profession's own performance standards. | W2 level 3 | High | Year 3-4; staged redesign across the core studio sequence and the Year 4 theses | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P14 | W3 | Extend the now-core Bower Studio placement, or an equivalent, into a required sequence across the program, supervised by a practitioner, assessed, with structured reflection and documented accountability to the host organisation. | W3 level 3 | High | Year 3-4; contingent on host-agreement negotiation and supervision capacity for the full cohort | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P15 | C5 | Make a substantial primary-evidence project required, rather than one route among several, within the Year 4 core theses ABPL90375 and ABPL90376, with methodology defended under staged supervised review. | C5 level 3 | High | Year 4; capstone redesign to ABPL90375/ABPL90376, contingent on assessor capacity for staged reviews | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | PASS: the program is professionally accredited by both AILA and PIA, and the course structure documents a staged, largely compulsory core sequence with progressive technical/design depth (Landscape Studio 1 → 2 → 3/4, and an Urban Design Studio sequence, culminating in Year 4 design theses), satisfying 'an accredited sequence, or a staged prerequisite chain.' | Any redesign must keep the accredited, staged core sequence — Landscape Studio 1 through 4 and the Urban Design Studio sequence, culminating in the Year 4 theses — intact; a change that thins the compulsory core's progressive technical depth would put the current PASS at risk. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | PASS: core studio subjects require defended design decisions under real site/technical constraints rather than recall or scripted responses — ABPL90271 (core) assesses students on landscape grading/drainage decisions and explicitly develops the generic skill to 'Support your design decisions with clear argument,' and ABPL90176 (core) requires students to formulate design responses to a set design brief. | Any redesign must keep the defended design-decision content already documented in ABPL90271 (grading and drainage decisions) and ABPL90176 (design responses to a set brief); reframing that content into a purely reflective or descriptive task would put the current PASS at risk. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C2 | 1 | 2 | +1 adaptive | 7 / 15 | 3 / 9 |
| P2 | C2 | 2 | 3 | +1 adaptive | 8 / 15 | 3 / 9 |
| P3 | C3 | 1 | 2 | +1 adaptive | 9 / 15 | 3 / 9 |
| P4 | C3 | 2 | 3 | +1 adaptive | 10 / 15 | 3 / 9 |
| P5 | C4 | 1 | 2 | +1 adaptive | 11 / 15 | 3 / 9 |
| P6 | C4 | 2 | 3 | +1 adaptive | 12 / 15 | 3 / 9 |
| P7 | C5 | 1 | 2 | +1 adaptive | 13 / 15 | 3 / 9 |
| P8 | C5 | 2 | 3 | +1 adaptive | 14 / 15 | 3 / 9 |
| P9 | W1 | 1 | 2 | +1 workplace | 14 / 15 | 4 / 9 |
| P10 | W1 | 2 | 3 | +1 workplace | 14 / 15 | 5 / 9 |
| P11 | W2 | 1 | 2 | +1 workplace | 14 / 15 | 6 / 9 |
| P12 | W2 | 2 | 3 | +1 workplace | 14 / 15 | 7 / 9 |
| P13 | W3 | 1 | 2 | +1 workplace | 14 / 15 | 8 / 9 |
| P14 | W3 | 2 | 3 | +1 workplace | 14 / 15 | 9 / 9 |
| P15 | C1 | 2 | 3 | +1 adaptive | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
