// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Bachelor of Commerce (UWA-BP002) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Bachelor of Commerce (UWA-BP002)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-09-07 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-uwa-bp002.md
**Position basis:** Destination AI Exposure 88.71 (field basis) × Curriculum Adaptiveness 7/15 (v4.2 draft, sub-scale A) · Workplace practice 3/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a field basis (Jobs and Skills Australia Higher Education Outcomes (JSA HEO) field 0803 Business and Management), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

The Bachelor of Commerce passes both gates: G1 on staged Level 1-to-3 prerequisite chains inside each of its eight degree-specific majors (for example LAWS1104 through LAWS2201/2207/2301 to the LAWS3308 capstone, and MGMT1135/1136 through MGMT2302 to MGMT3347), reinforced by course rule 10(1)(a)(iii)'s 72-point Level 2/3 requirement with 18 points at Level 3; G2 on assessed trade-off decisions documented in three different majors' core units (MKTG3306, LAWS3308, MGMT3347). Adaptiveness sits at 7/15 and workplace practice at 3/9. C1 and C4 sit at 2/3: assessed collaboration and case-based transfer already recur across most majors, but neither yet couples that work with a digital/AI tool or a self-scoped extension. C2, C3, C5, W1, W2 and W3 each sit at 1/3, mostly on ambiguity between a program-wide and a major-core reading of the evidence: LAWS3308's peer assessment, STAT1520's introductory statistics, MKTG1203's team presentation and BUSN2001's tool-based learning outcome each supply a level-1 anchor without the assessed, criterion-referenced or professional-genre step level 2 requires. C3 is the sharpest gap: no AI content of any kind appears in any of the 127 prescribed units in the extract. W3 (1/3) reflects WILG2201's real 100-hour, host-supervised placement sitting as a competitive-entry elective rather than a guaranteed core requirement.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | Direct — Market Section 3 Theme 1 records APESB professional standards requiring auditors to verify automated ledger anomaly-detection algorithms and maintain documented audit-trail logs for AI-generated financial estimates — appraisal of a tool's output as a professional duty. The one criterion-referenced appraisal task the extract documents, LAWS3308's peer assessment, is core to the Business Law major alone, leaving it ambiguous whether it counts as program-wide core. | 1 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | Direct — Market Section 3 Theme 1 (the APESB AI-verification duty) and Section 4's rising ASRS sustainability-assurance keyword both describe AI-adjacent professional obligations entering this degree's destination occupations. No prescribed unit in the extract contains AI content of any kind — the sole occurrence of the phrase names an unrelated degree's major sequence. | 2 |
| C5 Inquiry & evidence generation | Adaptive | 1 / 3 | 2 | Direct — Market Section 2 Signal 1 and Section 4 record Audit sampling as a rising, recurring keyword across 6,240 accountant/auditor postings, and Section 3 Theme 1 requires those sampling and estimation decisions to be defensible. STAT1520, the degree's one unit stated as compulsory for every Bachelor of Commerce student, teaches only introductory statistics. | 3 |
| C1 Distributed cognition & relational capability | Adaptive | 2 / 3 | 1 | Direct — Market Section 5 CI-3 and Section 3 Theme 4 name clerical, administrative and retail entry destinations (Office Clerks, General; Retail Salespersons) as the field's most automation-exposed group, and JSA (2025) attributes that exposure to routine, rules-based tasks. Assessed collaborative practice already appears in six of eight majors' core units (ACCT2112, EMPL2202, MGMT3347, MKTG1203, BUSN2001, LAWS3308), but none couples that work with a named digital or AI tool, the distinguishing feature the market evidence points toward. | 7 |
| C4 Life-long learning & transfer | Adaptive | 2 / 3 | 1 | Direct — Market Section 3 Theme 2 and Section 5 CI-2 describe a mandatory, dated, regulator-created shortage of accounting graduates able to carry existing assurance methodology into a new multi-capital sustainability-disclosure context — exactly the documented, structured transfer C4 level 3 asks for, which no BP002 student is currently required to complete. | 8 |
| **Adaptive capabilities** | **Adaptive** | **7 / 15** | **8** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Direct — Market Section 3 Theme 3 and Section 5 CI-4 record that the Privacy Act 1988 Australian Privacy Principles bind the entities these graduates enter directly, with nothing in the advertisement sample suggesting the obligation is delegated to a specialist; Section 1 places Accountant (General) and General Clerk among the field's top entry occupations. No documented core assessment yet reaches a professional genre or an audience beyond the teaching team. | 4 |
| W2 Authentic task design | Workplace | 1 / 3 | 2 | Direct — Market Section 5 CI-3 and Section 3 Theme 4 argue that making a professional-grade artefact assessable early is what would separate a commerce graduate's transcript from the field's general clerical and retail entry pool. BUSN2001 names the practitioner tools (dashboards, scorecards, storyboards) as an outcome but assesses them by quiz and assignment, not a practice-judged artefact. | 5 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | Direct — Market Section 2 Signal 1 names the Big Four and mid-tier firms (PwC, Deloitte, EY, KPMG, BDO, Grant Thornton) as the most frequent employers in the largest destination occupation, an occupation Section 3 Theme 1 ties to documented, supervised audit-trail practice. WILG2201 already places students with a real host and 100 hours of supervised industry experience, but only as a competitive-entry elective, so no BP002 student is guaranteed it. | 6 |
| **Workplace practice** | **Workplace** | **3 / 9** | **6** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Add a published, criterion-referenced rubric to LAWS3308's existing peer-assessment component (Business Law core), turning its currently ambiguous peer assessment into an unambiguous criterion-referenced appraisal of quality that meets level 2 outright rather than resting on a major-core reading — answering the appraisal-of-output duty APESB now places on auditors (Section 3 Theme 1). Cost: rubric authoring inside an existing assessment item, no new credit points. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Attach a reliance-and-override log to the now rubric-based LAWS3308 peer assessment, requiring students to document and justify instances where they accepted or overrode a peer's, source's or supplied tool's judgement — the documentation duty Theme 1 imposes on practising auditors maintaining audit-trail logs. Cost: an added assessment component and marking criteria. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Add an assessed module on AI capabilities and limitations to CITS1401 (Business Analytics core, the extract's only unit already teaching programming and data tooling) — answering the APESB AI-verification duty (Theme 1) and the rising ASRS sustainability-assurance skill (Section 4). Cost: a new module and assessment item inside an existing unit, no new credit points. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Add an assessed AI-governance critique task to the new CITS1401 module, in which students evaluate a supplied AI system's bias, transparency or data-governance properties in a business context — moving from tool operation to governance of the tool itself, the level-3 anchor. Cost: an assessment brief extension inside the same unit. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 1 → 2 | "Students design and conduct an inquiry with methodology selection and data collection, assessed." | Add a methodology-selection and data-collection component to STAT1520, the one unit the handbook records as compulsory for every Bachelor of Commerce student, turning its introductory statistics assessment into a designed inquiry — addressing the audit-sampling skill rising across 6,240 accountant/auditor postings (Section 2 Signal 1; Section 4). Cost: an assignment redesign inside an existing compulsory unit. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make a primary-evidence sampling or survey project a required element of a shared capstone across majors, extending the model already used in the Business Analytics or Economics projects (BUSN3001, ECON3206), with a staged, supervised defence of the chosen methodology — answering Theme 1's requirement that sampling and estimation decisions be defensible under scrutiny. Cost: capstone-structure change plus supervision capacity. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Redesign MKTG1203's team-project presentation (Marketing core) into a client-style brief addressed to a named external audience and marked against professional-communication criteria drawn from practice — meeting the professional-genre requirement the Privacy Act obligations of Section 3 Theme 3 and Section 5 CI-4 place directly on these graduates' first employers. Cost: assessment brief and marking-criteria redesign. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Recruit a small external practitioner panel, drawing on the Business Law major's professional-conduct outcomes, to judge the redesigned client-brief task, assessing professional conduct and accountability explicitly — so accountability runs to a real external audience rather than teaching staff, matching the named employer set in Section 2 Signal 1. Cost: external-judge coordination each offering. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Redesign the BUSN2001 dashboard/storyboard learning outcome (Business Analytics core) into an assessed artefact built for a real or realistic client problem and judged against practice criteria, replacing its current quiz-and-assignment assessment — separating the graduate's transcript from the field's general clerical and retail entry pool named in Section 5 CI-3. Cost: assessment redesign inside an existing unit. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Carry the redesigned client-facing artefact into a shared capstone across majors, adding a genuine constraint of practice — a real resource or time limit, or an externally supplied problem — so authentic tasks become the program's assessment spine rather than a single instance in Business Analytics. Cost: capstone-structure update. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Move WILG2201 from a competitive-entry elective to a core placement requirement in at least one major, expanding places so enrolment is guaranteed rather than competitive — turning the existing 100-hour, host-supervised internship into a placement every student in that major completes, matching the market's largest employer set (PwC, Deloitte, EY, KPMG, BDO, Grant Thornton — Section 2 Signal 1). Cost: placement-capacity expansion and a course-rule change. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the now-core placement into a supervised sequence with structured reflection on professional practice and documented accountability to the host employer, budgeting travel or income support so an unpaid or relocation-dependent placement does not add an equity cost — justified by skill development and professional identity, not by employment rates. Cost: partner agreements and equity-support funding. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Add a documented role-and-tool allocation requirement to one of the six existing group-assessed core tasks (for example ACCT2112's group assignment or LAWS3308's group work), requiring students to record which parts of the task were completed by people and which by a named digital or AI tool — moving collaboration from a people-only to a people-and-systems assessment. Cost: a new criterion added to an existing group task. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Convert one of the case-based transfer tasks already assessed in MGMT3347, MKTG3306, HRMT3345 or FINA2222 into the entry point for a self-scoped extension component in which students identify their own knowledge gap against the sustainability-reporting shortage in Theme 2 and CI-2, and document a plan to close it. Cost: an added reflective-planning criterion, no new unit. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| P1 | C2 | APESB professional standards require auditors to verify automated ledger anomaly-detection algorithms and maintain documented audit-trail logs for AI-generated financial estimates. | Section 3 Theme 1 | HIGH (Accountants and Auditors — regulatory and statutory instruments) |
| P2 | C3 | The same APESB AI-verification standard, plus a rising ASRS sustainability-assurance keyword across the accountant/auditor advertisement sample, describe AI-adjacent professional obligations the core does not yet assess. | Section 3 Theme 1; Section 4 | HIGH (Accountants and Auditors — regulatory and statutory instruments) |
| P3 | C5 | Audit sampling is a rising, recurring keyword across 6,240 accountant/auditor postings, and APESB now requires sampling and estimation decisions to be defensible. | Section 2 Signal 1; Section 3 Theme 1; Section 4 | HIGH (Accountants and Auditors — job-advertisement signals) |
| P4 | W1 | Privacy Act 1988 Australian Privacy Principles bind the entities these graduates enter directly, with no delegation to a specialist; General Clerk and Accountant (General) sit among the field's top entry occupations. | Section 1; Section 3 Theme 3; Section 5 CI-4 | MEDIUM (Office Clerks, General — regulatory and statutory instruments) |
| P5 | W2 | Making a professional-grade artefact assessable early is what would separate a commerce transcript from the field's general clerical and retail entry pool. | Section 1; Section 3 Theme 4; Section 5 CI-3 | MEDIUM (Office Clerks, General — scholarly and grey-literature studies) |
| P6 | W3 | The Big Four and mid-tier firms (PwC, Deloitte, EY, KPMG, BDO, Grant Thornton) are the most frequent employers in the largest destination occupation, which is bound to documented, supervised audit-trail practice. | Section 2 Signal 1; Section 3 Theme 1 | HIGH (Accountants and Auditors — job-advertisement signals) |
| P7 | C1 | Clerical, administrative and retail entry destinations are the field's most automation-exposed group; JSA (2025) names routine, rules-based office tasks as most readily automated. | Section 1; Section 3 Theme 4; Section 5 CI-3 | MEDIUM (Office Clerks, General — scholarly and grey-literature studies) |
| P8 | C4 | Mandatory Australian Sustainability Reporting Standards create an acute, dated shortage of accounting graduates able to apply assurance methodology to multi-capital greenhouse-gas and climate-risk disclosure. | Section 3 Theme 2; Section 5 CI-2 | HIGH (Accountants and Auditors — scholarly and grey-literature studies) |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C2 | Add a published, criterion-referenced rubric to LAWS3308's existing peer-assessment component. | C2 level 2 (criterion-referenced appraisal of quality) | Low | Term 1; rubric authoring only | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P2 | C3 | Add an assessed AI capabilities-and-limitations module to CITS1401. | C3 level 2 (capabilities and limitations discussed and assessed) | Low-Medium | Term 1; module and assessment brief update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P3 | C5 | Add a methodology-selection and data-collection component to STAT1520. | C5 level 2 (methodology selection and data collection assessed) | Low-Medium | Term 1; assessment brief update | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P4 | W1 | Redesign MKTG1203's team-project presentation into a client-style brief marked against professional-communication criteria. | W1 level 2 (recognised professional genre or external audience) | Medium | Term 1-2; assessment redesign | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P5 | W2 | Redesign the BUSN2001 dashboard/storyboard outcome into an assessed, practice-judged artefact. | W2 level 2 (professional task reproduced end to end) | Medium | Term 2; assessment redesign | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P6 | C2 | Attach a reliance-and-override log to the now rubric-based LAWS3308 peer assessment. | C2 level 3 (reliance decisions documented and justified) | Medium | Term 2; assessment brief update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P7 | C3 | Add an assessed AI-governance critique task to the new CITS1401 module. | C3 level 3 (critique or governance of AI systems) | Medium | Term 2; module extension | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P8 | C1 | Add a documented role-and-tool allocation requirement to an existing group-assessed core task. | C1 level 3 (coordination across people and tools) | Medium | Term 2; assessment criterion added | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P9 | C4 | Add a self-scoped extension component to an existing core case-based transfer task. | C4 level 3 (self-scoped extension; independent learning progression) | Medium | Term 2; reflective-planning criterion added | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P10 | C5 | Require a primary-evidence sampling project with a staged supervised methodology defence in a shared capstone. | C5 level 3 (required primary-evidence project, defended under scrutiny) | Medium-High | Next course review; capstone-structure update | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P11 | W1 | Recruit an external practitioner panel to judge the client-brief task and assess professional conduct explicitly. | W1 level 3 (external practitioner judge; conduct assessed) | Medium-High | Next course review; external-judge coordination | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P12 | W2 | Carry the redesigned client-facing artefact into a shared capstone with a genuine constraint of practice. | W2 level 3 (assessment spine with a genuine constraint of practice) | Medium-High | Next course review; capstone-structure update | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P13 | W3 | Move WILG2201 from a competitive-entry elective to a guaranteed core placement in at least one major. | W3 level 2 (core placement with practitioner supervision and assessment) | High | Next course review; course-rule and placement-capacity change | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P14 | W3 | Extend the now-core placement into a supervised sequence with structured reflection and documented host accountability, budgeting equity support. | W3 level 3 (extended, supervised, assessed placement sequence) | High | Following course review; partner and funding agreements | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | The gate passes on the staged prerequisite chain route rather than an all-compulsory specialist core. Course rule 10(1)(a) requires a degree-specific major chosen from a closed list of eight, and rule 10(1)(a)(iii) forces at least 72 credit points at Level 2 or 3 including 18 points at Level 3, so depth is structural rather than optional. Each major then documents its own staged chain: Business Law runs LAWS1104 to LAWS2201, LAWS2207 and LAWS2301 and on to the LAWS3308 capstone, which names all three Level 2 units as prerequisites; Management runs MGMT1135 and MGMT1136 to MGMT2302 and on to MGMT3347, which requires any two named Level 2 management units. This is disciplinary identity with progressive depth, not generic or interchangeable content. | Redesign must preserve the staged Level 1-to-3 prerequisite chains inside each major (for example LAWS1104 through LAWS2201/2207/2301 to the LAWS3308 capstone, and MGMT1135/1136 through MGMT2302 to MGMT3347) and the 72-point Level 2/3 requirement with 18 points at Level 3 in course rule 10(1)(a)(iii). New collaboration, digital-literacy or AI-governance content sits alongside these chains and does not displace or thin the specialist core. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | Assessments requiring defended trade-off decisions are documented in core units of more than one major, so the gate is not carried by recall or scripted responses alone. MKTG3306, core to the Marketing major, is assessed by case study and its outcome ties that assessment to cases that require weighing societal and ethical issues against business profit — a trade-off the student must resolve and defend. LAWS3308, the Business Law capstone, requires students to design solutions to unpredictable and sometimes complex problems and then to evaluate the solutions provided to the business entity, which is a capstone carrying real uncertainty. MGMT3347's assessed case studies require informed recommendations for the organisation's sustainable performance. | Redesign must keep at least one of MKTG3306's ethics-versus-profit case, LAWS3308's capstone evaluation of unpredictable legal problems, or MGMT3347's sustainable-performance recommendations intact, since the gate's pass rests on these three major-specific trade-off tasks rather than a program-wide requirement. The C5 and W2 interventions above should be built to also produce a documented, defended trade-off decision, so the gate strengthens rather than staying dependent on major choice. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C2 | 1 | 2 | +1 adaptive | 8 / 15 | 3 / 9 |
| P2 | C2 | 2 | 3 | +1 adaptive | 9 / 15 | 3 / 9 |
| P3 | C3 | 1 | 2 | +1 adaptive | 10 / 15 | 3 / 9 |
| P4 | C3 | 2 | 3 | +1 adaptive | 11 / 15 | 3 / 9 |
| P5 | C5 | 1 | 2 | +1 adaptive | 12 / 15 | 3 / 9 |
| P6 | C5 | 2 | 3 | +1 adaptive | 13 / 15 | 3 / 9 |
| P7 | W1 | 1 | 2 | +1 workplace | 13 / 15 | 4 / 9 |
| P8 | W1 | 2 | 3 | +1 workplace | 13 / 15 | 5 / 9 |
| P9 | W2 | 1 | 2 | +1 workplace | 13 / 15 | 6 / 9 |
| P10 | W2 | 2 | 3 | +1 workplace | 13 / 15 | 7 / 9 |
| P11 | W3 | 1 | 2 | +1 workplace | 13 / 15 | 8 / 9 |
| P12 | W3 | 2 | 3 | +1 workplace | 13 / 15 | 9 / 9 |
| P13 | C1 | 2 | 3 | +1 adaptive | 14 / 15 | 9 / 9 |
| P14 | C4 | 2 | 3 | +1 adaptive | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
