// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Electrical Engineering (MC-ELECENG) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Electrical Engineering (MC-ELECENG)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-29 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-eleceng.md
**Position basis:** Destination AI Exposure 82.73 (field basis) × Curriculum Adaptiveness 7/15 (v4.2 draft, sub-scale A) · Workplace practice 4/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a field basis (Jobs and Skills Australia Higher Education Outcomes (JSA HEO) field 031301 Electrical Engineering), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

The Master of Electrical Engineering shows a strong disciplinary foundation and sound decision-making assessment: G1 passes on a fully compulsory, staged specialist core across electronics, control, signal processing, communications and power engineering, professionally accredited by Engineers Australia, and G2 passes on defended trade-off decisions under real uncertainty in core subjects such as Probability and Random Models and Control Systems. C1 (2/3), C4 (2/3) and W2 (2/3) each clear the program's first bar — collaborative practice with individual accountability, application to novel problems, and at least one authentic end-to-end design task — but stop short of the level-3 anchors that require documented coordination between people and AI/software tools, a verified self-scoped capstone, or a genuine constraint of practice.

The remaining five items — C2, C3, C5, W1 and W3 — sit at level 1, two steps below the instrument ceiling. §2 and §3 of the market report show the destination job families placing continued weight on design, project delivery and reporting work (Signal 1, Signal 2), a high-augmentation AI profile for the Engineers, All Other family (Theme 2), and an expanding state-based professional registration regime (Theme 4, Theme 5) — evidence that bears most directly on C3's digital and AI governance gap and W1's professional-conduct gap, and, via the compulsory but elective-routed Engineering Practice Hurdle, on W3.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | Direct — §3 Theme 2 records a high-augmentation, low-automation profile (JSA-derived data) for the Engineers, All Other family: engineers increasingly work alongside AI-assisted design and analysis output that needs judged quality, but core assessment attaches no criterion-referenced review or reliance-and-override log to that output. | 1 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | Direct — §4 records "compliance" as a rising skill-shift row, drawn only from the Electrical Engineers sample (Signal 2), alongside §3 Theme 2's high-augmentation profile for the wider family; core digital-tool content stays at tool-operation level and every AI-named unit sits in Group A electives, never core. | 2 |
| C5 Inquiry & evidence generation | Adaptive | 1 / 3 | 2 | Direct — §2 Signal 1 records "report" as a recurring keyword for Engineers, All Other (36,848 postings); the one subject built around a substantial primary-evidence research project is a Group A elective, not the required route. | 3 |
| C1 Distributed cognition & relational capability | Adaptive | 2 / 3 | 1 | Direct — §2 Signal 1 ("project") and Signal 2 ("project management") both record project delivery as a recurring keyword; core group assessment does not extend to documenting how work is divided between people and AI/software tools. | 6 |
| C4 Life-long learning & transfer | Adaptive | 2 / 3 | 1 | Indirect — §1's job family map shows this program's own destination record resolving into three distinct job families (Engineers, All Other; Electrical Engineers; Mechanical Engineers), consistent with the transfer capability this item measures, but the compulsory Year 3 capstone that could carry a documented self-scoping process is not present in the supplied extract. | 7 |
| **Adaptive capabilities** | **Adaptive** | **7 / 15** | **8** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Direct — §3 Theme 4 and Theme 5 record mandatory state-based professional registration rolling out across prescribed engineering areas from 6 March 2025; core communication assessment is judged only by teaching staff, with no accreditation-facing or practitioner audience. | 4 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | Direct — §2 Signal 2 names employers hiring directly into this field (BAE Systems, RTX Corporation, KBR, Raytheon Australia) and §3 Theme 4/Theme 5 record registration regimes resting on supervised professional practice; the mandatory Engineering Practice Hurdle's one credit-bearing internship route sits in Approved Electives (Group B), not core. | 5 |
| W2 Authentic task design | Workplace | 2 / 3 | 1 | Direct — §4 records "design" as stable and recurring across both the Engineers, All Other and Electrical Engineers samples; core design projects reproduce the professional task end to end, but no instance is documented with a genuine constraint of practice. | 8 |
| **Workplace practice** | **Workplace** | **4 / 9** | **5** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Attach a criterion-referenced peer-review component, marked against published exemplars, to ENGR90051's existing 'Peer feedback + evaluation' component (cost: developing and calibrating exemplars each offering). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Extend ENGR90051's individual 'Reflection' component into an assessed reliance-and-override log: students document and justify instances where they relied on or overrode a simulation tool, dataset or teammate's design choice (cost: rubric redesign and additional marking time per submission). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Move the capability-and-limitation content of one AI-related Group A elective (e.g. ELEN90095, ELEN90097, ELEN90098, ELEN90099, ELEN90088) into an assessed core module discussing AI use and limits, rather than leaving it accessible only to students who choose that elective (cost: core curriculum-hours reallocation). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Add a core assessment task requiring students to critique an AI-assisted engineering tool's governance properties — bias, accountability, transparency or regulatory compliance — in an electrical-engineering context (cost: developing a new assessed component and marking criteria). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 1 → 2 | "Students design and conduct an inquiry with methodology selection and data collection, assessed." | Extend ELEN30011's laboratory workshop-based project so students select and justify their own experimental methodology, rather than working to a staff-designed protocol (cost: additional supervision time to support varied student-chosen methods). | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Move ELEN90083 (Electrical Engineering Research Project) from a Group A elective into a required core route, or add an equivalent required primary-evidence project with a defended methodology (cost: additional supervision capacity for a now cohort-wide project). | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Reframe one of ELEN30013's or ENGR90051's group presentations as a client-brief or consultancy-style deliverable, judged against criteria drawn from professional practice (cost: developing a professional-genre rubric and briefing materials). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Add a core assessment item delivered to, or judged by, an external industry panel or a registered practising engineer, with professional conduct explicitly among the assessed criteria (cost: coordinating and briefing external assessors each offering). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Move the credit-bearing internship subject (ENGR90033) from Approved Electives (Group B) into the core, so a supervised, assessed workplace placement is guaranteed rather than one route among several Engineering Practice Hurdle options (cost: securing enough placement-host capacity for the whole cohort). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the now-core placement into a sequence, or a single extended placement, with formal host accountability and structured reflection assessed across the program (cost: sustained host-relationship management and structured-reflection marking load). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | In ENGR90051's team project, require student teams to submit and defend a documented allocation of work between team members and simulation/AI design tools (cost: rubric redesign and moderation time for a new assessed component). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Document the compulsory Year 3 Engineering Capstone Project (ENGR90037/ENGR90038) as a self-scoped project with an assessed knowledge-gap-and-plan component, or add one if not already present (cost: capstone assessment redesign and supervisor time to assess self-scoping). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Add a genuine constraint of practice — an externally supplied or resource-limited brief, real time/resource limits, or a consequential external audience — to one of the recurring design-project instances in ELEN30009, ELEN30013 or ENGR90051 (cost: staff time to source or validate an external brief, and to moderate a less predictable outcome). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| P1 | C2 | The Engineers, All Other family shows a high-augmentation, low-automation AI profile: engineers work alongside AI-generated output that must be judged, not simply produced. | §3 Theme 2 | MEDIUM (§3 discussion-signal confidence) |
| P2 | W1 | State-based professional registration for engineers became mandatory in prescribed areas from 6 March 2025 and continues rolling out, raising the practical stakes of professional conduct and accountability, judged externally. | §3 Theme 4; Theme 5 | MEDIUM (§3 discussion-signal confidence) |
| P3 | C1 | "Project" and "project management" recur as advertisement keywords for both destination job families, evidence that coordinated, multi-person delivery is a standing employer expectation. | §2 Signal 1; Signal 2 | MEDIUM (§2 advertisement-index confidence) |
| P4 | C3 | "Compliance" is a rising skill-shift row drawn from the Electrical Engineers sample, and the wider Engineers, All Other family already shows heavy AI augmentation — the tools this item's anchors ask students to critique are already in the job. | §4 Skill Shift Summary; §3 Theme 2 | MEDIUM (§2/§3 combined confidence) |
| P5 | C5 | "Report" is a recurring advertisement keyword for the largest destination job family, consistent with employers valuing documented, evidence-based engineering output. | §2 Signal 1 | MEDIUM (§2 advertisement-index confidence) |
| P6 | W2 | "Design" recurs as a stable skill-shift row across both the Engineers, All Other and Electrical Engineers samples, evidence that authentic, end-to-end design work remains the field's core deliverable. | §4 Skill Shift Summary; §2 Signal 1, Signal 2 | MEDIUM (§2/§4 combined confidence) |
| P7 | C4 | This program's own destination record resolves into three distinct job families, consistent with graduates needing to transfer skills across roles rather than repeat one fixed task set. | §1 Job Family Map | HIGH (§1 destination-record basis) |
| P8 | C2 | The same high-augmentation AI profile that warrants criterion-referenced review also warrants a documented reliance-and-override discipline once judgement is being exercised repeatedly. | §3 Theme 2 | MEDIUM (§3 discussion-signal confidence) |
| P9 | C3 | Governance of AI systems (bias, accountability, regulation) follows from the same augmentation profile once operation-level use is already assessed. | §3 Theme 2 | MEDIUM (§3 discussion-signal confidence) |
| P10 | C5 | A required, defended primary-evidence project follows employer valuation of documented engineering output once methodology selection is already assessed. | §2 Signal 1 | MEDIUM (§2 advertisement-index confidence) |
| P11 | W1 | The same registration rollout that warrants a professional-genre task also warrants external practitioner judgement once professional communication is repeatedly assessed. | §3 Theme 4; Theme 5 | MEDIUM (§3 discussion-signal confidence) |
| P12 | W3 | Named employers (BAE Systems, RTX Corporation, KBR, Raytheon Australia) hire directly into this field, and the registration regimes rolling out typically rest on supervised professional practice. | §2 Signal 2; §3 Theme 4, Theme 5 | MEDIUM (§2/§3 combined confidence) |
| P13 | W3 | Once a core placement exists, the same employer and registration evidence supports extending it into a substantial, accountable sequence rather than a single short instance. | §2 Signal 2; §3 Theme 4, Theme 5 | MEDIUM (§2/§3 combined confidence) |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C2 | Embed criterion-referenced peer review, marked against exemplars, in ENGR90051's existing peer-feedback component. | C2 level 2 (criterion-referenced appraisal of quality) | Low | Term 1; rubric and exemplar update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P2 | W1 | Reframe an existing ELEN30013 or ENGR90051 presentation as a client-brief deliverable judged against professional-practice criteria. | W1 level 2 (recognised professional genre or audience beyond the teaching team) | Low | Term 1; assessment-brief update | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P3 | C1 | Require ENGR90051 team submissions to document and defend how work was allocated between team members and simulation/AI tools. | C1 level 3 (coordinating work across people AND tools/AI systems) | Medium | Term 1; assessment-brief update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P4 | C3 | Move an AI-related Group A elective's capability-and-limitation content into an assessed core module. | C3 level 2 (AI capabilities AND limitations/ethics addressed and assessed) | Low-Medium | Term 1-2; syllabus update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P5 | C5 | Add a methodology-selection requirement to ELEN30011's assessed laboratory project. | C5 level 2 (design and conduct an inquiry with methodology selection) | Medium | Term 2; subject update | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P6 | W2 | Add a genuine constraint of practice — an external brief or real resource limit — to a recurring core design project. | W2 level 3 (assessment spine plus a genuine constraint of practice) | Medium | Term 2; subject update | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P7 | C4 | Document the compulsory capstone (ENGR90037/ENGR90038) as a self-scoped project with an assessed knowledge-gap-and-plan component. | C4 level 3 (structured progression toward independent learning) | Medium | Term 2; capstone documentation update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P8 | C2 | Attach an assessed reliance-and-override log to ENGR90051's Reflection component. | C2 level 3 (document and justify reliance decisions) | Medium | Term 2; assessment-brief update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P9 | C3 | Add an assessed AI-governance critique task in an electrical-engineering context. | C3 level 3 (critique or governance of AI systems beyond tool operation) | Medium-High | Term 2-3; new assessed component | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P10 | C5 | Move ELEN90083 (Electrical Engineering Research Project) from Group A elective into a required core route. | C5 level 3 (a substantial primary-evidence project is REQUIRED, defended under scrutiny) | High | Next course review; core structure change | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P11 | W1 | Invite an external industry panel or registered practising engineer to judge a core assessment item, with professional conduct as an assessed criterion. | W1 level 3 (external practitioner audience with conduct/accountability criteria) | Medium-High | Term 2-3; external-panel coordination | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P12 | W3 | Move the credit-bearing internship (ENGR90033) from Approved Electives into the core. | W3 level 2 (a core unit places students in a real workplace setting, supervised and assessed) | High | Next course review; core structure and placement-capacity change | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P13 | W3 | Extend the now-core placement into an extended or repeated sequence with host accountability and structured reflection. | W3 level 3 (substantial required work-situated learning, supervised, assessed, accountable to the host) | High | Following course review; placement-capacity change | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | The program documents a fully compulsory, staged specialist core (100 credit points each in Year 1 and Year 2, plus a compulsory Year 3 capstone) covering electronics, control, signal processing, communications and power engineering, and is professionally accredited by Engineers Australia — an accredited sequence with progressive technical depth. | Redesign must preserve the fully compulsory, staged specialist core across electronics, control, signal processing, communications and power engineering, and the Engineers Australia accreditation it carries. Adding AI-literacy or governance content must enrich this core sequence rather than displace its disciplinary depth. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | Core subjects are explicitly built around decision-making under real uncertainty (Probability and Random Models; Control Systems' framing of feedback design under modelling and environmental uncertainty), and core assessment requires defended trade-off/design decisions (ELEN30013's ILO on identifying and justifying implementation tradeoffs; ENGR90051's assessed requirement to 'justify design decisions throughout the design process'). | Redesign must preserve the core's assessed, defended trade-off decisions under real uncertainty (Probability and Random Models; Control Systems' feedback-design framing; ENGR90051's justified design decisions). New assessment items must not replace these with recall or scripted response. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C2 | 1 | 2 | +1 adaptive | 8 / 15 | 4 / 9 |
| P2 | C2 | 2 | 3 | +1 adaptive | 9 / 15 | 4 / 9 |
| P3 | C3 | 1 | 2 | +1 adaptive | 10 / 15 | 4 / 9 |
| P4 | C3 | 2 | 3 | +1 adaptive | 11 / 15 | 4 / 9 |
| P5 | C5 | 1 | 2 | +1 adaptive | 12 / 15 | 4 / 9 |
| P6 | C5 | 2 | 3 | +1 adaptive | 13 / 15 | 4 / 9 |
| P7 | W1 | 1 | 2 | +1 workplace | 13 / 15 | 5 / 9 |
| P8 | W1 | 2 | 3 | +1 workplace | 13 / 15 | 6 / 9 |
| P9 | W3 | 1 | 2 | +1 workplace | 13 / 15 | 7 / 9 |
| P10 | W3 | 2 | 3 | +1 workplace | 13 / 15 | 8 / 9 |
| P11 | C1 | 2 | 3 | +1 adaptive | 14 / 15 | 8 / 9 |
| P12 | C4 | 2 | 3 | +1 adaptive | 15 / 15 | 8 / 9 |
| P13 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
