// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Bachelor of Engineering (ADELAIDE-BENGH_BEHCIVS1) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Bachelor of Engineering (ADELAIDE-BENGH_BEHCIVS1)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-09-07 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-adelaide-bengh_behcivs1.md
**Position basis:** Destination AI Exposure 83.48 (field basis) × Curriculum Adaptiveness 9/15 (v4.2 draft, sub-scale A) · Workplace practice 4/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a field basis (Jobs and Skills Australia Higher Education Outcomes (JSA HEO) field 039999 Engineering and Related Technologies, n.e.c.), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

The Bachelor of Engineering (Civil and Structural) runs a fully compulsory, prerequisite-gated civil engineering core, accredited by Engineers Australia under the Washington Accord. G1 passes on that all-compulsory specialist core and its staged prerequisite chain (Structural Mechanics before Reinforced Concrete Design and Structural Steel Design; Civil Engineering Hydraulics before Advanced Civil Engineering Hydraulics). G2 passes on the required capstone's assessment of open-ended, uncertain engineering problems through report and oral defence, and on the Reinforced Concrete Design course's defended environmental trade-off.

Operating on an estimated field-of-education exposure of 83.48, drawn from Jobs and Skills Australia Higher Education Outcomes (JSA HEO) destinations for field 039999 Engineering and Related Technologies, n.e.c. rather than this program's own graduates, the program shows headroom on both sub-scales: 9/15 on Adaptiveness and 4/9 on Workplace. The clearest deficits are C2, C3, W1 and W3 (each 1/3): appraisal, digital and AI literacy, professional communication and work-situated learning are each anchored in outcomes or captured only in an elective or an unassessed unit shell, without core criterion-referenced assessment. C1, C4 and W2 (each 2/3) show a core assessment reaching the mid anchor but not yet the further documentation the next anchor requires. C5 (3/3) already meets the maximum and needs no action.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | CI-1 (§5) reads the phased state registration requirement — mandatory from 6 March 2025 in prescribed areas and rolling out further (§3 Themes 2, 3, 5) — as making a named human legally answerable for engineering work whatever produced it. The judgement that sign-off requires, appraising a supplied design or calculation and defending acceptance, is C2's own next anchor, and no core unit in the extract is documented as assessing it against criteria. | 1 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | Engineers Australia already accredits the program (§3 Theme 1), so CI-2 (§5) treats the accreditation gate as met and names what remains open instead: whether a graduate can supervise generated work. Assessing verification of a computational or generated design output, including what would falsify it, is CI-2's own recommended action and matches C3's next anchor. | 2 |
| C1 Distributed cognition & relational capability | Adaptive | 2 / 3 | 1 | Signal 1 (§2) names 'cad' among the recurring skill keywords in the 3,668-posting civil-engineer sample, and Theme 6 (§3) records design, engineering, science and transport professionals among the most AI-exposed occupational groups in Australia. C1's next anchor — assessed coordination of work across people AND tools/AI systems — is the capability that would let the capstone's existing group work document that same design-software allocation, rather than leave it unexamined. | 5 |
| C4 Life-long learning & transfer | Adaptive | 2 / 3 | 1 | CI-3 (§5) names design, engineering, science and transport professionals among the most AI-exposed occupational groups (§3 Theme 6), scored at task level rather than as an employment forecast, and recommends assessing transfer of an established method to an unfamiliar problem as the part of that exposure score curriculum can still reach. That is C4's own next anchor, which the Honours Research Project's supervisor-scoped topics do not currently document. | 6 |
| C5 Inquiry & evidence generation | Adaptive | 3 / 3 | 0 | No gap. C5 already meets the level-3 anchor: the required, two-semester Honours Research Project generates primary evidence through theoretical analysis, simulation and experiment, and is defended through a staged supervised review and two Oral Defence tasks. No signal in this market report or the skill-shift table (§4) calls for additional inquiry-related change. | 8 |
| **Adaptive capabilities** | **Adaptive** | **9 / 15** | **6** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | The same registration requirement CI-1 (§5) names (§3 Themes 2, 3, 5) makes professional accountability for sign-off a conduct matter, not only a technical one. W1's next anchor calls for a recognised professional genre or an audience beyond the teaching team judged against practice criteria, which the capstone's two Oral Defence tasks do not yet document as reaching. | 3 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | Signal 1 (§2) records sustained civil-engineering employer demand (3,668 postings, 2025-08-01 to 2026-08-27) with consulting employers named including Aurecon, Stantec, AtkinsRealis and KBR — evidence that host placements at a practitioner-supervised standard are available for the existing 0-unit ENG3100 internship shell to draw on. | 4 |
| W2 Authentic task design | Workplace | 2 / 3 | 1 | The skill-shift table (§4) records 'compliance' as a rising recurring keyword in the same 3,668-posting civil-engineer sample as 'design' and 'sustainability' (§2 Signal 1). The program's own code-compliance constraints (AS3600, AS4100, the Australian Rainfall and Runoff guidelines) already carry the genuine-constraint-of-practice feature at Level III and IV; the market's compliance signal is a reason to document that same feature earlier in the spine, not to add a new task. | 7 |
| **Workplace practice** | **Workplace** | **4 / 9** | **5** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Move the existing Construction Materials Peer Review (worth 30%) into a core Level III unit — for example attaching an equivalent criterion-referenced peer-critique rubric to an assessed task in Research Methods and Project Management — an option since CI-1 (§5) reads the 6 March 2025 registration requirement (§3 Themes 2, 3, 5) as making a named human answerable for engineering work, which starts with being able to appraise a design or calculation against a standard (cost: a rubric adaptation and a core-unit assessment-weighting change; no new unit). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Add a reliance-and-override log to a core design task — for example requiring students to record and defend where they accepted or overrode a commercial structural-analysis software output in Computer Analysis of Structures or Reinforced Concrete Design — an option since CI-1 (§5) frames sign-off accountability as the standard a registered engineer must meet whatever tool produced the work (cost: a new assessed component layered on an existing task; depends on the C2:2 step). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Extend the existing commercial structural-analysis software content in a core unit (for example Computer Analysis of Structures) to require discussion and assessment of that software's limitations, not only its operation, an option since CI-2 (§5) notes accreditation already passes the gate but does not settle whether a graduate can supervise generated work (cost: a content and assessment-criteria update inside an existing unit). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Add an assessed verification task requiring students to identify what would falsify a computational or generated design output before accepting it, an option since CI-2 (§5) names exactly this — verification of a computational or generated design output, including what would falsify it — as the unmet governance question behind the program's existing accreditation (cost: a new assessed component; depends on the C3:2 step). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Reframe one of the two capstone Oral Defence tasks in ENG 4002A/B as a defence to an external or industry-practitioner panel rather than the teaching team alone, an option since CI-1 (§5) ties the March 2025 state-registration rollout (§3 Themes 2, 3, 5) to a named human being answerable for engineering work, an accountability a practitioner-judged defence would start to evidence (cost: scheduling an external or alumnus panel; no change to the assessed deliverable). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Add professional-conduct and accountability criteria to the capstone panel assessment introduced at the prior step, and extend at least one further core assessment earlier in the program (for example a Level III design report) to a practitioner-judged or client-facing format, an option since CI-1's registration-driven accountability (§3 Themes 2, 3, 5; §5 CI-1) applies across a graduate's career, not only at the capstone (cost: a second practitioner-panel booking and a rubric addition; depends on the W1:2 step). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Convert the existing 0-unit ENG 3100 Engineering Internship shell into an assessed, credit-bearing core requirement with documented practitioner supervision, drawing on the sustained civil-engineering employer demand Signal 1 (§2) records (3,668 postings; consulting employers named include Aurecon, Stantec and KBR) as evidence that host placements are available, an option consistent with [29] on the professional-identity value of supervised practice rather than any employment-rate claim (cost: a credit-point and enrolment-rule change plus a placement-coordination function; [28] found WIL does not raise employment rates, so that is not the justification offered). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the assessed placement introduced at the prior step into a required sequence of two supervised placements with structured reflection and accountability to the host, an option since Signal 1's sustained employer demand (§2) suggests capacity for more than one placement window, justified again by skill development and professional identity [29] rather than employment-rate gains [28], and any expansion should account for the equity cost of unpaid or relocation-dependent placement [30] (cost: a second placement slot and expanded coordination capacity; depends on the W3:2 step). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Add a documented role-and-tool allocation requirement to the capstone group project (ENG 4002A/B) or the Computer Analysis of Structures group-programming task, requiring students to record how work was divided between team members and the commercial analysis software or code they used, an option since Signal 1 (§2) names 'cad' among the recurring skill keywords in the 3,668-posting civil-engineer sample and Theme 6 (§3) records design and engineering professionals among the most AI-exposed occupational groups nationally (cost: an assessed documentation requirement added to an existing group task). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Add an assessed knowledge-gap and learning-plan component to the Honours Research Project, requiring students to identify what they do not yet know relative to their chosen topic and a plan to close it, an option since CI-3 (§5) names exactly this — transfer of an established method to an unfamiliar problem — as the part of AI-exposure scoring (§3 Theme 6) that task-level automation measures do not reach (cost: an added assessed component in the existing project; the supervisor-scoped topic list stays as is). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Extend the documented code-compliance constraint already used at Level III and IV (AS3600, AS4100, the Australian Rainfall and Runoff guidelines) to the earlier Level II Structural Mechanics computer-analysis assignment, so a genuine constraint of practice is evidenced at every stage of the spine rather than only its later stages, an option since 'compliance' is a rising recurring keyword in the 3,668-posting civil-engineer sample alongside 'design' and 'sustainability' (§4 skill-shift table; §2 Signal 1) (cost: a criterion added to an existing assignment brief; no new task). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| P1 | C2 | From 6 March 2025 professional engineers in prescribed areas must be registered, with state-based registration mandatory or rolling out nationally, making a named human answerable for engineering work whatever produced it. | §3 Themes 2, 3, 5; §5 CI-1 | MEDIUM |
| P2 | C3 | Engineers Australia already accredits the program; what CI-1 names as unsettled is whether a graduate can supervise generated work, which the anchor's capabilities-and-limitations requirement targets. | §3 Theme 1; §5 CI-2 | MEDIUM |
| P3 | W1 | The same phased registration requirement makes professional accountability for sign-off a conduct matter, not only a technical one. | §3 Themes 2, 3, 5; §5 CI-1 | MEDIUM |
| P4 | W3 | Sustained civil-engineering employer demand (3,668 postings) with consulting employers named that could host practitioner-supervised placement. | §2 Signal 1 | MEDIUM |
| P5 | C1 | 'cad' is a recurring skill keyword in the civil-engineer advertisement sample, and design/engineering professionals are named among the most AI-exposed occupational groups. | §2 Signal 1; §3 Theme 6 | MEDIUM |
| P6 | C4 | Design, engineering, science and transport professionals are named among the most AI-exposed occupational groups, scored at task level; CI-3 recommends assessing transfer to an unfamiliar problem as the part that reaches beyond that score. | §3 Theme 6; §5 CI-3 | MEDIUM |
| P7 | W2 | 'compliance' is a rising recurring keyword in the civil-engineer advertisement sample alongside 'design' and 'sustainability'. | §4 Skill shift summary; §2 Signal 1 | MEDIUM |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C2 | Move the existing criterion-referenced peer-review task into a core Level III unit | C2 level 2 (criterion-referenced appraisal of quality) | Low | Term 1; rubric and unit-placement update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P2 | W1 | Reframe one capstone Oral Defence as a defence to an external or industry-practitioner panel | W1 level 2 (recognised professional genre or audience beyond the teaching team) | Low | Term 1; panel scheduling | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P3 | W2 | Extend the documented code-compliance constraint to the earlier Level II computer-analysis assignment | W2 level 3 (spine-wide, with a genuine constraint of practice) | Low-Medium | Term 1-2; assignment-brief update | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P4 | C3 | Extend existing structural-analysis software content to cover its limitations, discussed and assessed | C3 level 2 (capabilities and limitations discussed and assessed) | Medium | Term 2; curriculum update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P5 | C1 | Require documented role-and-tool allocation in the capstone group project | C1 level 3 (coordination across people and tools/AI systems) | Medium | Term 2; subject update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P6 | C4 | Add an assessed knowledge-gap and learning-plan component to the Honours Research Project | C4 level 3 (structured progression toward independent learning) | Medium | Term 2; capstone update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P7 | W3 | Convert the 0-unit internship shell into an assessed, supervised, credit-bearing placement | W3 level 2 (real workplace setting with practitioner supervision and assessment) | Medium-High | Next course review; enrolment-rule and credit update | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P8 | C2 | Add a reliance-and-override log to a core design task | C2 level 3 (reliance/override justification) | Medium-High | Next course review; assessment-brief update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P9 | C3 | Add an assessed verification task naming what would falsify a generated design output | C3 level 3 (governance of AI/computation beyond tool operation) | High | Next course review; subject update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P10 | W1 | Add practitioner-panel conduct criteria and extend a second core assessment to a practitioner-judged format | W1 level 3 (repeated, progressive, real external audience, conduct assessed) | High | Next course review; two-unit rubric update | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P11 | W3 | Extend the assessed placement into a required sequence of two supervised placements | W3 level 3 (substantial required work-situated learning) | High | Next course review; capstone-structure update | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | PASS on the anchor's all-compulsory specialist core and accredited sequence, with progressive technical depth. The core is 66 units of named civil engineering courses compulsory at each of Levels I to IV, the program is accredited by Engineers Australia with graduates qualifying for professional membership, and depth is staged - Structural Mechanics precedes Reinforced Concrete Design and Structural Steel Design, and Civil Engineering Hydraulics precedes Advanced Civil Engineering Hydraulics. Content is disciplinary, not interchangeable. | Redesign must preserve the all-compulsory, Engineers-Australia-accredited civil engineering core and its staged prerequisite depth (Structural Mechanics before Reinforced Concrete Design and Structural Steel Design; Civil Engineering Hydraulics before Advanced Civil Engineering Hydraulics); added appraisal, AI-governance, communication or placement assessment should sit inside or alongside existing core units, not displace specialist content. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | PASS on the anchor's capstone-with-real-uncertainty route and its defended trade-off route. The required capstone assesses engineering solutions to complex, open ended problems through reports and two oral defences, and the Level III core Reinforced Concrete Design assesses design decisions informed by environmental impact through a 40% Design Project - a defended trade-off rather than recall. Recognising uncertainty and the limits of engineering approaches is an explicit outcome of the Level II core hydraulics course. | Redesign must preserve the capstone's assessment of open-ended, uncertain engineering problems through report and oral defence, and the Reinforced Concrete Design course's defended environmental trade-off; added reliance-log, governance, panel-defence or knowledge-gap tasks should sit alongside that defended decision-making, not substitute a scripted exercise for it. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C2 | 1 | 2 | +1 adaptive | 10 / 15 | 4 / 9 |
| P2 | C2 | 2 | 3 | +1 adaptive | 11 / 15 | 4 / 9 |
| P3 | C3 | 1 | 2 | +1 adaptive | 12 / 15 | 4 / 9 |
| P4 | C3 | 2 | 3 | +1 adaptive | 13 / 15 | 4 / 9 |
| P5 | W1 | 1 | 2 | +1 workplace | 13 / 15 | 5 / 9 |
| P6 | W1 | 2 | 3 | +1 workplace | 13 / 15 | 6 / 9 |
| P7 | W3 | 1 | 2 | +1 workplace | 13 / 15 | 7 / 9 |
| P8 | W3 | 2 | 3 | +1 workplace | 13 / 15 | 8 / 9 |
| P9 | C1 | 2 | 3 | +1 adaptive | 14 / 15 | 8 / 9 |
| P10 | C4 | 2 | 3 | +1 adaptive | 15 / 15 | 8 / 9 |
| P11 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
