// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Mechatronics Engineering (MC-MTRNENG) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Mechatronics Engineering (MC-MTRNENG)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-30 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-mtrneng.md
**Position basis:** Destination AI Exposure 83.23 (exact basis) × Curriculum Adaptiveness 8/15 (v4.2 draft, sub-scale A) · Workplace practice 4/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

This program clears both regression gates and reaches level 2 on four of eight items, but the highest-volume destination family, Engineers, All Other, carries a high-augmentation, low-automation AI profile (Theme 2, §3) that widens the digital and AI literacy gap (C3) and strengthens the case for level-3 human-AI collaboration work (C1) and reliance-judgement work (C2). State-based professional-engineer registration, now mandatory or rolling out across several jurisdictions (Theme 3, Theme 4, §3), and the Computer Systems Analysts destination family's binding professional-conduct code (Theme 6, §3) both point the same way: toward work-situated learning (W3) and professional-genre communication (W1) that the extract currently documents only as optional, not core.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | Theme 6 (§3) records that the ACS Code of Professional Conduct binds ICT practitioners, including systems and business analysts, to competence and public-interest obligations in the design and oversight of systems, while Theme 5 (§3) records that software and systems-analysis roles carry no AI-specific statutory duty beyond existing, technology-neutral law. Digital and AI literacy that extends to governance, not only tool operation, is what the professional-conduct code already requires of this destination family. | 1 |
| C5 Inquiry & evidence generation | Adaptive | 1 / 3 | 2 | Theme 2 (§3) draws on Jobs and Skills Australia-derived occupational exposure analysis for "Other Engineering Professionals" — the same kind of applied, data-driven evidence work this item scores. A program sending graduates into that family in volume (Signal 1, §2, this program's largest destination) benefits from training in that primary-evidence method, not only its consumption. | 2 |
| C1 Distributed cognition & relational capability | Adaptive | 2 / 3 | 1 | Stakeholder-facing collaboration recurs as an advertisement keyword in both this program's largest destination family, Engineers, All Other (Signal 1, §2), and Computer Systems Analysts, where "Stakeholder engagement" is named alongside AI-tooling literacy among the family's recurring skills (Signal 3, §2) — cross-family evidence that employers want people coordinating work with AI tools together, not people working alone. | 5 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 2 / 3 | 1 | Computer Systems Analysts postings name AI-tooling literacy among the family's recurring skills (Signal 3, §2), and Engineers, All Other, this program's largest destination, carries a high-augmentation AI profile (Theme 2, §3): both point to graduates needing to judge and justify their reliance on AI-assisted output, not only produce it. | 6 |
| C4 Life-long learning & transfer | Adaptive | 2 / 3 | 1 | The Tech Council of Australia's 2026 update, cited under Signal 3 (§2), finds software-engineer job-advertisement volumes roughly halved between 2022 and 2025 while the share of employers expecting prior experience rose from 70% to 85% — a market moving toward candidates who can demonstrate self-directed skill development, not only completed coursework. | 7 |
| **Adaptive capabilities** | **Adaptive** | **8 / 15** | **7** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Theme 6 (§3) records that the ACS Code of Professional Conduct requires honesty and primacy of the public interest from ICT practitioners including systems and business analysts, and Theme 5 (§3) confirms no AI-specific statutory obligation currently overrides it. Theme 3 and Theme 4 (§3) add that professional engineers face mandatory or rolling-out state registration and a national credentialling register, both administered against declared conduct and competency standards. Two of this program's destination families are bound to conduct standards judged by a real professional body, not only the teaching team. | 3 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | State-based registration of professional engineers is now mandatory or rolling out in several jurisdictions (Theme 3, §3), and Engineers Australia's National Engineering Register frames registration as a national credentialling pathway with progressive requirements (Theme 4, §3). The supervised, assessed practice this item's level-2 and level-3 anchors describe is the same practice those registration pathways rest on. | 4 |
| W2 Authentic task design | Workplace | 2 / 3 | 1 | Design, CAD and commissioning recur as advertisement keywords for both Engineers, All Other (Signal 1, §2, this program's largest destination) and Electronics Engineers, Except Computer (Signal 5, §2) — the practitioner artefact and process this item's level-3 anchor asks the assessment spine to keep reproducing. | 8 |
| **Workplace practice** | **Workplace** | **4 / 9** | **5** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Add an assessed component to the existing core AI/machine-learning unit covering AI limitations, ethics, bias and societal impact alongside its current technical/operational content, closing the anchor's gap between tool operation and "limits discussed and assessed" [1][3]. Market warrant: the high-augmentation profile recorded for this program's largest destination family (Theme 2, §3) and the professional-conduct duty recorded for its Computer Systems Analysts destination (Theme 6, §3) both weigh toward graduates who understand AI's limits, not only its operation. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Extend that assessment to require critique or governance analysis of an AI system in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond describing how the tool works [1][11][12][13]. Market warrant: Theme 5 (§3) records that software and systems-analysis roles currently rely on existing, technology-neutral law rather than AI-specific statute, and Theme 6 (§3) records the ACS Code's own governance and public-interest obligations — governance literacy, not tool operation, is what the destination profession asks for. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 1 → 2 | "Students design and conduct an inquiry with methodology selection and data collection, assessed." | Give the primary-evidence research project, currently a Group B elective, a required equivalent inside the core sequence, with methodology selection and data collection assessed [14][15][7]. Market warrant: Theme 2 (§3) shows the destination profession itself relies on applied, occupation-level exposure analysis, the kind of evidence-generation work this anchor asks the program to teach, for the family this program sends its largest cohort into (Signal 1, §2). | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make that primary-evidence project a required route rather than one option among several, with methodology defended under scrutiny — a viva, panel defence or staged supervised review [14][15][7]. Market warrant: as the level-2 step, extended to make the route mandatory rather than optional, matching the anchor's requirement that it be "REQUIRED (not one route among several)". | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Add a core assessment task judged against a professional genre or an audience beyond the teaching team — a client brief, consultancy memo or public-facing artefact — building on the existing interactive-discussion and demonstration components [19][31]. Market warrant: Theme 6 (§3) records the ACS Code of Professional Conduct binding systems and business analysts to public-interest and competence standards judged by a professional body, not only a marker. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Make professional-communication assessment recur across at least two program stages and add one core assessment judged by a real external audience or practitioner — an industry panel, client or public exhibition — with professional conduct explicitly among the criteria [19][20][31][32]. Market warrant: Theme 3 and Theme 4 (§3) record mandatory or rolling-out state registration and Engineers Australia's National Engineering Register, both assessed against declared conduct and competency standards by a body outside the university. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Convert one of the existing optional routes — the employability program, the internship elective, or the unassessed self-arranged internship — into a required core placement, practicum or live-client project with practitioner supervision and assessment [19][27]. Market warrant: state-based registration of professional engineers is now mandatory or rolling out (Theme 3, §3), and supervised practical experience is the substance those registration pathways assess. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend that core placement into a required sequence, either one extended placement or repeated shorter ones, supervised by a practitioner, assessed, with structured reflection and accountability to the host [19][27][29]. Justify by skill development, employment relevance and professional identity, not employment-rate claims [29], and weigh the equity cost of unpaid or relocation-dependent placements before committing [28][30]. Market warrant: Engineers Australia's National Engineering Register (Theme 4, §3) frames registration as a progressive national credentialling pathway, and state-based registration is mandatory or rolling out in several jurisdictions (Theme 3, §3), both resting on demonstrated, supervised practice. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Add a documented role-and-tool allocation requirement to the capstone team assessment, so the division of work between team members and AI/tool systems is itself assessed, not only team collaboration [1][5][7]. Market warrant: stakeholder-facing collaboration recurs as a keyword in both the Engineers, All Other (Signal 1, §2) and Computer Systems Analysts (Signal 3, §2) advertisement samples, evidence that coordinating people and tools together is what employers ask for. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Extend the existing project log and final reflection to require students to document and justify a specific reliance decision — a point where they relied on, overrode or checked an AI tool, source or collaborator — rather than a general reflection [1][3][4]. Market warrant: Computer Systems Analysts postings name AI-tooling literacy among the family's recurring skills (Signal 3, §2), and Engineers, All Other carries a high-augmentation AI profile (Theme 2, §3); both destination families need graduates who can account for how they used AI assistance, not only that they used it. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Add a self-scoping component to the capstone: students identify their own knowledge gaps against the capstone brief and document a plan to close them, assessed alongside the existing design and research work [1][9][10]. Market warrant: the Tech Council of Australia's 2026 update (Signal 3, §2) records rising employer expectations of demonstrated experience even as related technical-role postings contract, favouring graduates who can show structured, self-directed progression. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Confirm the capstone carries a genuine constraint of practice — an externally supplied problem, a real resource or time limit, or a professional standard of performance — so the authentic-task spine already established earlier in the program continues into the final stage rather than stopping short of it [22][23][24][25]. Market warrant: design, CAD and commissioning recur as advertisement keywords across the Engineers, All Other and Electronics Engineers, Except Computer destination families (Signal 1, Signal 5, §2), the practitioner artefacts the capstone should keep producing. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| AI-augmented engineering work | C3 | High-augmentation, low-automation AI profile recorded for Engineers, All Other, this program's largest destination family. | §3, Theme 2 | HIGH |
| Professional-conduct code for ICT and analyst work | C3, W1 | ACS Code of Professional Conduct binds ICT practitioners, including systems and business analysts, to competence and public-interest obligations. | §3, Theme 6 | HIGH |
| State-based professional-engineer registration | W3, W1 | Mandatory or rolling-out state registration for professional engineers across several jurisdictions, plus Engineers Australia's National Engineering Register. | §3, Theme 3 and Theme 4 | HIGH |
| Design and CAD practitioner-artefact demand | W2 | Design, CAD and commissioning recur as advertisement keywords for Engineers, All Other and Electronics Engineers, Except Computer. | §2, Signal 1 and Signal 5 | HIGH (Engineers, All Other) / MEDIUM (Electronics Engineers, Except Computer) |
| Stakeholder-facing collaboration and AI-tooling literacy | C1, C2 | "stakeholder" recurs in the Engineers, All Other sample, and "Stakeholder engagement" and "AI-tooling literacy" recur in the Computer Systems Analysts sample. | §2, Signal 1 and Signal 3 | HIGH |
| Rising experience expectations in adjacent technical roles | C4 | Tech Council of Australia 2026 update: software-engineer advertisement volume roughly halved 2022 to 2025 while the share of employers expecting prior experience rose from 70% to 85%. | §2, Signal 3 | HIGH |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C2 | Extend the existing project log and reflection to require documenting and justifying one specific AI-reliance decision, rather than general reflection. | Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment). | low | Term 1 — criteria and prompt change to an existing assessed task | [1][3][4] |
| P2 | C3 | Add assessed coverage of AI limitations, ethics, bias and societal impact to the existing core AI/machine-learning unit. | Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed. | medium | Term 1-2 — new assessed component within an existing unit | [1][3] |
| P3 | W1 | Add a core assessment task judged against a professional genre or an audience beyond the teaching team — a client brief, consultancy memo or public-facing artefact. | At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice. | medium | Term 1-2 — new assessed component within an existing unit | [19][31] |
| P4 | C1 | Add a documented role-and-tool allocation requirement to the capstone team assessment. | Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed. | medium | Term 1-2 — new assessed component within an existing unit | [1][5][7] |
| P5 | C4 | Add a self-scoping component to the capstone: identify knowledge gaps against the brief and document a plan to close them. | The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them. | medium | Term 1-2 — new assessed component within an existing unit | [1][9][10] |
| P6 | W2 | Confirm the capstone carries a genuine constraint of practice so the authentic-task spine continues into the final stage. | Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance. | medium | Term 1-2 — confirmation and, if needed, addition to an existing unit | [22][23][24][25] |
| P7 | C3 | Extend the AI/machine-learning unit's assessment to require critique or governance analysis of an AI system in the discipline's own context. | Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation. | high | Curriculum review cycle — builds on the C3:2 step | [1][11][12][13] |
| P8 | W1 | Make professional-communication assessment recur across at least two program stages, with one core assessment judged by a real external audience or practitioner. | Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria. | high | Curriculum review cycle — builds on the W1:2 step and needs an external panel or partner | [19][20][31][32] |
| P9 | C5 | Give the primary-evidence research project a required core equivalent, with methodology selection and data collection assessed. | Students design and conduct an inquiry with methodology selection and data collection, assessed. | high | Curriculum review cycle — moves an elective's substance into the core | [14][15][7] |
| P10 | C5 | Make the primary-evidence project a required route with methodology defended under scrutiny. | A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review). | high | Curriculum review cycle — builds on the C5:2 step | [14][15][7] |
| P11 | W3 | Convert one of the existing optional placement or internship routes into a required core placement, practicum or live-client project with practitioner supervision. | A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone. | high | Curriculum review cycle — structural change to a required route | [19][27] |
| P12 | W3 | Extend the core placement into a required sequence, supervised, assessed, with structured reflection and accountability to the host. | Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer). | high | Curriculum review cycle — builds on the W3:2 step | [19][27][29] |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | PASS: the program documents a coherent, accredited specialist core with progressive structure - 225 of 300 credit points are compulsory, arranged in a staged Year 1 to Year 2 to Year 3 sequence with noted prerequisite/requisite dependencies between Years 2 and 3, and the course carries Engineers Australia and EURACE professional accreditation. This matches the anchor's 'accredited sequence' and 'staged prerequisite chain' clauses. | Keep the specialist core's compulsory proportion and staged Year 1 to Year 2 to Year 3 prerequisite chain intact, and keep the Engineers Australia and EURACE accreditation requirements satisfied, when adding new assessed AI-literacy, evidence-generation or work-situated content — do not displace core technical content to make room. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | PASS: ENGR90051 requires students to 'justify design decisions' and weigh stakeholder, sustainability, safety, feasibility and ethical trade-offs on a real-world project across multiple assessed components (review, demonstration, final submission) - defended trade-off decisions under real constraints, matching the anchor. This is reinforced by MCEN30021's assessed design-with-hurdle project work, which similarly requires reasoned engineering requirements and physical demonstration/defence of design choices. | Keep the defended-trade-off component in any redesigned unit — a new AI-governance or reflection task must sit alongside the existing justify-design-decisions work in units such as the capstone and the design-with-hurdle project, not replace it with a scripted or purely computational task. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C3 | 1 | 2 | +1 adaptive | 9 / 15 | 4 / 9 |
| P2 | C3 | 2 | 3 | +1 adaptive | 10 / 15 | 4 / 9 |
| P3 | C5 | 1 | 2 | +1 adaptive | 11 / 15 | 4 / 9 |
| P4 | C5 | 2 | 3 | +1 adaptive | 12 / 15 | 4 / 9 |
| P5 | W1 | 1 | 2 | +1 workplace | 12 / 15 | 5 / 9 |
| P6 | W1 | 2 | 3 | +1 workplace | 12 / 15 | 6 / 9 |
| P7 | W3 | 1 | 2 | +1 workplace | 12 / 15 | 7 / 9 |
| P8 | W3 | 2 | 3 | +1 workplace | 12 / 15 | 8 / 9 |
| P9 | C1 | 2 | 3 | +1 adaptive | 13 / 15 | 8 / 9 |
| P10 | C2 | 2 | 3 | +1 adaptive | 14 / 15 | 8 / 9 |
| P11 | C4 | 2 | 3 | +1 adaptive | 15 / 15 | 8 / 9 |
| P12 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
