// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Agricultural Sciences (MC-AGSC) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Agricultural Sciences (MC-AGSC)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-29 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-agsc.md
**Position basis:** Destination AI Exposure 73.00 (field basis) × Curriculum Adaptiveness 6/15 (v4.2 draft, sub-scale A) · Workplace practice 6/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a field basis (Jobs and Skills Australia Higher Education Outcomes (JSA HEO) field 050101 Agricultural Science), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

Panel C v4 scores this program 6/15 on Curriculum Adaptiveness and 6/9 on Workplace practice. Gate G1 (Disciplinary foundation) FAILs — the extract does not document the program's actual Degree Core/Selective and Specialisation subject lists, only the choice of one specialisation among five named options — and gate G2 (Decision-making under uncertainty) PASSes on the internship's host-supervised placement and the research project's supervised original investigation. C3 sits at Level 0, the largest single gap; C1 and C2 sit at Level 1; C4, C5, W1, W2 and W3 sit at Level 2, one step short of the maximum on each.

The market report names five job families this program's own destination titles map to. Advertisement signals show the largest single-family volume in Environmental Scientists (Signal 2, 1,167 postings) inside an active reform cycle for the Act that family works under (Theme 3), sustained demand in Agricultural, Plant, and Horticultural Scientists for field, research and crop skills (Signal 1, 223 postings), and analytical, data-driven demand in Animal Scientists (Signal 3, 96 postings) alongside GMO and biosecurity compliance obligations (Themes 5, 6). Management Analysts recurs among the program's own destination titles with generalist collaboration and communication keywords (Signal 4, 169 postings), and the Jobs and Skills Australia Generative AI Capacity Study places this program's professional-level destinations in the highest augmentation band nationally (Theme 4). Each intervention below targets one of these named gaps at its item's next anchor level.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | Adaptive | 0 / 3 | 3 | Theme 4 (§3) reports that augmentation, not automation, dominates for professionals and managers nationally — the skill level this program's Agricultural, Environmental and Animal Scientist destinations sit at — evidencing a governance and AI-literacy gap the program's currently absent AI content leaves open. | 1 |
| C1 Distributed cognition & relational capability | Adaptive | 1 / 3 | 2 | Signal 4 (§2, Management Analysts, 169 postings) carries Communication Skills, Change Management, Stakeholder Management and Project Management as its top recurring advertisement keywords, evidencing employer demand for coordinated, accountable teamwork beyond the outcomes-only level the program currently assesses. | 2 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | Signal 3 (§2, Animal Scientists, 96 postings) recurs on data, genetics and research as advertisement keywords, and Theme 4 (§3) reports professionals face the highest AI-augmentation exposure nationally — both put a premium on defensible evaluative judgement the program does not yet assess against criteria. | 3 |
| C4 Life-long learning & transfer | Adaptive | 2 / 3 | 1 | Theme 3 (§3) records an active reform cycle for the Environmental Scientists job family's governing Act — new National Environmental Standards and a new federal EPA — for the program's largest single destination by advertisement volume (Signal 2, §2, 1,167 postings), evidencing a transfer-and-update capability the program's current novel-problem assessment does not yet extend to independent, self-scoped learning. | 4 |
| C5 Inquiry & evidence generation | Adaptive | 2 / 3 | 1 | Signal 1 (§2, Agricultural, Plant, and Horticultural Scientists, 223 postings) recurs on research, science and crop as advertisement keywords, evidencing employer demand for the kind of rigorous, primary-evidence inquiry the Research Project currently offers as only one of three capstone routes. | 5 |
| **Adaptive capabilities** | **Adaptive** | **6 / 15** | **9** | — | — |
| W1 Professional communication & conduct | Workplace | 2 / 3 | 1 | Theme 1 (§3) records the Ag Institute Australia's Certified Practising Agriculturalist accreditation scheme, and Themes 5 and 6 (§3) place documented compliance obligations on animal scientists working with genetically modified organisms or imported biologicals — both point to professional-conduct expectations beyond the single, non-recurring professional-audience assessment the program currently offers. | 6 |
| W2 Authentic task design | Workplace | 2 / 3 | 1 | Signal 2 (§2, Environmental Scientists, 1,167 postings) recurs on assessment, environmental impact, compliance, remediation and monitoring as advertisement keywords, and Theme 3 (§3) describes the referrals and field-assessment reports the EPBC Act reform depends on — both evidence demand for a practitioner-grade artefact as the assessment spine, not a single capstone option. | 7 |
| W3 Work-situated learning | Workplace | 2 / 3 | 1 | The field keyword recurs in both the Agricultural, Plant, and Horticultural Scientists sample (Signal 1, §2, 223 postings) and the Environmental Scientists sample (Signal 2, §2, 1,167 postings), evidencing sustained employer demand for hands-on, field-situated practice beyond the single capstone-option placement the program currently offers. | 8 |
| **Workplace practice** | **Workplace** | **6 / 9** | **3** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | 0 → 1 | "AI or digital tools appear only as electives or as tool operation/training — the operational level TEQSA identifies as non-durable." | Option: add AI/digital-tool content as an elective, or as tool-operation training within a core unit, matching Theme 4's (§3) finding that professionals and managers — the skill level this program's science destinations sit at — see the highest AI augmentation exposure nationally (cost: one new or repurposed elective, or a tool-training module within an existing core unit). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Option: extend that core content so it addresses AI capabilities AND limitations/ethics, with use-with-limits discussed and assessed, closing the tool-operation-only gap Theme 4 (§3) leaves open (cost: curriculum-hours reallocation and staff development in AI-ethics content). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Option: add a core assessment requiring critique or governance of AI systems in the agricultural, environmental or animal-science context — bias, accountability, transparency or data governance — beyond tool operation, matching Theme 4's (§3) augmentation finding for this program's destinations (cost: case-study development and assessment-criteria design for governance judgement). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Option: add an assessed group project with individual accountability, or client/stakeholder-facing work, to one core subject, matching the Communication Skills, Change Management, Stakeholder Management and Project Management keywords recurring in the Management Analysts advertisement sample (Signal 4, §2, 169 postings) (cost: new assessment task and marking criteria for individual accountability within a group mark). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Option: extend that assessed collaborative practice, or a capstone, so the division of work between students and AI tools is itself documented and assessed, recurring across the program rather than once, still answering Signal 4's (§2) stakeholder-coordination demand (cost: capstone redesign plus a documented role/tool-allocation rubric). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Option: add a criterion-referenced peer-review or structured-critique task to one core subject, responding to the data, genetics and research keywords recurring in the Animal Scientists advertisement sample (Signal 3, §2, 96 postings) (cost: exemplar development and calibration/moderation time). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Option: require students to document and justify a reliance decision — when they relied on or overrode an AI tool's output — in one core assessment, extending that same analytical-judgement demand and Theme 4's (§3) augmentation finding (cost: rubric design for defensible-judgement marking and additional marking load). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Option: add a self-scoped capstone or a documented knowledge-gap plan to the program's structured progression, matching the ongoing regulatory reform Theme 3 (§3) records for the Environmental Scientists job family — the program's largest single destination by advertisement volume (Signal 2, §2, 1,167 postings) (cost: capstone redesign and individualised supervision). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Option: make the Research Project the required capstone route rather than one of three options, with methodology defended under staged review, matching the research and science keywords recurring in the Agricultural, Plant, and Horticultural Scientists advertisement sample (Signal 1, §2, 223 postings) (cost: removing the other two capstone options, or expanded supervision capacity to make the research route universal). | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Option: have one core assessment delivered to, or judged by, an external practitioner panel with conduct or accountability explicitly marked, matching the Ag Institute Australia accreditation scheme (Theme 1, §3) and the documentation and biosafety-committee obligations Themes 5 and 6 (§3) place on graduates working with GMOs or biologicals (cost: sourcing and briefing panel members each offering). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Option: make the internship's professional portfolio and the research project's stakeholder mini-symposium the program's assessment spine rather than single capstone options, with at least one carrying a genuine constraint of practice such as ambiguous field conditions or a consequential regulatory audience, matching the assessment, environmental-impact and compliance keywords recurring in the Environmental Scientists advertisement sample (Signal 2, §2, 1,167 postings) and the EPBC Act reform cycle (Theme 3, §3) (cost: sequenced redesign across multiple core subjects). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Option: build a required sequence of supervised, assessed placement in the core with structured reflection and accountability to the host, rather than one of three capstone options, matching the field keyword recurring across both the Agricultural, Plant, and Horticultural Scientists sample (Signal 1, §2, 223 postings) and the Environmental Scientists sample (Signal 2, §2, 1,167 postings) (cost: sustained placement-partner capacity and supervision funding — justified by skill development and professional identity, not by an employment-rate claim, since WIL does not raise employment rates [28]). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| Field-based inquiry and work-situated practice | C5, W3 | Field, research and crop recur as advertisement keywords for Agricultural, Plant, and Horticultural Scientists, and field recurs again for Environmental Scientists. | §2 Signal 1, Signal 2 | HIGH (Agricultural, Plant, and Horticultural Scientists — job-advertisement signals; Environmental Scientists and Specialists, Including Health — job-advertisement signals) |
| Regulatory-reform transfer capability | C4 | The EPBC Act, the Act environmental scientists work under, is being reformed through 2026 (new National Environmental Standards; a new federal EPA). | §3 Theme 3 | HIGH (Environmental Scientists and Specialists, Including Health — regulatory and statutory instruments) |
| AI governance and evaluative judgement | C2, C3 | Jobs and Skills Australia's Generative AI Capacity Study places professionals and managers, the skill level this program's destinations sit at, in the highest augmentation category nationally. | §3 Theme 4 | HIGH (Environmental Scientists and Specialists, Including Health — scholarly and grey-literature studies) |
| Stakeholder-coordinated teamwork | C1 | Communication Skills, Change Management, Stakeholder Management and Project Management recur as advertisement keywords for Management Analysts, a job family recurring among this program's own destination titles. | §2 Signal 4 | MEDIUM (Management Analysts — job-advertisement signals) |
| GMO and biosecurity compliance conduct | W1 | Animal scientists working with genetically modified organisms or imported biologicals must comply with the Gene Technology Act 2000 and the Biosecurity Act 2015, administered through institutional biosafety and animal-ethics committees. | §3 Theme 5, Theme 6 | HIGH (Animal Scientists — regulatory and statutory instruments) |
| Practitioner-grade environmental assessment artefact | W2 | Assessment, environmental impact, compliance, remediation and monitoring recur as advertisement keywords for Environmental Scientists, the program's largest single destination family by advertisement volume. | §2 Signal 2 | HIGH (Environmental Scientists and Specialists, Including Health — job-advertisement signals) |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C3 | Introduce AI/digital-tool content as an elective, or as tool-operation training within a core unit. | AI or digital tools appear only as electives or as tool operation/training — the operational level TEQSA identifies as non-durable. | low | Term 1 (documentation) | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P2 | C1 | Add an assessed group project with individual accountability, or client/stakeholder-facing work, to one core subject. | At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity. | medium | Term 2 (pilot assessment) | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P3 | C2 | Add a criterion-referenced peer-review or structured-critique task to one core subject. | Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars. | medium | Term 2 (pilot assessment) | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P4 | C4 | Add a self-scoped capstone or a documented knowledge-gap plan to the program's structured progression. | The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them. | high | Term 3 (assessment redesign) | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P5 | C5 | Make the Research Project the required capstone route, with methodology defended under staged review. | A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review). | high | Term 3 (assessment redesign) | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P6 | W1 | Have one core assessment delivered to, or judged by, an external practitioner panel with conduct or accountability explicitly marked. | Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria. | medium | Term 2 (pilot assessment) | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P7 | W2 | Make the internship portfolio and research-project mini-symposium the program's assessment spine, with at least one carrying a genuine constraint of practice. | Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance. | high | Term 3 (assessment redesign) | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P8 | W3 | Build a required sequence of supervised, assessed placement in the core with structured reflection and accountability to the host. | Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer). | high | Term 4 (structural redesign) | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | FAIL | Verification review found PASS unsupported by the extract's own scope. The Course structure page states the actual Degree Core/Selective and Specialisation subject lists were not captured ('Please refer to the relevant Entry Point Program and Specialisation pages for respective Degree Core/Selective and Specialisation subjects'), and the only quoted evidence (one specialisation required; five named specialisations exist) shows breadth of choice, not documented progressive technical or methodological depth, an accredited sequence, or a staged prerequisite chain as G1 requires. The visible Elective subjects table is a flat list of codes/points with no prerequisite chain shown. Insufficient evidence in this extract to support PASS; demoted to FAIL. | Any redesign must first document the program's actual Degree Core/Selective and Specialisation subject lists and their prerequisite structure before this gate can move to PASS; the actions above add or reshape assessment inside existing subjects and specialisations, but none of them supplies the missing course-structure documentation this gate needs. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | The internship's satisfactory-placement hurdle with host-supervisor assessment, and the research project's supervised original experiment/investigation, both involve genuine uncertainty and accountability rather than recall or scripted responses. | Any redesign must keep the internship's host-supervised, satisfactory-placement hurdle and the research project's supervised original experiment or investigation intact; the actions above extend assessment method and add a governance or judgement layer, none of them removes the genuine uncertainty and accountability that carries this gate. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C3 | 0 | 1 | +1 adaptive | 7 / 15 | 6 / 9 |
| P2 | C3 | 1 | 2 | +1 adaptive | 8 / 15 | 6 / 9 |
| P3 | C3 | 2 | 3 | +1 adaptive | 9 / 15 | 6 / 9 |
| P4 | C1 | 1 | 2 | +1 adaptive | 10 / 15 | 6 / 9 |
| P5 | C1 | 2 | 3 | +1 adaptive | 11 / 15 | 6 / 9 |
| P6 | C2 | 1 | 2 | +1 adaptive | 12 / 15 | 6 / 9 |
| P7 | C2 | 2 | 3 | +1 adaptive | 13 / 15 | 6 / 9 |
| P8 | C4 | 2 | 3 | +1 adaptive | 14 / 15 | 6 / 9 |
| P9 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 6 / 9 |
| P10 | W1 | 2 | 3 | +1 workplace | 15 / 15 | 7 / 9 |
| P11 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 8 / 9 |
| P12 | W3 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
