// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Medical Technology Innovation (MC-MTI) — Market Intelligence",
  institution: "University of Melbourne",
  markdown: `# DFVA MARKET INTELLIGENCE: Master of Medical Technology Innovation (MC-MTI)
**Assessment Date:** 2026-09-01 | **Source:** https://handbook.unimelb.edu.au/2026/courses/mc-mti

## 1. JOB FAMILY MAP
| Job Family | Typical Entry Titles | Core Tasks | AI Substitution Pressure | Skills Increasing in Demand | Evidence Notes |
|---|---|---|---|---|---|
| Medical Device Design / R&D Engineer | Biomedical Engineer, Medical Device Engineer, R&D Engineer (MedTech) | Concept development from an identified clinical need, prototyping, design controls, cross-functional development with clinical and regulatory teams | **MEDIUM** — human raters judged roughly a quarter to over half of this occupation's O*NET tasks as directly reducible with GPT-4-class tools, but design judgement and clinical need-screening are not shown to transfer | Needs-discovery methodology, prototyping, cross-disciplinary BioDesign practice | Direct match to the program's own compulsory BioDesign sequence (BMEN90042, BMEN90044) |
| Regulatory Affairs & Quality Specialist (MedTech) | Regulatory Affairs Associate, Quality Assurance Specialist, Device Compliance Officer | Device labelling and traceability compliance, regulatory submission documentation, quality-management-system operation | **MEDIUM** — a named industry op-ed frames AI as removing drafting friction in regulatory documentation, not replacing the regulatory specialist role | AusUDID data-submission workflows, UDI labelling compliance, electronic quality-management systems | Directly tied to a binding 2026-07-01 Therapeutic Goods Administration compliance deadline |
| Clinical / Healthcare Technology Management Engineer | Clinical Engineer, Healthcare Technology Management (HTM) Specialist, Biomedical Equipment Technician | Device maintenance, hospital technology operations, equipment-servicing accountability | **LOW-MEDIUM** — generative AI is reported simulating device behaviour and drafting maintenance protocols, described by practitioners as assisting rather than replacing the servicing role | AI-enabled device analytics, generative-AI-assisted maintenance documentation | The program has no supervised placement in this function (see §3, Theme 3) |
| MedTech Commercialisation & Innovation Manager | Product Manager (MedTech), Innovation Manager, Health Technology Commercialisation Associate | Needs screening, IP strategy, market and reimbursement pathway assessment, business-plan development for a novel device | **LOW** — no sourced study measures AI exposure for this commercialisation-and-strategy function specifically; the closest evidence (regulatory-documentation drafting) covers only one adjacent task | Market-viability assessment, IP strategy, reimbursement-pathway design | This is the program's own compulsory capstone content (BMEN90044): a predetermined health need carried through prototype and business plan |
| Biomedical Data / ML Engineer (adjacent pathway) | Machine Learning Engineer (Biomedical / Preclinical Imaging), Biomedical Data Scientist | Applying AI models within a biomedical technical domain (for example preclinical imaging), rather than being subject to AI substitution | **LOW** (as a destination for AI-literate graduates, not a substitution target) | AI/ML application within a biomedical technical domain | One sourced practitioner account: a BME graduate now working as a senior ML engineer at a preclinical-imaging instrumentation company |

## 2. RECENT JOB AD SIGNALS
> **Confidence: LOW** — no live job-ad platform data exists for this profession record.

1. **No job-ad data was collected.** \`data/professions/039903.json\`'s \`jobAds\` block records \`source: "none"\`, \`count: 0\`, with no employers or skill tags listed. This section cannot state vacancy counts, named employers, or in-demand skill-tag frequencies for biomedical/medical-device engineering roles for the current assessment window (2025-03-01 to 2026-08-31). Treat this whole area as an unfilled gap, not as an estimate. LOW confidence.

2. **The one dated, quantifiable driver in the record is regulatory, not job-ad, data.** Australia's Therapeutic Goods Administration made its Unique Device Identification (UDI) framework legally effective on 2025-03-24, with Class IIb and Class III device sponsors and manufacturers required to meet AusUDID data-submission requirements from **2026-07-01** ([TGA, "New UDI requirements for medical devices commence 1 July 2026"](https://www.tga.gov.au/news/news-articles/new-udi-requirements-medical-devices-commence-1-july-2026)). This is a scheduled compliance deadline, not a measured hiring signal — it says nothing about current vacancy volume for compliance-related roles. LOW-MEDIUM confidence (the date is firm; the hiring-volume inference is not sourced).

3. **The only quantitative labour-adjacent figure in the record is a vendor-commissioned survey, not job-ad data.** MD+DI reported (30 October 2025) that the ETQ Pulse of Quality Manufacturing 2025 Survey found medical device manufacturers citing a **68%** labour-shortage figure, with **47%** of surveyed organisations planning AI implementation within two years ([MD+DI, "Medtech Turns to AI as Labor Crisis & Recalls Surge"](https://www.mddionline.com/manufacturing/medical-device-makers-turn-to-ai-as-labor-crisis-recalls-surge-new-survey-reveals)). This describes medical device manufacturing and quality-management functions broadly (752 quality leaders across three countries), not vacancies for MC-MTI's specific destination titles, and the primary survey instrument was not independently retrieved here. LOW confidence for degree-specific inference.

4. **Close this gap before using the section for planning.** Commission a live job-ad pull (Seek, seek.com.au/Adzuna AU, LinkedIn) against MC-MTI's actual destination titles — Medical Device Design Engineer, Regulatory Affairs Associate (MedTech), Clinical Engineer, Innovation/Product Manager (MedTech) — before this section is used for any hiring-volume or employer claim. See §6.

## 3. CURRENT DISCUSSION SIGNALS — MEDIUM CONFIDENCE

**What these sources are.** A binding regulatory instrument (Australia's Therapeutic Goods Administration), a national professional body's credentialing publication (Engineers Australia), two peer-reviewed occupational-exposure studies with public primary datasets (Felten, Raj and Seamans in *Strategic Management Journal*, 2021; Eloundou, Manning, Mishkin and Rock in *Science*, 2024), medtech trade press (MedCity News, MD+DI/mddionline.com), a healthcare-technology-management trade publication (24x7 Magazine), and one practitioner podcast episode (The BME Grad Podcast). Direct extraction from X or LinkedIn was **not** performed and no professional forum was sampled — "discourse" here means these named regulator, academic and trade-press sources, not a survey of practitioner sentiment. Every claim below is carried forward from \`data/professions/039903.json\`, where it is already marked sourced or scoped; none required correction or removal for this report.

### Theme 1 — a binding compliance deadline is a firmer signal than anything the profession itself has said about hiring

Australia's UDI mandate is not a proposal under discussion — it is a legal amendment to the Therapeutic Goods (Medical Devices) Regulations 2002, legally effective from 2025-03-24, with Class IIb and Class III device sponsors and manufacturers required to meet AusUDID data-submission requirements from **2026-07-01** and lower-risk device classes phased in over subsequent years ([TGA](https://www.tga.gov.au/news/news-articles/new-udi-requirements-medical-devices-commence-1-july-2026); corroborated by [Advena Medical, regulatory-affairs consultancy](https://advenamedical.com/australias-udi-mandatory-deadlines-urgent-action-for-tga-market-access/)). Separately, Engineers Australia's National Engineering Register — the peak professional body's national credentialing scheme applicable to biomedical engineers — remains entirely voluntary, requiring five or more years of relevant full-time-equivalent work experience against five defined competencies, alongside separate statutory registration regimes that exist only in Queensland, Victoria, the ACT and Western Australia ([Engineers Australia, NER](https://www.engineersaustralia.org.au/credentials/registration/national-engineering-register)).

This binds device sponsors and manufacturers on labelling and traceability compliance for regulated products; it says nothing about employer hiring volume, engineer headcount or how the profession itself views the requirement, and the NER detail describes a post-graduation, voluntary credential rather than an entry-level curriculum requirement.

**Bearing:** C4 and W2. Regulatory-pathway evaluation is already a compulsory assessed outcome in BMEN90039 ("evaluate the process and regulations…to market"), but the evidence file does not record UDI/AusUDID-specific content within it.

### Theme 2 — the occupation carries measurable AI task exposure, and the profession's own account frames the result as augmentation rather than replacement

Biomedical/bioengineers sit at roughly the 74th percentile of AI exposure among 774 US occupations on the Felten-Raj-Seamans AI Occupational Exposure index (score 0.987 against a sample median near -0.05) ([*Strategic Management Journal*, 2021](https://sms.onlinelibrary.wiley.com/doi/full/10.1002/smj.3286); [primary AIOE dataset](https://github.com/AIOE-Data/AIOE)). In Eloundou, Manning, Mishkin and Rock's GPT-4 labour-exposure study, human raters judged roughly **26%** of this occupation's O*NET tasks as directly exposed to GPT-4-class language models, rising to about **54%** when tasks completable with LLM-plus-complementary-software are half-weighted and up to about **82%** under the study's most inclusive measure ([*Science*, 2024](https://www.science.org/doi/10.1126/science.adj0998); [primary occupation-level dataset](https://github.com/openai/GPTs-are-GPTs/blob/main/data/occ_level.csv)). A January 2026 MedCity News op-ed by a named J&J MedTech principal engineer argues AI's role across medical-device development is removing workflow friction — from literature review to regulatory documentation — stating explicitly that this "isn't about replacing engineers, regulatory specialists, or clinical teams" and citing a McKinsey estimate of 20-30% effort reduction in regulatory-documentation drafting ([MedCity News, 21 January 2026](https://medcitynews.com/2026/01/how-ai-is-actually-helping-medtech-teams-move-faster-across-every-stage-of-medical-device-development/)).

Both exposure studies use the US O*NET occupation classification, not Australian data, and are not adjusted for the Australian labour market; the Eloundou study predates most 2024-2026 generative-AI capability gains, so it likely understates current exposure. The McKinsey 20-30% figure is a secondary citation inside the MedCity News op-ed, not independently retrieved here, and should be treated as unverified even though the surrounding op-ed is genuine.

**Bearing:** C3. AI/digital-tools content in this program currently sits only among 18 elective options students choose 25 credit points from (COMP90087 The Ethics of Artificial Intelligence, COMP90049 Introduction to Machine Learning) — none of the four compulsory subjects documents AI content — while the sourced task-exposure figures for the destination occupation run from roughly a quarter to over half.

### Theme 3 — documented AI adoption is showing up faster in operational and quality functions than in device-design R&D itself, and the program has no placement in those functions

An October 2025 trade-press year-in-review found healthcare technology management and clinical-engineering leaders describing generative AI simulating device behaviour, generating maintenance protocols and assisting documentation as among 2025's biggest shifts in their operational work ([24x7 Magazine, 30 October 2025](https://24x7mag.com/market-trends/industry-leaders-reflect-htms-biggest-shifts-2025/)). Separately, MD+DI reported the ETQ Pulse of Quality Manufacturing 2025 Survey found medical device manufacturers citing labour shortages (a reported 68% figure) and rising product recalls as drivers for adopting AI and electronic quality-management systems, with 47% of surveyed organisations planning AI implementation within two years ([MD+DI, 30 October 2025](https://www.mddionline.com/manufacturing/medical-device-makers-turn-to-ai-as-labor-crisis-recalls-surge-new-survey-reveals)).

The 24x7 Magazine quotes were solicited by a journalist for a year-in-review roundup, and only 2 of the 4 speakers quoted specifically described generative-AI use — both are vendor and service-company executives in equipment-servicing and hospital-technology operations, not device-design R&D engineers, so this does not support a claim about AI discussion prevalence among design engineers specifically. The ETQ figures describe manufacturing quality-management functions broadly (752 quality leaders across three countries), and the primary survey instrument was not independently retrieved.

**Bearing:** W3. The compulsory subject list (75 of 100 credit points) and the full elective list contain no placement, practicum, internship or community-based-project subject — the clinician engagement documented in BMEN90042/BMEN90044 is coursework informed by external stakeholder input on campus, not supervised participation in a workplace. The two operational functions where this record's sourced material documents real 2025 AI adoption — clinical/healthcare technology management and manufacturing quality — are functions this program gives students no supervised exposure to.

## 4. SKILL SHIFT SUMMARY (DECLINING vs RISING)
| Declining Demand | Velocity | Rising Demand | Velocity |
|---|---|---|---|
| Manual, boilerplate regulatory-documentation drafting (literature review, submission text) | Medium | AI-assisted drafting and review within regulatory-documentation workflows | Fast |
| Generic, standalone "AI-adjacent" job titles (for example AI ethicist, robotic-process-automation engineer) | Medium | AI content absorbed into specific, regulated, clinically anchored job families (software and regulatory roles) | Medium |
| Manual UDI/traceability labelling and paper-based compliance record-keeping | Fast | AusUDID data-submission and structured device-traceability compliance workflows (binding from 2026-07-01 for Class IIb/III) | Fast |
| Manual quality-management and recall-tracking processes | Medium | Electronic quality-management systems integrated with AI-driven quality analytics | Fast |
| Reactive equipment servicing without predictive tooling | Slow | AI-enabled device analytics and generative-AI-assisted maintenance-protocol generation in clinical/healthcare technology management | Medium |
| AI/digital-tools content treated as elective-only, outside the compulsory core (mirrors this program's own C3 finding) | Slow (structural, institution-level) | Baseline AI/ML literacy expected of MedTech engineers entering an occupation with measured GPT-4-class task exposure in the roughly 26-54% range | Fast |

## 5. CURRICULUM IMPLICATIONS
| # | Implication | Dimension | Action |
|---|---|---|---|
| CI-1 | The program's only AI/digital-tools content sits in a 25-point elective basket a student can complete the degree without ever choosing, while the destination occupation carries peer-reviewed GPT-4-class task exposure of roughly 26-54% (up to 82% on the most inclusive measure). | D3 Technical Currency / C3 | Embedding required AI-literacy content within an existing compulsory subject's assessment (for example BMEN90039 or BMEN90044) avoids displacing the 75 compulsory credit points already allocated, but adds assessment-design and marking-criteria work to unit coordinators; adding a new compulsory subject instead would displace existing core content or extend total credit load. |
| CI-2 | The two operational functions where this record's sourced material documents real 2025 AI adoption — clinical/healthcare technology management and manufacturing quality — are functions the program gives students no supervised exposure to; the compulsory structure carries zero placement or practicum content (W3 = 0). | D7 Work-Integrated Learning / W3 | A shorter clinical-engineering or MedTech-manufacturing placement elective is lower cost than a full practicum: it needs host-organisation partnerships (hospital HTM units, device manufacturers) but not a restructure of the 75 compulsory + 25 elective credit-point split; a full practicum subject would require displacing or extending that structure. |
| CI-3 | BMEN90039 already assesses regulatory-pathway evaluation as a compulsory outcome, but the evidence file records no UDI/AusUDID-specific content, even though Class IIb/III compliance under that regime became binding on 2026-07-01 — before most current MC-MTI cohorts graduate. | D3 Technical Currency / C4, W2 | Refreshing BMEN90039's regulatory content to name UDI/AusUDID specifically is a syllabus-level update within an existing compulsory subject, not a new subject — cost is instructor time to update teaching materials, the lowest-cost item on this list. |
| CI-4 | No compulsory assessment requires students to appraise the quality of their own, a peer's, or a tool's work (C2 = 0), while sourced trade press describes AI increasingly drafting regulatory documentation and literature-review content — precisely the judgement layer both the (unverified) McKinsey estimate and the profession's own "isn't about replacing engineers" framing say remains human. | D2 Metacognition / C2 | Adding a peer-review or AI-output-critique task to an existing compulsory assessment (for example BMEN90044's team assignments) is a marking-design change within the current subject rather than new credit points, but requires developing and piloting new marking criteria. |
| CI-5 | Compulsory assessment already reaches C1 level 2 (group work with individual accountability) but not level 3, which additionally requires assessing the division of work between people and AI systems — the one clause separating the program's current score from the next level, against an occupation with documented LLM task exposure. | D2 Metacognition / C1 | Extending existing team-assessment criteria (BMEN90039/BMEN90044) to require teams to document and justify which parts of their work used AI-assisted tools is a rubric-level change, not new credit points, but needs explicit alignment with the faculty's assessment-integrity policy on disclosed AI tool use before it can be implemented. |

## 6. EVIDENCE CONFIDENCE + GAPS
| Signal Area | Confidence | Gap / Caveat |
|---|---|---|
| Regulatory driver (TGA UDI mandate) | HIGH | A national regulator's own notice describing a binding legal instrument with a firm compliance date, corroborated by an independent regulatory-affairs consultancy; it says nothing about hiring volume. |
| AI occupational-exposure indices (AIOE, Eloundou GPT-4 study) | HIGH for source quality, MEDIUM for Australian applicability | Peer-reviewed with public primary datasets, but both are US O*NET-classification studies not adjusted for Australia, and the Eloundou study predates most 2024-2026 generative-AI capability gains. |
| Live job-ad data (§2) | NONE — not conducted this cycle | \`jobAds.source = "none"\` in the profession record; no employer names, vacancy counts or skill-tag frequencies exist for this window. |
| Trade-press discussion (MedCity News, MD+DI x2, 24x7 Magazine) | MEDIUM | Genuine named outlets with dates, but MD+DI's "future of medtech jobs" piece returned HTTP 403 on direct fetch (confirmed via search instead) and its salary-comparison detail is unconfirmed; the McKinsey regulatory-documentation figure inside the MedCity News op-ed is a secondary citation, not independently verified here. |
| Practitioner-level discourse (podcast, HTM year-in-review quotes) | LOW | One podcast episode (a single practitioner, career-advice framing) and 4 solicited HTM quotes (only 2 on-topic for generative AI); neither is a survey, and neither represents device-design R&D engineers, the program's core destination. |
| Program curriculum evidence (dfva/source/evidence/mc-mti.json) | HIGH, mechanically verified | \`panelCv4.verified.mechanical\` is true and adversarially reviewed 2026-08-31; the evidence file itself flags 2 data-quality issues (a course-level graduate-attributes page and one elective subject's overview both returned mismatched, wrong-subject content), which were excluded from scoring, not from this report's use of the remaining scores. |

### Critical evidence gaps to close before institutional use:
1. No live job-ad data exists for this profession record — commission a Seek/Adzuna/LinkedIn pull against MC-MTI's actual destination titles before using §2 for hiring-volume or employer claims.
2. No Australian-specific AI-exposure study exists for biomedical or medical-device engineers — both peer-reviewed exposure studies are US-only, and the profession record's own search log shows Jobs and Skills Australia, Productivity Commission and ABS searches for an Australian equivalent returned nothing.
3. The McKinsey 20-30% regulatory-documentation reduction figure, cited inside the MedCity News op-ed, was never independently retrieved — confirm it against the primary McKinsey source before using it in any downstream document, or drop it.
4. No structured survey or forum sampling of device-design R&D engineers themselves exists — every practitioner-level source in this record is either one podcast guest or healthcare-technology-management and quality-management leaders adjacent to, not inside, the program's core design-engineering destination.

---

**Assessment Date:** 2026-09-01
**Source URL:** https://handbook.unimelb.edu.au/2026/courses/mc-mti
**Prompt Version:** DFVA-COPILOT-MARKET-v1

## REAL GRADUATE DESTINATIONS (JSA HEO)

**Where graduates of this field actually work** — [JSA Higher Education Outcomes](https://www.jobsandskills.gov.au/publications/higher-education-outcomes-exploring-administrative-data) (ATO tax-linked administrative data, Table_3, workbook dated 2025-12-04), field of education **039903 Biomedical Engineering** (n = 360 completions). Shares are the percentage of the field's graduates in wage or salary work; the field's ten most common entry occupations account for 25.0% of them, and the 5 largest are shown at each stage.

| Career stage | Top occupations |
|---|---|
| Entry (~1yr) | Biomedical Engineer (25.0%) |
| Early (~3yr) | Biomedical Engineer (25.0%) |
| Senior (~5yr) | Biomedical Engineer (22.2%) |

**Field grain, not program grain.** These are graduates of the whole Biomedical Engineering field of education at every completion level — not this program's graduates, and not a per-degree distribution. ANZSCO-6 does not encode seniority, so the 1/3/5-year lists move little for most fields.
`,
};

export default content;
