// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Environmental Law (MC-ENVLAW) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Environmental Law (MC-ENVLAW)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-23 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-envlaw.md
**Position basis:** Destination AI Exposure 94.83 (partial basis) × Curriculum Adaptiveness 5/15 (v4.2 draft, sub-scale A) · Workplace practice 3/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a partial basis (Master of Laws), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

MC-ENVLAW scores 1 on all eight items — 5/15 adaptive, 3/9 workplace — and fails G1. That uniformity is the diagnosis, not a coincidence. **The course structure specifies no compulsory core unit taken by every student.** Every level-2 and level-3 anchor in this instrument requires evidence in a *core* unit, so a program without a core cannot reach level 2 on anything, however good its individual subjects are. The scores measure a structural fact about the course rules, not the quality of the teaching inside them.

And the teaching is not the problem. The prescribed subjects carry substantial assessed research papers of 4,000–7,500 words worth 70–85% of subject marks; the extract documents problem-based framing reaching assessment tasks; graduate attributes claim teamwork, reflection, adaptability and communication. G2 passes comfortably on exactly this evidence. What the program cannot currently say is that any *particular* student encountered any *particular* one of those things — which is also why G1 fails: there is no documented coherent specialist core with progressive depth, because there is no documented core.

The plan below therefore has an unusual shape. **P1 is a course-rule change that adds no new teaching** — designate two or three existing prescribed subjects as required, in sequence — and it is the precondition for all sixteen scored steps as well as the remedy for G1. Three of the four levers that follow it (P2, P3, P4) are single-task substitutions inside subjects that already run. This program is one governance decision away from being scoreable at a level its curriculum arguably already supports; until that decision, every other intervention on this page is unreachable.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C1 Distributed cognition & relational capability | Adaptive | 1 / 3 | 2 | Direct — cross-jurisdictional climate and nature law rises Fast against single-jurisdiction practice, and in-house ESG counsel postings rose 35% in 2024–2025; both describe lawyers embedded in multi-disciplinary teams. Teamwork is claimed in the graduate attributes and assessed in no core unit, because there is no core unit | 1 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | Direct — greenwashing liability is named the defining corporate concern of 2026, and the task clients now bring is auditing marketing material, product disclosure statements and ESG reports against actual environmental performance: appraisal of someone else's work against criteria. The course ILOs claim critical reflection; nothing assesses it against standards | 2 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | Direct — AI tools are documented as replacing junior document review and discovery, manual EIS summarisation declines Very Fast, and CI-4 finds no explicit development of AI proficiency in practice contexts. The only program-level technology statement in the extract is a graduate attribute about IT infrastructure being available in the Law Library | 3 |
| C4 Life-long learning & transfer | Adaptive | 1 / 3 | 2 | Direct — Nature Positive implementation is "a live, unsettled area" and graduates entering practice in 2026–2028 will work through foundational case-law development, while climate litigation shifts from public-law review to private-law duty-of-care claims. Transfer is claimed in outcomes and assessed in no required unit | 4 |
| C5 Inquiry & evidence generation | Adaptive | 1 / 3 | 2 | Direct — Theme 7: lawyers who can critically assess EIS reports, climate modelling outputs and ecological assessments are "rare and highly valued", and law schools are not consistently producing them. The program's research papers are substantial but are secondary synthesis; nothing requires students to generate or interrogate primary evidence | 5 |
| **Adaptive capabilities** | **Adaptive** | **5 / 15** | **10** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Direct — titles that did not exist before 2022 ("Climate & Sustainability Lawyer (Graduate)", "ESG Legal Analyst") now come from the Tier 1 firms with LLM-level environmental credentials preferred; postings combining climate disclosure, sustainability law and TCFD more than doubled in the year to March 2026. Spoken presentation to peers and staff is assessed; a professional genre or external audience is not | 6 |
| W2 Authentic task design | Workplace | 1 / 3 | 2 | Direct — the destination families are defined by the artefact: regulatory submissions, environment protection licences, ASRS disclosure advice, judicial review filings. Problem-based framing reaches the assessment tasks, but the artefact produced and the criteria applied stay academic | 7 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | Direct and comparative — CI-6: "peer LLMs at ANU and UNSW are using EDO placements and government secondments as differentiators", while EDO and state environment centres are posting graduate solicitor roles and EPA Victoria advertised 14 legal and compliance roles in the year to March 2026. LAWS70067 International Legal Internship exists as an elective under "further subjects related to course" and is never mandatory | 8 |
| **Workplace practice** | **Workplace** | **3 / 9** | **6** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Assess collaborative practice in core — a joint regulatory submission, a moot team, or a multi-party negotiation with documented individual accountability | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Make collaboration recurrent across the core and require one task to document how work was divided across people *and* research tools, assessing the division itself | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Add structured peer critique against published criteria to a core subject — the same appraisal move clients now ask of practitioners auditing ESG claims against performance | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Require students to document and justify where they relied on or overrode an AI research output, a scientific report or a co-author, and mark that record | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Put AI-in-practice into core content and assessment: an AI-assisted EIS review, a critique of AI-generated summaries against the source, and the professional-responsibility obligations attaching to tool use in client work | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Require core assessment governing an AI system in its legal context — disclosure of AI use to a court or regulator, accountability for an AI-missed non-compliance in an EIS, or a firm's model data governance | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 1 → 2 | "At least one core assessment requires application to novel or unfamiliar problems — case variation, unseen datasets, cross-context projects." | Require a core assessment applying settled doctrine to an unsettled problem: a disputed biodiversity assessment under the Nature Positive regime, or a private-law climate claim with no controlling authority | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Let students scope their own capstone problem and assess a statement of what they do not yet know together with the plan to close it | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 1 → 2 | "Students design and conduct an inquiry with methodology selection and data collection, assessed." | Require the core research paper to state and defend a methodology and assemble its own evidence base — a case-law dataset, an EIS corpus, a set of regulator decisions — rather than synthesising secondary scholarship | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make the primary-evidence project required rather than one route among several, with the methodology defended in a staged supervised review | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Replace one core research paper with the genre a practitioner writes — a regulatory submission, an advice memorandum, or counsel's opinion — marked against practice criteria | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Make professional communication progressive across the core and have at least one task judged by a practitioner, with professional conduct among the assessed criteria | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Give the professional-genre task a real client posture end to end: a supplied brief with incomplete facts, a named regulator or counterparty, and the artefact judged as that reader would judge it | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Extend practitioner artefacts across the core so they are the assessment spine, with at least one carrying a genuine constraint of practice — an ambiguous instruction, a filing deadline, or the profession's own standards | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Build the clinical placement stream CI-6 recommends — EDO, EPA Victoria, DCCEEW, one commercial environment and planning practice — and place it in the core rather than beside it | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the core placement into a sequence, or one extended placement, with structured reflection and documented accountability to the host | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| P1 — a compulsory core | G1, and every lever below | Not a market lever. Every level-2 and level-3 anchor requires *core* placement, and this program has none, so P1 is the precondition for all sixteen scored steps and the direct remedy for the G1 failure | — (instrument, not market) | — |
| P3, P4, P15, P16 — practitioner artefacts and audiences | W1, W2 | Roles that did not exist before 2022 — "Climate & Sustainability Lawyer (Graduate)", "ESG Legal Analyst" — are now posted by Ashurst, HSF, MinterEllison and KWM with LLM-level environmental credentials preferred over general LLB; postings combining "climate disclosure", "sustainability law" and "TCFD" more than doubled in the 12 months to March 2026 | §2 Signal 1; §2 Signal 4 | MEDIUM-HIGH on commercial demand, though the volume of MC-ENVLAW-eligible roles is not separable from LLB generalist roles without a live scrape (§6) |
| P7, P10 — AI in legal practice, and its governance | C3 | "AI tools (Harvey, CoCounsel, Thomson Reuters AI) are replacing junior work in document review and discovery"; manual EIS review and summarisation declines Very Fast while AI-assisted EIA analysis and regulatory risk mapping rises Fast. The practitioner consensus is that AI raises the floor and the ceiling stays human — which increases demand for graduates who can work with the tools | §3 Theme 3; §4 Skill Shift Summary; §5 CI-4 | MEDIUM — pattern-based from practitioner discourse rather than measured adoption (§6) |
| P2, P14 — primary evidence and science literacy | C5 | Environmental lawyers who can "fluently read and critically assess environmental impact reports, climate modelling outputs, and ecological assessments are rare and highly valued", and law schools are not consistently producing them; multiple Melbourne Law alumni in practice name this the most persistent gap they observe in new graduates | §3 Theme 7; §5 CI-3 | MEDIUM — consistent employer discourse, not a measured signal |
| P8, P13 — doctrine applied to unsettled law | C4 | Nature Positive implementation is "a live, unsettled area": how biodiversity credits are valued, traded and litigated is undecided, and "graduates entering practice in 2026–2028 will work in a period of foundational case law development". Climate litigation is simultaneously shifting from public-law review to private-law negligence, nuisance and duty-of-care claims | §3 Theme 2; §3 Theme 5; §2 Signal 2 | HIGH on the regulatory pipeline (federal budget allocations confirm growth through 2027); MEDIUM on the practice-shape consequences (§6) |
| P5, P11 — criterion-referenced appraisal and reliance decisions | C2 | Greenwashing liability is "the defining corporate concern of 2026": clients are asking lawyers to audit marketing materials, product disclosure statements and ESG reports against actual environmental performance — an appraisal task against criteria, applied to someone else's work product | §3 Theme 1; §4 Skill Shift Summary (proactive risk governance rising) | MEDIUM |
| P6, P12 — assessed collaboration | C1 | Cross-jurisdictional climate and nature law rises Fast against single-jurisdiction practice, and in-house ESG counsel postings rose 35% in 2024–2025 — both describe lawyers working inside multi-disciplinary teams (science, finance, governance) rather than as sole advisers | §1 Job Family Map (Corporate ESG & In-House); §4 Skill Shift Summary | MEDIUM |
| P9, P17 — clinical placement in the core | W3 | Direct and comparative: "peer LLMs at ANU and UNSW are using EDO placements and government secondments as differentiators", while EDO, ClientEarth Australia and state environment centres are actively posting graduate solicitor roles and EPA Victoria alone advertised 14 legal and compliance roles in the 12 months to March 2026 | §5 CI-6; §2 Signal 3; §2 Signal 5 | HIGH on the regulatory and public-interest hiring signal (§6); note that work-integrated learning is not evidenced to raise employment rates [[28]](https://doi.org/10.1007/s10734-017-0216-z) |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | Enabling — G1 | **Designate a compulsory core.** Name two or three of the existing prescribed subjects as required of every student, in a stated sequence. This adds no new teaching: the subjects, the staff and the assessment already exist. It is a course-rule change, and it is the precondition for every lever below, because every level-2 and level-3 anchor in this instrument requires *core* placement. It is also the direct remedy for the G1 failure | No score of its own; moves G1 from FAIL toward PASS and unlocks P2–P17 | Medium (governance, not teaching) | Sem 1 2027 rules cycle | [[19]](https://www.legislation.gov.au/F2021L00488)[[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) |
| P2 | C5 | Require the core research paper to state and defend a methodology and to assemble its own evidence base — a case-law dataset, an EIS corpus, a set of regulator decisions — rather than synthesising secondary scholarship | C5 level 2 — students design and conduct an inquiry with methodology selection and data collection, assessed | Low | Sem 1 2027 | [[14]](https://doi.org/10.1016/j.techfore.2016.08.019)[[15]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P3 | W1 | Replace one core research paper with the genre a practitioner writes — a regulatory submission, an advice memorandum, or counsel's opinion — marked against criteria drawn from practice | W1 level 2 — a recognised professional genre judged against practice criteria | Low | Sem 1 2027 | [[19]](https://www.legislation.gov.au/F2021L00488)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined) |
| P4 | W2 | Give P3's task a real client posture end to end: a supplied brief with incomplete facts, a named regulator or counterparty, and the artefact judged as that reader would judge it | W2 level 2 — a core assessment reproduces a professional task end to end | Low | Sem 1 2027 | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396) |
| P5 | C2 | Add structured peer critique against published criteria to a core subject — the same appraisal move clients now ask of practitioners when auditing ESG claims against performance | C2 level 2 — criterion-referenced appraisal of quality in core assessment | Medium | Sem 2 2027 | [[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P6 | C1 | Assess collaborative practice in core: a joint regulatory submission, a moot team, or a multi-party negotiation with documented individual accountability | C1 level 2 — at least one core unit assesses collaborative practice | Medium | Sem 2 2027 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022) |
| P7 | C3 | Put AI-in-practice into core content and assessment: an AI-assisted EIS review exercise, a critique of AI-generated legal summaries against the source, and the professional-responsibility obligations that attach to using these tools for client work | C3 level 2 — core units address AI capabilities AND limitations/ethics, assessed | Medium | Sem 2 2027 | [[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P8 | C4 | Require a core assessment that applies settled doctrine to an unsettled problem — a disputed biodiversity assessment under the Nature Positive regime, or a private-law climate claim with no controlling authority | C4 level 2 — core assessment requires application to novel or unfamiliar problems | Medium | Sem 1 2028 | [[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y) |
| P9 | W3 | Build the clinical placement stream CI-6 recommends — EDO, EPA Victoria, DCCEEW and one commercial environment and planning practice — and place it in the core rather than beside it. Note the equity constraint below | W3 level 2 — a core unit places students in a real workplace with practitioner supervision and assessment | High | 2029 intake | [[27]](https://doi.org/10.1080/07294360.2016.1139551)[[29]](https://doi.org/10.1080/07294360.2016.1139551)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P10 | C3 | Require core assessment governing an AI system in its legal context — disclosure of AI use to a court or regulator, accountability for an AI-missed non-compliance in an EIS, or the data governance of a firm's model | C3 level 3 — core assessment requires critique or governance of AI systems in the discipline's own context | High | 2029 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P11 | C2 | Require students to document and justify where they relied on or overrode an AI research output, a scientific report or a co-author, and mark that record | C2 level 3 — assessment requires documented and justified reliance decisions | High | 2029 | [[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P12 | C1 | Make collaboration recurrent across the core and require one task to document how work was divided across people *and* research tools, with the division itself assessed | C1 level 3 — recurrent assessed collaboration coordinating people AND tools/AI systems | High | 2029 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022) |
| P13 | C4 | Let students scope their own capstone problem and assess a statement of what they do not yet know together with the plan to close it | C4 level 3 — documented structured progression toward independent learning | High | 2030 | [[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P14 | C5 | Make the primary-evidence project required rather than one route among several, with the methodology defended in a staged supervised review | C5 level 3 — a required substantial project generating primary evidence, methodology defended under scrutiny | High | 2030 | [[14]](https://doi.org/10.1016/j.techfore.2016.08.019)[[15]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P15 | W1 | Make professional communication progressive across the core and have at least one task judged by a practitioner — an EDO or EPA lawyer, or a partner from an environment and planning practice — with professional conduct among the assessed criteria | W1 level 3 — assessed progressively and judged by a real external audience, conduct among the criteria | High | 2030 | [[19]](https://www.legislation.gov.au/F2021L00488)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[32]](https://doi.org/10.1086/504455) |
| P16 | W2 | Extend practitioner artefacts across the core so they are the assessment spine, with at least one carrying a genuine constraint of practice — an ambiguous instruction, a filing deadline, or the profession's own standards | W2 level 3 — such tasks are the assessment spine and one carries a genuine constraint of practice | High | 2030 | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P17 | W3 | Extend the core placement into a sequence, or one extended placement, with structured reflection on professional practice and documented accountability to the host | W3 level 3 — substantial required work-situated learning with host accountability and structured reflection | High | 2031 | [[27]](https://doi.org/10.1080/07294360.2016.1139551)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | FAIL | The G1 PASS condition requires a documented coherent specialist core with progressive technical or methodological depth via an all-compulsory specialist core, an accredited sequence, or a staged prerequisite chain. The extract documents none of the three. (a) No all-compulsory specialist core: students with a law degree have zero compulsory subjects and 12.5 credit points of free choice from across the Master of Laws, so an eighth of the degree is interchangeable; the one compulsory subject (Fundamentals of the Common Law) applies only to non-common-law entrants and is a generic MLM legal-method subject, not environmental law. (b) No accredited sequence: no professional accreditation is documented anywhere in the extract. (c) No staged prerequisite chain: all prescribed subjects are standalone 12.5-point level-7 intensives with no prerequisite chain, sequencing or capstone. Furthermore, the prescribed lists include generic non-environmental subjects under 'Further subjects related to course' (e.g. Construction Law, Construction Risk). Precedent in 504aa, 507aa, 526aa, and 502cw binds. | **This gate currently FAILS, and P1 is its remedy.** The constraint is therefore inverted: rather than protecting existing core from displacement, this plan must *create* the core the gate requires. The designated core must show progressive depth — a stated sequence, not three subjects picked for convenience — because a set of unordered required subjects would satisfy the letter of "compulsory" and still fail the gate's depth condition. Until P1 lands, the adaptiveness score should be read as a measurement of the course rules rather than of the curriculum | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | The FAIL condition (recall or scripted responses only) is contradicted by the documented assessment across the extract. Core and prescribed subjects assess 4,000–7,500 word research papers, 3,000–5,000 word take-home examinations, advisory reports, and case-study evaluations. The program documents at graduate attribute level that students must critically analyse problems and develop a range of appropriate solutions through assessment tasks. Subject learning outcomes require evaluating complex trade-offs under high scientific and socio-economic uncertainty (e.g. assessing regulatory efficacy and the precautionary principle in LAWS70100, inter-jurisdictional water conflicts in LAWS70185, carbon pricing vs direct action in LAWS70293, urban sprawl and land use trade-offs in LAWS70349, and toxics/PFAS governance under scientific uncertainty in LAWS90352). | The gate is carried by the substantial assessed research papers (4,000–7,500 words at 70–85% of subject marks) and the problem-based framing that reaches the assessment tasks. P2, P3 and P4 all convert those papers into something else. Each substitution must preserve the defended-judgement demand the gate rests on: a regulatory submission on a contested approval keeps it, a checklist-style compliance memo does not | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

Every row below presupposes **P1**. Without a compulsory core there is no "core unit"
for an anchor to bind to, so none of these steps is reachable and the table describes a
program that does not yet exist.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P6 | C1 | 1 | 2 | +1 adaptive | 6 / 15 | 3 / 9 |
| P12 | C1 | 2 | 3 | +1 adaptive | 7 / 15 | 3 / 9 |
| P5 | C2 | 1 | 2 | +1 adaptive | 8 / 15 | 3 / 9 |
| P11 | C2 | 2 | 3 | +1 adaptive | 9 / 15 | 3 / 9 |
| P7 | C3 | 1 | 2 | +1 adaptive | 10 / 15 | 3 / 9 |
| P10 | C3 | 2 | 3 | +1 adaptive | 11 / 15 | 3 / 9 |
| P8 | C4 | 1 | 2 | +1 adaptive | 12 / 15 | 3 / 9 |
| P13 | C4 | 2 | 3 | +1 adaptive | 13 / 15 | 3 / 9 |
| P2 | C5 | 1 | 2 | +1 adaptive | 14 / 15 | 3 / 9 |
| P14 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 3 / 9 |
| P3 | W1 | 1 | 2 | +1 workplace | 15 / 15 | 4 / 9 |
| P15 | W1 | 2 | 3 | +1 workplace | 15 / 15 | 5 / 9 |
| P4 | W2 | 1 | 2 | +1 workplace | 15 / 15 | 6 / 9 |
| P16 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 7 / 9 |
| P9 | W3 | 1 | 2 | +1 workplace | 15 / 15 | 8 / 9 |
| P17 | W3 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
