// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Contemporary Chinese Studies (MC-CONTCS) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Contemporary Chinese Studies (MC-CONTCS)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-29 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-contcs.md
**Position basis:** Destination AI Exposure 80.60 (field basis) × Curriculum Adaptiveness 6/15 (v4.2 draft, sub-scale A) · Workplace practice 3/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a field basis (Jobs and Skills Australia Higher Education Outcomes (JSA HEO) field 099999 Society and Culture, n.e.c.), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

Master of Contemporary Chinese Studies scores 6/15 on the adaptive sub-scale (C1 at level 2; C2–C5 all at level 1) and 3/9 on the workplace-practice sub-scale (W1–W3 all at level 1), and both gates — G1 Disciplinary foundation and G2 Decision-making under uncertainty — fail on verification review. Only INTS90007 is confirmed as compulsory (25 of 200 points); CHIN90008's intended-learning-outcome content on peer appraisal and professional-genre outputs would raise several scores if its assessment table were captured, and the capstone stream — CHIN90011's research proposal, the Minor Thesis (CHIN90009/CHIN90010), or the internship (CHIN90007) — carries most of the remaining headroom, but each is one of three parallel streams, not a program-wide requirement.

This program has no destination record of its own; its job families rest on a field-of-education basis (§1 of the market report), so the market evidence bears unevenly across items — most directly on C3 and C4 (automation exposure and governance across the field's routine destinations) and W1 (the largest advertisement signal in the report, plus conduct obligations in the compliance-bound destinations), more thinly on C2, and not at all on C1, C5, W2 and W3, which carry no direct market signal and are planned on the instrument's own anchor terms alone.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | Theme 2 (§3) names clerical and secretarial work as the clear automation-exposed group, with routine, rules-based office tasks the most readily automated; the §4 Falling/Falling sharply directions for administration, clerical, data entry and office administration follow from the same theme. Graduates entering Office Clerks, General destinations need evaluative judgement over an automated or AI-drafted output, which the program does not yet assess. | 1 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | Theme 1 (§3) binds office clerks' handling of personal and commercial information to Privacy Act 1988 Australian Privacy Principles and Fair Work Act 2009 record-keeping duties; Theme 4 (§3, Jobs and Skills Australia Generative AI Capacity Study) places routine clerical, administrative and public-relations roles in the highest automation-exposure band; Themes 5–6 (§3) describe emerging biometric-surveillance and facial-recognition privacy regulation reaching the Police and Sheriff's Patrol Officers destination. Three of the four committed job families carry a governance-literacy demand the program's only AI content, in the elective ASIA20008, does not meet. | 2 |
| C4 Life-long learning & transfer | Adaptive | 1 / 3 | 2 | Theme 2 (§3) and the §4 Falling/Falling sharply directions for administration, clerical, data entry, office administration and reception name routine, rules-based office tasks as the clearest automation-exposed group; graduates who take on Office Clerks, General work, the field's most common entry destination, need transferable skills beyond the routine tasks losing demand. | 3 |
| C5 Inquiry & evidence generation | Adaptive | 1 / 3 | 2 | None reported — no theme or signal in the market report addresses research-methods training or primary-evidence generation for any of the four committed job families; this item is planned on anchor terms alone. | 4 |
| C1 Distributed cognition & relational capability | Adaptive | 2 / 3 | 1 | None reported — no theme or signal in the market report addresses coordinating work between people and tools or AI systems for any of the four committed job families; this item is planned on anchor terms alone. | 8 |
| **Adaptive capabilities** | **Adaptive** | **6 / 15** | **9** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Signal 4 (§2, 1,024 postings) is the largest advertisement volume recorded in this report, against the Public Relations Specialists destination, a communications-centred family; Theme 1 and Theme 3 (§3) separately bind Office Clerks, General and the energy/solar-consulting slice of Business Operations Specialists, All Other to statutory record-keeping and accreditation conduct obligations. | 5 |
| W2 Authentic task design | Workplace | 1 / 3 | 2 | None reported — no theme or signal in the market report describes the artefacts or criteria of any of the four committed job families' day-to-day work in enough detail to warrant a specific authentic-task redesign; this item is planned on anchor terms alone. | 6 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | None reported — no theme or signal in the market report addresses placement, practicum or work-situated arrangements for any of the four committed job families; this item is planned on anchor terms alone. | 7 |
| **Workplace practice** | **Workplace** | **3 / 9** | **6** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Formalise CHIN90008's existing intended-learning-outcome language on peer appraisal into a criterion-referenced peer-review or structured-critique task, marked against published standards. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Require students in a compulsory assessment — CHIN90008's policy-recommendation or report task, once its assessment table is confirmed, or an equivalent core task — to document and justify a reliance decision: where they relied on or overrode an AI-drafted section or source. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Move ASIA20008 Digital Asia's AI-capability content, or an equivalent module, into a compulsory core unit such as INTS90007, with its capabilities and limitations discussed and assessed rather than confined to the elective pool. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Require a core assessment that critiques the governance of AI systems in a contemporary-China context — for example, algorithmic bias in machine translation, or platform content-governance in Chinese-language digital spaces — beyond tool operation. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 1 → 2 | "At least one core assessment requires application to novel or unfamiliar problems — case variation, unseen datasets, cross-context projects." | Add an assessed task to a compulsory unit that applies the program's analytical methods to a novel or unfamiliar case — an unseen contemporary-China policy scenario or cross-context dataset — rather than the current fixed content sequence. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Extend CHIN90011's research-proposal task, currently required for only two of the three capstone streams, to all three streams, with a documented, staged progression toward independent inquiry. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 1 → 2 | "Students design and conduct an inquiry with methodology selection and data collection, assessed." | Extend CHIN90011's introductory methods training so students design and conduct a small inquiry with methodology selection and data collection, assessed, rather than a proposal document alone. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make the Thesis capstone stream's primary-evidence project (CHIN90009/CHIN90010) a required element of the program rather than one of three parallel streams, with the methodology defended in a staged supervised review. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Extend INTS90007's compulsory group presentation, currently addressed only to the teaching team, to a professional genre or an audience beyond it — for example a policy brief judged by a visiting contemporary-China or communications practitioner. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Assess professional communication repeatedly and progressively across the compulsory core, with at least one assessment judged by a real external audience or practitioner and professional conduct explicitly among the marking criteria. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Confirm and formalise CHIN90008's professional-genre outputs — policy recommendations, reports — into an end-to-end professional task judged against criteria drawn from practice, once its assessment table is captured. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Make practice-derived tasks the program's assessment spine across the compulsory core — a capstone plus earlier scaffolding — with at least one carrying a genuine constraint of practice, such as an externally supplied brief or a real audience. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Move CHIN90007's optional internship stream into the compulsory core, with practitioner supervision and assessment, even as an initially short placement. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the core placement into a required sequence across the program, supervised, assessed, with structured reflection and documented accountability to the host organisation. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Extend INTS90007's existing assessed group presentation to require documenting the allocation of work between students and any AI tools used, with that allocation among the assessed criteria. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| P1 | C2 | Theme 2 names clerical and secretarial work as the clear automation-exposed group, with routine office tasks the most readily automated; the §4 Falling directions for administration and clerical follow from it. | §3 Theme 2; §4 | MEDIUM |
| P2 | C2 | As P1 — Theme 2's automation-exposure finding carries through to the level-3 reliance-decision anchor. | §3 Theme 2; §4 | MEDIUM |
| P3 | C3 | Theme 1 binds office clerks to Privacy Act and Fair Work Act information-handling duties; Theme 4 places clerical, administrative and public-relations roles in the highest automation-exposure band; Themes 5–6 describe emerging biometric-surveillance privacy regulation reaching the police destination. | §3 Theme 1; §3 Theme 4; §3 Themes 5–6 | HIGH |
| P4 | C3 | As P3 — the same three themes carry through to the level-3 governance-critique anchor. | §3 Theme 1; §3 Theme 4; §3 Themes 5–6 | HIGH |
| P5 | C4 | Theme 2 and the §4 Falling/Falling sharply directions for administration, clerical, data entry, office administration and reception name routine office tasks as the clearest automation-exposed group. | §3 Theme 2; §4 | MEDIUM |
| P6 | C4 | As P5 — the same automation-exposure finding carries through to the level-3 independent-learning anchor. | §3 Theme 2; §4 | MEDIUM |
| P7 | C5 | No theme or signal in the market report bears on research-methods training or primary-evidence generation for any of the four committed job families. | §1 job family map (no direct signal) | Not rated — no signal for this item |
| P8 | C5 | As P7 — no market signal for inquiry at the level-3 anchor either. | §1 job family map (no direct signal) | Not rated — no signal for this item |
| P9 | W1 | Signal 4 (1,024 postings) is the report's largest advertisement volume, against the communications-centred Public Relations Specialists destination; Theme 1 and Theme 3 bind Office Clerks, General and the energy/solar-consulting slice of Business Operations Specialists, All Other to statutory conduct obligations. | §2 Signal 4; §3 Theme 1; §3 Theme 3 | MEDIUM-HIGH |
| P10 | W1 | As P9 — Signal 4 and Themes 1 and 3 carry through to the level-3 repeated-assessment anchor. | §2 Signal 4; §3 Theme 1; §3 Theme 3 | MEDIUM-HIGH |
| P11 | W2 | No theme or signal in the market report describes the artefacts or criteria of any of the four committed job families' day-to-day work in enough detail to warrant a specific authentic-task redesign. | §1 job family map (no direct signal) | Not rated — no signal for this item |
| P12 | W2 | As P11 — no market signal for authentic task design at the level-3 anchor either. | §1 job family map (no direct signal) | Not rated — no signal for this item |
| P13 | W3 | No theme or signal in the market report addresses placement, practicum or work-situated arrangements for any of the four committed job families. | §1 job family map (no direct signal) | Not rated — no signal for this item |
| P14 | W3 | As P13 — no market signal for work-situated learning at the level-3 anchor either. | §1 job family map (no direct signal) | Not rated — no signal for this item |
| P15 | C1 | No theme or signal in the market report addresses coordinating work between people and tools or AI systems for any of the four committed job families. | §1 job family map (no direct signal) | Not rated — no signal for this item |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C2 | Formalise CHIN90008's existing intended-learning-outcome language on peer appraisal into a criterion-referenced peer-review or structured-critique task, marked against published standards. | C2 level 2 | Low | Year 1; assessment-table update to CHIN90008's existing peer-appraisal outcome | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P2 | C1 | Extend INTS90007's existing assessed group presentation to require documenting the allocation of work between students and any AI tools used, with that allocation among the assessed criteria. | C1 level 3 | Low | Year 1; assessment-criteria update to INTS90007's existing group-presentation component | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P3 | C3 | Move ASIA20008 Digital Asia's AI-capability content, or an equivalent module, into a compulsory core unit such as INTS90007, with its capabilities and limitations discussed and assessed rather than confined to the elective pool. | C3 level 2 | Low-medium | Year 1; syllabus and rubric update moving ASIA20008's content into INTS90007 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P4 | C4 | Add an assessed task to a compulsory unit that applies the program's analytical methods to a novel or unfamiliar case — an unseen contemporary-China policy scenario or cross-context dataset — rather than the current fixed content sequence. | C4 level 2 | Low-medium | Year 1-2; assessment-table update to INTS90007 or another compulsory core unit | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P5 | C2 | Require students in a compulsory assessment — CHIN90008's policy-recommendation or report task, once its assessment table is confirmed, or an equivalent core task — to document and justify a reliance decision: where they relied on or overrode an AI-drafted section or source. | C2 level 3 | Medium | Year 1-2; assessment-brief update requiring a documented reliance decision | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P6 | W1 | Extend INTS90007's compulsory group presentation, currently addressed only to the teaching team, to a professional genre or an audience beyond it — for example a policy brief judged by a visiting contemporary-China or communications practitioner. | W1 level 2 | Medium | Year 1-2; external-audience or practitioner panel added to INTS90007's group presentation | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P7 | W2 | Confirm and formalise CHIN90008's professional-genre outputs — policy recommendations, reports — into an end-to-end professional task judged against criteria drawn from practice, once its assessment table is captured. | W2 level 2 | Medium | Year 1; task and criteria confirmation for CHIN90008's professional-genre outputs | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P8 | C3 | Require a core assessment that critiques the governance of AI systems in a contemporary-China context — for example, algorithmic bias in machine translation, or platform content-governance in Chinese-language digital spaces — beyond tool operation. | C3 level 3 | Medium | Next annual course review; assessment redesign to INTS90007 or the unit carrying the moved C3:2 content | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P9 | C5 | Extend CHIN90011's introductory methods training so students design and conduct a small inquiry with methodology selection and data collection, assessed, rather than a proposal document alone. | C5 level 2 | Medium | Contingent on capstone-stream redesign; assessment redesign within CHIN90011 | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P10 | W1 | Assess professional communication repeatedly and progressively across the compulsory core, with at least one assessment judged by a real external audience or practitioner and professional conduct explicitly among the marking criteria. | W1 level 3 | Medium-high | Year 2-3; a second externally judged assessment added across the compulsory core | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P11 | C4 | Extend CHIN90011's research-proposal task, currently required for only two of the three capstone streams, to all three streams, with a documented, staged progression toward independent inquiry. | C4 level 3 | Medium-high | Contingent on capstone-stream redesign; extending CHIN90011's proposal task across all three streams | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P12 | W3 | Move CHIN90007's optional internship stream into the compulsory core, with practitioner supervision and assessment, even as an initially short placement. | W3 level 2 | Medium-high | Year 2; course-structure change moving CHIN90007's internship into the compulsory core | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P13 | W2 | Make practice-derived tasks the program's assessment spine across the compulsory core — a capstone plus earlier scaffolding — with at least one carrying a genuine constraint of practice, such as an externally supplied brief or a real audience. | W2 level 3 | High | Contingent on capstone-stream redesign; staged redesign across the compulsory core | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P14 | C5 | Make the Thesis capstone stream's primary-evidence project (CHIN90009/CHIN90010) a required element of the program rather than one of three parallel streams, with the methodology defended in a staged supervised review. | C5 level 3 | High | Contingent on capstone-stream redesign; capstone-structure change, contingent on supervisory capacity for the full cohort | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P15 | W3 | Extend the core placement into a required sequence across the program, supervised, assessed, with structured reflection and documented accountability to the host organisation. | W3 level 3 | High | Year 3; contingent on host-agreement negotiation and supervision capacity for the full cohort | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | FAIL | Only 25 of 200 points compulsory; remainder is a broad cross-disciplinary elective pool plus a chosen capstone stream — no coherent specialist core, accredited sequence, or prerequisite chain documented. | Any redesign must document a coherent specialist core with progressive technical or methodological depth beyond INTS90007's 25 compulsory points; moving elective content such as ASIA20008 into the core, or confirming CHIN90008's compulsory status and assessment table, does not by itself satisfy this gate without a demonstrated prerequisite chain or accredited sequence. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | FAIL | Captured compulsory-subject assessment is conventional essay/quiz/presentation work with no documented defended trade-off decisions; the capstone streams that might carry this evidence have no assessment detail in the extract, so PASS cannot be substantiated. | Any redesign must add a documented capstone, simulation or live project with a defended trade-off decision under assessed scrutiny; extending CHIN90011's research-proposal task or the Thesis stream's methodology defence satisfies this gate only if the defended decision is itself graded, not merely described. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C2 | 1 | 2 | +1 adaptive | 7 / 15 | 3 / 9 |
| P2 | C2 | 2 | 3 | +1 adaptive | 8 / 15 | 3 / 9 |
| P3 | C3 | 1 | 2 | +1 adaptive | 9 / 15 | 3 / 9 |
| P4 | C3 | 2 | 3 | +1 adaptive | 10 / 15 | 3 / 9 |
| P5 | C4 | 1 | 2 | +1 adaptive | 11 / 15 | 3 / 9 |
| P6 | C4 | 2 | 3 | +1 adaptive | 12 / 15 | 3 / 9 |
| P7 | C5 | 1 | 2 | +1 adaptive | 13 / 15 | 3 / 9 |
| P8 | C5 | 2 | 3 | +1 adaptive | 14 / 15 | 3 / 9 |
| P9 | W1 | 1 | 2 | +1 workplace | 14 / 15 | 4 / 9 |
| P10 | W1 | 2 | 3 | +1 workplace | 14 / 15 | 5 / 9 |
| P11 | W2 | 1 | 2 | +1 workplace | 14 / 15 | 6 / 9 |
| P12 | W2 | 2 | 3 | +1 workplace | 14 / 15 | 7 / 9 |
| P13 | W3 | 1 | 2 | +1 workplace | 14 / 15 | 8 / 9 |
| P14 | W3 | 2 | 3 | +1 workplace | 14 / 15 | 9 / 9 |
| P15 | C1 | 2 | 3 | +1 adaptive | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
