// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Commerce (Management) (MC-COMMGMT) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Commerce (Management) (MC-COMMGMT)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-29 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-commgmt.md
**Position basis:** Destination AI Exposure 90.73 (cognate basis) × Curriculum Adaptiveness 8/15 (v4.2 draft, sub-scale A) · Workplace practice 1/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a cognate basis (Master of Management), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

The Master of Commerce (Management) provides a staged, discipline-specific research-methods sequence, but almost no assessed contact with real professional practice. G1 passes on the four-subject methods progression — Foundations in Qualitative/Quantitative Methods through Research Design and Advanced Qualitative/Quantitative Research Methods to the Research Report — gated to Management- and Marketing-coded subjects between Year 1 and Year 2. G2 passes on Research Design's assessed critique of alternative research strategies feeding into the Research Report's genuinely undetermined findings. C4 (3/3) reaches the instrument ceiling through the mandatory, individually assessed, self-scoped 12,000-word Research Report.

Against 8/15 on Adaptiveness and 1/9 on Workplace, the two largest gaps are W2 and W3, both at 0/3: every graded task in the core is an essay, individual assignment, presentation or exam, and no placement, practicum or live client project appears anywhere in the structure. C1, C2, C3 and W1 each sit at 1/3, one step past the floor. The program's destinations rest on a cognate-basis estimate (exposure 90.73, field-of-education job families) rather than the program's own graduates, so the following market evidence is scoped to what that field-level record supports.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C1 Distributed cognition & relational capability | Adaptive | 1 / 3 | 2 | Indirect — §2 Signal 2 records 'team leadership and coaching' as a recurring keyword for Sales Managers, and §2 Signal 3 records 'team' among the leading keywords for General and Operations Managers. §5 CI-5 finds no theme accelerating this specific demand, so it does not alone warrant new content, but the destination occupations already assess a collaborative capability the core does not. | 3 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | Direct — §3 Theme 1 requires auditors to verify automated ledger anomaly-detection algorithms and keep documented audit trail logs for AI-generated financial estimates (§5 CI-2); that is a reliance-and-override judgement, not a one-off reflection. The core's only reflective assessment, the Research reflection assignment, is never described as judged against quality criteria. | 4 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | Direct — §3 Themes 1, 3, 4 and 5 place four of the program's job families under active AI-verification, consumer-law, financial-services-licensee or work-health-and-safety officer obligations (§5 CI-2, CI-3, CI-4), and §4 records ASRS sustainability assurance rising sharply. The only digital-tool evidence in the core is STATA instruction in a research-methods subject — operating specialised software, not AI capabilities, limits or governance. | 5 |
| C5 Inquiry & evidence generation | Adaptive | 2 / 3 | 1 | Direct — §3 Theme 2 records an acute shortage of accounting graduates able to generate primary evidence on climate risk governance and multi-capital greenhouse gas assurance under the ASRS mandate. The Research Report already requires original research at 100% of the subject; the market evidence does not distinguish a designed inquiry from one whose methodology is defended under scrutiny, so the item sits one step short of ceiling. | 7 |
| C4 Life-long learning & transfer | Adaptive | 3 / 3 | 0 | None needed — C4 sits at the instrument ceiling (3/3) through the Research Report's mandatory, assessed, self-scoped 12,000-word individual project. The ASRS shortage in §3 Theme 2 and the General Manager exposure figures in §3 Theme 6 confirm the graduate labour market keeps changing under this cohort; the existing capstone structure already gives the program a mechanism to keep pace without further redesign. | 8 |
| **Adaptive capabilities** | **Adaptive** | **8 / 15** | **7** | — | — |
| W2 Authentic task design | Workplace | 0 / 3 | 3 | Direct — market report §3 Theme 2 records an acute shortage of accounting graduates skilled in multi-capital greenhouse gas assurance and climate risk governance under the mandatory Australian Sustainability Reporting Standards, and Theme 1 requires auditors to verify automated ledger anomaly-detection algorithms and keep documented audit trail logs for AI-generated financial estimates; §4 confirms ASRS sustainability assurance rising sharply and audit sampling and internal controls both rising. None of this reaches assessment as a real professional artefact: every graded core task is an essay, individual assignment, presentation or exam. | 1 |
| W3 Work-situated learning | Workplace | 0 / 3 | 3 | Indirect — §2 Signal 1 names the major accounting-firm employers of this program's largest destination family (PwC, Deloitte, EY, KPMG, BDO, Grant Thornton), and §3 Theme 5 shows General Managers who meet the officer test carry a personal work-health-and-safety due-diligence duty. Graduates enter roles carrying accountability to a supervisor, a client or the law from day one, with no assessed placement, practicum or live client project anywhere in the course to rehearse it beforehand. | 2 |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Indirect — §5 CI-3 and CI-4 recommend a compliance case brief and an officer-duty case study as capstone options; both are professional genres the core does not currently assess. Individual presentations recur across the core, but the market report records no audience beyond the teaching team for any of them. | 6 |
| **Workplace practice** | **Workplace** | **1 / 9** | **8** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| W2 Authentic task design | 0 → 1 | "Contextualised or scenario-framed tasks appear (case studies, worked scenarios), but the artefact produced and the criteria applied remain academic." | Add a contextualised case study to an existing core assessment — for example, an Australian Sustainability Reporting Standards scenario in Research Design (Theme 2, §3; ASRS sustainability assurance rising sharply, §4) — framing the task around a real scenario while the artefact produced and the marking criteria stay academic (cost: one assessment redesign), or add a shorter contextualising preamble to an existing exam or essay question citing the same scenario without redesigning the artefact (cost: minimal, question-wording update only). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Redesign one core assessment to reproduce a professional task end to end — for example, an audit-sampling exercise in the methods sequence that requires verifying AI-generated ledger anomaly flags and producing the documented audit trail log the APESB standard requires (Theme 1, §3; §5 CI-2) — marked against practice-drawn criteria rather than an academic rubric (cost: revised assessment brief and marking criteria), or commission an accounting-firm practitioner to supply the marking criteria for an existing exercise rather than redesigning the task itself (cost: guest-practitioner time only). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Make the redesigned professional task the program's assessment spine rather than a single instance — one per stage of the methods sequence plus the Research Report capstone — with at least one carrying a genuine constraint of practice, such as an externally supplied dataset and a real reporting deadline (cost: staged redesign across the methods sequence, ongoing industry-partner coordination for the supplied dataset), or confine the constraint-of-practice requirement to the Research Report capstone alone, with the earlier methods subjects providing lighter scaffolding (cost: single-subject redesign only). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 0 → 1 | "Work-situated learning exists only as an elective, an optional internship, or an unassessed extracurricular or careers activity." | Introduce work-situated learning as an optional, unassessed activity alongside the discipline electives — a careers-office-brokered industry visit or short shadowing placement (cost: careers-office coordination time, no curriculum redesign), or list an existing accounting-firm graduate program from the employers named in §2 Signal 1 as a recommended, unassessed pathway in course materials (cost: negligible, documentation only). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Add a core unit, or a compulsory component of an existing core unit, that places students with a host organisation for a short client project or practicum with practitioner supervision and assessment, drawing on the employers named in §2 Signal 1 or a general-management or sales host (cost: host-partnership development, one new or restructured core unit, supervision and assessment design), or embed a shorter four- to six-week live-client project within an existing core unit rather than a full external placement (cost: lower — single-unit redesign, one client relationship per offering). Per the honest bound on this claim, justify the change by skill development and professional-identity formation rather than employment-rate uplift [[28]](https://doi.org/10.1007/s10734-017-0216-z)[[29]](https://doi.org/10.1080/07294360.2016.1139551), and note the equity cost of an unpaid or relocation-dependent placement [[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the placement or practicum to a substantial required sequence in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice (cost: extended host-partnership capacity, sustained placement-coordination staffing, assessed reflective component), or require a single extended placement rather than a sequence, holding the same supervision and reflection standard (cost: lower — one host relationship, less sustained coordination staffing). The equity cost noted at the previous step applies at greater scale; a paid or subsidised placement model would offset it (cost: placement stipend funding). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Add a group-assessed task with individual accountability to an existing core or discipline-elective subject — for example, a team-based case analysis in a Management- or Marketing-coded elective, responding to the team-leadership and coaching demand recorded for Sales Managers and the team-coordination demand recorded for General and Operations Managers (§2 Signals 2 and 3) (cost: one assessment redesign, group-marking rubric), or convert an existing individual presentation into a small-group presentation with individually marked contribution statements (cost: marking-scheme change only, no new task). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Extend the group assessment so it recurs across the program and at least one instance requires coordinating work across people and tools or AI systems — for example, a team stage of the Research Report with documented role and tool allocation (cost: staged redesign across two or more subjects, documented allocation rubric), or confine the requirement to a single capstone-stage team task rather than redesigning multiple subjects (cost: single-subject redesign only). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Attach explicit criterion-referenced marking criteria to the Research reflection assignment so appraisal of quality is assessed rather than merely invited (cost: rubric development, no new unit), or add a structured peer-review stage to the same assignment instead of new marking criteria (cost: peer-review coordination, one assessment-brief update). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Extend the criterion-referenced assessment to require students to document and justify reliance decisions — a reflective log in the methods sequence recording where an AI-generated audit estimate or anomaly flag (Theme 1, §3; §5 CI-2) was relied on or overridden, and why (cost: assessment redesign, marking-criteria update), or add a single reliance-and-override question to the existing Research reflection assignment rather than a standalone log (cost: minimal, assignment-brief update only). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Add an assessed module on AI capabilities and limitations to an existing methods or discipline-elective subject, covering the verification duties Theme 1 places on auditors for AI-generated estimates or the compliance obligations Themes 3 and 4 place on Sales Managers under the Australian Consumer Law and, where financial products are sold, the Corporations Act 2001 (§5 CI-2, CI-3) (cost: one module addition, no new unit), or run a single guest-practitioner briefing on the same content rather than a full module (cost: one contact-hour, no assessment change). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Extend the module to require critique or governance of AI systems in the discipline's own context — an assessed audit of an AI-generated estimate's compliance trail against the APESB documentation requirement (Theme 1, §3), or an assessed work-health-and-safety officer-duty case study responding to Theme 5 (§5 CI-4) (cost: assessment redesign), or invite a guest practitioner to brief and judge the existing module rather than redesigning the assessment (cost: practitioner time only). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Add a professional-genre assessment to an existing core or elective subject — a compliance case brief responding to the Australian Consumer Law and Corporations Act 2001 obligations recorded in §3 Themes 3 and 4 (§5 CI-3), or an officer-duty briefing memo responding to Theme 5 (§5 CI-4) — judged against criteria drawn from practice rather than academic essay criteria (cost: one assessment redesign), or add a compliance-focused section to an existing exam rather than a full brief (cost: minimal, exam-question addition only). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Assess professional communication repeatedly and progressively across the program, and deliver at least one core assessment to a real external audience or practitioner — present the compliance case brief or officer-duty briefing to an invited industry panel drawn from the employers named in §2 Signals 1 to 3, with professional conduct explicitly among the assessed criteria (cost: recurring assessment redesign across two or more subjects, external-panel coordination each offering), or hold a single capstone-stage panel presentation rather than a recurring one, accepting a lighter cumulative-progression case for the anchor (cost: one-off panel coordination, single-subject redesign). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Require the Research Report's methodology to be defended under scrutiny — a viva, panel defence or staged supervised review — rather than resting on supervision alone, positioning graduates to generate the primary evidence on sustainability assurance and climate risk governance that Theme 2 records as short in supply (§3; §5 CI-1) (cost: added staff time for the defence panel, assessment-structure amendment), or require a structured written methodology-defence memo reviewed by a second supervisor rather than a live viva (cost: lower — no panel scheduling, added marking load for the second reviewer). | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| P1 | W2 | The ASRS sustainability-assurance shortage (Theme 2) and the AI-verification duty on auditors (Theme 1) both describe real, defensible professional artefacts, not academic exercises; §4 confirms both associated skills rising. | §3 Theme 1; §3 Theme 2; §4 | HIGH (regulatory and statutory instruments; scholarly and grey-literature studies; job-advertisement signals — Accountants and Auditors, §6) |
| P2 | W3 | The Accountants and Auditors employer list and the General Manager officer-duty finding both show graduates entering roles with immediate personal or client accountability, which the course provides no supervised workplace exposure to rehearse. | §2 Signal 1; §3 Theme 5 | HIGH (job-advertisement signals — Accountants and Auditors; regulatory and statutory instruments — General and Operations Managers, §6) |
| P3 | C1 | Team leadership and team-coordination keywords recur in the job-advertisement sample for Sales Managers and General and Operations Managers, though no discussion-signal theme specifically accelerates this demand. | §2 Signal 2; §2 Signal 3; §5 CI-5 | MEDIUM — job-advertisement keyword presence is HIGH-confidence (§6), but no discussion-signal theme corroborates rising demand for this specific capability |
| P4 | C2 | The APESB requirement that auditors verify automated anomaly-detection algorithms and keep documented audit trail logs is a reliance-and-override judgement, not a reflection exercise. | §3 Theme 1; §5 CI-2 | HIGH (regulatory and statutory instruments — Accountants and Auditors, §6) |
| P5 | C3 | Four job families in this program's field carry active AI-verification, consumer-law, financial-services-licensee or work-health-and-safety obligations that presume digital and AI literacy beyond tool operation. | §3 Themes 1, 3, 4 and 5; §5 CI-2, CI-3, CI-4 | HIGH (regulatory and statutory instruments — Accountants and Auditors, Sales Managers and General and Operations Managers, §6) |
| P6 | W1 | The recommended compliance case brief and officer-duty briefing are professional genres addressed to a client, regulator or panel, not the teaching team the core currently addresses. | §5 CI-3; §5 CI-4 | MEDIUM — the underlying regulatory sources are HIGH-confidence (§6), but no theme addresses professional-communication genre or audience directly |
| P7 | C5 | The ASRS-driven shortage of accounting graduates able to generate primary climate-risk-governance evidence supports strengthening inquiry rigour past a designed study toward one defended under scrutiny. | §3 Theme 2; §5 CI-1 | HIGH (scholarly and grey-literature studies — Accountants and Auditors, §6) |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C2 | Attach criterion-referenced marking criteria to the Research reflection assignment. | C2 level 2 (criterion-referenced appraisal of quality) | Low | Term 1; rubric update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P2 | C1 | Add a group-assessed case task with individual accountability to a Management- or Marketing-coded discipline elective. | C1 level 2 (assessed collaborative practice) | Low | Term 1; assessment redesign | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P3 | C3 | Add an assessed module on AI capabilities and limitations to an existing methods or elective subject. | C3 level 2 (capabilities and limitations discussed/assessed) | Low–Medium | Term 1; module addition | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P4 | W1 | Add a compliance case brief or officer-duty briefing memo, judged against practice-drawn criteria. | W1 level 2 (professional genre judged against practice criteria) | Medium | Term 2; assessment redesign | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P5 | W2 | Redesign an audit-sampling exercise to require verifying AI-generated estimates and producing a documented audit trail log. | W2 level 2 (professional task end to end) | Medium | Term 2; assessment brief and criteria update | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P6 | C2 | Attach an assessed reliance-and-override log to the methods sequence. | C2 level 3 (reliance/override justification) | Medium | Term 2; assessment redesign | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P7 | C3 | Introduce an assessed AI-governance or compliance-trail audit in the same module. | C3 level 3 (governance of AI/data in disciplinary context) | Medium | Term 2; subject update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P8 | W3 | Add a core placement, practicum or live-client project with practitioner supervision and assessment. | W3 level 2 (core placement or live project) | Medium–High | Next course review; host-partnership development | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P9 | C5 | Require the Research Report's methodology to be defended under scrutiny. | C5 level 3 (defence under scrutiny) | Medium | Next course review; capstone-structure update | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P10 | W2 | Extend the professional-task redesign across the methods sequence and the Research Report, with a genuine constraint of practice. | W2 level 3 (assessment spine with constraint of practice) | High | Next course review; staged redesign across the methods sequence | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | A staged, discipline-specific methods sequence (Foundations in Qualitative/Quantitative Methods to Research Design to Advanced Qualitative/Quantitative Research Methods to Research Report) plus a Year 1 to Year 2 progression gate keyed specifically to Management/Marketing-coded subjects constitutes a coherent specialist core with progressive depth. | Redesign must preserve the staged methods sequence and its Management- and Marketing-coded progression gate — Foundations in Qualitative/Quantitative Methods, Research Design, Advanced Qualitative/Quantitative Research Methods and the Research Report must stay compulsory and in sequence. New AI-verification, compliance or sustainability-assurance content should extend this sequence, not substitute for it. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | Research Design explicitly assesses identifying strengths/limitations of alternative research strategies (a defended trade-off decision), feeding into the Research Report's required original-research findings, whose outcome is genuinely undetermined at the point of design — real uncertainty with accountability to a supervisor and the program coordinator. | Redesign must preserve Research Design's assessed critique of alternative research strategies and the Research Report's genuinely undetermined findings. A new authentic or work-situated task should add a further defended trade-off decision, not replace the existing one with a scripted exercise. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | W2 | 0 | 1 | +1 workplace | 8 / 15 | 2 / 9 |
| P2 | W2 | 1 | 2 | +1 workplace | 8 / 15 | 3 / 9 |
| P3 | W2 | 2 | 3 | +1 workplace | 8 / 15 | 4 / 9 |
| P4 | W3 | 0 | 1 | +1 workplace | 8 / 15 | 5 / 9 |
| P5 | W3 | 1 | 2 | +1 workplace | 8 / 15 | 6 / 9 |
| P6 | W3 | 2 | 3 | +1 workplace | 8 / 15 | 7 / 9 |
| P7 | C1 | 1 | 2 | +1 adaptive | 9 / 15 | 7 / 9 |
| P8 | C1 | 2 | 3 | +1 adaptive | 10 / 15 | 7 / 9 |
| P9 | C2 | 1 | 2 | +1 adaptive | 11 / 15 | 7 / 9 |
| P10 | C2 | 2 | 3 | +1 adaptive | 12 / 15 | 7 / 9 |
| P11 | C3 | 1 | 2 | +1 adaptive | 13 / 15 | 7 / 9 |
| P12 | C3 | 2 | 3 | +1 adaptive | 14 / 15 | 7 / 9 |
| P13 | W1 | 1 | 2 | +1 workplace | 14 / 15 | 8 / 9 |
| P14 | W1 | 2 | 3 | +1 workplace | 14 / 15 | 9 / 9 |
| P15 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
