// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Bachelor of Commerce (MONASH-B2001) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Bachelor of Commerce (MONASH-B2001)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-09-07 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-monash-b2001.md
**Position basis:** Destination AI Exposure 88.71 (field basis) × Curriculum Adaptiveness 5/15 (v4.2 draft, sub-scale A) · Workplace practice 3/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a field basis (Jobs and Skills Australia Higher Education Outcomes (JSA HEO) field 0803 Business and Management), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

The Bachelor of Commerce passes both gates. G1 rests on the staged prerequisite/progression condition: a compulsory six-unit disciplinary core plus a required eight-unit major carrying a documented level-1 to level-3 progression, with an overall rule requiring at least four level-3 units from the Faculty of Business and Economics — a specialist core with progressive depth, not the generic or interchangeable content the FAIL condition describes. G2 rests on course outcome 6's requirement to critically evaluate the implications of various options, MGC1010's Project (40%) assessing critical evaluation of managerial decisions against ethical, environmental and social responsibility, and ETC1000's modelling of uncertainty and risk, with a capstone unit required of every student; the gate's own rationale notes the evidence is thin on documented defence of trade-offs, since core assessment tasks in the extract are named only by type and weight, so this PASS sits closer to the bar than G1's.

Every one of the eight items sits at level 1 of 3: adaptiveness is 5/15 and workplace practice 3/9, both close to the instrument floor. The same pattern repeats across C1–C5 and W1–W2: teamwork, reflection, digital or AI content, transfer and professional communication are all named in course-level or unit-level outcomes, but the documented core assessment in the three compulsory Part A units (MGC1010, ECC1000, ETC1000), BTC1110 and MKC1200 is recorded only by task type and weight (Project, Exercise, Quiz, Examination, Presentation), with no assessed collaborative task, criterion-referenced appraisal, AI content, novel-context application, or professional-genre audience beyond the teaching team. W3 shows the same gap from the opposite direction: BEX3350's consulting project for an actual client, together with internship and tax-clinic options, already reach level 2 or above of their own anchors, but sit as one route among several inside the Part C capstone portfolio — which equally admits taught capstone units and international-experience programs — rather than a requirement every graduate meets.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C1 Distributed cognition & relational capability | Adaptive | 1 / 3 | 2 | Direct — Section 5 CI-3 and Section 3 Theme 4 identify clerical, administrative and retail entry destinations as the field's most automation-exposed group, with JSA (2025) naming routine, rules-based office tasks as most readily automated. No documented core assessment in MGC1010, ECC1000 or ETC1000 carries a collaborative or stakeholder task that would distinguish a graduate from that exposed pool. | 1 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | Direct — Section 3 Theme 1 records APESB professional standards requiring auditors to verify automated ledger anomaly-detection algorithms and maintain documented audit-trail logs for AI-generated financial estimates — appraisal of a tool's output as a professional duty. No documented core assessment in the compulsory Part A units includes criterion-referenced appraisal of quality. | 2 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | Direct — Section 3 Theme 1 (the APESB AI-verification standard) and Section 4's rising ASRS sustainability-assurance keyword both describe AI-adjacent professional obligations in the accounting destination. Digital content in the core extract is limited to BTC1110's privacy and data-protection law and ETC1000's statistical data handling; no core unit addresses AI capabilities, limitations or governance. | 3 |
| C4 Life-long learning & transfer | Adaptive | 1 / 3 | 2 | Direct — Section 3 Theme 2 and Section 5 CI-2 describe mandatory Australian Sustainability Reporting Standards creating an acute, dated, regulator-created shortage of accounting graduates able to carry existing assurance or analysis methodology into a new, unfamiliar disclosure context. No documented core task in MGC1010, ECC1000 or ETC1000 requires transfer to a novel or unfamiliar problem. | 4 |
| C5 Inquiry & evidence generation | Adaptive | 1 / 3 | 2 | Direct — Section 2 Signal 1 and Section 4 record Audit sampling as a rising, recurring keyword across 6,240 accountant and auditor postings, and Section 3 Theme 1 requires auditors to defend algorithmic sampling and estimation decisions. ETC1000 is an introductory quantitative-methods unit confined to interpreting supplied data; no documented core task requires students to design their own inquiry or defend a chosen methodology. | 5 |
| **Adaptive capabilities** | **Adaptive** | **5 / 15** | **10** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Direct — Section 3 Theme 3 and Section 5 CI-4 record that the Privacy Act 1988 Australian Privacy Principles bind the entities these graduates enter, with nothing in the advertisement sample suggesting the obligation is delegated to a specialist; Section 1 shows Accountant (General) and General Clerk among the field's top entry occupations. MKC1200's Presentation (30%) documents no audience beyond the teaching team, and no core assessment carries a professional-conduct or disclosure-handling criterion. | 6 |
| W2 Authentic task design | Workplace | 1 / 3 | 2 | Direct — Section 5 CI-3 argues that making a professional-grade artefact assessable early is what would distinguish a commerce graduate's transcript from the field's general clerical and retail entry pool (Section 1; Section 3 Theme 4). Documented core assessment in the extract is confined to Examinations, Exercises, Quizzes and undescribed Projects; no task reproduces a professional artefact judged against practice criteria. | 7 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | Direct — Section 2 Signal 1 names the Big Four and mid-tier firms (PwC, Deloitte, EY, KPMG, BDO, Grant Thornton) as the most frequent employers in the largest destination occupation, and Section 3 Theme 1 ties audit practice to documented, supervised evidence trails. BEX3350's consulting project and available internships sit as options within the Part C capstone portfolio rather than a required unit, so no core unit yet guarantees a supervised workplace placement for every graduate. | 8 |
| **Workplace practice** | **Workplace** | **3 / 9** | **6** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Convert one assessment task in MGC1010 or ECC1000 into a graded group project with individually assessed contribution, answering the market's finding that clerical, administrative and retail entry destinations are the field's most automation-exposed group (Section 5 CI-3), so collaborative practice becomes a compulsory core requirement rather than an outcome-only claim. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Extend the Part C capstone unit to require a documented allocation of tasks and at least one nominated digital or AI tool across team members, so coordination spans both people and tools as C1's top anchor requires. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Introduce a structured, rubric-marked peer-review stage in the ETC1000 Project (20%), answering the APESB requirement that auditors now verify — not merely produce — an automated analytical output (Section 3 Theme 1). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Once peer review is embedded, add a documented reliance-and-override log in which students record and justify where they accepted or rejected a supplied simulated automated estimate, mirroring the audit-trail documentation duty Section 3 Theme 1 describes. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Extend ETC1000's statistical content into an assessed module on the capabilities and limits of AI-assisted analysis tools, answering the AI-verification duty in Section 3 Theme 1 and the rising ASRS sustainability-assurance skill in Section 4. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Add an assessed governance task, sitting alongside BTC1110's existing privacy and data-protection content, in which students audit a supplied AI-generated ledger anomaly flag for bias, accountability and transparency — moving from tool-adjacent legal content to critique of the AI system itself. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 1 → 2 | "At least one core assessment requires application to novel or unfamiliar problems — case variation, unseen datasets, cross-context projects." | Add a sustainability-disclosure case to MGC1010 or ETC1000 that carries an existing analysis or evaluation method into an unfamiliar context, answering the acute, regulator-created ASRS skills shortage in Section 3 Theme 2 and Section 5 CI-2. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Restructure the Part C capstone selection so every student's chosen unit requires a self-scoped project component — identifying and closing an individually chosen knowledge gap — rather than leaving self-scoping to BEX3350 alone. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 1 → 2 | "Students design and conduct an inquiry with methodology selection and data collection, assessed." | Add a data-collection component to ETC1000's Project (20%) requiring students to select and justify a sampling or survey method, the rising Audit sampling skill named across 6,240 accountant and auditor postings (Section 2 Signal 1; Section 4). | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make a primary-evidence project — collecting data, applying a defended methodology, staged supervised review — a required element of the Part C capstone rather than an optional route, answering Section 3 Theme 1's requirement that sampling and estimation decisions be defensible under scrutiny. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Replace the MKC1200 Presentation (30%) audience with a client-style brief addressed to a hypothesised small-business or audit client, judged against professional-communication criteria drawn from practice, reflecting Section 5 CI-4's finding that Privacy Act disclosure obligations bind these graduates' first employers directly. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Recruit a small practitioner panel to judge the redesigned MKC1200 brief each offering, assessing professional conduct and disclosure handling explicitly, so accountability runs to a real external audience matching the named employer set in Section 2 Signal 1. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Redesign the ETC1000 Project (20%) or MGC1010 Project (40%) as a single professional artefact — a compliance memo, an audit-scope note, or a client-facing analysis — judged against practice criteria, so the transcript records more than the field's general clerical and retail entry pool named in Section 5 CI-3. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Carry the professional-artefact format into the Part C capstone across every selectable option, adding a genuine constraint of practice such as a real or externally supplied brief with a resource or time limit, consistent with Section 3 Theme 2's picture of already time- and disclosure-constrained assurance work. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Make BEX3350's consulting project for an actual client organisation — or an equivalent internship placement — a compulsory core unit rather than one of several Part C capstone-portfolio alternatives, so every graduate, not only those who elect it, is supervised in a real workplace or client setting. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the now-core placement into a supervised sequence with structured reflection and documented accountability to the host, at the scale the sector's dominant employers already expect of graduate entrants (PwC, Deloitte, EY, KPMG, BDO, Grant Thornton — Section 2 Signal 1); justify the sequence by skill development and professional identity rather than employment rates, and budget travel or income support so an unpaid or relocation-dependent placement does not add an equity cost. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| P1 | C1 | Clerical, administrative and retail entry destinations are the field's most automation-exposed group; JSA (2025) names routine, rules-based office tasks as most readily automated. | Section 1; Section 3 Theme 4; Section 5 CI-3 | MEDIUM (Office Clerks, General — scholarly and grey-literature studies) |
| P2 | C2 | APESB professional standards require auditors to verify automated ledger anomaly-detection algorithms and maintain documented audit-trail logs for AI-generated financial estimates. | Section 3 Theme 1 | HIGH (Accountants and Auditors — regulatory and statutory instruments) |
| P3 | C3 | The same APESB AI-verification standard, plus a rising ASRS sustainability-assurance keyword across the accountant/auditor advertisement sample, describe AI-adjacent professional obligations the core does not yet assess. | Section 3 Theme 1; Section 4 | HIGH (Accountants and Auditors — regulatory and statutory instruments) |
| P4 | C4 | Mandatory Australian Sustainability Reporting Standards create an acute, dated shortage of accounting graduates able to apply assurance methodology to multi-capital greenhouse-gas and climate-risk disclosure. | Section 3 Theme 2; Section 5 CI-2 | HIGH (Accountants and Auditors — scholarly and grey-literature studies) |
| P5 | C5 | Audit sampling is a rising, recurring keyword across 6,240 accountant/auditor postings, and APESB now requires sampling and estimation decisions to be defensible. | Section 2 Signal 1; Section 3 Theme 1; Section 4 | HIGH (Accountants and Auditors — job-advertisement signals) |
| P6 | W1 | Privacy Act 1988 Australian Privacy Principles bind the entities these graduates enter directly, with no delegation to a specialist; General Clerk and Accountant (General) sit among the field's top entry occupations. | Section 1; Section 3 Theme 3; Section 5 CI-4 | MEDIUM (Office Clerks, General — regulatory and statutory instruments) |
| P7 | W2 | Making a professional-grade artefact assessable early is what would separate a commerce transcript from the field's general clerical and retail entry pool. | Section 1; Section 3 Theme 4; Section 5 CI-3 | MEDIUM (Office Clerks, General — scholarly and grey-literature studies) |
| P8 | W3 | The Big Four and mid-tier firms (PwC, Deloitte, EY, KPMG, BDO, Grant Thornton) are the most frequent employers in the largest destination occupation, which is bound to documented, supervised audit-trail practice. | Section 2 Signal 1; Section 3 Theme 1 | HIGH (Accountants and Auditors — job-advertisement signals) |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C2 | Introduce a structured, rubric-marked peer-review stage in the ETC1000 Project (20%). | C2 level 2 (criterion-referenced appraisal of quality) | Low | Term 1; rubric update only | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P2 | C3 | Extend ETC1000's statistical content into an assessed module on AI capabilities and limits. | C3 level 2 (capabilities and limitations discussed and assessed) | Low-Medium | Term 1; syllabus update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P3 | C5 | Add a data-collection and sampling-justification component to ETC1000's Project. | C5 level 2 (methodology selection and data collection assessed) | Low-Medium | Term 1; assessment brief update | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P4 | C1 | Convert one MGC1010 or ECC1000 task into a group assignment with individually assessed contribution. | C1 level 2 (collaborative practice assessed) | Low-Medium | Term 2; assessment brief update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P5 | C4 | Add a sustainability-disclosure novel-context case to MGC1010 or ETC1000. | C4 level 2 (application to a novel or unfamiliar problem) | Low-Medium | Term 2; new case, no new credit points | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P6 | W1 | Replace the MKC1200 Presentation audience with a client-style advisory brief marked against professional-communication criteria. | W1 level 2 (recognised professional genre or external audience) | Medium | Term 2; assessment redesign | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P7 | W2 | Redesign the ETC1000 or MGC1010 Project as a single professional artefact judged against practice criteria. | W2 level 2 (professional task reproduced end to end) | Medium | Term 2; assessment redesign | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P8 | W3 | Make BEX3350's consulting project (or an equivalent internship) a compulsory core placement rather than one of several Part C capstone alternatives. | W3 level 2 (core placement with practitioner supervision and assessment) | High | Next course review; course-structure update | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P9 | C2 | Attach an assessed reliance-and-override log to the ETC1000 peer-review task. | C2 level 3 (reliance decisions documented and justified) | Medium | Term 3; assessment brief update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P10 | C3 | Add an assessed AI-governance audit task alongside BTC1110's privacy content, built on the new AI-literacy module. | C3 level 3 (critique or governance of AI systems) | Medium | Term 3; subject update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P11 | C1 | Extend the Part C capstone brief to require a documented allocation of tasks across team members and at least one digital or AI tool. | C1 level 3 (coordination across people and tools) | Medium-High | Next course review; capstone structure update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P12 | C4 | Restructure the Part C capstone selection so every option requires a self-scoped project component, identifying and closing an ASRS-related knowledge gap. | C4 level 3 (self-scoped capstone; independent learning progression) | Medium-High | Next course review; capstone structure update | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P13 | C5 | Require a primary-evidence sampling project with a staged supervised methodology defence in the Part C capstone. | C5 level 3 (required primary-evidence project, defended under scrutiny) | Medium-High | Next course review; capstone staging update | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P14 | W1 | Recruit a practitioner panel to judge the redesigned MKC1200 brief, assessing professional conduct explicitly. | W1 level 3 (external practitioner judge; conduct assessed) | Medium-High | Next course review; external-judge coordination | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P15 | W2 | Carry the professional-artefact format into the Part C capstone with a genuine constraint of practice. | W2 level 3 (assessment spine with a genuine constraint of practice) | Medium-High | Next course review; capstone structure update | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P16 | W3 | Extend the now-core placement into a supervised sequence with structured reflection and documented host accountability, budgeting equity support for unpaid or relocation-dependent placements. | W3 level 3 (extended, supervised, assessed placement sequence) | High | Following course review; partner and funding agreements | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | PASS on the staged prerequisite/progression condition: the program documents a compulsory six-unit disciplinary core plus a required eight-unit major carrying a documented level-1 to level-3 progression, with an overall rule requiring at least four level-3 units from the Faculty of Business and Economics. That is a specialist core with progressive depth in one discipline, not the generic or interchangeable content the FAIL condition describes. | Redesign must preserve the compulsory six-unit disciplinary core and the eight-unit major's level-1-to-level-3 progression, including the rule requiring at least four level-3 Faculty of Business and Economics units. New collaboration, digital-literacy or AI-governance content sits alongside this progression and does not displace or thin it. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | PASS: assessment is not confined to recall or scripted responses. Course outcome 6 requires critical evaluation of the implications of various options, MGC1010 requires critical evaluation of managerial decisions against ethical, environmental and social responsibility and carries Project assessment at 40%, and ETC1000 requires modelling uncertainty and assessing risk. A capstone unit consolidating the course is required of every student. The evidence is thin on documented defence of trade-offs, since assessment tasks are named only by type and weight, but the FAIL condition (recall or scripted responses only) is clearly not met. | The gate's own rationale flags the PASS as resting on outcome-6 wording, MGC1010's ethical/environmental/social evaluation and ETC1000's uncertainty modelling rather than on documented defended trade-off decisions, so it is close to the bar. Redesign must keep the required capstone, and the interventions above (C5's methodology defence, W2's constrained professional artefact) should be built to also produce a documented trade-off decision, so the gate strengthens rather than staying fragile. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C1 | 1 | 2 | +1 adaptive | 6 / 15 | 3 / 9 |
| P2 | C1 | 2 | 3 | +1 adaptive | 7 / 15 | 3 / 9 |
| P3 | C2 | 1 | 2 | +1 adaptive | 8 / 15 | 3 / 9 |
| P4 | C2 | 2 | 3 | +1 adaptive | 9 / 15 | 3 / 9 |
| P5 | C3 | 1 | 2 | +1 adaptive | 10 / 15 | 3 / 9 |
| P6 | C3 | 2 | 3 | +1 adaptive | 11 / 15 | 3 / 9 |
| P7 | C4 | 1 | 2 | +1 adaptive | 12 / 15 | 3 / 9 |
| P8 | C4 | 2 | 3 | +1 adaptive | 13 / 15 | 3 / 9 |
| P9 | C5 | 1 | 2 | +1 adaptive | 14 / 15 | 3 / 9 |
| P10 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 3 / 9 |
| P11 | W1 | 1 | 2 | +1 workplace | 15 / 15 | 4 / 9 |
| P12 | W1 | 2 | 3 | +1 workplace | 15 / 15 | 5 / 9 |
| P13 | W2 | 1 | 2 | +1 workplace | 15 / 15 | 6 / 9 |
| P14 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 7 / 9 |
| P15 | W3 | 1 | 2 | +1 workplace | 15 / 15 | 8 / 9 |
| P16 | W3 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
