// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Applied Econometrics (MC-AEMTRCS) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Applied Econometrics (MC-AEMTRCS)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-29 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-aemtrcs.md
**Position basis:** Destination AI Exposure 96.53 (cognate basis) × Curriculum Adaptiveness 6/15 (v4.2 draft, sub-scale A) · Workplace practice 3/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a cognate basis (Master of Economics), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

Master of Applied Econometrics scores 6/15 on adaptive capabilities and 3/9 on workplace practice, with headroom concentrated in hybrid metacognition and evaluative judgement (C2, 0/3) and shallower gaps across digital and AI literacy (C3), life-long learning and transfer (C4), and all three workplace-practice items. The market evidence is strongest where it names the accounting and audit destinations directly — mandatory AI-verification duties under APESB standards (Theme 3) and an acute sustainability-assurance skills shortage under the mandatory Australian Sustainability Reporting Standards (Theme 4) — and weaker for economists, whose peak body has issued no binding AI conduct code (Theme 5). Both gates pass: the program's specialist econometrics core and its required real-data research project are the foundation the interventions below build on, not something they should displace.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 0 / 3 | 3 | The five falling clerical and administrative skills in §4 (administration, clerical, data entry, office administration, reception) sit inside the family Theme 2 (§3) names as the clear automation-exposed group; a program whose only link to entry-level office work is producing first-draft output, not evaluating it, graduates students into a shrinking segment of that destination (§1 Office Clerks, General). | 1 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | Theme 3 (§3) obliges auditors under APESB professional standards to verify automated anomaly-detection algorithms and keep documented AI audit trails, and Theme 5 (§3) records that economists have no binding AI-specific code beyond the voluntary national AI Ethics Principles — together, the destination occupations need graduates who can critique and govern AI tools, not only operate them. | 2 |
| C4 Life-long learning & transfer | Adaptive | 1 / 3 | 2 | Theme 4 (§3) reports an acute shortage of accounting graduates skilled in multi-capital greenhouse-gas assurance and climate-risk governance under the mandatory Australian Sustainability Reporting Standards — a named, unfilled skill gap the program can address by requiring students to apply their methods to this unfamiliar regulatory problem. | 3 |
| C1 Distributed cognition & relational capability | Adaptive | 2 / 3 | 1 | Theme 6 (§3) finds AI now embedded across five economics research streams, including forecasting and prediction, reshaping how economists conduct their analytical work — evidence that entry-level economist tasks increasingly require coordinating between a person and an AI or statistical tool, not that either alone suffices. | 7 |
| C5 Inquiry & evidence generation | Adaptive | 2 / 3 | 1 | Theme 4's (§3) ASRS shortage and Theme 3's (§3) AI-verification requirement both point to Audit sampling (§4, stable demand) shifting from a manual technique to a defended verification skill layered on automated tooling and new assurance standards — work that increasingly means designing and defending an inquiry, not only executing a known method. | 8 |
| **Adaptive capabilities** | **Adaptive** | **6 / 15** | **9** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Theme 4 (§3) ties ASRS-mandated sustainability assurance reporting to an external, regulator-facing audience — the same professional-genre and external-accountability gap that the accounting and audit destination occupations (§1) show against the level-2 and level-3 anchors. | 4 |
| W2 Authentic task design | Workplace | 1 / 3 | 2 | Theme 4 (§3) names sustainability assurance and climate-risk governance as a skills gap under the mandatory ASRS regime — a real, practice-drawn problem rather than a case study, of the kind a core unit could reproduce end to end, matching what the level-2 and level-3 anchors test for. | 5 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | Signal 2 (§2) names the employers most often advertising this program's largest destination family — PwC, Deloitte, EY, KPMG, BDO, Grant Thornton, all professional-services firms whose graduate entry runs through structured, practitioner-supervised training — evidence for the value of supervised work-situated learning, not for higher employment odds. | 6 |
| **Workplace practice** | **Workplace** | **3 / 9** | **6** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | 0 → 1 | "Reflection or self-assessment appears in outcomes or graduate attributes, but no core unit assesses it against criteria." | Add a reflection or self-assessment component to an existing core assessment (for example BUSA90520's data project) asking students to appraise the quality of their own or a tool's first-draft output against a stated standard, responding to the clerical and administrative automation exposure Theme 2 (§3) names (cost: revised assessment brief, no new unit). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Extend that reflection into a criterion-referenced appraisal task — peer review, structured critique, or marking against exemplars — of AI-generated first-draft output, closing the gap between producing and evaluating output that CI-1 (§5) names (cost: new marking rubric and moderator time). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Require students to document and justify when they relied on or overrode an AI tool's output in a core assessment, evidencing the verification discipline Theme 3 (§3) requires of auditors checking automated anomaly-detection algorithms (cost: process-focused assessment design and marking time). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Extend an existing methods or audit-related core unit to address AI capabilities and limitations together, not only tool operation, drawing on the voluntary national AI Ethics Principles that Theme 5 (§3) identifies as the only applicable standard for economists (cost: staff time to develop teaching material, no new unit, per CI-5 §5). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Add an assessed task requiring students to verify the output of an automated anomaly-detection tool against a sampling standard, meeting the documented AI-audit-trail obligation Theme 3 (§3) places on auditors and matching CI-2's (§5) audit-sampling action (cost: access to or simulation of a detection tool, plus marking time). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 1 → 2 | "At least one core assessment requires application to novel or unfamiliar problems — case variation, unseen datasets, cross-context projects." | Introduce an elective or embedded module on sustainability assurance and climate-risk governance, addressing the acute graduate shortage Theme 4 (§3) reports under the mandatory Australian Sustainability Reporting Standards (cost: new curriculum content and, if elective, competition for enrolment against existing options, per CI-3 §5). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Fold that sustainability-assurance content into the required capstone (ECOM90001/ECOM90002) as one of the novel problem contexts students may choose for their staged research project, giving the program's existing structured-progression capstone a documented, market-named unfamiliar-problem application (cost: capstone brief revision and supervisor familiarity with the new content area). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Add a client-facing or regulator-facing deliverable — for example a short ASRS-style sustainability assurance memo — to a core unit, judged against professional-practice criteria, responding to the external-audience gap Theme 4 (§3) implies for ASRS-mandated reporting (cost: new artefact design and practice-drawn marking criteria). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Sequence that professional-genre task across two or more core units and add assessment by, or delivery to, a real external audience such as a practising auditor or industry panel, with professional conduct named among the criteria — extending the accountability standard Theme 3 (§3) documents for auditors' own AI-verification duties (cost: sourcing and briefing external assessors, additional coordination each term). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Redesign the existing data-project assessment (BUSA90520 or ECOM90025) around a real sustainability-assurance or climate-risk problem, producing the kind of assurance artefact a practitioner would produce and marking it against practice-drawn criteria, directly answering the shortage Theme 4 (§3) names (cost: sourcing a real or realistic dataset and rewriting marking criteria, per CI-3 §5). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Make an authentic, practice-based assurance or audit task the spine of the core sequence — one per stage, culminating in the ECOM90002 capstone — with at least one carrying a genuine practice constraint such as an externally supplied, ambiguous ASRS scenario or a real resource limit (cost: coordinated redesign across multiple core units and consistent practitioner-sourced criteria). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Add a required, short work-situated component to a core unit — for example a supervised live-client or professional-community project run through the current Business Practicum or Internship electives' host network — rather than leaving it as an optional elective, following the structured, supervised-entry pattern of the audit and accounting employers Signal 2 (§2) names (cost: securing host placements and supervisor time; this does not claim a graduate-outcomes benefit — Jackson & Collings [28] found WIL does not raise employment rates). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend that placement into a required sequence — an extended practicum or two shorter ones — in the core, supervised and assessed with structured reflection and accountability to the host, matching the scale of graduate-entry training the professional-services employers in Signal 2 (§2) run (cost: substantial coordination and host capacity; note the equity cost of unpaid or relocation-dependent placements [30]). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Add a required forecasting or econometric-modelling assessment (in ECOM90001, ECOM90002 or an advanced capstone) that documents and marks the division of work between the student and an AI or statistical tool, responding to Theme 6's (§3) finding that AI is now embedded across five economics research streams including forecasting (cost: revised assessment brief and rubric, no new unit, per CI-4 §5). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make the existing Proposal, Progress and Submission Report sequence in ECOM90001/ECOM90002 an explicit staged supervised review with documented defence of methodology choices, formalising what is currently implicit staging, so the required primary-evidence project meets the level-3 anchor's defence-under-scrutiny test, consistent with the verification standard Theme 3 (§3) sets for auditors defending their own methods (cost: revised assessment criteria and marking guide, no new unit). | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| Automation-exposed clerical and administrative destinations need graduates who evaluate AI output, not only produce it | C2, C3 | Theme 2 names clerical and secretarial work the clear automation-exposed group; five clerical skills are falling in the job-ad sample (§4). | CI-1 (§5), sourced from Theme 2 (§3) and the skill shift table (§4) | MEDIUM (§6 Office Clerks, General — scholarly and grey-literature studies) |
| APESB standards require auditors to verify automated anomaly-detection tools and keep documented AI audit trails | C2, C3 | APES 110's technology and AI provisions bind all registered company auditors and public-practice accountants in Australia. | Theme 3 (§3) | HIGH (§6 Accountants and Auditors — regulatory and statutory instruments) |
| Mandatory ASRS reporting creates an acute shortage of sustainability-assurance and climate-risk-governance skilled graduates | C4, W2 | A peer-reviewed study of the changing competency profile of Australian auditors under the Australian Sustainability Reporting Standards. | Theme 4 (§3) | HIGH (§6 Accountants and Auditors — scholarly and grey-literature studies) |
| Audit sampling stays in demand but as a verification skill layered on automated tooling, not a manual-only technique | C3, C5 | Audit sampling recurs as a stable-demand keyword in the Accountants and Auditors job-ad sample (6,240 postings). | §4 skill shift table; Signal 2 (§2) | HIGH (§6 Accountants and Auditors — job-advertisement signals) |
| AI is now embedded across five economics research streams, including forecasting and prediction | C1, C5 | A systematic review of 2,231 economics articles finds AI embedded in economic modelling, macroeconomics, prediction and data-analysis methods. | Theme 6 (§3) | HIGH (§6 Economists — scholarly and grey-literature studies) |
| No binding AI-specific code governs economists' own analytical work | C3 | The Economic Society of Australia has issued no binding AI conduct code; the only applicable instrument is the voluntary national AI Ethics Principles. | Theme 5 (§3) | HIGH for the cited AI Ethics Principles instrument (§6 Economists — regulatory and statutory instruments); the no-binding-code finding itself is flagged as a LOW-confidence coverage gap (§6 Economists — L1 via Economic Society of Australia) |
| Professional-services employers advertising this program's largest destination family run structured, practitioner-supervised graduate entry | W1, W3 | PwC, Deloitte, EY, KPMG, BDO and Grant Thornton are the employers named most often in the Accountants and Auditors job-ad sample. | Signal 2 (§2) | HIGH (§6 Accountants and Auditors — job-advertisement signals) |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C3 | Add explicit AI capability, limitation and governance content — drawing on the voluntary national AI Ethics Principles — to an existing core methods unit. | Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed. | low | Immediate — no new unit; a lecture/tutorial and assessment-criteria redesign in an existing core unit. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P2 | C2 | Add a reflection or self-assessment component to an existing core assessment asking students to appraise the quality of their own or a tool's first-draft output against a stated standard. | Reflection or self-assessment appears in outcomes or graduate attributes, but no core unit assesses it against criteria. | low | Immediate, alongside the C3 redesign — same review cycle. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P3 | C1 | Require a forecasting or econometric-modelling assessment that documents and marks the division of work between the student and an AI or statistical tool. | Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems. | low | Next capstone offering (ECOM90002) — revised assessment brief only. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P4 | C5 | Formalise the Proposal, Progress and Submission Report sequence in ECOM90001/ECOM90002 as an explicit staged supervised review with documented methodology defence. | A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review). | medium | Same capstone redesign cycle as the C1 change (both touch ECOM90001/ECOM90002). | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P5 | C2 | Extend the C2 reflection component into a criterion-referenced appraisal task — peer review, structured critique, or marking against exemplars — of AI-generated first-draft output. | Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars. | medium | Following term, once the level-1 reflection component is embedded. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P6 | C3 | Add an assessed task requiring students to verify the output of an automated anomaly-detection tool against a sampling standard. | Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation. | medium | After the level-2 AI-governance content lands; needs access to or simulation of a detection tool. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P7 | C4 | Introduce an elective or embedded module on sustainability assurance and climate-risk governance. | At least one core assessment requires application to novel or unfamiliar problems — case variation, unseen datasets, cross-context projects. | medium | Curriculum-committee approval cycle; lands ahead of the W2 assessment redesign (next row), which draws on the same content. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P8 | W1 | Add a client-facing or regulator-facing deliverable — for example a short ASRS-style sustainability assurance memo — to a core unit, judged against professional-practice criteria. | At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice. | medium | Pairs with the C4 sustainability content; same term. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P9 | W2 | Redesign the existing data-project assessment (BUSA90520 or ECOM90025) around a real sustainability-assurance or climate-risk problem, producing the artefact a practitioner would produce. | At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice. | high | After the C4 module content exists to draw the scenario from. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P10 | W3 | Add a required, short work-situated component to a core unit — for example a supervised live-client or professional-community project run through the current Business Practicum or Internship host network. | A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project. | high | Longest lead time — begin host and supervisor negotiation immediately, land last. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | The program documents a coherent, all-compulsory-plus-staged-choice specialist core in econometrics with progressive methodological depth: Basic Econometrics (multiple regression) feeds directly into the required capstone Econometrics 2 ('Extensions of the multiple regression model are examined'), which in turn is a prerequisite gate for the choice of advanced capstone (Applied Microeconometric Modelling / Time Series Analysis / Quantitative Analysis of Finance I), with an explicit staged-prerequisite note steering subject choice by prior completion. | New sustainability-assurance, AI-governance or documentation content must sit alongside, not displace, the compulsory Basic Econometrics to Econometrics 2 to advanced-capstone prerequisite chain that carries this gate; do not reduce contact hours or assessment weight in the specialist econometrics core to make room. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | The required ECOM90001/ECOM90002 research and capstone projects require students to formulate their own hypotheses, work with real-world (not scripted/textbook) data, and diagnose and remediate model misspecification — decisions with real uncertainty and no single scripted answer, defended in a formally assessed report — rather than recall or scripted responses only. | Any new documentation or process-focused assessment — recording AI-tool reliance decisions, staging a supervised methodology defence — must be layered onto the existing ECOM90001/ECOM90002 real-data research project, preserving genuine uncertainty and a defended report; do not replace it with a scripted or templated exercise. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C2 | 0 | 1 | +1 adaptive | 7 / 15 | 3 / 9 |
| P2 | C2 | 1 | 2 | +1 adaptive | 8 / 15 | 3 / 9 |
| P3 | C2 | 2 | 3 | +1 adaptive | 9 / 15 | 3 / 9 |
| P4 | C3 | 1 | 2 | +1 adaptive | 10 / 15 | 3 / 9 |
| P5 | C3 | 2 | 3 | +1 adaptive | 11 / 15 | 3 / 9 |
| P6 | C4 | 1 | 2 | +1 adaptive | 12 / 15 | 3 / 9 |
| P7 | C4 | 2 | 3 | +1 adaptive | 13 / 15 | 3 / 9 |
| P8 | W1 | 1 | 2 | +1 workplace | 13 / 15 | 4 / 9 |
| P9 | W1 | 2 | 3 | +1 workplace | 13 / 15 | 5 / 9 |
| P10 | W2 | 1 | 2 | +1 workplace | 13 / 15 | 6 / 9 |
| P11 | W2 | 2 | 3 | +1 workplace | 13 / 15 | 7 / 9 |
| P12 | W3 | 1 | 2 | +1 workplace | 13 / 15 | 8 / 9 |
| P13 | W3 | 2 | 3 | +1 workplace | 13 / 15 | 9 / 9 |
| P14 | C1 | 2 | 3 | +1 adaptive | 14 / 15 | 9 / 9 |
| P15 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
