// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Clinical Research (N01AA) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Clinical Research (N01AA)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-30 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-n01aa.md
**Position basis:** Destination AI Exposure 75.80 (field basis) × Curriculum Adaptiveness 8/15 (v4.2 draft, sub-scale A) · Workplace practice 6/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a field basis (Jobs and Skills Australia Higher Education Outcomes (JSA HEO) field 019901 Medical Science), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

Both gates pass and workplace practice sits at the mid-band, but the two lowest-scoring items, C3 (Digital and AI literacy) and C4 (Life-long learning and transfer), sit at level 1: AI content lives only in an elective and novel-problem transfer is claimed in outcome statements but not assessed. Section 3 names AHPRA-bounded clinical judgement, multidisciplinary case formulation and hands-on procedural work as what employers reward, and routine administrative work as the exposed comparator.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | §3 Theme 1: the AHPRA mandate keeps clinical decision-making non-delegable, so AI content needs to teach the governance boundary, not just tool operation (currently only in the COMP90094 elective). | 1 |
| C4 Life-long learning & transfer | Adaptive | 1 / 3 | 2 | §4 skill rows: Clinical diagnostic acumen and Multidisciplinary case formulation are both rising in the 5,120-posting sample, naming novel-case application as market-rewarded, not yet a core-assessed requirement. | 2 |
| C1 Distributed cognition & relational capability | Adaptive | 2 / 3 | 1 | §2 Signal 1 and §4: Multidisciplinary case formulation recurs as a rising skill keyword across 5,120 postings, naming team-based, tool-coordinated case work as market-rewarded. | 3 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 2 / 3 | 1 | §3 Theme 1: AHPRA requires practitioners to distinguish decision-support tools from delegable clinical tasks, a reliance judgement current assessment does not yet require students to document. | 4 |
| C5 Inquiry & evidence generation | Adaptive | 2 / 3 | 1 | §6 Evidence confidence and gaps: the destination basis is field-of-education grain, not program grain (LOW confidence), so a required primary-evidence project would let the program generate its own graduate-outcome evidence rather than rely on the field-wide JSA HEO figures. | 5 |
| **Adaptive capabilities** | **Adaptive** | **8 / 15** | **7** | — | — |
| W1 Professional communication & conduct | Workplace | 2 / 3 | 1 | §2 Signal 1 and §4: Patient communication and Multidisciplinary case formulation both recur as rising skill keywords across the 5,120-posting sample, naming assessed communication to a real clinical audience as market-rewarded. | 6 |
| W2 Authentic task design | Workplace | 2 / 3 | 1 | §3 Theme 2: physical bedside examinations and intraoperative procedural adjustments carry near-zero automated substitution potential, naming hands-on clinical task design as the durable comparator to classroom case study. | 7 |
| W3 Work-situated learning | Workplace | 2 / 3 | 1 | §3 Theme 2 and §2 Signal 1: bedside and procedural clinical work is named durable against automation, and the 5,120-posting employer sample concentrates in hospital and health-service settings, both naming supervised clinical placement as market-aligned. | 8 |
| **Workplace practice** | **Workplace** | **6 / 9** | **3** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Add AI capabilities-and-limits content to a core unit alongside the existing COMP90094 elective, discussing use and limits under AHPRA's non-delegable clinical-decision-making mandate (§3 Theme 1) rather than leaving AI in an elective only (cost: one core-unit redesign). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Extend that core content to an assessed critique of a diagnostic-support tool's governance boundary, where AHPRA draws the line between decision support and a delegable task (§3 Theme 1), beyond describing how the tool works (cost: one assessment redesign plus AHPRA-liaison time). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 1 → 2 | "At least one core assessment requires application to novel or unfamiliar problems — case variation, unseen datasets, cross-context projects." | Add a core assessment applying diagnostic and case-formulation skills to a novel or unseen case, drawing on the market-rewarded Clinical diagnostic acumen and Multidisciplinary case formulation skills (§4) rather than a fixed case set (cost: case-bank development). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Extend the Research Thesis Pathway's supervised, independent project so identifying and closing one's own knowledge gaps is itself assessed, matching the market's diagnostic-transfer emphasis (§4 skill rows) (cost: supervision-load time). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Add documented role- and tool-allocation to the multidisciplinary team-based case conference (curriculum implication CI-3), so dividing work across people and diagnostic tools is itself assessed, matching Multidisciplinary case formulation rising across the 5,120-posting sample (§2 Signal 1) (cost: additional facilitator load per cohort). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Add a reliance-judgement component to an existing quality-assessment task (structured peer review or article critique), requiring students to document and justify when a diagnostic-support tool's output was accepted or overridden, within the AHPRA non-delegable-decision boundary (§3 Theme 1) (cost: one assessment-criteria redesign). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make the primary-evidence-generating project required across both pathways rather than the Thesis pathway alone, so every graduate can supply the program-specific outcome evidence the field-of-education destination basis currently lacks (§6) (cost: an Industry Project pathway redesign adding a defended primary-data component). | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Deliver the multidisciplinary case-conference output (CI-3) to a real clinical panel or supervising practitioner rather than the teaching team alone, with professional conduct assessed, matching Patient communication and Multidisciplinary case formulation both rising across the 5,120-posting sample (§2 Signal 1; §4) (cost: sourcing and briefing an external panel each cohort). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Give the ethics-application and randomised-controlled-trial protocol tasks a genuine constraint of practice, a real ethics-committee timeline or an externally supplied case, matching Theme 2's near-zero-automation finding for bedside and procedural clinical work (§3 Theme 2) (cost: sourcing a live or realistic constraint each cohort). | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the Industry Project pathway's placement into a required sequence across both pathways, with structured reflection and documented accountability to the host, matching Theme 2's durable-clinical-practice finding (§3 Theme 2). This is not justified by employment rates, placement does not raise them [[28]](https://doi.org/10.1007/s10734-017-0216-z), but by skill development and professional identity [[29]](https://doi.org/10.1080/07294360.2016.1139551), and it carries an equity cost where the placement is unpaid or requires relocation [[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) (cost: placement-provider negotiation across both pathways, plus support for students who cannot self-fund relocation). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| Supervised clinical placement or high-fidelity simulation added to the practicum sequence (CI-1) | W2, W3 | Employer demand concentrates on physician and medical-specialist roles requiring supervised, hands-on clinical exposure; bedside and procedural work carries near-zero automated substitution potential. | §2 Signal 1; §3 Theme 2 | MEDIUM |
| Assessed AHPRA AI-governance module (CI-2) | C2, C3 | The Medical Board of Australia and AHPRA mandate that clinical decision-making, procedural execution and prescription authorisation stay non-delegable to diagnostic algorithms. | §3 Theme 1 | MEDIUM |
| Multidisciplinary team-based case-conference assessment (CI-3) | C1, W1 | Multidisciplinary case formulation and Patient communication both recur as rising skill keywords across the 5,120-posting sample. | §2 Signal 1; §4 | MEDIUM |
| Audit and replace routine administrative assessment tasks (CI-4) | C4 | Office-clerk administrative work is named the clear automation-exposed comparator group. | §3 Theme 4; §2 Signal 2 | MEDIUM |
| Program-specific graduate-destination survey and a required primary-evidence project (CI-5) | C5 | The destination basis is field-of-education grain, not program grain. | §6 Evidence confidence and gaps | LOW |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C3 | Add AI capabilities-and-limits content to the core, alongside the COMP90094 elective, within the AHPRA non-delegable-decision boundary. | C3 level 2 — core AI content with limits discussed and assessed | low | Year 1, Semester 1 | §3 Theme 1; [1] |
| P2 | C4 | Add a core assessment applying diagnostic and case-formulation skills to a novel or unseen case, matching the market's rising Clinical diagnostic acumen and Multidisciplinary case formulation keywords. | C4 level 2 — assessed application to novel problems | low | Year 1, Semester 1 | §4; [1] |
| P3 | C1 | Add role- and tool-allocation documentation to the multidisciplinary case-conference assessment, matching the rising Multidisciplinary case formulation keyword. | C1 level 3 — coordinating people and tools/AI assessed | medium | Year 1, Semester 2 | §2 Signal 1; [5][7] |
| P4 | C2 | Add a reliance-judgement component to an existing quality-assessment task, documenting when a diagnostic-support tool's output was accepted or overridden, within the AHPRA boundary. | C2 level 3 — documented and justified reliance decisions | medium | Year 1, Semester 2 | §3 Theme 1; [4][3] |
| P5 | W1 | Deliver the multidisciplinary case-conference output to a real clinical panel or supervising practitioner, with conduct assessed, matching Patient communication and Multidisciplinary case formulation both rising. | W1 level 3 — external-audience delivery with conduct assessed | medium | Year 1, Semester 2 | §2 Signal 1; [20][31] |
| P6 | C3 | Extend the new core AI content to an assessed critique of a diagnostic tool's governance boundary, where AHPRA draws the decision-support/delegable-task line, beyond describing how the tool works. | C3 level 3 — assessed critique or governance of AI | medium | Year 2, Semester 1 | §3 Theme 1; [1][2] |
| P7 | W2 | Give the existing ethics-application and randomised-controlled-trial protocol tasks a genuine constraint of practice, a real ethics-committee timeline or an externally supplied case, matching Theme 2's near-zero-automation finding for procedural clinical work. | W2 level 3 — assessment spine with a genuine constraint | medium | Year 2, Semester 1 | §3 Theme 2; [22][23] |
| P8 | C4 | Extend the Research Thesis Pathway's supervised project so identifying and closing one's own knowledge gaps is itself assessed, matching the market's diagnostic-transfer emphasis. | C4 level 3 — structured progression to independent learning | high | Year 2 | §4; [9][10] |
| P9 | C5 | Make the primary-evidence-generating project required across both pathways, not the Thesis pathway alone, so every graduate supplies the program-specific evidence the field-of-education destination basis lacks. | C5 level 3 — a required, defended primary-evidence project | high | Year 2 | §6; [7] |
| P10 | W3 | Extend the Industry Project pathway's placement into a required sequence across both pathways, with structured reflection and host accountability, matching Theme 2's durable-clinical-practice finding. Not justified by employment rates, placement does not raise them [[28]](https://doi.org/10.1007/s10734-017-0216-z), but by skill development and professional identity [[29]](https://doi.org/10.1080/07294360.2016.1139551), noting the equity cost where a placement is unpaid or requires relocation [[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report). | W3 level 3 — extended, accountable, reflective placement sequence | high | Year 2 | §3 Theme 2; [28][29][30] |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | The program documents a coherent, all-compulsory specialist core (5 core subjects, 75 credit points, all clinical-research-specific: study design, responsibilities/ethics, data analysis, principles, and research development/translation), plus a compulsory specialist thesis or industry-project pathway, with progressive depth referenced explicitly across the Graduate Certificate → Graduate Diploma → Master sequence. | Preserve the all-compulsory specialist core (5 units, 75 credit points) and the progressive Graduate Certificate to Graduate Diploma to Master sequence; none of the interventions above remove or make elective a core clinical-research unit. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | Multiple core/pathway assessments require defended trade-off decisions or live projects with real uncertainty and accountability: CLRS90011's negotiated-scenario study design with critical justification, and MEED90002's industry placement requiring students to solve practical issues within 'unstructured/semi-structured research projects.' This is not recall or scripted response. | Preserve the negotiated-scenario study-design task and the Industry Project's unstructured and semi-structured problem-solving requirement; redesigns add reliance-judgement and tool-coordination assessment (C2:3, C1:3) without narrowing either task to scripted response. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C3 | 1 | 2 | +1 adaptive | 9 / 15 | 6 / 9 |
| P2 | C3 | 2 | 3 | +1 adaptive | 10 / 15 | 6 / 9 |
| P3 | C4 | 1 | 2 | +1 adaptive | 11 / 15 | 6 / 9 |
| P4 | C4 | 2 | 3 | +1 adaptive | 12 / 15 | 6 / 9 |
| P5 | C1 | 2 | 3 | +1 adaptive | 13 / 15 | 6 / 9 |
| P6 | C2 | 2 | 3 | +1 adaptive | 14 / 15 | 6 / 9 |
| P7 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 6 / 9 |
| P8 | W1 | 2 | 3 | +1 workplace | 15 / 15 | 7 / 9 |
| P9 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 8 / 9 |
| P10 | W3 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
