// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Architecture/Master of Urban Cultural Heritage (MC-ARCHUCH) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Architecture/Master of Urban Cultural Heritage (MC-ARCHUCH)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-29 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-archuch.md
**Position basis:** Destination AI Exposure 90.34 (partial basis) × Curriculum Adaptiveness 10/15 (v4.2 draft, sub-scale A) · Workplace practice 6/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a partial basis (Master of Architecture ∪ Master of Urban Planning), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

This program's Panel C v4 scores sit mostly at level 1-2 across the eight adaptive and workplace items, with the largest gaps at C3 (Digital and AI literacy, including governance) and W3 (Work-situated learning). The market report (reports/dfva-market-mc-archuch.md) ties this program's exposed occupations to two current pressures: new work health and safety duties for AI-enabled construction-site tools, and state licensing regimes that hold construction managers personally accountable for the accuracy of AI-generated content. Both pressures argue for curriculum that assesses AI governance and reliance judgement, not only AI tool operation. The destination-exposure estimate for this program's field-of-education basis is 90.34, on a partial basis derived from the field rather than this program's own graduates, so the priority ordering below reads as directional rather than as a program-specific ranking.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | Safe Work Australia's July 2026 guidance and NSW's WHS Amendment (Digital Work Systems) Act 2026 treat AI-enabled site tools as a governance matter for construction managers, and state licensing holds them accountable for AI-generated content accuracy (§3 Theme 3, Theme 4) — beyond the tool-operation level this program currently assesses. | 1 |
| C1 Distributed cognition & relational capability | Adaptive | 2 / 3 | 1 | Construction managers now coordinate AI-enabled site tools — cameras, scheduling software, AI assistants — alongside people under the new WHS duties described in §3 Theme 3. | 3 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 2 / 3 | 1 | State builder licensing (NSW Fair Trading, Victorian Building Authority, QBCC) holds the licensed builder responsible for the accuracy of AI-generated quotes and representations, so a construction manager cannot delegate accuracy checking to a generative tool (§3 Theme 4). | 4 |
| C5 Inquiry & evidence generation | Adaptive | 2 / 3 | 1 | Jobs and Skills Australia's Generative AI Capacity Study (August 2025) finds routine, evidence-poor clerical and administrative tasks carry the highest automation exposure of the occupations covered by this report (§3 Theme 6) — the inverse of a required, defended primary-evidence project. | 5 |
| C4 Life-long learning & transfer | Adaptive | 3 / 3 | 0 | Already at level 3; §3 Theme 6's automation-exposure finding for routine roles corroborates the value of sustaining the program's self-directed Design Thesis capstone rather than narrowing it. | 7 |
| **Adaptive capabilities** | **Adaptive** | **10 / 15** | **5** | — | — |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | Live job-advertisement demand for construction managers and quantity surveyors is the largest signal in this report (6,711 postings, §2 Signal 2), with 'project delivery' the recurring rising skill keyword (§4) — evidence for supervised, workplace-based delivery experience. | 2 |
| W1 Professional communication & conduct | Workplace | 2 / 3 | 1 | The same WHS and licensing duties (§3 Theme 3, Theme 4) that bear on C1 and C3 require construction managers to communicate compliance and accountability decisions professionally, including for AI-assisted output, to regulators and clients. | 6 |
| W2 Authentic task design | Workplace | 3 / 3 | 0 | Already at level 3; the sustained construction-manager demand in §2 Signal 2 and the project-delivery emphasis in §4 corroborate keeping professional-format design and delivery artefacts as the assessment spine. | 8 |
| **Workplace practice** | **Workplace** | **6 / 9** | **3** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Option: add an assessed AI-capabilities-and-limits component to an existing core unit, drawing on §3 Theme 4's finding that AI-generated content needs human verification before use (cost: one assessed task plus a rubric revision, no new contact hours). Option: embed a short AI-limits case discussion, assessed via a reflective task, into an existing core studio brief (cost: minimal — one seminar slot plus a marking-criteria addition). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Option: build a governance-and-accountability assessment task around §3 Theme 3's WHS duties for AI-enabled site tools, having students draft or critique an AI-use policy against the NSW WHS Amendment (Digital Work Systems) Act 2026 (cost: new assessment brief plus marking rubric). Option: extend an existing practice unit's assessment so students review an AI-generated design or quote output against the state-licensing accountability standard in §3 Theme 4 (cost: moderate — new marking criteria, no new content hours). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Option: introduce a core, assessed short work-situated task — a supervised site or practice placement — tied to the construction-manager demand signal in §2 Signal 2 (cost: partnership sourcing, supervision time, and a new assessment rubric). Option: add a short, assessed live-client project drawing on the rising 'project delivery' skill keyword in §4 (cost: industry-partner sourcing and a moderate supervision load). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Option: extend a landed short placement into a substantial required placement sequence — supervised, assessed, with structured reflection and accountability to the host — anchored to the sustained demand in §2 Signal 2 (cost: significant — placement coordination, host agreements, ongoing supervision). Option: sequence two shorter assessed placements across different program stages building toward the same standard (cost: staged coordination effort, lower load per placement). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Option: redesign an existing core group project so the assessed task requires students to document how work is divided between team members and AI or digital tools, tied to §3 Theme 3's finding that construction managers must manage AI-enabled site tools alongside people under WHS duties (cost: revised assessment brief and marking criteria, no new contact hours). Option: add a team scheduling exercise using an AI scheduling tool as one allocation among others, where the division of work is itself assessed (cost: moderate — tool access plus rubric design). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Option: add a reliance-justification component to an existing core assessment — for example a design or quote-review task — requiring students to document when they relied on or overrode an AI-generated output, drawing on §3 Theme 4's finding that construction managers cannot delegate accuracy checking to a generative tool (cost: rubric and prompt revision, minimal new hours). Option: require a short defence discussion on one assessed reliance decision per studio (cost: moderate — additional assessment and marking time). | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Option: make an existing optional primary-evidence route required and add a staged methodology-defence review, informed by §3 Theme 6's finding that routine, evidence-poor tasks carry the highest automation exposure (cost: curriculum-structure change, moderate). Option: add a defended-methodology component to the existing Design Thesis so students justify their primary research or evidence approach under review (cost: low — extends an existing assessment point). | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Option: extend the existing guest-critic panel presentation so professional conduct and accountability are explicit assessed criteria, tied to the compliance-communication duties in §3 Theme 3 and Theme 4 (cost: rubric revision only). Option: add a second, earlier assessed external-audience presentation point so professional communication is assessed progressively rather than once (cost: moderate — a new assessment point and coordination with an external panel). | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| WHS duties for AI-enabled site tools | C1 | Construction managers now hold express work health and safety duties for AI-enabled site tools — cameras, scheduling software, AI assistants — under NSW's WHS Amendment (Digital Work Systems) Act 2026 and Safe Work Australia's July 2026 guidance. | §3 Theme 3 | HIGH |
| WHS duties for AI-enabled site tools | C3 | The same WHS guidance frames AI and digital technologies at work as a matter requiring the normal risk-management process, not tool training alone. | §3 Theme 3 | HIGH |
| WHS duties for AI-enabled site tools | W1 | Employers using AI, automation and digital platforms carry express WHS duties, which construction managers must be able to discharge and communicate. | §3 Theme 3 | HIGH |
| Licensed-builder accountability for AI-generated content | C2 | State builder licensing (NSW Fair Trading, Victorian Building Authority, QBCC) holds the licensed builder responsible for the accuracy of AI-generated quotes and representations, so a construction manager cannot delegate accuracy to a generative tool. | §3 Theme 4 | HIGH |
| Licensed-builder accountability for AI-generated content | C3 | The same licensing accountability requires the PCBU or supervisor to review and adopt AI output rather than rely on it. | §3 Theme 4 | HIGH |
| Licensed-builder accountability for AI-generated content | W1 | Accountability for AI-generated content sits with the licensed builder, which requires professional communication of what was reviewed and adopted. | §3 Theme 4 | HIGH |
| Sustained construction-manager and quantity-surveyor demand | W3 | 6,711 live postings match 'construction manager' with 'project delivery' the recurring skill keyword across the sample. | §2 Signal 2 / §4 Skill shift | MEDIUM |
| Automation exposure of routine, evidence-poor tasks | C5 | Jobs and Skills Australia's Generative AI Capacity Study (August 2025) finds routine clerical and administrative tasks carry the highest automation exposure, with limited mobility options for graduates in exposed roles. | §3 Theme 6 | HIGH |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | W1 | Extend the existing guest-critic panel presentation so professional conduct and accountability are explicit assessed criteria. | Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria. | low | Next assessment-rubric review cycle | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P2 | C2 | Add a reliance-justification component to an existing core assessment, requiring students to document when they relied on or overrode an AI-generated output. | Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment). | low | Next assessment-rubric review cycle | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P3 | C3 | Add an assessed AI-capabilities-and-limits component to an existing core unit. | Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed. | low | Next unit-outline revision | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P4 | C5 | Add a defended-methodology component to the existing Design Thesis, requiring students to justify their primary research or evidence approach under review. | A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review). | low | Next Design Thesis assessment-brief revision | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P5 | C1 | Redesign an existing core group project so the assessed task requires students to document how work is divided between team members and AI or digital tools. | Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed. | medium | Following C3 governance task, same review cycle | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P6 | C3 | Build a governance-and-accountability assessment task around AI-enabled site tools, having students draft or critique an AI-use policy against the WHS duties in §3 Theme 3. | Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation. | medium | Following the C3 level-2 unit revision | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P7 | W3 | Introduce a core, assessed short work-situated task — a supervised site or practice placement, or a short assessed live-client project. | A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone. | medium-high | Next placement-partnership sourcing cycle | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P8 | W3 | Extend a landed short placement into a substantial required placement sequence, or sequence two shorter assessed placements across program stages. | Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer). | high | After the W3 short placement is established | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | Coherent, progressive specialist core (275/350cp) culminating in an ARBV-accredited registration pathway. | Any new AI-governance or reliance-justification task must sit inside the existing specialist core and the ARBV-accredited registration sequence, not replace core disciplinary content. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | Studio and practice assessments require defended trade-off decisions on complex, real-world design/procurement problems rather than recall. | New reliance-justification or governance tasks must keep testing defended trade-off decisions on real design or procurement problems, not shift toward recall or checklist-style AI-compliance exercises. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C3 | 1 | 2 | +1 adaptive | 11 / 15 | 6 / 9 |
| P2 | C3 | 2 | 3 | +1 adaptive | 12 / 15 | 6 / 9 |
| P3 | W3 | 1 | 2 | +1 workplace | 12 / 15 | 7 / 9 |
| P4 | W3 | 2 | 3 | +1 workplace | 12 / 15 | 8 / 9 |
| P5 | C1 | 2 | 3 | +1 adaptive | 13 / 15 | 8 / 9 |
| P6 | C2 | 2 | 3 | +1 adaptive | 14 / 15 | 8 / 9 |
| P7 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 8 / 9 |
| P8 | W1 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
