// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Bachelor of Arts (ANU-BARTS) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Bachelor of Arts (ANU-BARTS)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-09-07 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-anu-barts.md
**Position basis:** Destination AI Exposure 81.93 (field basis) × Curriculum Adaptiveness 5/15 (v4.2 draft, sub-scale A) · Workplace practice 3/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a field basis (Jobs and Skills Australia Higher Education Outcomes (JSA HEO) field 0009 Society and Culture), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

Both gates fail. G1 fails because the program specifies no compulsory courses at all: 144 of 144 units come from a 709-unit prescribed list, 24 of them open to other Colleges, so no staged disciplinary core or prerequisite chain is documented anywhere in the extract. G2 fails for the same reason — assessed defended trade-off tasks exist inside the prescribed list, but because no course is compulsory, no such task is attributable to every student. Every redesign option below therefore carries the same first cost: designating something compulsory, not merely redesigning an existing core assessment.

All eight adaptive and workplace items score 1 of 3 (adaptive 5/15, workplace 3/9): each capability is named in a program learning outcome but assessed, at best, inside an elective a student may never take. The market evidence points the redesign toward specific destinations rather than generic ones. The field's largest recorded entry destinations sit in retail, general clerical work and secondary teaching — occupations the discussion signals mark as automation-exposed or as running through an accreditation gate this degree does not supply — with a smaller recorded tail in law, business operations and market research, where the recurring skill keywords are drafting, statutory interpretation, operations coordination and analysis. Jobs and Skills Australia's Generative AI Capacity Study frames augmentation, not replacement, as the dominant pattern, which is what most actions below target: judgement over AI-drafted material, coordination across people and tools, and a professional communication genre with a real audience.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C1 Distributed cognition & relational capability | Adaptive | 1 / 3 | 2 | Office-manager and administrative-supervisor postings (§2 Signal 7, 4,091 postings matching "office manager") recur on operations, facilities, compliance and procurement coordination — supervisory, stakeholder-facing work that no compulsory unit in this program currently assesses as collaborative practice. | 1 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | Jobs and Skills Australia's Generative AI Capacity Study finds augmentation dominant across the workforce; an arts graduate's comparative advantage in an augmented role is judgement about text a tool produced (§5 CI-3, §3 Theme 6) — a judgement this program's electives assess only as self-reported reflection, never against criteria, and never as a compulsory task. | 2 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | Education-professional and other knowledge-intensive occupations cluster toward higher augmentation and automation exposure because their core tasks are language- and knowledge-intensive and readily supported by generative AI (§3 Theme 6); Secondary School Teacher is a top-five entry destination for this field (REAL GRADUATE DESTINATIONS table, JSA HEO). The program's own AI and digital-tools content sits entirely in electives. | 3 |
| C4 Life-long learning & transfer | Adaptive | 1 / 3 | 2 | The field's largest recorded entry destinations are retail, hospitality and general clerical work (§1 Job family map), and 2025 evidence names clerical and secretarial work as the clearest automation-exposed group (§3 Theme 4) — the most common first destination is also among the most exposed, and no compulsory unit assesses transfer into a non-disciplinary setting of that kind. | 4 |
| C5 Inquiry & evidence generation | Adaptive | 1 / 3 | 2 | Market Research Analysts and Marketing Specialists is a recorded destination family (Advertising Specialist, Audience Insights Officer, Digital Marketing Analyst; §2 Signal 9, §1 Job family map) that markets analytic inquiry skill beyond the recognition-level, essay-based assessment the program's one methods-adjacent elective currently carries. | 5 |
| **Adaptive capabilities** | **Adaptive** | **5 / 15** | **10** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Retail salespersons personally comply with Australian Consumer Law provisions on truthful product representation; the obligation is not delegated to a compliance function (§5 CI-4, §3 Theme 1) — a real statutory audience the program's compulsory-in-theory but elective-in-practice spoken-presentation outcome does not use. | 6 |
| W2 Authentic task design | Workplace | 1 / 3 | 2 | 4,820 postings matching lawyer/solicitor/legal counsel (§2 Signal 4) recur on contract drafting, statutory interpretation and dispute resolution — a professional artefact and criterion set the case-study assessment in the prescribed list's data-for-decision-making elective does not yet reproduce end to end, and which no student is required to take. | 7 |
| W3 Work-situated learning | Workplace | 1 / 3 | 2 | Program or Project Administrator is the only entry-occupation share in the field's top five that grows over the career, rising from 2.2% at entry to 4.4% by the senior stage (REAL GRADUATE DESTINATIONS table, JSA HEO) — a coordination-heavy destination the program's existing national-internships and science-communication-internship electives could rehearse, but only for the students who opt in and are selected. | 8 |
| **Workplace practice** | **Workplace** | **3 / 9** | **6** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Option: designate one existing group-assessed course from the prescribed list — one that already assesses collaborative practice with individual accountability — as a compulsory requirement point, reflecting the coordination and procurement work recurring in office-manager and administrative-supervisor postings (§2 Signal 7, 4,091 postings). Cost: a compulsory-requirement designation inside the existing 709-unit list; no new course. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Option: within that now-compulsory unit, add a documented role-and-tool allocation component so the assessed collaborative task also records how work was divided between team members and any AI tools used, matching the augmentation pattern Jobs and Skills Australia's Generative AI Capacity Study finds dominant across the workforce (§3 Theme 6). Cost: an assessment-brief and marking-criteria update on the now-compulsory unit. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Option: designate the course (or courses) already carrying self-assessment and critical-analysis tasks as compulsory, and attach a criterion-referenced rubric to that task, warranted by the augmented-role advantage of judgement over AI-drafted text that Jobs and Skills Australia's study identifies (§3 Theme 6, §5 CI-3). Cost: one compulsory-requirement designation plus a rubric. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Option: attach a reliance-and-override log to that same compulsory appraisal task, in which students record and justify a point where they relied on or overrode an AI-drafted source, extending the same CI-3 rationale (§5 CI-3). Cost: one additional graded component on the now-compulsory task. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Option: designate the Asian-technology course covering AI ethics, or the science-communication course whose outcomes name machine learning and artificial intelligence as research methods, as a compulsory requirement, warranted by Jobs and Skills Australia's finding that knowledge-intensive occupations — including Secondary School Teacher, a top-five destination in this field's own graduate table — cluster toward higher augmentation and automation exposure (§3 Theme 6; REAL GRADUATE DESTINATIONS table). Cost: one compulsory-requirement designation; no new course. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Option: within that now-compulsory unit, add a governance-focused assessed task addressing bias, accountability or the data-privacy obligations the market report documents for office-clerk-type destinations (§3 Theme 3, Privacy Act/Fair Work Act), rather than a generic AI-ethics case. Cost: a case-study swap inside the now-compulsory assessment. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 1 → 2 | "At least one core assessment requires application to novel or unfamiliar problems — case variation, unseen datasets, cross-context projects." | Option: designate the algorithms course, or another prescribed-list course whose assessment already applies a method to a novel case, as compulsory, warranted by the field's largest entry destinations sitting in retail, general clerical and secondary teaching work outside the discipline itself (§1 Job family map; §3 Theme 4). Cost: one compulsory-requirement designation; no new course. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C4 Life-long learning & transfer | 2 → 3 | "The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them." | Option: add a self-scoped, gap-identification component to that same now-compulsory unit, in which students identify their own knowledge gaps against the field's automation-exposed destinations and set a plan to close them (§3 Theme 4). Cost: a unit-brief revision on the now-compulsory course. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C5 Inquiry & evidence generation | 1 → 2 | "Students design and conduct an inquiry with methodology selection and data collection, assessed." | Option: designate the foundations-of-social-research course as compulsory and extend its synoptic, research-essay assessment into a full inquiry task requiring methodology selection and data collection, warranted by the analytic-inquiry demand recorded in the Market Research Analysts and Marketing Specialists family (§2 Signal 9, §1 Job family map). Cost: one compulsory-requirement designation plus one added assessment stage. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Option: make one of the methods-plus-fieldwork electives the required capstone route rather than one option among several, and add a staged supervised review or oral defence of methodology, extending the same Signal 9 rationale (§2 Signal 9). Cost: aligning capstone requirements so the research-project route becomes compulsory rather than elective. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Option: designate one course already assessing spoken presentation to peers and staff as compulsory, and redesign that presentation into a professional-facing genre — a client brief or public-facing communication — marked against criteria drawn from the ACCC's own guidance on truthful product representation, warranted by the statutory obligation retail salespersons carry personally (§5 CI-4, §3 Theme 1). Cost: one compulsory-requirement designation plus a criteria sheet. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Option: repeat that professional-genre task at an earlier stage of the now-compulsory sequence and add an external or simulated-external assessor (an industry guest marker or practitioner panel), with professional conduct explicit among the criteria, extending the same statutory rationale (§3 Theme 1). Cost: recruiting an external or simulated assessor for two compulsory assessment points. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Option: designate the data-for-decision-making course (structured around case studies from business, community and public sectors) as compulsory, and replace one of its case-study assessments with an end-to-end task producing the artefact a practitioner would produce — for example a policy or business brief modelled on the drafting and dispute-resolution work recurring in the Lawyers family postings (§2 Signal 4, 4,820 postings). Cost: one compulsory-requirement designation plus an artefact-and-criteria redesign of one assessment. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Option: repeat that end-to-end task design at a second stage of the now-compulsory sequence and add a genuine constraint of practice — an ambiguous or externally supplied brief, a real time limit, or a consequential audience — drawing on the same Lawyers signal (§2 Signal 4). Cost: coordinated redesign of two compulsory assessment points. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Option: convert the national internships program (placing students in government departments, agencies and NGOs) or the science-communication internship from an optional, entry-selective elective into a required placement for at least one stream, warranted by Program or Project Administrator's rising share of the field's graduate destinations across career stages (REAL GRADUATE DESTINATIONS table). Cost: negotiating guaranteed host placements for a compulsory cohort; note the equity cost of unpaid or relocation-dependent placement [[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report). | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Option: extend that placement into a required sequence of two placements, or one extended placement, with host supervision, structured reflection and documented accountability to the host — justified by skill development, employment relevance and professional identity [[29]](https://doi.org/10.1080/07294360.2016.1139551) rather than by employment rates, since Jackson and Collings found work-integrated learning did not raise them [[28]](https://doi.org/10.1007/s10734-017-0216-z); the equity cost of unpaid or relocation-dependent placement stays live at this scale [[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report). Cost: sustained employer partnerships and placement-quality assurance. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| P1 | C1 | Office-manager and administrative-supervisor postings recur on operations, facilities, compliance and procurement coordination (4,091 postings matching "office manager"). | §2 Signal 7 | MEDIUM |
| P2 | C2 | Jobs and Skills Australia's Generative AI Capacity Study finds augmentation dominant across the workforce; an arts graduate's advantage in an augmented role is judgement about text a tool produced. | §5 CI-3; §3 Theme 6 | MEDIUM |
| P3 | W1 | Retail salespersons personally comply with Australian Consumer Law provisions on truthful product representation; the obligation is not delegated to a compliance function. | §5 CI-4; §3 Theme 1 | MEDIUM |
| P4 | C4 | The field's largest recorded entry destinations are retail, hospitality and general clerical work, and 2025 evidence names clerical and secretarial work as the clearest automation-exposed group. | §5 CI-1; §3 Theme 4; §1 Job family map | MEDIUM |
| P5 | C5 | Market Research Analysts and Marketing Specialists is a recorded destination family (Advertising Specialist, Audience Insights Officer, Digital Marketing Analyst) with 6 postings matching "market research analyst". | §2 Signal 9; §1 Job family map | MEDIUM |
| P6 | C3 | Education-professional and other knowledge-intensive occupations cluster toward higher augmentation and automation exposure because their core tasks are language- and knowledge-intensive. | §3 Theme 6 | MEDIUM |
| P7 | W2 | 4,820 postings matching lawyer/solicitor/legal counsel recur on contract drafting, statutory interpretation, dispute resolution and legal advocacy. | §2 Signal 4 | MEDIUM |
| P8 | W3 | Program or Project Administrator rises from 2.2% of the field's graduates at entry to 4.4% by the senior career stage — the only entry-occupation share in the top five that grows over time. | REAL GRADUATE DESTINATIONS table (JSA HEO); field grain, not program grain | LOW |
| P9 | C1 | The same augmentation-dominant pattern supports assessing the division of work between people and AI tools, not people alone. | §3 Theme 6 | MEDIUM |
| P10 | C2 | The same augmented-role advantage extends from appraising AI-drafted text to documenting and justifying reliance decisions on it. | §5 CI-3; §3 Theme 6 | MEDIUM |
| P11 | W1 | The same statutory-obligation rationale supports repeating the professional-genre task with a real external or simulated-external assessor. | §3 Theme 1 | MEDIUM |
| P12 | C4 | The same automation-exposure evidence for the field's largest entry destinations supports a self-scoped, gap-identification extension. | §3 Theme 4 | MEDIUM |
| P13 | C5 | The same market-research destination's need to defend a design, not only execute one, supports a required, defended capstone route. | §2 Signal 9 | MEDIUM |
| P14 | C3 | The same knowledge-intensive exposure pattern supports moving from AI-capabilities content to a governance-focused critique task. | §3 Theme 6 | MEDIUM |
| P15 | W2 | The same Lawyers-family signal supports repeating the end-to-end task design with a genuine constraint of practice. | §2 Signal 4 | MEDIUM |
| P16 | W3 | The same rising Program or Project Administrator share supports extending a single placement into a required sequence. | REAL GRADUATE DESTINATIONS table (JSA HEO); field grain, not program grain | LOW |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C1 | Designate an existing group-assessed course from the prescribed list as compulsory, reflecting the coordination work named in office-manager postings. | At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity. | medium | Term 1 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P2 | C2 | Designate the course already carrying self-assessment and critical-analysis tasks as compulsory, and attach a criterion-referenced rubric. | Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars. | medium | Term 1 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P3 | W1 | Designate the course already assessing spoken presentation as compulsory, redesigned into a professional genre marked against ACCC truthful-representation criteria. | At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice. | medium | Term 1 | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P4 | C4 | Designate the algorithms course, or another prescribed-list course applying a method to a novel case, as compulsory. | At least one core assessment requires application to novel or unfamiliar problems — case variation, unseen datasets, cross-context projects. | medium | Term 1-2 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P5 | C5 | Designate the foundations-of-social-research course as compulsory and extend its assessment into a full inquiry task with methodology selection and data collection. | Students design and conduct an inquiry with methodology selection and data collection, assessed. | medium | Term 1-2 | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P6 | C3 | Designate the Asian-technology (AI ethics) or science-communication (machine-learning-as-method) elective as compulsory. | Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed. | medium | Term 2 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P7 | W2 | Designate the data-for-decision-making course as compulsory and replace one case-study assessment with an end-to-end professional artefact. | At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice. | medium | Term 2 | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P8 | W3 | Convert the national internships program or the science-communication internship from optional and entry-selective into a required placement for at least one stream. | A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone. | medium-high | Term 2-3 (requires host or industry partnerships) | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P9 | C1 | Within the now-compulsory unit, add a documented role-and-tool allocation component to the collaborative task. | Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed. | medium | After P1; next teaching cycle | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P10 | C2 | Attach a reliance-and-override log to the now-compulsory appraisal task. | Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment). | low-medium | After P2; assessment-criteria extension only | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P11 | W1 | Repeat the professional-genre task at an earlier stage and add an external or simulated-external assessor. | Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria. | medium-high | After P3; recurring external or simulated-assessor bookings | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P12 | C4 | Add a self-scoped, gap-identification component to the now-compulsory unit. | The program documents structured progression toward independent learning: a self-scoped capstone or research project, or assessed identification of one's own knowledge gaps together with the plan to close them. | medium | After P4; unit-brief revision | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[9]](https://www.nationalacademies.org/read/13398/chapter/2)[[10]](https://doi.org/10.1007/s10459-025-10413-y)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P13 | C5 | Make one methods-plus-fieldwork elective the required capstone route and add a staged supervised review. | A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review). | high | After P5; removes elective alternatives, staffs supervised reviews | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P14 | C3 | Within the now-compulsory unit, add a governance-focused assessed task auditing bias, accountability or data-privacy obligations. | Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation. | medium-high | After P6; next teaching cycle | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P15 | W2 | Repeat the end-to-end task design at a second stage of the now-compulsory sequence and add a genuine constraint of practice. | Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance. | medium-high | After P7; coordinated two-point redesign | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P16 | W3 | Extend the now-required placement into a sequence of two, or one extended placement, with structured reflection and host accountability. | Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer). | high | After P8; additional placement terms, yearly host-agreement renewal | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | FAIL | FAIL condition met: generic or interchangeable content without disciplinary identity. The handbook states outright that the Bachelor of Arts specifies no compulsory courses and that no specific course must be taken; 144 units are chosen from a 709-unit prescribed list, with 24 of them selectable from other Colleges entirely, including non-arts subjects. That is neither an all-compulsory specialist core, nor an accredited sequence, nor a staged prerequisite chain. The extract contains no major, minor or specialisation page, so any compulsory sequence at major level is undocumented here and cannot be scored (R1). | The program must establish a defined compulsory sequence — a designated single-discipline major within the current pool, or a shared compulsory foundation set — so every student acquires the same staged disciplinary core with genuine prerequisites, rather than leaving all 144 units to unconstrained choice across a 709-unit list spanning other Colleges. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | FAIL | PASS requires that assessments require defended trade-off decisions, or simulations, capstones or live projects with real uncertainty and accountability. The program requires no assessment of any kind: it names no compulsory course, so no assessed task is attributable to the program rather than to a course a student may or may not choose. Tasks of that kind do exist within the prescribed list, which is why this is recorded as an ambiguity, but it resolves down under the lower-level rule. | Redesign must place at least one of the case-study, methods-and-fieldwork or data-for-decision-making courses already documented in the prescribed list inside that compulsory core, so a defended trade-off or uncertainty-bearing task becomes something every student completes, not one only some students choose. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C1 | 1 | 2 | +1 adaptive | 6 / 15 | 3 / 9 |
| P2 | C1 | 2 | 3 | +1 adaptive | 7 / 15 | 3 / 9 |
| P3 | C2 | 1 | 2 | +1 adaptive | 8 / 15 | 3 / 9 |
| P4 | C2 | 2 | 3 | +1 adaptive | 9 / 15 | 3 / 9 |
| P5 | C3 | 1 | 2 | +1 adaptive | 10 / 15 | 3 / 9 |
| P6 | C3 | 2 | 3 | +1 adaptive | 11 / 15 | 3 / 9 |
| P7 | C4 | 1 | 2 | +1 adaptive | 12 / 15 | 3 / 9 |
| P8 | C4 | 2 | 3 | +1 adaptive | 13 / 15 | 3 / 9 |
| P9 | C5 | 1 | 2 | +1 adaptive | 14 / 15 | 3 / 9 |
| P10 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 3 / 9 |
| P11 | W1 | 1 | 2 | +1 workplace | 15 / 15 | 4 / 9 |
| P12 | W1 | 2 | 3 | +1 workplace | 15 / 15 | 5 / 9 |
| P13 | W2 | 1 | 2 | +1 workplace | 15 / 15 | 6 / 9 |
| P14 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 7 / 9 |
| P15 | W3 | 1 | 2 | +1 workplace | 15 / 15 | 8 / 9 |
| P16 | W3 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
