// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Cancer Sciences (MC-CNCRSC) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Cancer Sciences (MC-CNCRSC)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-29 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-cncrsc.md
**Position basis:** Destination AI Exposure 75.80 (field basis) × Curriculum Adaptiveness 7/15 (v4.2 draft, sub-scale A) · Workplace practice 2/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a field basis (Jobs and Skills Australia Higher Education Outcomes (JSA HEO) field 019901 Medical Science), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

MC-CNCRSC scores 8/15 on adaptive capabilities and 2/9 on workplace practice, against a destination exposure of 75.8 estimated on a field-of-education basis (019901 Medical Science, not this program's own graduates). The curriculum's Research Capstone sequence (Cancer Research, Research Capstone Parts 1 and 2) is genuinely strong — a required, staged, assessment-backed research project that already sits at the instrument ceiling for life-long learning and transfer. What is missing is everything the market signals name as durable: no digital or AI content in any core unit, no work-integrated or clinical-placement component anywhere in the course structure, and no assessed team-based or professional-genre communication beyond an unjudged spoken update.

That gap matters because the market evidence points the opposite way from the curriculum's current weighting. Bedside procedural skill, multidisciplinary case formulation and patient communication all recur across a 5,120-posting advertisement sample for the profession this field feeds, and the Medical Board of Australia and AHPRA frame clinical decision-making as a non-delegable human responsibility precisely because it is not automatable. A capstone-heavy, placement-free curriculum builds the research capability the market rewards least and skips the clinically-facing, human-judgement capability it rewards most.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | Adaptive | 0 / 3 | 3 | Direct. Theme 1 (§3) frames the AHPRA boundary as a governance distinction between non-delegable clinical decision-making and decision-support tool use — exactly the judgement C3 scores — and no core unit in this program carries any AI or digital content to teach that boundary (§5 CI-2). | 1 |
| C1 Distributed cognition & relational capability | Adaptive | 1 / 3 | 2 | Indirect. Multidisciplinary case formulation recurs across the 5,120-posting sample (§2 Signal 1), and §5 CI-3 names team-based case conferencing as the assessment mode the market is rewarding; no core assessment currently reaches collaborative practice with individual accountability. | 3 |
| C5 Inquiry & evidence generation | Adaptive | 1 / 3 | 2 | Indirect. §6 flags the destination basis as field-of-education grain, not program grain (LOW confidence), and §5 CI-5 recommends a program-specific destination survey; the capstone's literature-review route (no required data collection) leaves the program unable to generate the primary evidence that would close that gap itself. | 4 |
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 2 / 3 | 1 | Indirect. Theme 1 (§3) requires practitioners to be able to justify reliance on, or override of, a decision-support tool within the non-delegable AHPRA boundary — the reliance-decision documentation C2 level 3 anchors, which the program's existing peer-reviewed presentation (level 2) does not yet require. | 7 |
| C4 Life-long learning & transfer | Adaptive | 3 / 3 | 0 | None needed — sits at the instrument ceiling (3/3) on the required, staged Research Capstone sequence (Cancer Research, Research Capstone Parts 1 and 2), which already satisfies the self-scoped-project anchor. | 8 |
| **Adaptive capabilities** | **Adaptive** | **7 / 15** | **8** | — | — |
| W3 Work-situated learning | Workplace | 0 / 3 | 3 | Direct. §2 Signal 1 (5,120 postings for Physicians, Surgeons, and Medical Specialists) and Theme 2 (§3, near-zero automation potential for bedside examination and procedural work) both concentrate on hands-on clinical practice, which no core unit in this program currently places students into (§5 CI-1). | 2 |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Direct. Patient communication recurs across the 5,120-posting sample (§2 Signal 1), and Theme 1 (§3) frames communication as part of the non-delegable clinical relationship; no core assessment currently reaches a recognised professional genre or an audience beyond the teaching team. | 5 |
| W2 Authentic task design | Workplace | 1 / 3 | 2 | Direct. Theme 2 (§3) names bedside examination, intraoperative procedural adjustment and crisis management as near-zero-automation, practice-anchored work, and §5 CI-1 recommends a placement or simulation component because current core assessment stops at an explicitly hypothetical proposal. | 6 |
| **Workplace practice** | **Workplace** | **2 / 9** | **7** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C3 Digital & AI literacy, including governance | 0 → 1 | "AI or digital tools appear only as electives or as tool operation/training — the operational level TEQSA identifies as non-durable." | Add an elective or operational-level digital/AI-tools component to a core subject — for example, AI-assisted diagnostic imaging or digital pathology tools referenced against the existing 'emerging technologies and techniques' course outcome — the discriminator between level 0 and level 1 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Convert that content into a core, assessed unit addressing both AI capabilities and their limitations and ethics, discussed and assessed rather than merely taught | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Require core assessment that critiques or governs an AI diagnostic or decision-support system in the oncology context — bias, accountability, transparency or data governance — beyond tool operation | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| W3 Work-situated learning | 0 → 1 | "Work-situated learning exists only as an elective, an optional internship, or an unassessed extracurricular or careers activity." | Add an elective clinical placement or simulation-based internship with practitioner supervision and an assessed outcome measure | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 1 → 2 | "A core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment — placement, practicum, live client project, community-based project — OR, for a cohort documented as already practising in the profession, a core unit assesses activity conducted in the student's own professional practice with real recipients and a documented outcome measure — but it is short or stands alone." | Move the placement into the core, either by requiring the elective structure already piloted at level 1 or by commissioning a core clinical-placement or simulated-bedside subject with practitioner supervision and assessment | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the core placement into a sequence, or one extended placement, with structured reflection on professional practice and documented accountability to the host — noting the equity cost of unpaid or relocation-dependent placements | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| C1 Distributed cognition & relational capability | 1 → 2 | "At least one core unit assesses collaborative practice — group projects with individual accountability, client or stakeholder work, interprofessional activity." | Convert the existing discussion-board participation task into an assessed group case-conference activity with documented individual accountability | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Make the capstone project a team deliverable in which the division of work across people and diagnostic or research tools is itself documented and assessed | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 1 → 2 | "Students design and conduct an inquiry with methodology selection and data collection, assessed." | Remove the 'hypothetical' framing from the Cancer Research project proposal and require students to select a methodology and collect their own primary data rather than model a hypothetical one | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Make a primary-evidence project required rather than one route among several, with the methodology defended in a staged supervised review | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Redesign the project-update presentation as a recognised clinical genre — a case presentation or clinical handover — judged against criteria drawn from professional practice, not just delivered to the teaching team | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Have that presentation delivered to, and judged by, a practitioner panel (oncology clinicians or the Research Capstone's own supervising experts), with professional conduct explicitly among the assessed criteria, and build earlier core units toward it so the assessment is progressive | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W2 Authentic task design | 1 → 2 | "At least one core assessment reproduces a professional task end to end: a real or realistic problem, producing the artefact a practitioner would produce, judged against criteria drawn from practice." | Rebuild the Cancer Research proposal as the artefact a practitioner would produce — a real or realistically constrained research or clinical-audit brief — judged against criteria drawn from oncology practice rather than academic criteria | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Extend practitioner-format tasks back through earlier core subjects so they form the assessment spine, and give at least one a genuine constraint of practice — an externally supplied brief, a real resource limit, or the profession's own standards of performance | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Require capstone students to document and justify where they relied on or overrode a diagnostic tool, model output or supervisor judgement, and mark that record as process evidence | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| P6, P12, P14 | C3 | Theme 1 (§3) frames the AHPRA boundary between non-delegable clinical decision-making and decision-support tool use as a governance distinction graduates need to be able to draw, and no core unit currently carries any AI or digital content that would teach it. | §3 Theme 1; §5 CI-2 | HIGH — restated from §6 (Physicians, Surgeons, and Medical Specialists — regulatory and statutory instruments: HIGH). |
| P7, P13, P15 | W3 | §2 Signal 1 (5,120 postings for Physicians, Surgeons, and Medical Specialists) and Theme 2 (§3, near-zero automation potential for bedside examination and procedural work) both concentrate on hands-on clinical practice, which the program's core does not currently place students into. | §2 Signal 1; §3 Theme 2; §5 CI-1 | HIGH for the advertisement and scholarly-literature signals (§6); the destination basis itself is LOW confidence (field-of-education grain, §6). |
| P3, P8 | C1 | Multidisciplinary case formulation recurs across the 5,120-posting sample, and §5 CI-3 names team-based case conferencing as the assessment mode the market is rewarding. | §2 Signal 1; §5 CI-3 | HIGH — restated from §6 (job-advertisement signal). |
| P5, P11 | C5 | §6 flags the destination basis as field-of-education grain, not program grain, and §5 CI-5 recommends a program-specific destination survey the program cannot itself generate without a required primary-evidence capability. | §6 Evidence confidence and gaps; §5 CI-5 | LOW — restated from §6 (destination basis). |
| P2, P9 | W1 | Patient communication recurs across the 5,120-posting sample, and Theme 1 (§3) frames communication as part of the non-delegable clinical relationship. | §2 Signal 1; §3 Theme 1 | HIGH — restated from §6 (job-advertisement and regulatory-instrument lanes). |
| P4, P10 | W2 | Theme 2 (§3) names bedside examination, intraoperative procedural adjustment and crisis management as near-zero-automation, practice-anchored work, and §5 CI-1 recommends a placement or simulation component because current core assessment stops at an explicitly hypothetical proposal. | §3 Theme 2; §5 CI-1 | HIGH — restated from §6 (scholarly and grey-literature lane). |
| P1 | C2 | Theme 1 (§3) requires practitioners to be able to justify reliance on, or override of, a decision-support tool within the non-delegable AHPRA boundary — the reliance-decision documentation C2 level 3 anchors. | §3 Theme 1 | HIGH — restated from §6 (regulatory-instrument lane). |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C2 | Require capstone students to document and justify where they relied on or overrode a diagnostic tool, model output or supervisor judgement, and mark that record as process evidence — extends the existing peer-reviewed presentation rubric rather than adding new teaching | C2 level 3 — assessment requires students to document and justify reliance decisions | Low | Sem 1 2027 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P2 | W1 | Redesign the project-update presentation as a recognised clinical genre — a case presentation or clinical handover — judged against practice-derived criteria rather than delivered only to the teaching team | W1 level 2 — a recognised professional genre or an audience beyond the teaching team, judged against criteria drawn from professional practice | Low | Sem 1 2027 | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P3 | C1 | Convert the existing discussion-board participation task into an assessed group case-conference activity with documented individual accountability | C1 level 2 — at least one core unit assesses collaborative practice | Low | Sem 1 2027 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P4 | W2 | Rebuild the Cancer Research proposal as the artefact a practitioner would produce — a real or realistically constrained research or clinical-audit brief — judged against criteria drawn from oncology practice, dropping the current 'hypothetical' framing | W2 level 2 — a core assessment reproduces a professional task end to end, producing the artefact a practitioner would produce, judged against practice criteria | Medium | Sem 2 2027 | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P5 | C5 | Remove the 'hypothetical' framing from the Cancer Research project proposal and require students to select a methodology and collect their own primary data rather than model a hypothetical project | C5 level 2 — students design and conduct an inquiry with methodology selection and data collection, assessed | Medium | Sem 2 2027 | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P6 | C3 | Add an elective or operational-level digital/AI-tools component to a core subject — AI-assisted diagnostic imaging or digital pathology tools referenced against the existing 'emerging technologies' course outcome | C3 level 1 — AI or digital tools appear only as electives or as tool operation/training | Medium | Sem 2 2027 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P7 | W3 | Add an elective clinical placement or simulation-based internship with practitioner supervision and an assessed outcome measure | W3 level 1 — work-situated learning exists only as an elective, an optional internship, or an unassessed extracurricular activity | Medium | Sem 2 2027 | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P8 | C1 | Make the capstone project a team deliverable in which the division of work across people and diagnostic or research tools is itself documented and assessed | C1 level 3 — assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems | High | Sem 1 2028 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P9 | W1 | Have the redesigned clinical-genre presentation delivered to, and judged by, a practitioner panel, with professional conduct explicitly among the assessed criteria, and build earlier core units toward it so the assessment is progressive | W1 level 3 — professional communication is assessed repeatedly and progressively AND at least one core assessment is judged by a real external audience or practitioner | High | Sem 1 2028 | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P10 | W2 | Extend practitioner-format tasks back through earlier core subjects so they form the assessment spine, and give at least one a genuine constraint of practice — an externally supplied brief, a real resource limit, or the profession's own standards of performance | W2 level 3 — such tasks are the program's assessment spine AND at least one carries a genuine constraint of practice | High | Sem 2 2028 | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P11 | C5 | Make a primary-evidence project required rather than one route among several, with the methodology defended in a staged supervised review | C5 level 3 — a substantial project generating primary evidence is required, with methodology defended under scrutiny | High | Sem 2 2028 | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P12 | C3 | Convert the elective digital/AI-tools component into a core, assessed unit addressing both AI capabilities and their limitations and ethics | C3 level 2 — core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed | High | Sem 2 2028 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P13 | W3 | Move the placement into the core, either by requiring the elective structure piloted at P7 or by commissioning a core clinical-placement or simulated-bedside subject with practitioner supervision and assessment. Note the equity cost of unpaid or relocation-dependent placements | W3 level 2 — a core unit places students in a real workplace or professional-community setting with practitioner supervision and assessment | High | 2029 intake | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |
| P14 | C3 | Require core assessment that critiques or governs an AI diagnostic or decision-support system in the oncology context — bias, accountability, transparency or data governance — beyond tool operation | C3 level 3 — core assessment requires critique or governance of AI systems in the discipline's own context | High | 2029 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P15 | W3 | Extend the core placement into a sequence, or one extended placement, with structured reflection on professional practice and documented accountability to the host | W3 level 3 — substantial required work-situated learning, supervised, assessed, with accountability to the host and structured reflection | High | 2029 | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | PASS: 'an all-compulsory specialist core...or a staged prerequisite chain.' All 4 core subjects are cancer-science-specific (Foundations of Cancer, Cancer Research, Research Capstone Part 1 and 2), and the handbook documents an explicit prerequisite chain — 'MEDI90086 Must be taken before Research Thesis Capstone subjects' — giving foundations-then-methodology-then-capstone progressive depth. | The core prerequisite chain (Foundations of Cancer before Cancer Research before the Research Capstone subjects) must stay intact — any redesign that removes or reorders the staged prerequisite chain would break this gate regardless of its effect on C1–C5. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | PASS: 'capstones...with real uncertainty and accountability.' The core Research Capstone requires students to 'Formulate testable hypotheses, aims and experimental design' and 'Independently manage a research project', gated by a hurdle 'Supervisory agreement and project summary' that 'Must be completed' — a capstone with genuine uncertainty and accountability rather than recall or scripted responses. | The hurdle-gated supervisory agreement and the requirement to formulate testable hypotheses and independently manage the research project must remain assessed and hurdle-gated — replacing that accountability with a lower-stakes or scripted deliverable would break this gate regardless of its effect on C1–C5. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C3 | 0 | 1 | +1 adaptive | 8 / 15 | 2 / 9 |
| P2 | C3 | 1 | 2 | +1 adaptive | 9 / 15 | 2 / 9 |
| P3 | C3 | 2 | 3 | +1 adaptive | 10 / 15 | 2 / 9 |
| P4 | W3 | 0 | 1 | +1 workplace | 10 / 15 | 3 / 9 |
| P5 | W3 | 1 | 2 | +1 workplace | 10 / 15 | 4 / 9 |
| P6 | W3 | 2 | 3 | +1 workplace | 10 / 15 | 5 / 9 |
| P7 | C1 | 1 | 2 | +1 adaptive | 11 / 15 | 5 / 9 |
| P8 | C1 | 2 | 3 | +1 adaptive | 12 / 15 | 5 / 9 |
| P9 | C5 | 1 | 2 | +1 adaptive | 13 / 15 | 5 / 9 |
| P10 | C5 | 2 | 3 | +1 adaptive | 14 / 15 | 5 / 9 |
| P11 | W1 | 1 | 2 | +1 workplace | 14 / 15 | 6 / 9 |
| P12 | W1 | 2 | 3 | +1 workplace | 14 / 15 | 7 / 9 |
| P13 | W2 | 1 | 2 | +1 workplace | 14 / 15 | 8 / 9 |
| P14 | W2 | 2 | 3 | +1 workplace | 14 / 15 | 9 / 9 |
| P15 | C2 | 2 | 3 | +1 adaptive | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
