// Auto-generated from reports/*.md by scripts/dfva-content-generate.ts — do not edit by hand.
// Run: npm --prefix scripts run dfva:gen-content
const content = {
  title: "Master of Dance (MC-DNCE) — Improvement Plan (v4 draft)",
  institution: "University of Melbourne",
  markdown: `# DFVA v4 IMPROVEMENT PLAN: Master of Dance (MC-DNCE)

**Instrument:** DFVA 4.2-draft — Panel C v4.2 on the TEQSA adaptive capabilities [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities) and the HESF generic and employment-related learning outcomes [[19]](https://www.legislation.gov.au/F2021L00488)
**Assessment date:** 2026-08-29 · **Derived from:** the verified panelCv4 scoring + reports/dfva-market-mc-dnce.md
**Position basis:** Destination AI Exposure 68.44 (field basis) × Curriculum Adaptiveness 9/15 (v4.2 draft, sub-scale A) · Workplace practice 5/9 (sub-scale W, reported beside the axis, not in it) — no v1 composite

> Citation marks in the Sources columns refer to the numbered list in
> [References](#references); full citations are given there and not repeated in
> the body.
>
> The exposure value is an **estimate**: it rests on a field basis (Jobs and Skills Australia Higher Education Outcomes (JSA HEO) field 100105 Dance), not on this program's own graduates. It is sound enough to say the destinations are highly exposed and not sound enough to rank this program against a peer on exposure alone — see [the estimated-basis methods note](../docs/dfva-panela-estimated-basis-methods.md).

## 1. DIAGNOSTIC SUMMARY — Basis: inferred

*This plan argues from the preceding scored evidence and market data; it is
interpretation, not observation.*

The Master of Dance (MC-DNCE) is a 200-point postgraduate program with an all-compulsory specialist core of seven dance subjects, staged so Year 2 subjects sit behind a Year 1 progression requirement. Its strongest evidence sits in the capstone: DNCE90019's Research Project is a required, self-scoped 50-point independent research project assessed via creative portfolio and exegesis, clearing life-long learning and transfer at the ceiling (C4 = 3/3). Both gates pass: G1 on the compulsory, staged core; G2 on live in-situ performance, a real professional placement and the capstone research project, each carrying genuine uncertainty and accountability.

Headroom is concentrated where the program's evidence is documented but does not reach the anchor's bar. C2: reflective statements carry assessment weight in several subjects but describe progression, not criterion-referenced appraisal against stated standards. C3: digital content is confined to tool and method operation — documentation, notation, video capture, digital analysis — with no AI content anywhere in the extract. W1: DNCE90017's Professional Placement Report is graded by the subject coordinator alone, so its audience stays inside the teaching team rather than an external professional judge. C1, C5, W2 and W3 each clear level 2 on documented core evidence (group choreography with individual accountability; the Research Project's methodology and primary-evidence generation; real or realistic performance and placement tasks; a compulsory, supervised, assessed placement) but stop short of level 3 on a single missing feature in each case — tool-coordination content, staged defence under scrutiny, explicit criteria drawn from practice, and placement length, respectively.

Because this program has no destination record of its own, the market report's job family rests on the Dance field of education's most common entry occupation, Secondary School Teacher — a pathway most, not all, graduates travel. The market evidence entries that follow are marked direct where a signal names teaching practice or the AITSL registration pathway, and marked as none reported where the market report is silent on a construct (inquiry methodology, choreographic task design) that the instrument still scores regardless.

| Item | Sub-scale | Score | Levels below maximum | Market evidence for the gap | Priority |
|---|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | Adaptive | 1 / 3 | 2 | Direct — Theme 2 (§3) and the skill-shift row (§4) find core teaching tasks (lesson planning, resource creation, feedback, assessment drafting) readily supported by generative AI; CI-3 (§5) ties evaluative judgement over AI-drafted material to this item. | 1 |
| C3 Digital & AI literacy, including governance | Adaptive | 1 / 3 | 2 | Direct — Theme 2 (§3) and the skill-shift row (§4); CI-2 (§5) names the AI-literacy and governance gap directly for the Secondary School Teacher pathway. | 2 |
| C1 Distributed cognition & relational capability | Adaptive | 2 / 3 | 1 | Indirect — Theme 2 (§3) and the skill-shift row (§4) note AI-assisted lesson planning and resource creation as part of the teaching pathway most graduates enter; no dance-specific tool-coordination signal is reported, so the bearing runs through that pathway, not the discipline core. | 4 |
| C5 Inquiry & evidence generation | Adaptive | 2 / 3 | 1 | None reported — no signal in the market report bears on research inquiry or evidence generation; the occupations in §1 and the themes in §3 concern classroom practice, not scholarly methodology. | 5 |
| C4 Life-long learning & transfer | Adaptive | 3 / 3 | 0 | At maximum — already 3/3 on a self-scoped capstone; no market signal changes an item already at the ceiling anchor. | 8 |
| **Adaptive capabilities** | **Adaptive** | **9 / 15** | **6** | — | — |
| W1 Professional communication & conduct | Workplace | 1 / 3 | 2 | Direct — Signal 1 (§2) shows the job-advertisement sample dominated by independent and faith-based schools rather than large employers; CI-4 (§5) ties this to individually demonstrable professional communication and conduct. | 3 |
| W2 Authentic task design | Workplace | 2 / 3 | 1 | None reported — no signal bears on authentic task design beyond what the program already documents; the market report speaks to classroom teaching practice, not choreographic or performance task design. | 6 |
| W3 Work-situated learning | Workplace | 2 / 3 | 1 | Direct — Theme 1 (§3) and CI-1 (§5): AITSL registration for the Secondary School Teacher pathway rests on an accredited initial-teacher-education program with its practicum expectations; a single 40-hour placement does not, alone, evidence that pathway. | 7 |
| **Workplace practice** | **Workplace** | **5 / 9** | **4** | — | — |

Priority orders items by size of gap. The P-numbers in the tables that follow are a
different ordering — sequenced by effort and dependency — so an item's priority and its
P-number do not correspond.

## 2. SCORE-TO-ACTION MAP — Basis: inferred

| Item | Now → target | Anchor requirement at the target level (verbatim) | Curriculum action | Sources |
|---|---|---|---|---|
| C2 Hybrid metacognition & evaluative judgement | 1 → 2 | "Core assessment includes criterion-referenced appraisal of quality: peer review, structured critique, portfolio with standards, marking against exemplars." | Convert one of the graded reflective statements (for example DNCE90015's individual reflective statement) into a criterion-referenced appraisal task: students judge their own and peers' choreographic or performance work against published standards, with the structured critique itself assessed. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C2 Hybrid metacognition & evaluative judgement | 2 → 3 | "Assessment requires students to document and justify reliance decisions — when they relied on or overrode a tool, source or collaborator; defend judgements of AI-output quality; or evidence strategy adjustment over time (process-focused assessment)." | Where a subject uses AI-assisted tools for documentation, notation or research synthesis, require students to document and defend when they relied on or overrode that tool's output — the same reliance-decision the Gen AI Capacity Study (Theme 2, §3) finds increasingly available for teaching-adjacent drafting tasks. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| C3 Digital & AI literacy, including governance | 1 → 2 | "Core units address AI capabilities AND limitations/ethics; use with limits discussed and assessed." | Add an assessed module addressing what generative AI tools can and cannot do for dance documentation and choreographic idea generation, and — for students heading into the Secondary School Teacher pathway — for lesson and resource preparation, with capabilities and limits both assessed. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| C3 Digital & AI literacy, including governance | 2 → 3 | "Core assessment requires critique or governance of AI systems in the discipline's own context — bias, accountability, transparency, regulation or data governance — beyond tool operation." | Require a core assessment critiquing the governance of AI use in dance-teaching practice — accountability for AI-drafted lesson or assessment material, and the limits AITSL registration places on delegating professional judgement to a tool — beyond operating the tools. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| W1 Professional communication & conduct | 1 → 2 | "At least one core assessment requires a recognised professional genre or an audience beyond the teaching team — client brief, consultancy or policy advice, clinical handover, pitch, public-facing artefact — judged against criteria drawn from professional practice." | Redesign the Professional Placement Report (DNCE90017) so at least one component is judged by the host supervisor or an external practitioner against criteria drawn from professional practice, rather than by the subject coordinator alone. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| W1 Professional communication & conduct | 2 → 3 | "Professional communication is assessed repeatedly and progressively across the program AND at least one core assessment is delivered to, or judged by, a real external audience or practitioner (industry panel, client, patient or simulated patient, public exhibition), with professional conduct or accountability explicitly among the assessed criteria." | Add a second, progressively staged externally judged assessment earlier in the program — a public showing or panel judged by a practitioner — with professional conduct explicitly among the assessed criteria, matching the individually demonstrated communication the independent- and faith-school hiring sample (Signal 1, §2) rewards. | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| C1 Distributed cognition & relational capability | 2 → 3 | "Assessed collaborative practice recurs across the program AND at least one assessment requires coordinating work across people AND tools/AI systems — e.g. a team capstone with documented role and tool allocation, or a task where the division of work between people and systems is itself assessed." | Require one group choreography assessment (building on DNCE90015) to document the allocation of work between performers or choreographers and any digital or AI tools used (music editing, documentation, scheduling), with that allocation among the assessed criteria. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| C5 Inquiry & evidence generation | 2 → 3 | "A substantial project generating primary evidence is REQUIRED (not one route among several), with methodology defended under scrutiny (viva, defence, or staged supervised review)." | Add a staged supervised review or viva to the Research Project's (DNCE90019) existing creative-portfolio-plus-exegesis assessment, so the required methodology is defended under scrutiny rather than submitted only in writing. | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| W2 Authentic task design | 2 → 3 | "Such tasks are the program's assessment spine rather than a single instance (a capstone plus earlier scaffolding, or at least one per stage) AND at least one carries a genuine constraint of practice — an ambiguous or externally supplied problem, real resource/time limits, a consequential audience, or the profession's own standards of performance." | Document explicitly, in at least one core unit's assessment criteria, that judgement is made against the profession's own standards of performance (a venue's programming brief, an external panel's criteria, or a comparable standard), so the program's existing spine of live and placement-based tasks meets the anchor on paper as well as in practice. | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| W3 Work-situated learning | 2 → 3 | "Substantial required work-situated learning: an extended placement or practicum, or a sequence of them, in the core, supervised by a practitioner, assessed, with accountability to the host and structured reflection on professional practice — OR, for a cohort documented as already practising, a required sequence of assessed own-practice activity with structured reflection and documented accountability to workplace stakeholders (trainees, patients, clients or employer)." | Extend the 40-hour Professional Placement (DNCE90017) into a longer placement or a required sequence of two placements, with structured reflection and documented accountability to the host, addressing AITSL's registration expectation (Theme 1, §3) that entry to the Secondary School Teacher pathway rest on more than a short, single placement. | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 3. MARKET ALIGNMENT — Basis: reported → inferred

| Lever | Item | Market evidence | Location in market report | Confidence |
|---|---|---|---|---|
| P1 | C2 | Theme 2: core teaching tasks (lesson planning, resource creation, feedback, assessment drafting) are readily supported by generative AI, making judgement about AI-drafted quality the resilient skill as manual drafting compresses. | §3 Theme 2; §4 skill shift row; §5 CI-3 | HIGH |
| P2 | C1 | Theme 2 and the skill-shift row: AI-assisted resource creation and lesson planning enter the teaching pathway most graduates travel, even though no dance-specific tool-coordination signal is reported. | §3 Theme 2; §4 skill shift row | MEDIUM |
| P3 | W2 | No signal in the market report bears on authentic task design beyond level 2; the report addresses classroom teaching practice, not choreographic or performance task design. | §1; §3 | Not rated — no signal for this item |
| P4 | C3 | Theme 2 and the skill-shift row: teaching tasks are readily AI-supported, and CI-2 names the AI-literacy and governance gap for the Secondary School Teacher pathway directly. | §3 Theme 2; §4 skill shift row; §5 CI-2 | HIGH |
| P5 | W1 | Signal 1: the job-advertisement sample for Secondary School Teacher is dominated by independent and faith-based schools rather than large employers; CI-4 ties this to individually demonstrable professional communication. | §2 Signal 1; §5 CI-4 | HIGH |
| P6 | C2 | As P1 — Theme 2 and the skill-shift row on AI-drafted lesson and assessment material; the level-3 anchor documents reliance decisions on those same tasks. | §3 Theme 2; §4 skill shift row | HIGH |
| P7 | C5 | No signal in the market report bears on inquiry or evidence generation; the occupations and themes named concern classroom practice, not scholarly methodology. | §1; §3 | Not rated — no signal for this item |
| P8 | C3 | As P4 — Theme 1's registration requirement and Theme 2's AI-exposure finding both bear on governance: a registered teacher who cannot critique AI-drafted material's provenance and limits is not meeting either standard. | §3 Theme 1; §3 Theme 2 | HIGH |
| P9 | W1 | As P5 — Signal 1's independent-school hiring pattern rewards demonstrable communication skill; a second externally judged assessment extends that evidence earlier in the program. | §2 Signal 1 | HIGH |
| P10 | W3 | Theme 1: AITSL registration for the Secondary School Teacher pathway rests on an accredited initial-teacher-education program and its practicum expectations; CI-1 records that this program's placement is short and does not, alone, evidence that pathway. | §3 Theme 1; §5 CI-1 | HIGH |

## 4. PRIORITISED INTERVENTIONS — Basis: inferred

| # | Item | Action | Anchor satisfied | Effort | Sequence | Sources |
|---|---|---|---|---|---|---|
| P1 | C2 | Convert one of the graded reflective statements (for example DNCE90015's individual reflective statement) into a criterion-referenced appraisal task: students judge their own and peers' choreographic or performance work against published standards, with the structured critique itself assessed. | C2 level 2 | Low | Year 1–2; rubric update to an existing reflective statement | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P2 | C1 | Require one group choreography assessment (building on DNCE90015) to document the allocation of work between performers or choreographers and any digital or AI tools used (music editing, documentation, scheduling), with that allocation among the assessed criteria. | C1 level 3 | Low | Year 1–2; assessment-criteria update to DNCE90015 | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[5]](https://doi.org/10.1093/qje/qjx022)[[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P3 | W2 | Document explicitly, in at least one core unit's assessment criteria, that judgement is made against the profession's own standards of performance (a venue's programming brief, an external panel's criteria, or a comparable standard), so the program's existing spine of live and placement-based tasks meets the anchor on paper as well as in practice. | W2 level 3 | Low | Next annual course review; criteria documentation only, no new task | [[22]](https://doi.org/10.1007/BF02504676)[[23]](https://doi.org/10.1080/02602938.2017.1412396)[[25]](https://doi.org/10.1016/j.stueduc.2021.101030)[26][[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| P4 | C3 | Add an assessed module addressing what generative AI tools can and cannot do for dance documentation and choreographic idea generation, and — for students heading into the Secondary School Teacher pathway — for lesson and resource preparation, with capabilities and limits both assessed. | C3 level 2 | Low–medium | Year 2; syllabus and rubric update to an existing core subject | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P5 | W1 | Redesign the Professional Placement Report (DNCE90017) so at least one component is judged by the host supervisor or an external practitioner against criteria drawn from professional practice, rather than by the subject coordinator alone. | W1 level 2 | Low–medium | Year 1–2; assessment-design change to DNCE90017's grading | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P6 | C2 | Where a subject uses AI-assisted tools for documentation, notation or research synthesis, require students to document and defend when they relied on or overrode that tool's output. | C2 level 3 | Medium | Year 2; assessment-brief update to a subject already using digital tools | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[4]](https://doi.org/10.1007/s10734-017-0220-3)[[3]](https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf) |
| P7 | C5 | Add a staged supervised review or viva to the Research Project's (DNCE90019) existing creative-portfolio-plus-exegesis assessment, so the required methodology is defended under scrutiny rather than submitted only in writing. | C5 level 3 | Medium | Year 2; assessment redesign to DNCE90019, contingent on assessor capacity for staged reviews | [14][15][[7]](https://doi.org/10.1016/j.techfore.2016.08.019) |
| P8 | C3 | Require a core assessment critiquing the governance of AI use in dance-teaching practice — accountability for AI-drafted lesson or assessment material, and the limits AITSL registration places on delegating professional judgement to a tool — beyond operating the tools. | C3 level 3 | Medium | Next annual course review; assessment redesign following the C3 level-2 module | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[13][[11]](https://doi.org/10.1145/3313831.3376727)[[12]](https://unesdoc.unesco.org/ark:/48223/pf0000391105)[[2]](https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/) |
| P9 | W1 | Add a second, progressively staged externally judged assessment earlier in the program — a public showing or panel judged by a practitioner — with professional conduct explicitly among the assessed criteria. | W1 level 3 | Medium–high | Year 1; a new externally judged showing in a core subject plus conduct criteria | [[19]](https://www.legislation.gov.au/F2021L00488)[[20]](https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29)[[21]](https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework)[[31]](https://www.naceweb.org/career-readiness/competencies/career-readiness-defined)[[5]](https://doi.org/10.1093/qje/qjx022)[[32]](https://doi.org/10.1086/504455) |
| P10 | W3 | Extend the 40-hour Professional Placement (DNCE90017) into a longer placement or a required sequence of two placements, with structured reflection and documented accountability to the host. | W3 level 3 | High | Year 2; course-structure change to DNCE90017, contingent on host-agreement negotiation and supervision capacity | [[19]](https://www.legislation.gov.au/F2021L00488)[27][[29]](https://doi.org/10.1080/07294360.2016.1139551)[[28]](https://doi.org/10.1007/s10734-017-0216-z)[[35]](https://doi.org/10.1080/03075070903216635)[[30]](https://www.education.gov.au/australian-universities-accord/resources/final-report) |

## 5. GATE GUARDRAILS — Basis: scored

| Gate | Status | Evidence carrying the gate | Constraint on redesign | Sources |
|---|---|---|---|---|
| G1 Disciplinary foundation | PASS | The program is documented as an all-compulsory specialist core (seven compulsory dance subjects, 200 points) with a staged progression requirement between Year 1 and Year 2. | Retain the seven-subject compulsory core and the Year 1 → Year 2 progression requirement; the AI-literacy, appraisal and governance additions above must sit inside existing compulsory subjects rather than adding new ones or displacing studio and practice time. | [[1]](https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities)[[6]](https://doi.org/10.1093/qje/qjaa021) |
| G2 Decision-making under uncertainty | PASS | The program documents live, in-situ performance work, a real professional placement, and a capstone research project — formats carrying genuine uncertainty and accountability rather than recall or scripted response. | Preserve the live in-situ performance work, the professional placement and the capstone Research Project as the venues for real uncertainty and accountability; any new assessed component (reliance documentation, governance critique, staged defence, extended reflection) should attach to these existing high-stakes activities rather than sit as a separate, low-stakes written exercise. | [16] |

## 6. WHAT WOULD CHANGE THE SCORE — Basis: inferred

Each row assumes the rows above it have landed; the cumulative columns are the two
sub-scales tracked separately, never summed.

| Lever | Item | From | To | Change | Cumulative adaptive | Cumulative workplace |
|---|---|---|---|---|---|---|
| P1 | C2 | 1 | 2 | +1 adaptive | 10 / 15 | 5 / 9 |
| P2 | C2 | 2 | 3 | +1 adaptive | 11 / 15 | 5 / 9 |
| P3 | C3 | 1 | 2 | +1 adaptive | 12 / 15 | 5 / 9 |
| P4 | C3 | 2 | 3 | +1 adaptive | 13 / 15 | 5 / 9 |
| P5 | W1 | 1 | 2 | +1 workplace | 13 / 15 | 6 / 9 |
| P6 | W1 | 2 | 3 | +1 workplace | 13 / 15 | 7 / 9 |
| P7 | C1 | 2 | 3 | +1 adaptive | 14 / 15 | 7 / 9 |
| P8 | C5 | 2 | 3 | +1 adaptive | 15 / 15 | 7 / 9 |
| P9 | W2 | 2 | 3 | +1 workplace | 15 / 15 | 8 / 9 |
| P10 | W3 | 2 | 3 | +1 workplace | 15 / 15 | 9 / 9 |

What does **not** move a score:

| Change | Why it does not move a score | Governing rule | Sources |
|---|---|---|---|
| Rewriting a course or subject learning outcome to name the capability | An outcome statement is not assessment evidence; the item stays at the level its assessed evidence supports | R2 (level 3 needs assessment evidence); Barrie on stated attributes [33] | [33] |
| Relabelling an existing task "authentic", "real-world" or "industry-relevant" | W2 is scored from documented task features against the discipline's criterion situation, never from the label | R4; Gulikers et al. [[22]](https://doi.org/10.1007/BF02504676); Fawns et al. on the label as a thought-terminating cliché [[24]](https://doi.org/10.1080/02602938.2024.2404634) | [[22]](https://doi.org/10.1007/BF02504676)[[24]](https://doi.org/10.1080/02602938.2024.2404634) |
| Adding or promoting an elective that would satisfy the anchor | Every level-2 and level-3 anchor in this instrument requires CORE placement; an elective leaves the cohort's guaranteed curriculum unchanged | Anchor wording ("core unit", "required"); the cohort-wide reading of HESF 1.4.3 [[19]](https://www.legislation.gov.au/F2021L00488) | [[19]](https://www.legislation.gov.au/F2021L00488) |

## REFERENCES

1. Lodge JM, de Barba P, Ainscough L, et al. (2026). Assuring quality learning in a gen AI-integrated future: The role of adaptive capabilities. TEQSA. https://www.teqsa.gov.au/guides-resources/resources/corporate-publications/assuring-quality-learning-gen-ai-integrated-future-role-adaptive-capabilities
2. Lodge JM, et al. (2025). Australian Framework for Artificial Intelligence in Higher Education. ACSES. (Principles 4 & 6.) https://www.acses.edu.au/publication/australian-framework-for-artificial-intelligence-in-higher-education/
3. Lodge JM, Howard S, Bearman M, Dawson P & Associates (2023). Assessment reform for the age of artificial intelligence. TEQSA. https://www.teqsa.gov.au/sites/default/files/2023-09/assessment-reform-age-artificial-intelligence-discussion-paper.pdf
4. Tai J, Ajjawi R, Boud D, Dawson P, Panadero E (2018). Developing evaluative judgement: enabling students to make decisions about the quality of work. Higher Education 76:467–481. https://doi.org/10.1007/s10734-017-0220-3
5. Deming DJ (2017). The growing importance of social skills in the labor market. Quarterly Journal of Economics 132(4):1593–1640. https://doi.org/10.1093/qje/qjx022
6. Deming DJ, Noray K (2020). Earnings dynamics, changing job skills, and STEM careers. Quarterly Journal of Economics 135(4):1965–2005. https://doi.org/10.1093/qje/qjaa021
7. Frey CB, Osborne MA (2017). The future of employment: how susceptible are jobs to computerisation? Technological Forecasting & Social Change 114:254–280. https://doi.org/10.1016/j.techfore.2016.08.019
8. Brynjolfsson E, Mitchell T, Rock D (2018). What can machines learn, and what does it mean for occupations and the economy? AEA Papers & Proceedings 108:43–47. (The SML rubric — the declarative-anchor form R1 copies.) https://doi.org/10.1257/pandp.20181019
9. Pellegrino JW, Hilton ML (eds) (2012). Education for Life and Work: Developing Transferable Knowledge and Skills in the 21st Century. National Research Council. https://www.nationalacademies.org/read/13398/chapter/2
10. Measuring adaptive expertise and adaptive performance in (becoming) healthcare professionals: a scoping review of measurement instruments (2025). Advances in Health Sciences Education. https://doi.org/10.1007/s10459-025-10413-y
11. Long D, Magerko B (2020). What is AI literacy? Competencies and design considerations. CHI 2020. https://doi.org/10.1145/3313831.3376727
12. UNESCO (2024). AI competency framework for students. https://unesdoc.unesco.org/ark:/48223/pf0000391105
13. European Commission JRC — DigComp (Digital Competence Framework for Citizens); basis of the Australian Digital Capability Framework (DEWR, 2022).
14. Boyer EL (1990). Scholarship Reconsidered: Priorities of the Professoriate. Carnegie Foundation.
15. Brew A (2006). Research and Teaching: Beyond the Divide. Palgrave Macmillan.
16. Knight FH (1921). Risk, Uncertainty and Profit. Houghton Mifflin.
17. Kane MT (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement 50(1):1–73. (The validity-argument frame for the v4 evidence plan.)
18. Woods L, Lyons K, et al. (2026). Assessing the effectiveness of artificial intelligence education and training for healthcare workers: a systematic review. BMC Medical Education 26:549. (The construct-validity critique v4 answers.) https://doi.org/10.1186/s12909-026-08969-3
19. Higher Education Standards Framework (Threshold Standards) 2021, F2021L00488. Clause 1.4.2(b)–(d) (generic and employment-related learning outcomes, applied in disciplinary context), 1.4.3 (assessment must confirm the outcomes), 5.4.1 (work-integrated learning and placements are quality assured, including supervision). https://www.legislation.gov.au/F2021L00488
20. QILT Employer Satisfaction Survey (ESS) — national employer ratings across five graduate attribute domains: foundation, adaptive, collaborative, technical and employability skills. (2025 national results: technical 94.0%, foundation 93.3%, adaptive 90.7%, collaborative 88.6%, employability 86.2%.) https://www.qilt.edu.au/surveys/employer-satisfaction-survey-%28ess%29
21. Core Skills for Work Developmental Framework (Australian Government, 2013). Three clusters — navigate the world of work, interact with others, get the work done — over ten skill areas and five performance stages. Anchor-content source; a VET framework, not a higher-education construct authority. https://www.dewr.gov.au/skills-information-training-providers/resources/core-skills-work-developmental-framework
22. Gulikers JTM, Bastiaens TJ, Kirschner PA (2004). A five-dimensional framework for authentic assessment. Educational Technology Research and Development 52(3):67–86. (Task, physical context, social context, result/form, criteria; authenticity is a continuum defined against the criterion situation — design rule R4.) https://doi.org/10.1007/BF02504676
23. Villarroel V, Bloxham S, Bruna D, Bruna C, Herrera-Seda C (2018). Authentic assessment: creating a blueprint for course design. Assessment & Evaluation in Higher Education 43(5):840–854. (Realism, cognitive challenge, evaluative judgement — the third dimension is DFVA C2, not W2.) https://doi.org/10.1080/02602938.2017.1412396
24. Fawns T, Bearman M, Dawson P, Nieminen JH, Ashford-Rowe K, Willey K, Jensen LX, Damşa C, Press N (2024). Authentic assessment: from panacea to criticality. Assessment & Evaluation in Higher Education 50(3):396–408. (The label risks becoming a 'thought-terminating cliché' — the constraint behind R4.) https://doi.org/10.1080/02602938.2024.2404634
25. Sokhanvar Z, Salehi K, Sokhanvar F (2021). Advantages of authentic assessment for improving the learning experience and employability skills of higher education students: a systematic literature review. Studies in Educational Evaluation 70:101030. (26 studies, 2010–2019; outcomes largely student self-report.) https://doi.org/10.1016/j.stueduc.2021.101030
26. Gibbs G, Simpson C (2004). Conditions under which assessment supports students' learning. Learning and Teaching in Higher Education 1:3–31. (Assessment governs what and how students study — the mechanism warrant for scoring assessment design rather than curriculum statement.)
27. Kuh GD (2008). High-Impact Educational Practices: What They Are, Who Has Access to Them, and Why They Matter. AAC&U. (Internships, capstones, undergraduate research, collaborative and community-based learning; shared features include sustained time and effort, feedback, and application in novel settings.)
28. Jackson D, Collings D (2018). The influence of work-integrated learning and paid work during studies on graduate employment and underemployment. Higher Education 76:403–425. (WIL did NOT raise full-time employment rates; evidence for better relevance and quality of employment — the honest bound on the W3 claim.) https://doi.org/10.1007/s10734-017-0216-z
29. Jackson D (2016). Re-conceptualising graduate employability: the importance of pre-professional identity. Higher Education Research & Development 35(5):925–939. (Identity formed through participation in communities of practice — the mechanism distinguishing W3 from W2.) https://doi.org/10.1080/07294360.2016.1139551
30. Australian Universities Accord Final Report (2024), Department of Education. (WIL as national priority; placement poverty and the Commonwealth Prac Payment — the equity limitation declared against W3.) https://www.education.gov.au/australian-universities-accord/resources/final-report
31. NACE Career Readiness Competencies (rev. April 2024). Eight competencies: career & self-development, communication, critical thinking, equity & inclusion, leadership, professionalism, teamwork, technology. https://www.naceweb.org/career-readiness/competencies/career-readiness-defined
32. Heckman JJ, Stixrud J, Urzua S (2006). The effects of cognitive and noncognitive abilities on labor market outcomes and social behavior. Journal of Labor Economics 24(3):411–482. https://doi.org/10.1086/504455
33. Barrie SC (2006). Understanding what we mean by the generic attributes of graduates. Higher Education 51:215–241; and Barrie SC (2007), A conceptual framework for the teaching and learning of generic graduate attributes, Studies in Higher Education 32(4):439–458. (Stated graduate attributes are not evidence of attainment — why R2 binds hardest on W1.)
34. Tomlinson M (2017). Forms of graduate capital and their relationship to graduate employability. Education + Training 59(4):338–352. (Scoping source: social, cultural and psychological capital are student and network properties, not curriculum properties, and are therefore out of scope.)
35. Lester S, Costley C (2010). Work-based learning at higher education level: value, practice and critique. Studies in Higher Education 35(5):561–575. (Work-based learning in the learner's own employment as an established higher-education mode for in-practice cohorts — the warrant for W3's own-practice route, added in v4.2.) https://doi.org/10.1080/03075070903216635
`,
};

export default content;
