// Auto-generated: all program improvement roadmaps
// Generated by scripts/generate-recommend-content.py

export const RECOMMEND_CONTENT_ALL: Record<string, { title: string; institution: string; markdown: string }> = {
  "dfva-recommend-439fs": {
    title: "Master of Food Science \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Food Science

**Current:** 21/36 MODERATE RISK | **Duration:** 2 years (200 pts)
**Target:** 28/36 RESILIENT | **Gap:** 7 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Technical Depth | 2 → 3 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 3 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 4 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |
| 5 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |
| 6 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 2 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 21 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 30 | RESILIENT |
`,
  },
  "dfva-recommend-527cl": {
    title: "527CL \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: 527CL

**Current:** 27/36 MODERATE RISK | **Duration:** 2y FT (200 pts)
**Target:** 28/36 RESILIENT | **Gap:** 1 point

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 2 | Technical Depth | 2 → 3 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 27 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 31 | RESILIENT |
`,
  },
  "dfva-recommend-746st": {
    title: "746ST \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: 746ST

**Current:** 20/36 MODERATE RISK | **Duration:** N/A
**Target:** 28/36 RESILIENT | **Gap:** 8 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 2 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |
| 3 | Automation Exposure | 1 → 2 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 4 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 5 | Research Rigour | 1 → 3 | +2 | Introduce a minor thesis or capstone research project | High |
| 6 | Irreplaceability (bonus) | 2 → 3 | +1 | Add regulatory accreditation or professional registration pathway | High |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 20 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
`,
  },
  "dfva-recommend-b-des": {
    title: "Bachelor of Design \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Bachelor of Design

**Current:** 17/36 MODERATE RISK | **Duration:** 3 years (typical full-time)
**Target:** 28/36 RESILIENT | **Gap:** 11 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Technical Depth | 1 → 2 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 2 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 3 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 4 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |
| 5 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |
| 6 | Outcome Evidence | 2 → 3 | +1 | Add QILT GOS data + 3-year outcomes to public program information | Low |
| 7 | Automation Exposure | 1 → 2 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 8 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 9 | Domain Depth | 2 → 3 | +1 | Seek professional accreditation or industry partnership | High |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 17 | MODERATE RISK |
| P1 only | 27 | MODERATE RISK |
`,
  },
  "dfva-recommend-b-sci": {
    title: "Bachelor of Science \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Bachelor of Science

**Current:** 23/36 MODERATE RISK | **Duration:** 3 years (300 credit points)
**Target:** 28/36 RESILIENT | **Gap:** 5 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Human & Relational | 1 → 2 | +1 | Add ethics/professional practice unit or workshop series | Low |
| 2 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 3 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 4 | Outcome Evidence | 2 → 3 | +1 | Add QILT GOS data + 3-year outcomes to public program information | Low |
| 5 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | AI Literacy | 2 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 23 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 30 | RESILIENT |
`,
  },
  "dfva-recommend-mc-actsc": {
    title: "Master of Actuarial Science \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Actuarial Science

**Current:** 20/36 MODERATE RISK | **Duration:** 1.5 years (150 credit points)
**Target:** 28/36 RESILIENT | **Gap:** 8 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 3 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |
| 4 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |
| 5 | Outcome Evidence | 2 → 3 | +1 | Add QILT GOS data + 3-year outcomes to public program information | Low |
| 6 | Automation Exposure | 1 → 2 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 7 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Research Rigour | 1 → 3 | +2 | Introduce a minor thesis or capstone research project | High |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 20 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 30 | RESILIENT |
`,
  },
  "dfva-recommend-mc-apbusa": {
    title: "MC-APBUSA \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: MC-APBUSA

**Current:** 20/36 MODERATE RISK | **Duration:** N/A
**Target:** 28/36 RESILIENT | **Gap:** 8 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 3 | Automation Exposure | 1 → 2 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 4 | Domain Depth | 2 → 3 | +1 | Seek professional accreditation or industry partnership | High |
| 5 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 20 | MODERATE RISK |
| P1 only | 25 | MODERATE RISK |
`,
  },
  "dfva-recommend-mc-arch": {
    title: "Master of Architecture \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Architecture

**Current:** 28/36 MODERATE RISK | **Duration:** N/A
**Target:** 28/36 RESILIENT | **Gap:** 0 points

---

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 2 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 28 | MODERATE RISK |
| All actions | 31 | RESILIENT |
`,
  },
  "dfva-recommend-mc-ba": {
    title: "Master of Business Administration \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Business Administration

**Current:** 25/36 MODERATE RISK | **Duration:** N/A
**Target:** 28/36 RESILIENT | **Gap:** 3 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Technical Depth | 2 → 3 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 3 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Automation Exposure | 1 → 2 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 2 | Research Rigour | 1 → 3 | +2 | Introduce a minor thesis or capstone research project | High |
| 3 | Domain Depth | 2 → 3 | +1 | Seek professional accreditation or industry partnership | High |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 25 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 32 | RESILIENT |
`,
  },
  "dfva-recommend-mc-bamktg": {
    title: "MC-BAMKTG \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: MC-BAMKTG

**Current:** 17/36 HIGH RISK | **Duration:** 2 years (300 pts)
**Target:** 28/36 RESILIENT | **Gap:** 11 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Technical Depth | 1 → 2 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 2 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 3 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 4 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |
| 5 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |
| 6 | Automation Exposure | 1 → 2 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 7 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 8 | Research Rigour | 1 → 3 | +2 | Introduce a minor thesis or capstone research project | High |
| 9 | Domain Depth | 2 → 3 | +1 | Seek professional accreditation or industry partnership | High |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Irreplaceability (bonus) | 2 → 3 | +1 | Add regulatory accreditation or professional registration pathway | High |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 17 | HIGH RISK |
| P1 only | 28 | RESILIENT |
| All actions | 29 | RESILIENT |
`,
  },
  "dfva-recommend-mc-base": {
    title: "MC-BASE \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: MC-BASE

**Current:** 18/36 HIGH RISK | **Duration:** 18m FT (225 pts)
**Target:** 28/36 RESILIENT | **Gap:** 10 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Technical Depth | 1 → 2 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 2 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 3 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |
| 4 | Automation Exposure | 1 → 2 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 5 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 6 | Research Rigour | 1 → 3 | +2 | Introduce a minor thesis or capstone research project | High |
| 7 | Irreplaceability (bonus) | 1 → 2 | +1 | Develop a dual-skill pathway (e.g., tech + domain, clinical + research) | High |
| 8 | Domain Depth | 2 → 3 | +1 | Seek professional accreditation or industry partnership | High |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 18 | HIGH RISK |
| P1 only | 28 | RESILIENT |
`,
  },
  "dfva-recommend-mc-bmedsc": {
    title: "Master of Biomedical Science \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Biomedical Science

**Current:** 25/36 MODERATE RISK | **Duration:** 2 years (200 pts)
**Target:** 28/36 RESILIENT | **Gap:** 3 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 25 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 29 | RESILIENT |
`,
  },
  "dfva-recommend-mc-busana": {
    title: "Master of Business Analytics \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Business Analytics

**Current:** 31/36 RESILIENT | **Duration:** N/A
**Target:** 28/36 RESILIENT | **Gap:** 0 points

---

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 2 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |
| 3 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 31 | RESILIENT |
| All actions | 34 | RESILIENT |
`,
  },
  "dfva-recommend-mc-climsci": {
    title: "Master of Climate Science \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Climate Science

**Current:** 26/36 MODERATE RISK | **Duration:** 2 years (200 pts)
**Target:** 28/36 RESILIENT | **Gap:** 2 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |
| 2 | Outcome Evidence | 2 → 3 | +1 | Add QILT GOS data + 3-year outcomes to public program information | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 2 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 3 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 26 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 32 | RESILIENT |
`,
  },
  "dfva-recommend-mc-clind": {
    title: "MC-CLIND \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: MC-CLIND

**Current:** 23/36 MODERATE RISK | **Duration:** N/A
**Target:** 28/36 RESILIENT | **Gap:** 5 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 1 → 2 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Technical Depth | 2 → 3 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 3 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |
| 4 | AI Literacy | 0 → 2 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 23 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 29 | RESILIENT |
`,
  },
  "dfva-recommend-mc-cs": {
    title: "Master of Computer Science \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Computer Science

**Current:** 27/36 MODERATE RISK | **Duration:** 2 years (200 credit points)
**Target:** 28/36 RESILIENT | **Gap:** 1 point

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 2 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 27 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 30 | RESILIENT |
`,
  },
  "dfva-recommend-mc-datasc": {
    title: "Master of Data Science \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Data Science

**Current:** 24/36 MODERATE RISK | **Duration:** 2 years (200 credit points)
**Target:** 28/36 RESILIENT | **Gap:** 4 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 3 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |
| 4 | Technical Depth | 2 → 3 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 2 | AI Literacy | 2 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 3 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 24 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 32 | RESILIENT |
`,
  },
  "dfva-recommend-mc-ed": {
    title: "Master of Education \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Education

**Current:** 24/36 MODERATE RISK | **Duration:** 2 years (200 pts)
**Target:** 28/36 RESILIENT | **Gap:** 4 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Technical Depth | 1 → 2 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 2 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 3 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 4 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 2 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 3 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 24 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 32 | RESILIENT |
`,
  },
  "dfva-recommend-mc-envlaw": {
    title: "Master of Environmental Law \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Environmental Law

**Current:** 24/36 MODERATE RISK | **Duration:** N/A
**Target:** 28/36 RESILIENT | **Gap:** 4 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Technical Depth | 1 → 2 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 2 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 3 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 4 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Automation Exposure | 1 → 2 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 2 | Research Rigour | 1 → 3 | +2 | Introduce a minor thesis or capstone research project | High |
| 3 | AI Literacy | 2 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 24 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 33 | RESILIENT |
`,
  },
  "dfva-recommend-mc-envsc": {
    title: "Master of Environmental Science \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Environmental Science

**Current:** 23/36 MODERATE RISK | **Duration:** 2 years (200 pts)
**Target:** 28/36 RESILIENT | **Gap:** 5 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Technical Depth | 2 → 3 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 2 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |
| 3 | Outcome Evidence | 2 → 3 | +1 | Add QILT GOS data + 3-year outcomes to public program information | Low |
| 4 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 2 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |
| 3 | Irreplaceability (bonus) | 2 → 3 | +1 | Add regulatory accreditation or professional registration pathway | High |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 23 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 31 | RESILIENT |
`,
  },
  "dfva-recommend-mc-gencoun": {
    title: "Master of Genetic Counselling \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Genetic Counselling

**Current:** 26/36 MODERATE RISK | **Duration:** 2 years (200 pts)
**Target:** 28/36 RESILIENT | **Gap:** 2 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Technical Depth | 2 → 3 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 2 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 26 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 31 | RESILIENT |
`,
  },
  "dfva-recommend-mc-indeng": {
    title: "MC-INDENG \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: MC-INDENG

**Current:** 22/36 MODERATE RISK | **Duration:** 2 years (200 pts)
**Target:** 28/36 RESILIENT | **Gap:** 6 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Technical Depth | 1 → 2 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 2 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 3 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |
| 4 | Automation Exposure | 1 → 2 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 5 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 22 | MODERATE RISK |
| P1 only | 27 | MODERATE RISK |
`,
  },
  "dfva-recommend-mc-intedib": {
    title: "MC-INTEDIB \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: MC-INTEDIB

**Current:** 16/36 HIGH RISK | **Duration:** N/A
**Target:** 28/36 RESILIENT | **Gap:** 12 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Technical Depth | 1 → 2 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 2 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 3 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 4 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |
| 5 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |
| 6 | Automation Exposure | 1 → 2 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 7 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 8 | Research Rigour | 1 → 3 | +2 | Introduce a minor thesis or capstone research project | High |
| 9 | Irreplaceability (bonus) | 1 → 2 | +1 | Develop a dual-skill pathway (e.g., tech + domain, clinical + research) | High |
| 10 | Domain Depth | 2 → 3 | +1 | Seek professional accreditation or industry partnership | High |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 16 | HIGH RISK |
| P1 only | 28 | RESILIENT |
`,
  },
  "dfva-recommend-mc-is": {
    title: "Master of Information Systems \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Information Systems

**Current:** 18/36 MODERATE RISK | **Duration:** 1.5–2 years (200 credit points)
**Target:** 28/36 RESILIENT | **Gap:** 10 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 3 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |
| 4 | Outcome Evidence | 2 → 3 | +1 | Add QILT GOS data + 3-year outcomes to public program information | Low |
| 5 | Automation Exposure | 1 → 2 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 6 | Irreplaceability (bonus) | 1 → 2 | +1 | Develop a dual-skill pathway (e.g., tech + domain, clinical + research) | High |
| 7 | Domain Depth | 2 → 3 | +1 | Seek professional accreditation or industry partnership | High |
| 8 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |
| 9 | AI Literacy | 2 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 18 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
`,
  },
  "dfva-recommend-mc-journ": {
    title: "Master of Journalism \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Journalism

**Current:** 23/36 MODERATE RISK | **Duration:** N/A
**Target:** 28/36 RESILIENT | **Gap:** 5 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Technical Depth | 1 → 2 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 2 | Curriculum Currency | 1 → 2 | +1 | Establish annual curriculum review with industry advisory panel | Low |
| 3 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 4 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 5 | Outcome Evidence | 2 → 3 | +1 | Add QILT GOS data + 3-year outcomes to public program information | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Automation Exposure | 1 → 2 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 2 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 3 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 23 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 32 | RESILIENT |
`,
  },
  "dfva-recommend-mc-nursc": {
    title: "Master of Nursing Science \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Nursing Science

**Current:** 26/36 MODERATE RISK | **Duration:** 2 years (200 pts)
**Target:** 28/36 RESILIENT | **Gap:** 2 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Technical Depth | 2 → 3 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 2 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 26 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 31 | RESILIENT |
`,
  },
  "dfva-recommend-mc-phtyph": {
    title: "MC-PHTYPH \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: MC-PHTYPH

**Current:** 25/36 MODERATE RISK | **Duration:** N/A
**Target:** 28/36 RESILIENT | **Gap:** 3 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 1 → 2 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Technical Depth | 2 → 3 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 3 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 25 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 30 | RESILIENT |
`,
  },
  "dfva-recommend-mc-prop": {
    title: "Master of Property \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Property

**Current:** 23/36 MODERATE RISK | **Duration:** N/A
**Target:** 28/36 RESILIENT | **Gap:** 5 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Technical Depth | 2 → 3 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 3 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 4 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |
| 5 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 2 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |
| 3 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 23 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 32 | RESILIENT |
`,
  },
  "dfva-recommend-mc-propsyc": {
    title: "Master of Professional Psychology \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Professional Psychology

**Current:** 26/36 MODERATE RISK | **Duration:** 2 years (200 pts)
**Target:** 28/36 RESILIENT | **Gap:** 2 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Technical Depth | 2 → 3 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 2 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 26 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 31 | RESILIENT |
`,
  },
  "dfva-recommend-mc-scibif": {
    title: "Master of Science (Bioinformatics) \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Science (Bioinformatics)

**Current:** 24/36 MODERATE RISK | **Duration:** 2 years (200 credit points) or 1.5 years (150 credit points cognate pathway)
**Target:** 28/36 RESILIENT | **Gap:** 4 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 3 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 24 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 29 | RESILIENT |
`,
  },
  "dfva-recommend-mc-scibio": {
    title: "Master of Science (BioSciences) \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Science (BioSciences)

**Current:** 25/36 MODERATE RISK | **Duration:** 2 years (200 pts)
**Target:** 28/36 RESILIENT | **Gap:** 3 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Outcome Evidence | 2 → 3 | +1 | Add QILT GOS data + 3-year outcomes to public program information | Low |
| 3 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 25 | MODERATE RISK |
| P1 only | 29 | RESILIENT |
| All actions | 30 | RESILIENT |
`,
  },
  "dfva-recommend-mc-scibit": {
    title: "Master of Biotechnology \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Biotechnology

**Current:** 24/36 MODERATE RISK | **Duration:** 2 years full-time / 4 years part-time
**Target:** 28/36 RESILIENT | **Gap:** 4 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Technical Depth | 2 → 3 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 3 | Outcome Evidence | 2 → 3 | +1 | Add QILT GOS data + 3-year outcomes to public program information | Low |
| 4 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 24 | MODERATE RISK |
| P1 only | 29 | RESILIENT |
| All actions | 30 | RESILIENT |
`,
  },
  "dfva-recommend-mc-sciche": {
    title: "Master of Science (Chemistry) \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Science (Chemistry)

**Current:** 25/36 MODERATE RISK | **Duration:** 2 years (200 pts)
**Target:** 28/36 RESILIENT | **Gap:** 3 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |
| 3 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 2 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 25 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 31 | RESILIENT |
`,
  },
  "dfva-recommend-mc-sciear": {
    title: "Master of Science \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Science

**Current:** 24/36 MODERATE RISK | **Duration:** 2 years full-time / 4 years part-time
**Target:** 28/36 RESILIENT | **Gap:** 4 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Outcome Evidence | 2 → 3 | +1 | Add QILT GOS data + 3-year outcomes to public program information | Low |
| 3 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 24 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
`,
  },
  "dfva-recommend-mc-sciepi": {
    title: "Master of Science \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Science

**Current:** 23/36 MODERATE RISK | **Duration:** 2 years full-time / 4 years part-time
**Target:** 28/36 RESILIENT | **Gap:** 5 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 3 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |
| 4 | Outcome Evidence | 2 → 3 | +1 | Add QILT GOS data + 3-year outcomes to public program information | Low |
| 5 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 23 | MODERATE RISK |
| P1 only | 29 | RESILIENT |
| All actions | 30 | RESILIENT |
`,
  },
  "dfva-recommend-mc-sciphy": {
    title: "Master of Science (Physics) \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Science (Physics)

**Current:** 25/36 MODERATE RISK | **Duration:** 2 years (200 pts)
**Target:** 28/36 RESILIENT | **Gap:** 3 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |
| 3 | Outcome Evidence | 2 → 3 | +1 | Add QILT GOS data + 3-year outcomes to public program information | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 2 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 25 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 31 | RESILIENT |
`,
  },
  "dfva-recommend-mc-scwr": {
    title: "MC-SCWR \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: MC-SCWR

**Current:** 11/36 CRITICAL | **Duration:** 18m FT (150 pts)
**Target:** 28/36 RESILIENT | **Gap:** 17 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 1 → 2 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Technical Depth | 1 → 2 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 3 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 4 | Human & Relational | 2 → 3 | +1 | Integrate stakeholder engagement into existing project assessment | Low |
| 5 | Outcome Evidence | 2 → 3 | +1 | Add QILT GOS data + 3-year outcomes to public program information | Low |
| 6 | Automation Exposure | 0 → 1 | +1 | Introduce capstone/internship with real client accountability | High |
| 7 | AI Literacy | 0 → 2 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 8 | Research Rigour | 0 → 2 | +2 | Introduce a minor thesis or capstone research project | High |
| 9 | Domain Depth | 2 → 3 | +1 | Seek professional accreditation or industry partnership | High |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 11 | CRITICAL |
| P1 only | 22 | MODERATE RISK |
`,
  },
  "dfva-recommend-mc-surged": {
    title: "MC-SURGED \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: MC-SURGED

**Current:** 23/36 MODERATE RISK | **Duration:** 3y PT (150 pts)
**Target:** 28/36 RESILIENT | **Gap:** 5 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Technical Depth | 1 → 2 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 2 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 3 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 4 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |
| 5 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 23 | MODERATE RISK |
| P1 only | 29 | RESILIENT |
| All actions | 30 | RESILIENT |
`,
  },
  "dfva-recommend-mc-tesol": {
    title: "Master of TESOL \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of TESOL

**Current:** 23/36 MODERATE RISK | **Duration:** N/A
**Target:** 28/36 RESILIENT | **Gap:** 5 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Technical Depth | 1 → 2 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 2 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 3 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |
| 4 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |
| 5 | Automation Exposure | 1 → 2 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 2 | Domain Depth | 2 → 3 | +1 | Seek professional accreditation or industry partnership | High |
| 3 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 23 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 32 | RESILIENT |
`,
  },
  "dfva-recommend-mc-urbdes": {
    title: "Master of Urban Design \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Urban Design

**Current:** 26/36 MODERATE RISK | **Duration:** 2 years (200 pts)
**Target:** 28/36 RESILIENT | **Gap:** 2 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Curriculum Currency | 2 → 3 | +1 | Add emerging-trends module updated each intake | Low |
| 2 | Outcome Evidence | 2 → 3 | +1 | Add QILT GOS data + 3-year outcomes to public program information | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 2 | Automation Exposure | 2 → 3 | +1 | Require industry project with defended outputs and stakeholder presentation | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 26 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 31 | RESILIENT |
`,
  },
  "dfva-recommend-mc-urbhort": {
    title: "Master of Urban Horticulture \u2014 Improvement Plan",
    institution: "University of Melbourne",
    markdown: `## IMPROVEMENT PLAN: Master of Urban Horticulture

**Current:** 25/36 MODERATE RISK | **Duration:** N/A
**Target:** 28/36 RESILIENT | **Gap:** 3 points

---

### Priority 1 Actions (reach RESILIENT)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | Systems Thinking | 2 → 3 | +1 | Integrate cross-disciplinary case studies into existing core units | Low |
| 2 | Technical Depth | 2 → 3 | +1 | Require technical-elective sequence (3+ units) with applied project | Low |
| 3 | Decision-Making | 2 → 3 | +1 | Add capstone project requiring documented decision rationale | Low |

### Priority 2 Actions (bonus resilience)

| # | Dimension | Current → Target | Impact | Action | Effort |
|---|-----------|-----------------|--------|--------|--------|
| 1 | AI Literacy | 1 → 3 | +2 | Add dedicated AI in discipline core unit (12.5pt) | Medium |
| 2 | Research Rigour | 2 → 3 | +1 | Replace literature review with primary data collection requirement | Medium |

### Score Impact

| Scenario | Score | Band |
|----------|-------|------|
| Current | 25 | MODERATE RISK |
| P1 only | 28 | RESILIENT |
| All actions | 31 | RESILIENT |
`,
  }
};
