// Auto-generated: per-faculty DFVA briefings (real UoM graduate-outcome evidence).
// Generated by scripts/generate-faculty-content.py — edit the source markdown in reports/, not here.

export const REPORT_CONTENT_FACULTY: Record<string, { title: string; institution: string; markdown: string }> = {
  "dfva-faculty-architecture": {
    title: "Faculty of Architecture, Building and Planning \u2014 DFVA Briefing",
    institution: "University of Melbourne",
    markdown: `# Faculty of Architecture, Building and Planning — DFVA Briefing

**University of Melbourne**  
**Coverage:** 4 DFVA-assessed programmes · 11 Job Insights reports · 1,558 alumni (2015–2025)  
**Generated:** 2026-06-21  
**Source:** UoM Job Insights Reports (LiveAlumni, 2015–2025) + the 41-programme DFVA assessment

## 1. FACULTY PROFILE

Architecture, Building and Planning is bimodal: a RESILIENT Master of Architecture at one end and a HIGH RISK Bachelor of Design at the other. Deep Domain Depth and strong decision-making across the faculty, with the familiar **AI Literacy** weak point and a soft **Outcome Evidence** score that the Job Insights data directly addresses.

## 2. DFVA SCORECARD — FACULTY MEAN

| # | Dimension | Mean /3 | Read |
|---|---|---|---|
| 1 | Automation Exposure | 2.0 | — |
| 2 | Systems Thinking | 2.5 | — |
| 3 | Technical Depth | 1.5 | — |
| 4 | Decision-Making | 2.5 | — |
| 5 | AI Literacy | 1.0 | Faculty weak point |
| 6 | Domain Depth | 2.75 | Faculty strength |
| 7 | Research Rigour | 2.25 | — |
| 8 | Human & Relational | 2.25 | — |
| 9 | Curriculum Currency | 2.0 | — |
| 10 | Outcome Evidence | 1.75 | — |
| B | Irreplaceability | 2.5 | — |

**TOTAL: 23 / 36** — MODERATE RISK (faculty mean; programme range 17–28)

**Programmes assessed:**

| Programme | Score | Band |
|---|---|---|
| Master of Architecture | 28 | RESILIENT |
| Master of Urban Design | 25 | MODERATE RISK |
| Master of Property | 22 | MODERATE RISK |
| Bachelor of Design | 17 | HIGH RISK |

## 3. GRADUATE OUTCOMES — UoM JOB INSIGHTS

Real destinations of **1,558 alumni** across **11 programmes** (LiveAlumni, 2015–2025).

**Top employers:** Lendlease · Multiplex · Mirvac · John Holland · AECOM · JLL · Victorian Planning Authority · Urbis · Woods Bagot · Hassell

**Entry roles (0–1 yr):** Architectural Assistant · Architectural Designer · Architectural Draftsperson · Architectural Technician · Graduate Cost Manager · Cadet Quantity Surveyor · Graphic Designer

**Early-mid roles (1–2 yr):** Urban Designer · Project Coordinator · Quantity Surveyor · Architect · Landscape Architect · Assistant Project Manager

**Skills in use:** Project Management · Teamwork · Adobe Photoshop · Sustainable Design · Urban Design · Time Management · Leadership · Stakeholder Management

**Largest samples:** Master of Architecture (n=621) · Bachelor of Design (Architecture) (n=248) · Master of Construction Management (n=161) · Master of Urban Planning (n=130) · Bachelor of Design (Construction) (n=97)

## 4. DESTINATION CONVERGENCE & EXPOSURE READ

Graduates flow to the major developers and contractors (Lendlease, Multiplex, Mirvac, John Holland), the global commercial-real-estate agencies (JLL, Urbis), and the leading design studios (Woods Bagot, Hassell, Bates Smart). The career arc is visible in the data — Architectural Assistant / Cadet Quantity Surveyor → Architect / Urban Designer / Quantity Surveyor — a registration-gated, judgement-led trajectory with moderate automation exposure.

## 5. OUTCOME-EVIDENCE RECLASSIFICATION

Programmes in this faculty whose **D10 Outcome Evidence** gains a documented basis to rise once the Job Insights destination data is folded in (exact match → D10=3; cognate → D10≥2). A re-review trigger, not an automatic recompute.

| Programme | Current | → Total | Band change |
|---|---|---|---|
| Master of Architecture | 28 | 29 | RESILIENT |
| Master of Property | 22 | 23 | MODERATE RISK |
| Bachelor of Design | 17 | 18 | HIGH RISK |

## 6. WHAT THIS MEANS

1. Publish the Bachelor of Design specialisation destinations (n=248) — the largest lever on its HIGH RISK score is Outcome Evidence, which the Job Insights data supplies.
2. Master of Architecture and Master of Property both gain a documented basis to lift Outcome Evidence.
3. Build computational-design / BIM AI literacy (the faculty's weak dimension); the built-environment toolchain is automating at the junior tier.

## Provenance

Graduate-outcome data: UoM Job Insights Reports (Careers Online / LiveAlumni, graduates 2015–2025); samples are a floor (not all alumni), AI-extracted and Careers-curated. DFVA scores: faculty means over the 41-programme assessment (means aggregate heterogeneous programmes; see the per-programme reports for detail). Reclassification projections are illustrative and reproducible from \`scratch/jobinsights/dfva_jir_map.json\`.
`,
  },
  "dfva-faculty-arts": {
    title: "Faculty of Arts \u2014 DFVA Briefing",
    institution: "University of Melbourne",
    markdown: `# Faculty of Arts — DFVA Briefing

**University of Melbourne**  
**Coverage:** 2 DFVA-assessed programmes · 33 Job Insights reports · 5,071 alumni (2015–2025)  
**Generated:** 2026-06-21  
**Source:** UoM Job Insights Reports (LiveAlumni, 2015–2025) + the 41-programme DFVA assessment

## 1. FACULTY PROFILE

The Faculty of Arts is where DFVA and the Job Insights data diverge most sharply — and most usefully. DFVA currently assesses only two Arts programmes (Journalism and the CRITICAL-rated Screenwriting, the portfolio's lowest score), giving a bleak faculty mean. But the Job Insights data illuminates **33 Arts degrees and 5,071 alumni** — the richest report set in the University. The faculty's real graduate story is far broader and more resilient than its two assessed programmes suggest.

## 2. DFVA SCORECARD — FACULTY MEAN

| # | Dimension | Mean /3 | Read |
|---|---|---|---|
| 1 | Automation Exposure | 0.5 | Faculty weak point |
| 2 | Systems Thinking | 1.5 | — |
| 3 | Technical Depth | 1.0 | — |
| 4 | Decision-Making | 2.0 | — |
| 5 | AI Literacy | 0.5 | — |
| 6 | Domain Depth | 2.5 | Faculty strength |
| 7 | Research Rigour | 1.0 | — |
| 8 | Human & Relational | 2.5 | — |
| 9 | Curriculum Currency | 1.0 | — |
| 10 | Outcome Evidence | 2.0 | — |
| B | Irreplaceability | 1.5 | — |

**TOTAL: 16 / 36** — HIGH RISK (faculty mean; programme range 12–20)

**Programmes assessed:**

| Programme | Score | Band |
|---|---|---|
| Master of Journalism | 20 | MODERATE RISK |
| Master of Screenwriting | 12 | HIGH RISK |

## 3. GRADUATE OUTCOMES — UoM JOB INSIGHTS

Real destinations of **5,071 alumni** across **33 programmes** (LiveAlumni, 2015–2025).

**Top employers:** Museums Victoria · National Gallery of Victoria · Australian Bureau of Statistics · Department of the Prime Minister and Cabinet · Australian Department of Foreign Affairs and Trade · National Gallery of Australia · Australian Centre for Contemporary Art · Asylum Seeker Resource Centre · Parliament of Australia · Monash University

**Entry roles (0–1 yr):** Research Assistant · Policy Officer · Content Writer · Curatorial Assistant · Research Officer · Copywriter · Marketing Coordinator

**Early-mid roles (1–2 yr):** Project Officer · Policy Analyst · Policy Officer · Policy Advisor · Content Manager · Research Officer

**Skills in use:** Research · Public Speaking · Project Management · Policy Analysis · Communication · Critical Thinking · Writing · Editing

**Largest samples:** Bachelor of Arts (Psychology) (n=859) · Bachelor of Arts (History) (n=524) · Bachelor of Arts (Criminology) (n=513) · Bachelor of Arts (Politics and International Studies) (n=339) · Bachelor of Arts (Philosophy) (n=215)

## 4. DESTINATION CONVERGENCE & EXPOSURE READ

Arts graduates converge on the **public sector and policy** (DFAT, Prime Minister & Cabinet, the ABS, Parliament), the **cultural sector** (NGV, Museums Victoria, ACCA), and media. Modal roles are Research Assistant, Policy Officer and Policy Analyst — analytical, judgement-led work. The highest-volume majors (Psychology n=859, History n=524, Criminology n=513, Politics n=339) are precisely the destination-rich programmes DFVA has not yet assessed.

## 5. OUTCOME-EVIDENCE RECLASSIFICATION

Programmes in this faculty whose **D10 Outcome Evidence** gains a documented basis to rise once the Job Insights destination data is folded in (exact match → D10=3; cognate → D10≥2). A re-review trigger, not an automatic recompute.

| Programme | Current | → Total | Band change |
|---|---|---|---|
| Master of Journalism | 20 | 21 | MODERATE RISK |

## 6. WHAT THIS MEANS

1. Extend DFVA assessment to the high-volume Arts majors (Psychology, History, Criminology, Politics) — the Job Insights data already provides their Outcome Evidence and market grounding.
2. Reposition the faculty narrative on the real evidence: Arts feeds durable analytical and policy roles, not the displacement story implied by Screenwriting alone.
3. Resolve Screenwriting separately (structural redesign, per the portfolio report) — it is an outlier, not the faculty signal.

## Provenance

Graduate-outcome data: UoM Job Insights Reports (Careers Online / LiveAlumni, graduates 2015–2025); samples are a floor (not all alumni), AI-extracted and Careers-curated. DFVA scores: faculty means over the 41-programme assessment (means aggregate heterogeneous programmes; see the per-programme reports for detail). Reclassification projections are illustrative and reproducible from \`scratch/jobinsights/dfva_jir_map.json\`.
`,
  },
  "dfva-faculty-business-economics": {
    title: "Faculty of Business and Economics \u2014 DFVA Briefing",
    institution: "University of Melbourne",
    markdown: `# Faculty of Business and Economics — DFVA Briefing

**University of Melbourne**  
**Coverage:** 6 DFVA-assessed programmes · 15 Job Insights reports · 10,307 alumni (2015–2025)  
**Generated:** 2026-06-21  
**Source:** UoM Job Insights Reports (LiveAlumni, 2015–2025) + the 41-programme DFVA assessment

## 1. FACULTY PROFILE

Business and Economics is the **most strategically exposed faculty** in the portfolio — the widest internal score spread and the highest concentration of HIGH RISK programmes. Paradoxically its strongest dimension is **Outcome Evidence** (the faculty already tracks destinations well) while its weakest is **Automation Exposure**: its graduates are trained for exactly the roles AI is compressing fastest, and the curriculum has not yet confronted that.

## 2. DFVA SCORECARD — FACULTY MEAN

| # | Dimension | Mean /3 | Read |
|---|---|---|---|
| 1 | Automation Exposure | 1.17 | Faculty weak point |
| 2 | Systems Thinking | 2.17 | — |
| 3 | Technical Depth | 2.0 | — |
| 4 | Decision-Making | 2.5 | — |
| 5 | AI Literacy | 2.0 | — |
| 6 | Domain Depth | 2.17 | — |
| 7 | Research Rigour | 1.5 | — |
| 8 | Human & Relational | 2.0 | — |
| 9 | Curriculum Currency | 2.17 | — |
| 10 | Outcome Evidence | 2.67 | Faculty strength |
| B | Irreplaceability | 2.0 | — |

**TOTAL: 22 / 36** — MODERATE RISK (faculty mean; programme range 18–30)

**Programmes assessed:**

| Programme | Score | Band |
|---|---|---|
| Master of Business Analytics | 30 | RESILIENT |
| Master of Business Administration | 25 | MODERATE RISK |
| Master of Applied Business Analytics | 22 | MODERATE RISK |
| Master of Advanced Social Enterprise | 20 | MODERATE RISK |
| Master of Business Admin (Marketing) | 19 | HIGH RISK |
| Master of Information Systems | 18 | HIGH RISK |

## 3. GRADUATE OUTCOMES — UoM JOB INSIGHTS

Real destinations of **10,307 alumni** across **15 programmes** (LiveAlumni, 2015–2025).

**Top employers:** Deloitte · PwC · KPMG · EY · Macquarie Group · ANZ · NAB · Commonwealth Bank · Accenture · Australian Taxation Office

**Entry roles (0–1 yr):** Business Analyst · Graduate Analyst · Graduate Accountant · Investment Analyst · Financial Analyst · Investment Banking Analyst · Marketing Coordinator

**Early-mid roles (1–2 yr):** Risk Analyst · Management Consultant · Strategy Analyst · Finance Manager · Project Manager · Business Development Manager

**Skills in use:** Teamwork · Leadership · Data Analysis · Problem Solving · Communication · Business Strategy · Project Management · Financial Analysis

**Largest samples:** Bachelor of Commerce (Finance) (n=3546) · Bachelor of Commerce (Accounting) (n=1693) · Bachelor of Commerce (Economics) (n=1549) · Bachelor of Commerce (Management) (n=928) · Bachelor of Commerce (Marketing) (n=921)

## 4. DESTINATION CONVERGENCE & EXPOSURE READ

Business and Economics is the origin of the **Big-Four consulting funnel**. Deloitte, PwC, KPMG and EY — plus the major banks (ANZ, NAB, Commonwealth, Macquarie) — are the dominant destinations, and the modal entry role is **Business Analyst**, alongside Graduate/Investment/Financial Analyst. This is the AI-substitution-pressure zone: junior analyst work (data analysis, reporting, research synthesis). The exposure is doubly signalled here — a low Automation-Exposure curriculum score AND a modal destination squarely in the exposed tier.

## 5. OUTCOME-EVIDENCE RECLASSIFICATION

Programmes in this faculty whose **D10 Outcome Evidence** gains a documented basis to rise once the Job Insights destination data is folded in (exact match → D10=3; cognate → D10≥2). A re-review trigger, not an automatic recompute.

| Programme | Current | → Total | Band change |
|---|---|---|---|
| Master of Information Systems | 18 | 20 | **HIGH RISK → MODERATE RISK** |

## 6. WHAT THIS MEANS

1. Master of Information Systems — the faculty's lowest-scoring programme — is liftable out of HIGH RISK on n=257 real alumni records (Outcome Evidence). Re-review its D10 with the Job Insights data first.
2. Treat the Big-Four funnel as a faculty-wide exposure signal: graduates entering junior-analyst roles need explicit AI-tool-direction and verification capability, not analyst execution skills AI now performs.
3. Act on the portfolio's faculty-wide review recommendation; the 14-point internal spread signals fragmentation, not a coherent modernisation strategy.

## Provenance

Graduate-outcome data: UoM Job Insights Reports (Careers Online / LiveAlumni, graduates 2015–2025); samples are a floor (not all alumni), AI-extracted and Careers-curated. DFVA scores: faculty means over the 41-programme assessment (means aggregate heterogeneous programmes; see the per-programme reports for detail). Reclassification projections are illustrative and reproducible from \`scratch/jobinsights/dfva_jir_map.json\`.
`,
  },
  "dfva-faculty-education": {
    title: "Faculty of Education \u2014 DFVA Briefing",
    institution: "University of Melbourne",
    markdown: `# Faculty of Education — DFVA Briefing

**University of Melbourne**  
**Coverage:** 3 DFVA-assessed programmes · 7 Job Insights reports · 1,123 alumni (2015–2025)  
**Generated:** 2026-06-21  
**Source:** UoM Job Insights Reports (LiveAlumni, 2015–2025) + the 41-programme DFVA assessment

## 1. FACULTY PROFILE

The Faculty of Education already leads the portfolio on **Outcome Evidence** (maximal — professional accreditation forces destination tracking) and Human & Relational capability, but is held back by low **Technical Depth** and **AI Literacy**. The fastest-growing adjacent roles (AI-specialised instructional design, EdTech) require capabilities the programmes do not yet build.

## 2. DFVA SCORECARD — FACULTY MEAN

| # | Dimension | Mean /3 | Read |
|---|---|---|---|
| 1 | Automation Exposure | 1.33 | — |
| 2 | Systems Thinking | 2.0 | — |
| 3 | Technical Depth | 1.0 | Faculty weak point |
| 4 | Decision-Making | 2.0 | — |
| 5 | AI Literacy | 1.0 | — |
| 6 | Domain Depth | 2.33 | — |
| 7 | Research Rigour | 1.67 | — |
| 8 | Human & Relational | 2.67 | — |
| 9 | Curriculum Currency | 2.0 | — |
| 10 | Outcome Evidence | 3.0 | Faculty strength |
| B | Irreplaceability | 1.33 | — |

**TOTAL: 20 / 36** — MODERATE RISK (faculty mean; programme range 18–24)

**Programmes assessed:**

| Programme | Score | Band |
|---|---|---|
| Master of Education | 24 | MODERATE RISK |
| Master of TESOL | 19 | HIGH RISK |
| Master of International Education (IB) | 18 | HIGH RISK |

## 3. GRADUATE OUTCOMES — UoM JOB INSIGHTS

Real destinations of **1,123 alumni** across **7 programmes** (LiveAlumni, 2015–2025).

**Top employers:** Department of Education · Victorian Curriculum and Assessment Authority · Monash University · Victoria University · Wesley College · Deakin University · RMIT University · NSW Department of Education · Victorian Academy of Teaching and Leadership · Teach For Australia

**Entry roles (0–1 yr):** Research Assistant · Secondary School Teacher · Primary School Teacher · Classroom Teacher · Education Officer · Instructional Designer · Learning Designer

**Early-mid roles (1–2 yr):** Educational Consultant · Learning Specialist · Research Officer · Education Manager · Evaluation Consultant · Monitoring And Evaluation Specialist

**Skills in use:** Curriculum Development · Curriculum Design · Research · Teaching · Classroom Management · Teamwork · Communication · Qualitative Research

**Largest samples:** Master of Education (n=611) · Master of Teaching (Secondary) (n=242) · Master of Evaluation (n=86) · Master of Instructional Leadership (n=64) · Master of Teaching (Primary) (n=49)

## 4. DESTINATION CONVERGENCE & EXPOSURE READ

Graduates flow to the Department of Education, the school systems, and universities, as classroom teachers, instructional designers, education officers and evaluators. These are relational, judgement-led roles with low automation exposure — but the EdTech and AI-assessment-design edge is where demand is moving and the curriculum lags.

## 5. OUTCOME-EVIDENCE RECLASSIFICATION

_No outcome-evidence reclassification candidates in this faculty's assessed programmes (either no exact Job Insights match, or D10 already maximal)._

## 6. WHAT THIS MEANS

1. Build AI-in-education literacy and assessment-redesign capability — the faculty's twin weak points, and now a live employer requirement as AI reshapes academic integrity.
2. Add technical/instructional-design depth to capture the growing AI-specialised instructional-design role category.
3. The faculty's strong Outcome Evidence is a model for the rest of the portfolio — its destination tracking is what Recommendation 3 asks every faculty to build.

## Provenance

Graduate-outcome data: UoM Job Insights Reports (Careers Online / LiveAlumni, graduates 2015–2025); samples are a floor (not all alumni), AI-extracted and Careers-curated. DFVA scores: faculty means over the 41-programme assessment (means aggregate heterogeneous programmes; see the per-programme reports for detail). Reclassification projections are illustrative and reproducible from \`scratch/jobinsights/dfva_jir_map.json\`.
`,
  },
  "dfva-faculty-engineering-it": {
    title: "Faculty of Engineering and Information Technology \u2014 DFVA Briefing",
    institution: "University of Melbourne",
    markdown: `# Faculty of Engineering and Information Technology — DFVA Briefing

**University of Melbourne**  
**Coverage:** 3 DFVA-assessed programmes · 12 Job Insights reports · 1,007 alumni (2015–2025)  
**Generated:** 2026-06-21  
**Source:** UoM Job Insights Reports (LiveAlumni, 2015–2025) + the 41-programme DFVA assessment

## 1. FACULTY PROFILE

Engineering and IT has the strongest **Technical Depth** in the portfolio (maximal across the faculty) and good AI Literacy, but its weak point is **Automation Exposure** — its graduates build the systems that automate other work and must be positioned to direct rather than execute. This is the faculty of the portfolio's single clearest reclassification.

## 2. DFVA SCORECARD — FACULTY MEAN

| # | Dimension | Mean /3 | Read |
|---|---|---|---|
| 1 | Automation Exposure | 1.0 | Faculty weak point |
| 2 | Systems Thinking | 2.67 | — |
| 3 | Technical Depth | 3.0 | Faculty strength |
| 4 | Decision-Making | 2.33 | — |
| 5 | AI Literacy | 2.0 | — |
| 6 | Domain Depth | 3.0 | — |
| 7 | Research Rigour | 2.0 | — |
| 8 | Human & Relational | 1.33 | — |
| 9 | Curriculum Currency | 2.0 | — |
| 10 | Outcome Evidence | 2.33 | — |
| B | Irreplaceability | 2.33 | — |

**TOTAL: 24 / 36** — MODERATE RISK (faculty mean; programme range 22–27)

**Programmes assessed:**

| Programme | Score | Band |
|---|---|---|
| Master of Computer Science | 27 | MODERATE RISK |
| Master of Industrial Engineering | 23 | MODERATE RISK |
| Master of Engineering Structures (746st) | 22 | MODERATE RISK |

## 3. GRADUATE OUTCOMES — UoM JOB INSIGHTS

Real destinations of **1,007 alumni** across **12 programmes** (LiveAlumni, 2015–2025).

**Top employers:** Accenture · Deloitte · IBM · Canva · ANZ · Telstra · Beca · Jacobs · WSP in Australia · Aurecon

**Entry roles (0–1 yr):** Data Analyst · Graduate Engineer · Software Engineer · Graduate Software Engineer · Business Analyst · Graduate Project Engineer · Software Developer

**Early-mid roles (1–2 yr):** Research And Development Engineer · Systems Engineer · Project Engineer · Technology Consultant · Product Manager · Software Engineer

**Skills in use:** Project Management · Teamwork · Problem Solving · Matlab · Python · Stakeholder Management · Microsoft Excel · Machine Learning

**Largest samples:** Master of Information Technology (n=373) · Master of Information Systems (n=257) · Master of Engineering Management (n=89) · Master of Energy Systems (n=61) · Master of Civil Engineering (n=48)

## 4. DESTINATION CONVERGENCE & EXPOSURE READ

Destinations split between technology and quantitative employers (IBM, Canva, plus the consulting majors Accenture and Deloitte) and engineering firms (Beca, Jacobs). The junior-vs-senior bifurcation is the dominant dynamic: AI-assisted execution as a standalone junior task is compressing, while systems architecture, evaluation and direction are growing — exactly where the faculty's technical depth positions graduates.

## 5. OUTCOME-EVIDENCE RECLASSIFICATION

Programmes in this faculty whose **D10 Outcome Evidence** gains a documented basis to rise once the Job Insights destination data is folded in (exact match → D10=3; cognate → D10≥2). A re-review trigger, not an automatic recompute.

| Programme | Current | → Total | Band change |
|---|---|---|---|
| Master of Computer Science | 27 | 29 | **MODERATE RISK → RESILIENT** |

## 6. WHAT THIS MEANS

1. **Master of Computer Science crosses into RESILIENT (27→29) on outcome evidence alone** — its only weak dimension is Outcome Evidence, and the Job Insights data (n=41, real destinations including quantitative trading at Optiver/IMC/Akuna) supplies it. Re-review this first; it adds a third RESILIENT programme to the portfolio.
2. Frame curricula around directing and evaluating AI systems, not executing AI-augmented tasks (the automation-exposure weak point).
3. Publish destination data across the faculty to convert 'Curriculum Without Market' programmes to evidenced ones.

## Provenance

Graduate-outcome data: UoM Job Insights Reports (Careers Online / LiveAlumni, graduates 2015–2025); samples are a floor (not all alumni), AI-extracted and Careers-curated. DFVA scores: faculty means over the 41-programme assessment (means aggregate heterogeneous programmes; see the per-programme reports for detail). Reclassification projections are illustrative and reproducible from \`scratch/jobinsights/dfva_jir_map.json\`.
`,
  },
  "dfva-faculty-fine-arts-music": {
    title: "Faculty of Fine Arts and Music \u2014 DFVA Briefing",
    institution: "University of Melbourne",
    markdown: `# Faculty of Fine Arts and Music — DFVA Briefing

**University of Melbourne**  
**Coverage:** 2 Job Insights reports · 130 alumni (2015–2025)  
**Generated:** 2026-06-21  
**Source:** UoM Job Insights Reports (LiveAlumni, 2015–2025) + the 41-programme DFVA assessment

## 1. FACULTY PROFILE

Fine Arts and Music is the portfolio's **blind spot**: DFVA assesses none of its programmes, so the Portfolio Intelligence Report has no view of this faculty at all. The Job Insights data is the only evidence available here — two reports (Music Performance, Music Therapy) covering 130 alumni — and it shows a labour market that the employer-and-exposure model used elsewhere does not fit.

## 2. DFVA SCORECARD

_No DFVA-assessed programmes in this faculty. The graduate-outcome evidence below is the only DFVA-relevant data the University currently holds for it._

## 3. GRADUATE OUTCOMES — UoM JOB INSIGHTS

Real destinations of **130 alumni** across **2 programmes** (LiveAlumni, 2015–2025).

**Top employers:** Freelance / Self-employed · Melbourne Symphony Orchestra · Melbourne Youth Orchestras · Opera Scholars Australia · Melba Opera Trust · Australian National Academy of Music · Orchestra Victoria · West Australian Symphony Orchestra · Cantabile School of Music · Metro Music School

**Entry roles (0–1 yr):** Instrument Teacher · Freelance Musician · Voice Teacher · Music Administrator · Concert Program Administrator · Ensemble Administrator · Music Label Assistant

**Early-mid roles (1–2 yr):** Music Teacher · Musician · Ensemble Manager · Audio Engineer · Stage Manager · Expressive Therapist

**Skills in use:** Music Education · Teaching · Performing · Project Management · Public Speaking · Music Therapy · Individual Session Facilitation · Group Session Facilitation

**Largest samples:** Bachelor of Music (Performance) (n=87) · Master of Music Therapy (n=43)

## 4. DESTINATION CONVERGENCE & EXPOSURE READ

Graduates enter a **portfolio-career / freelance** market, not an employer pipeline: the top 'employer' is self-employment, followed by the orchestras and ensembles (Melbourne Symphony, Orchestra Victoria, ANAM) and teaching. Modal roles are Instrument Teacher, Freelance Musician and Music Administrator — a gig-and-teaching structure where automation exposure, employer concentration and salary progression all behave differently.

## 5. OUTCOME-EVIDENCE RECLASSIFICATION

_No outcome-evidence reclassification candidates in this faculty's assessed programmes (either no exact Job Insights match, or D10 already maximal)._

## 6. WHAT THIS MEANS

1. DFVA does not currently assess this faculty; any future assessment needs a viability lens suited to portfolio/freelance careers rather than employer-based exposure.
2. The Job Insights data is the only graduate-outcome evidence the University holds for these programmes — it should anchor any future review.
3. Music Therapy (an allied-health pathway) may warrant assessment under the Medicine/Health lens rather than the creative-arts one.

## Provenance

Graduate-outcome data: UoM Job Insights Reports (Careers Online / LiveAlumni, graduates 2015–2025); samples are a floor (not all alumni), AI-extracted and Careers-curated. DFVA scores: faculty means over the 41-programme assessment (means aggregate heterogeneous programmes; see the per-programme reports for detail). Reclassification projections are illustrative and reproducible from \`scratch/jobinsights/dfva_jir_map.json\`.
`,
  },
  "dfva-faculty-law": {
    title: "Melbourne Law School \u2014 DFVA Briefing",
    institution: "University of Melbourne",
    markdown: `# Melbourne Law School — DFVA Briefing

**University of Melbourne**  
**Coverage:** 1 DFVA-assessed programmes · 7 Job Insights reports · 2,236 alumni (2015–2025)  
**Generated:** 2026-06-21  
**Source:** UoM Job Insights Reports (LiveAlumni, 2015–2025) + the 41-programme DFVA assessment

## 1. FACULTY PROFILE

Melbourne Law School is DFVA-sparse but Job-Insights-rich: DFVA assesses one programme (Environmental Law) while the Job Insights data illuminates **seven, and 2,236 alumni**, led by the Juris Doctor (n=1,277) and Master of Laws (n=676). The assessed programme already scores maximally on Curriculum Currency and Outcome Evidence; the weak points are Automation Exposure and Research Rigour.

## 2. DFVA SCORECARD — FACULTY MEAN

| # | Dimension | Mean /3 | Read |
|---|---|---|---|
| 1 | Automation Exposure | 1.0 | Faculty weak point |
| 2 | Systems Thinking | 2.0 | — |
| 3 | Technical Depth | 1.0 | — |
| 4 | Decision-Making | 2.0 | — |
| 5 | AI Literacy | 2.0 | — |
| 6 | Domain Depth | 3.0 | Faculty strength |
| 7 | Research Rigour | 1.0 | — |
| 8 | Human & Relational | 2.0 | — |
| 9 | Curriculum Currency | 3.0 | — |
| 10 | Outcome Evidence | 3.0 | — |
| B | Irreplaceability | 2.0 | — |

**TOTAL: 22 / 36** — MODERATE RISK (faculty mean; programme range 22–22)

**Programmes assessed:**

| Programme | Score | Band |
|---|---|---|
| Master of Environmental Law | 22 | MODERATE RISK |

## 3. GRADUATE OUTCOMES — UoM JOB INSIGHTS

Real destinations of **2,236 alumni** across **7 programmes** (LiveAlumni, 2015–2025).

**Top employers:** King & Wood Mallesons · Herbert Smith Freehills · Corrs Chambers Westgarth · Ashurst · MinterEllison · Clayton Utz · Victorian Government Solicitor's Office · Victoria Legal Aid · Allens · Victorian Bar

**Entry roles (0–1 yr):** Paralegal · Law Clerk · Law Graduate · Legal Assistant · Seasonal Clerk · Graduate Lawyer · Research Assistant

**Early-mid roles (1–2 yr):** Legal Counsel · Legal Officer · Legal Analyst · Lawyer · Solicitor · Legal Advisor

**Skills in use:** Legal Research · Legal Writing · Negotiation · Dispute Resolution · Litigation · Problem Solving · Public Speaking · Teamwork

**Largest samples:** Juris Doctor (n=1277) · Master of Laws (n=676) · Master of Construction Law (n=88) · Master of Commercial Law (n=63) · Master of Tax (n=57)

## 4. DESTINATION CONVERGENCE & EXPOSURE READ

Destinations are the top-tier commercial firms (King & Wood Mallesons, Herbert Smith Freehills, Corrs, Ashurst, MinterEllison, Allens, Clayton Utz) and the government legal sector (Victorian Government Solicitor, Legal Aid). The arc — Paralegal / Law Clerk / Seasonal Clerk → Lawyer / Legal Counsel — runs through the junior-legal-research tier, which is exactly where AI document review and drafting tools are advancing.

## 5. OUTCOME-EVIDENCE RECLASSIFICATION

_No outcome-evidence reclassification candidates in this faculty's assessed programmes (either no exact Job Insights match, or D10 already maximal)._

## 6. WHAT THIS MEANS

1. Extend DFVA assessment to the Juris Doctor (the flagship, n=1,277) — the Job Insights data already supplies its destination and market evidence.
2. Address junior-legal-research automation exposure: graduates entering paralegal/clerk roles need AI legal-research governance and verification capability.
3. The faculty's strong AI Literacy on Environmental Law ('AI and Justice' elective) is a template for the wider School.

## Provenance

Graduate-outcome data: UoM Job Insights Reports (Careers Online / LiveAlumni, graduates 2015–2025); samples are a floor (not all alumni), AI-extracted and Careers-curated. DFVA scores: faculty means over the 41-programme assessment (means aggregate heterogeneous programmes; see the per-programme reports for detail). Reclassification projections are illustrative and reproducible from \`scratch/jobinsights/dfva_jir_map.json\`.
`,
  },
  "dfva-faculty-medicine-health": {
    title: "Faculty of Medicine, Dentistry and Health \u2014 DFVA Briefing",
    institution: "University of Melbourne",
    markdown: `# Faculty of Medicine, Dentistry and Health — DFVA Briefing

**University of Melbourne**  
**Coverage:** 8 DFVA-assessed programmes · 23 Job Insights reports · 3,665 alumni (2015–2025)  
**Generated:** 2026-06-21  
**Source:** UoM Job Insights Reports (LiveAlumni, 2015–2025) + the 41-programme DFVA assessment

## 1. FACULTY PROFILE

Medicine, Dentistry and Health is the **highest-scoring and most consistent faculty**, anchored by a genuine physical-and-relational moat (maximal Domain Depth, Human & Relational, and Irreplaceability). Its one systemic weakness is the portfolio's lowest **AI Literacy** — a clinical-AI paradox: hands-on clinical work cannot be automated, yet AI diagnostic tools are entering routine practice and graduates have little framework to govern, evaluate or contextualise them. The risk here is reputational and regulatory, not displacement.

## 2. DFVA SCORECARD — FACULTY MEAN

| # | Dimension | Mean /3 | Read |
|---|---|---|---|
| 1 | Automation Exposure | 2.88 | — |
| 2 | Systems Thinking | 1.75 | — |
| 3 | Technical Depth | 2.0 | — |
| 4 | Decision-Making | 2.88 | — |
| 5 | AI Literacy | 0.88 | Faculty weak point |
| 6 | Domain Depth | 3.0 | Faculty strength |
| 7 | Research Rigour | 2.38 | — |
| 8 | Human & Relational | 2.88 | — |
| 9 | Curriculum Currency | 2.0 | — |
| 10 | Outcome Evidence | 2.5 | — |
| B | Irreplaceability | 3.0 | — |

**TOTAL: 26 / 36** — MODERATE RISK (faculty mean; programme range 25–28)

**Programmes assessed:**

| Programme | Score | Band |
|---|---|---|
| Master of Clinical Psychology (527cl) | 28 | RESILIENT |
| Master of Physiotherapy (Pelvic Health) | 27 | MODERATE RISK |
| Master of Professional Psychology | 27 | MODERATE RISK |
| Master of Genetic Counselling | 26 | MODERATE RISK |
| Master of Nursing Science | 26 | MODERATE RISK |
| Master of Biomedical Science | 25 | MODERATE RISK |
| Master of Clinical Dentistry | 25 | MODERATE RISK |
| Master of Surgical Education | 25 | MODERATE RISK |

## 3. GRADUATE OUTCOMES — UoM JOB INSIGHTS

Real destinations of **3,665 alumni** across **23 programmes** (LiveAlumni, 2015–2025).

**Top employers:** The Royal Melbourne Hospital · The Royal Children's Hospital · St Vincent's Hospital Melbourne · Alfred Health · Austin Health · Peter MacCallum Cancer Centre · Monash Health · Western Health · Walter and Eliza Hall Institute of Medical Research · Barwon Health

**Entry roles (0–1 yr):** Research Assistant · Laboratory Technician · Clinical Data Officer · Clinical Research Assistant · Clinical Trial Assistant · Laboratory Assistant · Allied Health Assistant

**Early-mid roles (1–2 yr):** Physiotherapist · Public Health Officer · Medical Science Liaison · Clinical Research Coordinator · Academic Tutor · Biomedical Engineer

**Skills in use:** Research · Public Speaking · Data Analysis · Clinical Research · Teamwork · Leadership · Customer Service · Project Management

**Largest samples:** Doctor of Medicine (n=762) · Master of Public Health (n=562) · Doctor of Physiotherapy (n=448) · Master of Social Work (n=203) · Doctor of Optometry (n=199)

## 4. DESTINATION CONVERGENCE & EXPOSURE READ

Destinations are the Victorian teaching-hospital network (Royal Melbourne, Royal Children's, St Vincent's, Alfred, Austin, Monash Health) and the medical research institutes (WEHI, Peter Mac), with a clinical + research-assistant role mix. Automation exposure is low across the board — these are physical, relational, accountable roles — which the real destinations confirm.

## 5. OUTCOME-EVIDENCE RECLASSIFICATION

Programmes in this faculty whose **D10 Outcome Evidence** gains a documented basis to rise once the Job Insights destination data is folded in (exact match → D10=3; cognate → D10≥2). A re-review trigger, not an automatic recompute.

| Programme | Current | → Total | Band change |
|---|---|---|---|
| Master of Genetic Counselling | 26 | 27 | MODERATE RISK |
| Master of Nursing Science | 26 | 27 | MODERATE RISK |
| Master of Biomedical Science | 25 | 26 | MODERATE RISK |

## 6. WHAT THIS MEANS

1. Address the clinical-AI-governance gap (the faculty's D5 floor): graduates entering settings where Pearl AI / Denti.AI and clinical decision support are already deployed need to evaluate and oversee these tools.
2. Three programmes (Genetic Counselling, Nursing Science, Biomedical Science) gain a documented basis to lift Outcome Evidence from the Job Insights data.
3. Preserve and make explicit the physical/relational moat in programme positioning — it is the portfolio's strongest genuine AI defence.

## Provenance

Graduate-outcome data: UoM Job Insights Reports (Careers Online / LiveAlumni, graduates 2015–2025); samples are a floor (not all alumni), AI-extracted and Careers-curated. DFVA scores: faculty means over the 41-programme assessment (means aggregate heterogeneous programmes; see the per-programme reports for detail). Reclassification projections are illustrative and reproducible from \`scratch/jobinsights/dfva_jir_map.json\`.
`,
  },
  "dfva-faculty-science": {
    title: "Faculty of Science \u2014 DFVA Briefing",
    institution: "University of Melbourne",
    markdown: `# Faculty of Science — DFVA Briefing

**University of Melbourne**  
**Coverage:** 14 DFVA-assessed programmes · 31 Job Insights reports · 4,762 alumni (2015–2025)  
**Generated:** 2026-06-21  
**Source:** UoM Job Insights Reports (LiveAlumni, 2015–2025) + the 41-programme DFVA assessment

## 1. FACULTY PROFILE

The Faculty of Science is the portfolio's largest and most internally consistent cohort — deep disciplinary expertise (Domain Depth is maximal across the faculty) and strong decision-making, but a uniform floor on the two dimensions AI most pressures: **AI Literacy** and **Outcome Evidence**. Thirteen of its Master of Science specialisations score the identical low band on graduate-outcome evidence — not a disciplinary artefact but a faculty governance norm in which employment outcomes are treated as downstream of disciplinary mastery rather than designed in. The Job Insights data shows that norm is now the fixable part.

## 2. DFVA SCORECARD — FACULTY MEAN

| # | Dimension | Mean /3 | Read |
|---|---|---|---|
| 1 | Automation Exposure | 2.07 | — |
| 2 | Systems Thinking | 2.14 | — |
| 3 | Technical Depth | 2.71 | — |
| 4 | Decision-Making | 2.5 | — |
| 5 | AI Literacy | 1.07 | Faculty weak point |
| 6 | Domain Depth | 3.0 | Faculty strength |
| 7 | Research Rigour | 2.43 | — |
| 8 | Human & Relational | 1.93 | — |
| 9 | Curriculum Currency | 2.14 | — |
| 10 | Outcome Evidence | 1.14 | — |
| B | Irreplaceability | 2.29 | — |

**TOTAL: 23 / 36** — MODERATE RISK (faculty mean; programme range 20–26)

**Programmes assessed:**

| Programme | Score | Band |
|---|---|---|
| Master of Climate Science | 26 | MODERATE RISK |
| Master of Science (BioSciences) | 25 | MODERATE RISK |
| Master of Science (Chemistry) | 25 | MODERATE RISK |
| Master of Science (Physics) | 25 | MODERATE RISK |
| Master of Data Science | 24 | MODERATE RISK |
| Master of Science (Bioinformatics) | 24 | MODERATE RISK |
| Master of Science (Biotechnology) | 24 | MODERATE RISK |
| Master of Science (Earth Sciences) | 24 | MODERATE RISK |
| Bachelor of Science | 23 | MODERATE RISK |
| Master of Environmental Science | 23 | MODERATE RISK |
| Master of Science (Epidemiology) | 23 | MODERATE RISK |
| Master of Food Science (439fs) | 21 | MODERATE RISK |
| Master of Urban Horticulture | 21 | MODERATE RISK |
| Master of Actuarial Science | 20 | MODERATE RISK |

## 3. GRADUATE OUTCOMES — UoM JOB INSIGHTS

Real destinations of **4,762 alumni** across **31 programmes** (LiveAlumni, 2015–2025).

**Top employers:** CSIRO · Walter and Eliza Hall Institute of Medical Research · Peter MacCallum Cancer Centre · Monash University · Murdoch Children's Research Institute · The Florey Institute of Neuroscience and Mental Health · Alfred Health · The Peter Doherty Institute for Infection and Immunity · CSL · Monash Health

**Entry roles (0–1 yr):** Research Assistant · Laboratory Technician · Data Analyst · Laboratory Assistant · Graduate Environmental Scientist · Veterinary Assistant · Clinical Trial Assistant

**Early-mid roles (1–2 yr):** Research Officer · Environmental Scientist · Environmental Officer · Research Scientist · Machine Learning Engineer · Business Analyst

**Skills in use:** Research · Data Analysis · Teamwork · Project Management · Time Management · Laboratory Skills · Public Speaking · Problem Solving

**Largest samples:** Bachelor of Science (Physiology) (n=439) · Master of Environment (n=408) · Bachelor of Science (Neuroscience) (n=373) · Bachelor of Science (Psychology) (n=351) · Bachelor of Science (Computing And Software Systems) (n=328)

## 4. DESTINATION CONVERGENCE & EXPOSURE READ

Science is the **research-retention pole** of the University's destination structure. Its graduates' top employers are research institutes and teaching hospitals — CSIRO, WEHI, Peter MacCallum, the Florey, the Doherty — and the modal entry role across the faculty is **Research Assistant / Laboratory Technician**. This is the academic and research-staff on-ramp: the **least automatable** destination (irreducible research work), but also the most precarious and PhD-dependent. Automation exposure is genuinely low; the strategic risk is career-pathway fragility, not displacement.

## 5. OUTCOME-EVIDENCE RECLASSIFICATION

Programmes in this faculty whose **D10 Outcome Evidence** gains a documented basis to rise once the Job Insights destination data is folded in (exact match → D10=3; cognate → D10≥2). A re-review trigger, not an automatic recompute.

| Programme | Current | → Total | Band change |
|---|---|---|---|
| Master of Data Science | 24 | 26 | MODERATE RISK |
| Master of Environmental Science | 23 | 25 | MODERATE RISK |
| Master of Food Science (439fs) | 21 | 23 | MODERATE RISK |

## 6. WHAT THIS MEANS

1. Publish the existing Job Insights destination data on Science programme pages — it is the role-title outcome evidence D10 measures, and it already exists. This alone lifts Master of Data Science, Master of Environmental Science and Master of Food Science toward the RESILIENT threshold.
2. Build one shared cross-Science AI-literacy module (the faculty's uniform weak point) rather than 13 separate redesigns — the single highest-leverage move for the largest faculty.
3. Track research-vs-industry destination split, since 'Research Assistant' straddles the exposure line (launchpad to Research Scientist, or holding pattern).

## Provenance

Graduate-outcome data: UoM Job Insights Reports (Careers Online / LiveAlumni, graduates 2015–2025); samples are a floor (not all alumni), AI-extracted and Careers-curated. DFVA scores: faculty means over the 41-programme assessment (means aggregate heterogeneous programmes; see the per-programme reports for detail). Reclassification projections are illustrative and reproducible from \`scratch/jobinsights/dfva_jir_map.json\`.
`,
  }
};
