/** Bump on every PROGRAMS change to invalidate stale client caches. */
export const CACHE_VERSION = 4;

export interface DimensionScore {
  label: string;
  score: number | null; // null = Not Applicable (construct doesn't exist for this program)
  max: number;
}

export interface ProgramReport {
  program: string;
  institution: string;
  level: string;
  date: string;
  score: number;
  maxScore: number;
  riskBand:
    | "RESILIENT"
    | "MODERATE RISK"
    | "HIGH RISK"
    | "CRITICAL"
    | "NOT RATABLE";
  thresholds: {
    q1: "YES" | "NO" | "UNCERTAIN";
    q2: "YES" | "NO" | "UNCERTAIN";
    q3: "YES" | "NO" | "UNCERTAIN";
  };
  dimensions: DimensionScore[];
  assessmentSlug: string;
  marketSlug: string;
  recommendSlug?: string;
  handbookUrl?: string;
}

export const PROGRAMS: ProgramReport[] = [
  {
    program: "Bachelor of Design",
    institution: "University of Melbourne",
    level: "Bachelor · 3 years",
    date: "2026-04-21",
    score: 18,
    maxScore: 36,
    riskBand: "HIGH RISK",
    thresholds: { q1: "YES", q2: "UNCERTAIN", q3: "NO" },
    dimensions: [
      { label: "Automation Exposure", score: 1, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 2, max: 3 },
      { label: "Research Rigour", score: 1, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 2, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-b-des",
    marketSlug: "dfva-market-b-des",
    recommendSlug: "dfva-recommend-b-des",
    handbookUrl: "https://handbook.unimelb.edu.au/2025/courses/b-des",
  },
  {
    program: "Master of Information Systems",
    institution: "University of Melbourne",
    level: "Master · 1.5–2 years",
    date: "2026-05-07",
    score: 20,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "YES", q2: "UNCERTAIN", q3: "NO" },
    dimensions: [
      { label: "Automation Exposure", score: 1, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 2, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 1, max: 3 },
    ],
    assessmentSlug: "dfva-mc-is",
    marketSlug: "dfva-market-mc-is",
    recommendSlug: "dfva-recommend-mc-is",
    handbookUrl: "https://handbook.unimelb.edu.au/2025/courses/mc-is",
  },
  {
    program: "Bachelor of Science",
    institution: "University of Melbourne",
    level: "Bachelor · 3 years",
    date: "2026-05-13",
    score: 23,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "UNCERTAIN", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 1, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 2, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-b-sci",
    marketSlug: "dfva-market-b-sci",
    recommendSlug: "dfva-recommend-b-sci",
    handbookUrl: "https://handbook.unimelb.edu.au/2025/courses/b-sci",
  },
  {
    program: "Master of Biotechnology",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-05-13",
    score: 24,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-scibit",
    marketSlug: "dfva-market-mc-scibit",
    recommendSlug: "dfva-recommend-mc-scibit",
    handbookUrl: "https://handbook.unimelb.edu.au/2025/courses/mc-scibit",
  },
  {
    program: "Master of Science (Earth Sciences)",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-05-15",
    score: 24,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 1, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-mc-sciear",
    marketSlug: "dfva-market-mc-sciear",
    recommendSlug: "dfva-recommend-mc-sciear",
    handbookUrl: "https://handbook.unimelb.edu.au/2025/courses/mc-sciear",
  },
  {
    program: "Master of Science (Epidemiology)",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-05-15",
    score: 23,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "UNCERTAIN", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-mc-sciepi",
    marketSlug: "dfva-market-mc-sciepi",
    recommendSlug: "dfva-recommend-mc-sciepi",
    handbookUrl: "https://handbook.unimelb.edu.au/2025/courses/mc-sciepi",
  },
  {
    program: "Master of Computer Science",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-08",
    score: 29,
    maxScore: 36,
    riskBand: "RESILIENT",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 3, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-cs",
    recommendSlug: "dfva-recommend-mc-cs",
    marketSlug: "dfva-market-mc-cs",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-cs",
  },
  {
    program: "Master of Data Science",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-08",
    score: 26,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "UNCERTAIN", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 2, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 3, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-mc-datasc",
    recommendSlug: "dfva-recommend-mc-datasc",
    marketSlug: "dfva-market-mc-datasc",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-datasc",
  },
  {
    program: "Master of Science (Bioinformatics)",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-08",
    score: 24,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-scibif",
    recommendSlug: "dfva-recommend-mc-scibif",
    marketSlug: "dfva-market-mc-scibif",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-scibif",
  },
  {
    program: "Master of Actuarial Science",
    institution: "University of Melbourne",
    level: "Master · 1.5 years",
    date: "2026-06-08",
    score: 20,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "YES", q2: "UNCERTAIN", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 1, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 1, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-mc-actsc",
    recommendSlug: "dfva-recommend-mc-actsc",
    marketSlug: "dfva-market-mc-actsc",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-actsc",
  },
  {
    program: "Master of Biomedical Science",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-08",
    score: 26,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 2, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-bmedsc",
    recommendSlug: "dfva-recommend-mc-bmedsc",
    marketSlug: "dfva-market-mc-bmedsc",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-bmedsc",
  },
  {
    program: "Master of Science (Physics)",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-08",
    score: 25,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-sciphy",
    recommendSlug: "dfva-recommend-mc-sciphy",
    marketSlug: "dfva-market-mc-sciphy",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-sciphy",
  },
  {
    program: "Master of Science (BioSciences)",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-08",
    score: 25,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-scibio",
    recommendSlug: "dfva-recommend-mc-scibio",
    marketSlug: "dfva-market-mc-scibio",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-scibio",
  },
  {
    program: "Master of Science (Chemistry)",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-08",
    score: 25,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-sciche",
    recommendSlug: "dfva-recommend-mc-sciche",
    marketSlug: "dfva-market-mc-sciche",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-sciche",
  },
  {
    program: "Master of Environmental Science",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-08",
    score: 25,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "UNCERTAIN", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-mc-envsc",
    recommendSlug: "dfva-recommend-mc-envsc",
    marketSlug: "dfva-market-mc-envsc",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-envsc",
  },
  {
    program: "Master of Climate Science",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-08",
    score: 26,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 3, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-climsci",
    recommendSlug: "dfva-recommend-mc-climsci",
    marketSlug: "dfva-market-mc-climsci",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-climsci",
  },
  {
    program: "Master of Food Science",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-08",
    score: 23,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "UNCERTAIN", q2: "UNCERTAIN", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-439fs",
    recommendSlug: "dfva-recommend-439fs",
    marketSlug: "dfva-market-439fs",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/439fs",
  },
  {
    program: "Master of Genetic Counselling",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-08",
    score: 27,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-gencoun",
    recommendSlug: "dfva-recommend-mc-gencoun",
    marketSlug: "dfva-market-mc-gencoun",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-gencoun",
  },
  {
    program: "Master of Nursing Science",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-08",
    score: 27,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-nursc",
    recommendSlug: "dfva-recommend-mc-nursc",
    marketSlug: "dfva-market-mc-nursc",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-nursc",
  },
  {
    program: "Master of Clinical Psychology",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-09",
    score: 28,
    maxScore: 36,
    riskBand: "RESILIENT",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-527cl",
    recommendSlug: "dfva-recommend-527cl",
    marketSlug: "dfva-market-527cl",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/527cl",
  },
  {
    program: "Master of Engineering Structures",
    institution: "University of Melbourne",
    level: "Master · 1 year",
    date: "2026-06-09",
    score: 22,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "YES", q2: "UNCERTAIN", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 1, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 1, max: 3 },
      { label: "Human & Relational", score: 1, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-746st",
    recommendSlug: "dfva-recommend-746st",
    marketSlug: "dfva-market-746st",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/746st",
  },
  {
    program: "Master of Applied Business Analytics",
    institution: "University of Melbourne",
    level: "Master · 1.5 years",
    date: "2026-06-09",
    score: 22,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "YES", q2: "UNCERTAIN", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 1, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 3, max: 3 },
      { label: "Domain Depth", score: 2, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 1, max: 3 },
      { label: "Curriculum Currency", score: 1, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-mc-apbusa",
    recommendSlug: "dfva-recommend-mc-apbusa",
    marketSlug: "dfva-market-mc-apbusa",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-apbusa",
  },
  {
    program: "Master of Architecture",
    institution: "University of Melbourne",
    level: "Master · 3 years",
    date: "2026-06-09",
    score: 29,
    maxScore: 36,
    riskBand: "RESILIENT",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-arch",
    recommendSlug: "dfva-recommend-mc-arch",
    marketSlug: "dfva-market-mc-arch",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-arch",
  },
  {
    program: "Master of Business Administration",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-09",
    score: 25,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "YES", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 1, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 3, max: 3 },
      { label: "Domain Depth", score: 2, max: 3 },
      { label: "Research Rigour", score: 1, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 3, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-ba",
    recommendSlug: "dfva-recommend-mc-ba",
    marketSlug: "dfva-market-mc-ba",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-ba",
  },
  {
    program: "Master of Business Administration (Marketing)",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-09",
    score: 19,
    maxScore: 36,
    riskBand: "HIGH RISK",
    thresholds: { q1: "UNCERTAIN", q2: "UNCERTAIN", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 1, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 2, max: 3 },
      { label: "Research Rigour", score: 1, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-mc-bamktg",
    recommendSlug: "dfva-recommend-mc-bamktg",
    marketSlug: "dfva-market-mc-bamktg",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-bamktg",
  },
  {
    program: "Master of Advanced Social Enterprise",
    institution: "University of Melbourne",
    level: "Master · 1.5 years",
    date: "2026-06-09",
    score: 20,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "YES", q2: "UNCERTAIN", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 1, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 2, max: 3 },
      { label: "Research Rigour", score: 1, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 1, max: 3 },
    ],
    assessmentSlug: "dfva-mc-base",
    recommendSlug: "dfva-recommend-mc-base",
    marketSlug: "dfva-market-mc-base",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-base",
  },
  {
    program: "Master of Business Analytics",
    institution: "University of Melbourne",
    level: "Master · 1 year",
    date: "2026-06-09",
    score: 30,
    maxScore: 36,
    riskBand: "RESILIENT",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 3, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 3, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-busana",
    recommendSlug: "dfva-recommend-mc-busana",
    marketSlug: "dfva-market-mc-busana",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-busana",
  },
  {
    program: "Master of Clinical Dentistry",
    institution: "University of Melbourne",
    level: "Master · 3 years",
    date: "2026-06-09",
    score: 25,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 1, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 0, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-clind",
    recommendSlug: "dfva-recommend-mc-clind",
    marketSlug: "dfva-market-mc-clind",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-clind",
  },
  {
    program: "Master of Education",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-09",
    score: 24,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-ed",
    recommendSlug: "dfva-recommend-mc-ed",
    marketSlug: "dfva-market-mc-ed",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-ed",
  },
  {
    program: "Master of Environmental Law",
    institution: "University of Melbourne",
    level: "Master · 1 year",
    date: "2026-06-09",
    score: 22,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "YES", q2: "UNCERTAIN", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 1, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 2, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 1, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 3, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-mc-envlaw",
    recommendSlug: "dfva-recommend-mc-envlaw",
    marketSlug: "dfva-market-mc-envlaw",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-envlaw",
  },
  {
    program: "Master of Industrial Engineering",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-09",
    score: 23,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "UNCERTAIN", q2: "UNCERTAIN", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 0, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 2, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 1, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-mc-indeng",
    recommendSlug: "dfva-recommend-mc-indeng",
    marketSlug: "dfva-market-mc-indeng",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-indeng",
  },
  {
    program: "Master of International Education (IB)",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-09",
    score: 18,
    maxScore: 36,
    riskBand: "HIGH RISK",
    thresholds: { q1: "UNCERTAIN", q2: "UNCERTAIN", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 1, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 2, max: 3 },
      { label: "Research Rigour", score: 1, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 1, max: 3 },
    ],
    assessmentSlug: "dfva-mc-intedib",
    recommendSlug: "dfva-recommend-mc-intedib",
    marketSlug: "dfva-market-mc-intedib",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-intedib",
  },
  {
    program: "Master of Journalism",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-09",
    score: 21,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "YES", q2: "UNCERTAIN", q3: "NO" },
    dimensions: [
      { label: "Automation Exposure", score: 1, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 1, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-mc-journ",
    recommendSlug: "dfva-recommend-mc-journ",
    marketSlug: "dfva-market-mc-journ",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-journ",
  },
  {
    program: "Master of Physiotherapy (Pelvic Health)",
    institution: "University of Melbourne",
    level: "Master · 1 year",
    date: "2026-06-09",
    score: 27,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 1, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-phtyph",
    recommendSlug: "dfva-recommend-mc-phtyph",
    marketSlug: "dfva-market-mc-phtyph",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-phtyph",
  },
  {
    program: "Master of Property",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-09",
    score: 23,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-mc-prop",
    recommendSlug: "dfva-recommend-mc-prop",
    marketSlug: "dfva-market-mc-prop",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-prop",
  },
  {
    program: "Master of Professional Psychology",
    institution: "University of Melbourne",
    level: "Master · 1 year",
    date: "2026-06-09",
    score: 27,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-propsyc",
    recommendSlug: "dfva-recommend-mc-propsyc",
    marketSlug: "dfva-market-mc-propsyc",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-propsyc",
  },
  {
    program: "Master of Screenwriting",
    institution: "University of Melbourne",
    level: "Master · 1.5 years",
    date: "2026-06-09",
    score: 12,
    maxScore: 36,
    riskBand: "HIGH RISK",
    thresholds: { q1: "YES", q2: "UNCERTAIN", q3: "NO" },
    dimensions: [
      { label: "Automation Exposure", score: 0, max: 3 },
      { label: "Systems Thinking", score: 1, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 0, max: 3 },
      { label: "Domain Depth", score: 2, max: 3 },
      { label: "Research Rigour", score: 0, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 1, max: 3 },
      { label: "Outcome Evidence", score: 2, max: 3 },
      { label: "Irreplaceability (bonus)", score: 1, max: 3 },
    ],
    assessmentSlug: "dfva-mc-scwr",
    recommendSlug: "dfva-recommend-mc-scwr",
    marketSlug: "dfva-market-mc-scwr",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-scwr",
  },
  {
    program: "Master of Surgical Education",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-09",
    score: 25,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-surged",
    recommendSlug: "dfva-recommend-mc-surged",
    marketSlug: "dfva-market-mc-surged",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-surged",
  },
  {
    // FIXME(dfva-data): only 10 of 11 dimensions recorded, and stored score 23 is impossible —
    // the 10 present dimensions sum to 19, so even a max (3) 11th dimension caps the total at 22.
    // Needs reassessment; total must equal sum of all 11 dimensions (dfva/source/rubric.ts → totalScore).
    program: "Master of TESOL",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-09",
    score: 23,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "YES", q2: "UNCERTAIN", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 1, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 2, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-tesol",
    recommendSlug: "dfva-recommend-mc-tesol",
    marketSlug: "dfva-market-mc-tesol",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-tesol",
  },
  {
    program: "Master of Urban Design",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-09",
    score: 25,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 0, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 2, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-urbdes",
    recommendSlug: "dfva-recommend-mc-urbdes",
    marketSlug: "dfva-market-mc-urbdes",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-urbdes",
  },
  {
    // FIXME(dfva-data): only 10 of 11 dimensions recorded, and stored score 25 is impossible —
    // the 10 present dimensions sum to 21, so even a max (3) 11th dimension caps the total at 24.
    // Needs reassessment; total must equal sum of all 11 dimensions (dfva/source/rubric.ts → totalScore).
    program: "Master of Urban Horticulture",
    institution: "University of Melbourne",
    level: "Master · 2 years",
    date: "2026-06-09",
    score: 25,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-mc-urbhort",
    recommendSlug: "dfva-recommend-mc-urbhort",
    marketSlug: "dfva-market-mc-urbhort",

    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-urbhort",
  },
  {
    program: "Juris Doctor",
    institution: "University of Melbourne",
    level: "Master (Extended) · 3 years",
    date: "2026-07-08",
    score: 24,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "YES", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 2, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 3, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-mc-jurisd",
    marketSlug: "dfva-market-mc-jurisd",
    recommendSlug: "dfva-recommend-mc-jurisd",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-jurisd",
  },
  {
    program: "Doctor of Philosophy - Engineering and IT",
    institution: "University of Melbourne",
    level: "Graduate Research, AQF Level 10",
    date: "2026-07-02",
    score: 25,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 1, max: 3 },
      { label: "Curriculum Currency", score: 1, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-dr-phileit",
    marketSlug: "dfva-market-dr-phileit",
    recommendSlug: "dfva-recommend-dr-phileit",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/dr-phileit",
  },
  {
    program: "Doctor of Philosophy - Business and Economics",
    institution: "University of Melbourne",
    level: "Graduate Research, AQF level 10",
    date: "2026-07-02",
    score: 22,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 1, max: 3 },
      { label: "Curriculum Currency", score: 1, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-dr-philbe",
    marketSlug: "dfva-market-dr-philbe",
    recommendSlug: "dfva-recommend-dr-philbe",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/dr-philbe",
  },
  {
    program: "Doctor of Philosophy - Arts",
    institution: "University of Melbourne",
    level: "Graduate Research, AQF level 10",
    date: "2026-07-02",
    score: 21,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 0, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 1, max: 3 },
      { label: "Outcome Evidence", score: 0, max: 3 },
      { label: "Irreplaceability (bonus)", score: 2, max: 3 },
    ],
    assessmentSlug: "dfva-dr-philart",
    marketSlug: "dfva-market-dr-philart",
    recommendSlug: "dfva-recommend-dr-philart",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/dr-philart",
  },
  {
    program: "Doctor of Philosophy - Science",
    institution: "University of Melbourne",
    level: "Graduate Research, AQF Level 10",
    date: "2026-07-02",
    score: 24,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 1, max: 3 },
      { label: "Curriculum Currency", score: 1, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-dr-philsci",
    marketSlug: "dfva-market-dr-philsci",
    recommendSlug: "dfva-recommend-dr-philsci",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/dr-philsci",
  },
  {
    program: "Doctor of Philosophy - Agricultural Sciences",
    institution: "University of Melbourne",
    level: "Graduate Research, AQF Level 10",
    date: "2026-07-02",
    score: 26,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 1, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-dr-philagr",
    marketSlug: "dfva-market-dr-philagr",
    recommendSlug: "dfva-recommend-dr-philagr",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/dr-philagr",
  },
  {
    program: "Doctor of Philosophy - Architecture, Building and Planning",
    institution: "University of Melbourne",
    level: "Graduate Research, AQF Level 10",
    date: "2026-07-02",
    score: 25,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 1, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-dr-philabp",
    marketSlug: "dfva-market-dr-philabp",
    recommendSlug: "dfva-recommend-dr-philabp",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/dr-philabp",
  },
  {
    program: "Doctor of Philosophy - Medicine, Dentistry and Health Sciences",
    institution: "University of Melbourne",
    level: "Graduate Research, AQF Level 10",
    date: "2026-07-02",
    score: 27,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-dr-philmdh",
    marketSlug: "dfva-market-dr-philmdh",
    recommendSlug: "dfva-recommend-dr-philmdh",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/dr-philmdh",
  },
  {
    program: "Doctor of Philosophy - Education",
    institution: "University of Melbourne",
    level: "Graduate Research, AQF Level 10",
    date: "2026-07-02",
    score: 15,
    maxScore: 36,
    riskBand: "HIGH RISK",
    thresholds: { q1: "UNCERTAIN", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 0, max: 3 },
      { label: "Domain Depth", score: 2, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 0, max: 3 },
      { label: "Outcome Evidence", score: 0, max: 3 },
      { label: "Irreplaceability (bonus)", score: 1, max: 3 },
    ],
    assessmentSlug: "dfva-dr-philedu",
    marketSlug: "dfva-market-dr-philedu",
    recommendSlug: "dfva-recommend-dr-philedu",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/dr-philedu",
  },
  {
    program: "Doctor of Philosophy - Fine Arts and Music",
    institution: "University of Melbourne",
    level: "Graduate Research, AQF level 10",
    date: "2026-07-02",
    score: 23,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 0, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 1, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-dr-philfam",
    marketSlug: "dfva-market-dr-philfam",
    recommendSlug: "dfva-recommend-dr-philfam",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/dr-philfam",
  },
  {
    program:
      "Master of Psychology (Educational and Developmental)/Doctor of Philosophy",
    institution: "University of Melbourne",
    level: "Graduate Research (combined Masters+PhD), AQF level 10",
    date: "2026-07-02",
    score: 32,
    maxScore: 36,
    riskBand: "RESILIENT",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 2, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-dr-philedp",
    marketSlug: "dfva-market-dr-philedp",
    recommendSlug: "dfva-recommend-dr-philedp",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/dr-philedp",
  },
  {
    program:
      "Master of Psychology (Clinical Neuropsychology)/Doctor of Philosophy",
    institution: "University of Melbourne",
    level: "Graduate Research (combined Masters+PhD), AQF Level 10",
    date: "2026-07-02",
    score: 29,
    maxScore: 36,
    riskBand: "RESILIENT",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 2, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-080cn",
    marketSlug: "dfva-market-080cn",
    recommendSlug: "dfva-recommend-080cn",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/080cn",
  },
  {
    program: "Master of Psychology (Clinical Psychology)/Doctor of Philosophy",
    institution: "University of Melbourne",
    level: "Graduate Research (combined Masters+PhD), AQF level 10",
    date: "2026-07-02",
    score: 28,
    maxScore: 36,
    riskBand: "RESILIENT",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 2, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-080cl",
    marketSlug: "dfva-market-080cl",
    recommendSlug: "dfva-recommend-080cl",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/080cl",
  },
  {
    program: "Doctor of Medicine",
    institution: "University of Melbourne",
    level: "Graduate Coursework (Masters Extended), AQF level 9",
    date: "2026-07-02",
    score: 27,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 1, max: 3 },
      { label: "Outcome Evidence", score: 2, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-dmed",
    marketSlug: "dfva-market-mc-dmed",
    recommendSlug: "dfva-recommend-mc-dmed",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-dmed",
  },
  {
    program: "Doctor of Veterinary Medicine",
    institution: "University of Melbourne",
    level: "Graduate Coursework (Masters Extended), AQF level 9",
    date: "2026-07-02",
    score: 27,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-dvetmed",
    marketSlug: "dfva-market-mc-dvetmed",
    recommendSlug: "dfva-recommend-mc-dvetmed",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-dvetmed",
  },
  {
    program: "Doctor of Education",
    institution: "University of Melbourne",
    level: "Graduate Research (professional research doctorate), AQF Level 10",
    date: "2026-07-02",
    score: 19,
    maxScore: 36,
    riskBand: "HIGH RISK",
    thresholds: { q1: "NO", q2: "UNCERTAIN", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 0, max: 3 },
      { label: "Domain Depth", score: 2, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 1, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-300bb",
    marketSlug: "dfva-market-300bb",
    recommendSlug: "dfva-recommend-300bb",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/300bb",
  },
  {
    program: "Doctor of Laws",
    institution: "University of Melbourne",
    level: "Higher Doctorate (by examination, no coursework), AQF level 10",
    date: "2026-07-02",
    // Renormalised: 16 raw over 8 applicable dims → round(16 × 11/8) = 22. D1/D9/D10 are Not
    // Applicable (no graduate cohort, no curriculum, no outcome data) and excluded, not scored 0.
    score: 22,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "UNCERTAIN", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: null, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 2, max: 3 },
      { label: "AI Literacy", score: 0, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 1, max: 3 },
      { label: "Curriculum Currency", score: null, max: 3 },
      { label: "Outcome Evidence", score: null, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-dh-lld",
    marketSlug: "dfva-market-dh-lld",
    recommendSlug: "dfva-recommend-dh-lld",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/dh-lld",
  },
  {
    program: "Doctor of Philosophy - Indigenous Knowledge",
    institution: "University of Melbourne",
    level: "Graduate Research, AQF Level 10",
    date: "2026-07-02",
    score: 27,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-dr-philik",
    marketSlug: "dfva-market-dr-philik",
    recommendSlug: "dfva-recommend-dr-philik",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/dr-philik",
  },
  {
    program: "Doctor of Philosophy - Law",
    institution: "University of Melbourne",
    level: "Graduate Research, AQF 10",
    date: "2026-07-02",
    score: 23,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 1, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 1, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-dr-phillaw",
    marketSlug: "dfva-market-dr-phillaw",
    recommendSlug: "dfva-recommend-dr-phillaw",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/dr-phillaw",
  },
  {
    program: "Doctor of Philosophy - Veterinary Science",
    institution: "University of Melbourne",
    level: "Graduate Research, AQF Level 10",
    date: "2026-07-02",
    score: 26,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 2, max: 3 },
      { label: "Curriculum Currency", score: 1, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-dr-philvet",
    marketSlug: "dfva-market-dr-philvet",
    recommendSlug: "dfva-recommend-dr-philvet",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/dr-philvet",
  },
  {
    program: "Doctor of Science",
    institution: "University of Melbourne",
    level: "Higher Doctorate (by examination, no coursework), AQF level 10",
    date: "2026-07-02",
    // Renormalised: 20 raw over 8 applicable dims → 20 × 11/8 = 27.5, which lands exactly on the
    // MODERATE|RESILIENT boundary. Renormalisation rounds ties DOWN → 27 (MODERATE), so an imputed
    // program isn't promoted into RESILIENT by a rounding tie alone. D1/D9/D10 are Not Applicable
    // (no cohort, no curriculum, no outcome data) and excluded, not scored 0.
    score: 27,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: null, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 1, max: 3 },
      { label: "Curriculum Currency", score: null, max: 3 },
      { label: "Outcome Evidence", score: null, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-dh-sc",
    marketSlug: "dfva-market-dh-sc",
    recommendSlug: "dfva-recommend-dh-sc",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/dh-sc",
  },
  {
    program: "Doctor of Clinical Dentistry",
    institution: "University of Melbourne",
    level: "Graduate Coursework (Masters Extended), AQF level 9",
    date: "2026-07-02",
    score: 29,
    maxScore: 36,
    riskBand: "RESILIENT",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 3, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 2, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-me-dcd",
    marketSlug: "dfva-market-me-dcd",
    recommendSlug: "dfva-recommend-me-dcd",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/me-dcd",
  },
  {
    program: "Doctor of Dental Surgery",
    institution: "University of Melbourne",
    level: "Graduate Coursework (Masters Extended), AQF level 9",
    date: "2026-07-02",
    score: 25,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 3, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 1, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-ddensur",
    marketSlug: "dfva-market-mc-ddensur",
    recommendSlug: "dfva-recommend-mc-ddensur",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-ddensur",
  },
  {
    program: "Doctor of Optometry",
    institution: "University of Melbourne",
    level: "Graduate Coursework (Masters Extended), AQF Level 9",
    date: "2026-07-02",
    score: 24,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "UNCERTAIN", q2: "YES", q3: "UNCERTAIN" },
    dimensions: [
      { label: "Automation Exposure", score: 2, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 3, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 1, max: 3 },
      { label: "Outcome Evidence", score: 1, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-doptom",
    marketSlug: "dfva-market-mc-doptom",
    recommendSlug: "dfva-recommend-mc-doptom",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-doptom",
  },
  {
    program: "Doctor of Physiotherapy",
    institution: "University of Melbourne",
    level: "Graduate Coursework (Masters Extended), AQF Level 9",
    date: "2026-07-02",
    score: 26,
    maxScore: 36,
    riskBand: "MODERATE RISK",
    thresholds: { q1: "NO", q2: "YES", q3: "YES" },
    dimensions: [
      { label: "Automation Exposure", score: 3, max: 3 },
      { label: "Systems Thinking", score: 2, max: 3 },
      { label: "Technical Depth", score: 2, max: 3 },
      { label: "Decision-Making", score: 3, max: 3 },
      { label: "AI Literacy", score: 1, max: 3 },
      { label: "Domain Depth", score: 3, max: 3 },
      { label: "Research Rigour", score: 2, max: 3 },
      { label: "Human & Relational", score: 3, max: 3 },
      { label: "Curriculum Currency", score: 2, max: 3 },
      { label: "Outcome Evidence", score: 2, max: 3 },
      { label: "Irreplaceability (bonus)", score: 3, max: 3 },
    ],
    assessmentSlug: "dfva-mc-dphysio",
    marketSlug: "dfva-market-mc-dphysio",
    recommendSlug: "dfva-recommend-mc-dphysio",
    handbookUrl: "https://handbook.unimelb.edu.au/2026/courses/mc-dphysio",
  },
];

export const riskBandConfig: Record<
  string,
  {
    bg: string;
    text: string;
    border: string;
    bar: string;
    label: string;
    hoverBg: string;
  }
> = {
  RESILIENT: {
    bg: "bg-emerald-50 dark:bg-emerald-900/20",
    text: "text-emerald-700 dark:text-emerald-300",
    border: "border-emerald-200 dark:border-emerald-800",
    bar: "bg-emerald-500",
    label: "Resilient",
    hoverBg: "hover:bg-emerald-100 dark:hover:bg-emerald-900/40",
  },
  "MODERATE RISK": {
    bg: "bg-yellow-50 dark:bg-yellow-900/20",
    text: "text-yellow-700 dark:text-yellow-300",
    border: "border-yellow-200 dark:border-yellow-800",
    bar: "bg-yellow-500",
    label: "Moderate Risk",
    hoverBg: "hover:bg-yellow-100 dark:hover:bg-yellow-900/40",
  },
  "HIGH RISK": {
    bg: "bg-orange-50 dark:bg-orange-900/20",
    text: "text-orange-700 dark:text-orange-300",
    border: "border-orange-200 dark:border-orange-800",
    bar: "bg-orange-500",
    label: "High Risk",
    hoverBg: "hover:bg-orange-100 dark:hover:bg-orange-900/40",
  },
  CRITICAL: {
    bg: "bg-red-50 dark:bg-red-900/20",
    text: "text-red-700 dark:text-red-300",
    border: "border-red-200 dark:border-red-800",
    bar: "bg-red-500",
    label: "Critical",
    hoverBg: "hover:bg-red-100 dark:hover:bg-red-900/40",
  },
};

export const thresholdConfig: Record<string, { color: string }> = {
  YES: { color: "text-red-600 dark:text-red-400" },
  NO: { color: "text-emerald-600 dark:text-emerald-400" },
  UNCERTAIN: { color: "text-yellow-600 dark:text-yellow-400" },
};

export const dimBarColor = (score: number | null, max: number) => {
  if (score === null) return "bg-muted-foreground/30"; // Not Applicable — neutral, not "poor"
  const pct = score / max;
  if (pct >= 0.67) return "bg-emerald-500";
  if (pct >= 0.34) return "bg-yellow-500";
  return "bg-orange-500";
};
