// GENERATED FILE — DO NOT EDIT.
// Source: dfva/source/rubricV4.ts + dfva/source/evidence/*.json (panelCv4 blocks)
// Regenerate: npm --prefix scripts run dfva:gen-v4
import type { V4PanelC } from "../v4Meta";

const record: V4PanelC = {
  "C1": {
    "score": 1,
    "rationale": "Level 1 anchor: collaboration appears in learning outcomes but no core unit assesses it. Program CILO 4 claims collaborative work. Level 2 requires 'at least one core unit assesses collaborative practice', and the program documents no core unit at all — the handbook states no specific course must be taken, so the assessed group work that does exist (ARCH3042, COMP2120) sits only in the 312-course prescribed pool a student may or may not enter. Under R1 that is documented elective provision, not documented core assessment, so level 2 is not reached.",
    "evidenceLines": [
      "4. Work and learn in both independent and collaborative ways with others to encompass diverse abilities and perspectives;",
      "lists of majors, lists of alpha codes, but no specific course that absolutely",
      "must be taken. A major in the BSC might have compulsory courses, but the",
      "The following 312 units of study are prescribed for this academic program:",
      "- Group work: Unbelievable Truths of Archaeological Dating: 10% (Hurdle: False)",
      "- Group Assignments & Presentation: 50% (Hurdle: False)"
    ]
  },
  "C2": {
    "score": 1,
    "rationale": "Level 0 is falsified: assessments in the prescribed pool do require students to appraise the quality of work — self-assessment in ANTH1003, peer review of reports in BIOL3109, compulsory peer feedback in BIOL3206. Level 2 requires 'core assessment includes criterion-referenced appraisal of quality'; no course in this program is compulsory, so no core assessment carries that appraisal. Level 1 is the highest anchor the documented evidence supports.",
    "evidenceLines": [
      "- Self-assessment of class participation: 10% (Hurdle: False)",
      "- Written report from practical 1 and peer review of practical 1 reports: 30% (Hurdle: False)",
      "- Explainer feedback, all students must give constructive feedback on other student's explainers.: 7% (Hurdle: False)",
      "lists of majors, lists of alpha codes, but no specific course that absolutely",
      "must be taken. A major in the BSC might have compulsory courses, but the"
    ]
  },
  "C3": {
    "score": 1,
    "rationale": "Level 1 anchor read literally: 'AI or digital tools appear only as electives or as tool operation/training'. COMP1730 teaches AI-assisted programming and prompt engineering, and COMP2400 and COMP3425 carry data ethics and privacy outcomes, but every one of these sits in the non-compulsory prescribed pool. Level 2 requires core units addressing AI capabilities AND limitations/ethics with that use assessed; with no compulsory course the program documents no such core unit, so level 2 is not reached.",
    "evidenceLines": [
      "- Explain key concepts in AI-assisted programming, including Large Language Models (LLMs), prompting, problem decomposition, and top-down design.",
      "- Apply the workflow of AI-assisted programming and prompt-engineering techniques to guide and improve code generated by AI assistants.",
      "- Connect database design with social and economic impacts including security, ethics, and Australian Privacy Principles.",
      "- Reflect upon ethical and social impacts of data mining.",
      "lists of majors, lists of alpha codes, but no specific course that absolutely",
      "must be taken. A major in the BSC might have compulsory courses, but the"
    ]
  },
  "C4": {
    "score": 1,
    "rationale": "Level 1 anchor: transfer is claimed in outcomes but not assessed. CILO 1 claims application of scientific knowledge in educational and professional contexts and CILO 2 claims responding to problems and issues, with no assessment attached at program level. Level 2 requires 'at least one core assessment requires application to novel or unfamiliar problems' — no assessment is required by this program. Level 3 requires the program to document structured progression toward independent learning; the self-scoped project courses that exist (ENVS3100, BIOL3208/3209) are Honours Pathway Courses with quotas, merit entry and supervisor availability conditions, so they are neither required nor a documented progression.",
    "evidenceLines": [
      "1. Develop, apply, integrate and generate scientific knowledge in educational and professional contexts;",
      "2. Use a range of skills and methods to identify, analyse and respond to problems and issues;",
      "course in which students undertake a self-directed research project under the guidance of a supervisor.",
      "NOTE: This course is an Honours Pathway Course that involves research oriented material of a greater conceptual difficulty than a typical 3000 level science course.",
      "Entry to this course requires at least 96 units towards a degree with an average of 80% or above in relevant second and third year courses.",
      "must be taken. A major in the BSC might have compulsory courses, but the"
    ]
  },
  "C5": {
    "score": 1,
    "rationale": "Level 0 is falsified — research-methods training is present in the prescribed pool (BIOL2202, ENVS1003). Level 2 requires that students design and conduct an inquiry with methodology selection and data collection, assessed; the handbook documents no course that every student must take, so it does not document that any student designs and conducts an inquiry. Level 3 additionally requires a substantial primary-evidence project that is REQUIRED rather than one route among several, and the research-project courses here are explicitly optional, quota-limited Honours Pathway Courses. Level 1 is the highest anchor supported.",
    "evidenceLines": [
      "Subject: Experimental Design and Analysis in Biology (BIOL2202)",
      "Subject: Introduction to Environmental and Social Research (ENVS1003)",
      "NOTE: This course is an Honours Pathway Course that involves research oriented material of a greater conceptual difficulty than a typical 3000 level science course.",
      "Entry to this course requires at least 96 units towards a degree with an average of 80% or above in relevant second and third year courses.",
      "lists of majors, lists of alpha codes, but no specific course that absolutely",
      "must be taken. A major in the BSC might have compulsory courses, but the"
    ]
  },
  "adaptiveness": 5,
  "W1": {
    "score": 1,
    "rationale": "Level 1 anchor: communication appears in learning outcomes (CILO 3 names conveying professional and disciplinary information to diverse audiences) and presentations are common across the pool, but no professional genre is documented in core assessment. Level 2 requires at least one CORE assessment in a recognised professional genre or to an audience beyond the teaching team; professional genres do appear — a policy brief in ENVS3028, a press release in SCOM2016, a mock job application in BIOL3194 — but all in courses no student is required to take. Barrie's warning against scoring stated graduate attributes applies with full force, so the CILO alone cannot lift this above 1.",
    "evidenceLines": [
      "3. Convey and relate professional and disciplinary information and ideas to diverse audiences in effective and appropriate ways;",
      "- Policy Brief: 20% (Hurdle: False)",
      "- Press release: 10% (Hurdle: False)",
      "- Mock job application: 25% (Hurdle: False)",
      "lists of majors, lists of alpha codes, but no specific course that absolutely",
      "must be taken. A major in the BSC might have compulsory courses, but the"
    ]
  },
  "W2": {
    "score": 1,
    "rationale": "Level 1 anchor: contextualised or scenario-framed tasks appear, but the artefact and criteria remain academic. The pool carries scenario framing — a hypothetical but realistic Environmental Impact Study in ENVS2015, mock expert testimony in BIAN2128, a mock treaty negotiation in ENVS3020 — while the assessment forms documented across the prescribed courses are overwhelmingly exams, quizzes, essays, lab reports and research reports in academic genres. Level 2 requires at least one core assessment reproducing a professional task end to end; no assessment in this program is core, so level 2 is not reached. R4 applies: no task was scored up for describing itself as real-world.",
    "evidenceLines": [
      "This course provides an introduction to Geographic Information Systems (GIS) and is based around a hypothetical, but realistic Environmental Impact Study in a small regional catchment.",
      "- Mock Expert Testimony: 15% (Hurdle: False)",
      "The culmination of the course is a mock treaty negotiation for \"The Canberra Agreement\" under the United Nations Framework Convention on Climate Change.",
      "lists of majors, lists of alpha codes, but no specific course that absolutely",
      "must be taken. A major in the BSC might have compulsory courses, but the"
    ]
  },
  "W3": {
    "score": 1,
    "rationale": "Level 1 anchor exactly: work-situated learning exists only as an elective or optional internship. SCNC3000 Science Internship and SCOM3004 Science Communication Internship are both in the prescribed pool and both supervised in a workplace, and the program page itself frames internships as something to hold spare electives for. Level 2 requires a CORE unit placing students in a real workplace with practitioner supervision and assessment; no course in this program is required, and the cohort is a school-leaver undergraduate intake, not a cohort documented as already practising, so the v4.2 in-practice route does not apply.",
    "evidenceLines": [
      "Subject: Science Internship (SCNC3000)",
      "Subject: Science Communication Internship (SCOM3004)",
      "other opportunities open, such as international exchange, internships, and",
      "lists of majors, lists of alpha codes, but no specific course that absolutely",
      "must be taken. A major in the BSC might have compulsory courses, but the"
    ]
  },
  "workplace": 3,
  "gates": {
    "G1": {
      "result": "FAIL",
      "rationale": "The PASS anchor needs a documented coherent specialist core with progressive technical or methodological depth by one of three routes — an all-compulsory specialist core, an accredited sequence, or a staged prerequisite chain. The handbook denies the first (no specific course must be taken), denies the third (no formal program prerequisites, and first-year science courses assume little specific knowledge), and documents no accreditation. What is documented is a 312-course prescribed pool spanning anthropology, economics, finance, management, sociology and computing alongside the sciences, with up to ten courses permitted from another ANU College — the FAIL descriptor's interchangeable content. The requirement to take 2000- and 3000-level courses from a BSc major supplies level progression, but the major's own compulsory courses are outside this extract, so the specialist core is not documented here.",
      "evidenceLines": [
        "lists of majors, lists of alpha codes, but no specific course that absolutely",
        "must be taken. A major in the BSC might have compulsory courses, but the",
        "There are no formal program prerequisites and many first-year science courses assume little specific knowledge. The exceptions are:",
        "The following 312 units of study are prescribed for this academic program:",
        "courses from another ANU College if you are undertaking the single Bachelor of Science program.",
        "2000 level course BSC Major",
        "3000 level course BSC Major"
      ]
    },
    "G2": {
      "result": "FAIL",
      "rationale": "The PASS anchor requires that assessments require defended trade-off decisions, or simulations, capstones or live projects with real uncertainty and accountability. No assessment in this program is required of any student, so nothing is documented that assessments require. Tasks of the right shape do exist in the pool — COMP3500 has students defend engineering decisions at project reviews before stakeholders — but that course is restricted-entry and optional. Scored down per the rule that ambiguity is never resolved upward; the FAIL descriptor 'recall or scripted responses only' does not describe the pool, but the PASS condition is not documented.",
      "evidenceLines": [
        "- Present, communicate, and effectively defend sound engineering decisions at project reviews, both orally and in writing, with peers, supervisors, and project stakeholders.",
        "To enrol in this course you must meet the eligibility criteria, which includes membership of a student project group before the end of week 1, where the project has been approved by the convener.",
        "lists of majors, lists of alpha codes, but no specific course that absolutely",
        "must be taken. A major in the BSC might have compulsory courses, but the"
      ]
    }
  },
  "ambiguities": [
    "Every item straddles level 1 and level 2 for the same reason: the construct is assessed somewhere in the 312-course prescribed pool but no course in the program is compulsory, so nothing qualifies as core assessment. Resolved down to 1 in all eight items by the rule that ambiguity is never resolved upward, and by R1 (score what the handbook documents, not what a graduate plausibly does).",
    "C1 versus W1: assessed group work (ARCH3042, COMP2120) and audience-facing communication (ENVS3028 policy brief, SCOM2016 press release) both sit in the same elective pool. Coordination evidence was scored in C1 and audience/genre evidence in W1 per the one-construct-one-home rule; neither reaches level 2 in either item.",
    "C2 versus W2: peer review and peer feedback (BIOL3109, BIOL3206) are appraisal of quality and were scored in C2 only, never as task fidelity in W2.",
    "G1: the requirement for four 2000-level and four 3000-level courses from a BSc major is a documented level progression and a real argument for PASS. It was resolved to FAIL because the extract contains no major's compulsory-course list, the program states no course must be taken, and it states there are no formal program prerequisites — so none of the three PASS routes is documented in this extract.",
    "G2: the pool contains capstones and simulations with genuine uncertainty (COMP3500, ENVS3020, BIOL3188), so the FAIL descriptor fits the evidence poorly; the gate was failed because the PASS condition requires assessments that are required, and this program requires none."
  ],
  "notScoreable": [
    "No item could be scored at level 2 or above on core-assessment grounds: the extract carries the program's prescribed 312-course pool but not the compulsory-course list of any individual BSc major, which the handbook says is where compulsory courses, if any, live. Recapturing the major requirement pages would be needed to test whether any of C1-C5, W1-W3 or G1 clears its level-2/PASS bar."
  ],
  "instrument": "4.2-draft",
  "verified": {
    "adversarial": true,
    "mechanical": true,
    "date": "2026-09-07"
  }
};

export default record;
