#!/usr/bin/env python3
"""Generate reportContent.recommend-all.ts with all 41 improvement roadmaps."""
import os

REPORTS_DIR = os.path.join(os.path.dirname(__file__), '..', 'reports')
OUTPUT = os.path.join(os.path.dirname(__file__), '..', 'compass', 'app', 'src', 'compass', 'reportContent.recommend-all.ts')

def main():
    files = sorted([f for f in os.listdir(REPORTS_DIR) if f.startswith('dfva-recommend-') and f.endswith('.md')])
    print(f"Found {len(files)} recommend files")
    
    lines = []
    lines.append('// Auto-generated: all program improvement roadmaps')
    lines.append('// Generated by scripts/generate-recommend-content.py')
    lines.append('')
    lines.append('export const RECOMMEND_CONTENT_ALL: Record<string, { title: string; institution: string; markdown: string }> = {')
    
    for i, fname in enumerate(files):
        slug = fname.replace('.md', '')
        with open(os.path.join(REPORTS_DIR, fname)) as f:
            content = f.read()
        
        # Extract title from first line
        first_line = content.split('\n')[0]
        title = first_line.replace('## IMPROVEMENT PLAN: ', '').strip()
        institution = 'University of Melbourne'
        
        # Escape for TypeScript template literal
        escaped = content
        escaped = escaped.replace('\\', '\\\\')
        escaped = escaped.replace('`', '\\`')
        escaped = escaped.replace('${', '\\${')
        
        comma = ',' if i < len(files) - 1 else ''
        lines.append('  "' + slug + '": {')
        lines.append('    title: "' + title + ' \\u2014 Improvement Plan",')
        lines.append('    institution: "' + institution + '",')
        lines.append('    markdown: `' + escaped + '`,')
        lines.append('  }' + comma)
    
    lines.append('};')
    lines.append('')
    
    with open(OUTPUT, 'w') as f:
        f.write('\n'.join(lines))
    
    print(f"Generated {len(files)} entries in {OUTPUT}")

if __name__ == '__main__':
    main()
