#!/usr/bin/env python3
"""Generate compass-static/src/data/reportContent.faculty.ts from reports/dfva-faculty-*.md.
Mirrors generate-recommend-content.py: embeds each briefing markdown as a TS template literal."""
import os

HERE = os.path.dirname(__file__)
REPORTS_DIR = os.path.join(HERE, '..', 'reports')
# Live target is the Wasp/OpenSaaS app (compass-static is decommissioned).
OUTPUT = os.path.join(HERE, '..', 'compass', 'app', 'src', 'compass', 'reportContent.faculty.ts')

def main():
    files = sorted(f for f in os.listdir(REPORTS_DIR)
                   if f.startswith('dfva-faculty-') and f.endswith('.md'))
    print(f"Found {len(files)} faculty briefings")

    lines = [
        '// Auto-generated: per-faculty DFVA briefings (real UoM graduate-outcome evidence).',
        '// Generated by scripts/generate-faculty-content.py — edit the source markdown in reports/, not here.',
        '',
        'export const REPORT_CONTENT_FACULTY: Record<string, { title: string; institution: string; markdown: string }> = {',
    ]
    for i, fname in enumerate(files):
        slug = fname[:-3]  # strip .md
        content = open(os.path.join(REPORTS_DIR, fname), encoding='utf-8').read()
        # First line is the '# <Faculty> — DFVA Briefing' title (stripped by the panel renderer).
        title = content.split('\n', 1)[0].lstrip('# ').strip().replace('—', '\\u2014').replace('"', '\\"')
        escaped = content.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
        comma = ',' if i < len(files) - 1 else ''
        lines += [
            f'  "{slug}": {{',
            f'    title: "{title}",',
            f'    institution: "University of Melbourne",',
            f'    markdown: `{escaped}`,',
            f'  }}{comma}',
        ]
    lines += ['};', '']
    open(OUTPUT, 'w', encoding='utf-8').write('\n'.join(lines))
    print(f"Generated {len(files)} entries -> {os.path.relpath(OUTPUT, os.path.join(HERE, '..'))}")

if __name__ == '__main__':
    main()
