// Mock for 'wasp/server/operations' used by vitest server-side tests
// Re-exports the type placeholders Wasp generates for operation types

// The actual types are generated by Wasp; for tests we use minimal versions
export type AssessProgram<I, O> = (args: I, context: any) => Promise<O>;

export type GetAssessmentJobs<I, O> = (args: I, context: any) => Promise<O>;

export type GetAssessmentJob<I, O> = (args: I, context: any) => Promise<O>;
